### ISSUE TITLE
HMR breaks when changing CSS

### ISSUE THREAD

**Issue by iamtmrobinson** [CompuIves/codesandbox-client#1003]
# 🐛 bug report

## Description of the problem

Unfortunately I still have the same problem as in #1001 in [this notebook](https://codesandbox.io/s/2w14n70w4y).

## How has this issue affected you? What are you trying to accomplish?

See #1001 

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  |
| Browser | Chrome Version 67.0.3396.99 (Official Build) (64-bit) |
| Operating System | Mac OSX Sierra 10.12.6 |

**Comment by CompuIves** [comment]
It's deployed!

**Comment by iamtmrobinson** [comment]
👌 working perfectly - thanks @CompuIves
