### ISSUE TITLE
Infinite Reload Parcel Redux template

### ISSUE THREAD

**Issue by reccanti** [CompuIves/codesandbox-client#1005]
# 🐛 bug report

## Description of the problem

Occasionally when I fork one of my sandboxes, I get stuck in an infinite reload loop.

## How has this issue affected you? What are you trying to accomplish?

The issue sometimes goes away if I try forking it again, but it's inconsistent. I'd like to be able to consistently fork the sandbox without this issue.

###  Link to sandbox: [link]() (optional)

https://codesandbox.io/s/38zplp5v76

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  PROD-1532347593-ffd408c
| Browser | 67.0.3396.99
| Operating System | MacOS

**Comment by CompuIves** [comment]
I think I fixed this in the last commit, I will keep the issue open for 2 days to evaluate if it's really fixed. If it doesn't occur again I will close it!

**Comment by SaraVieira** [comment]
Appears fixed 🎉
