### ISSUE TITLE
Toggle Comment key

### ISSUE THREAD

**Issue by cloud-walker** [CompuIves/codesandbox-client#1006]
# 🌈 Toggle Comment key
I found my self searching for that feature many times, I think it will be very useful for people making workshop or streaming for example!

**Comment by CompuIves** [comment]
Do you mean toggle the code? For me it works with CMD+/. But maybe we don't have proper bindings for Windows or something?

**Comment by cloud-walker** [comment]
Oh! It can't work for me because my keyboard layout T_T

Would be awesome if added on the Keybinding section then?

**Comment by einarlove** [comment]
![image](https://user-images.githubusercontent.com/1495211/47103598-d9951980-d23f-11e8-8232-48c85c859a2f.png)

Here in Norway—and probably many no-English countries—the `/` key is behind a modifier key. So ⌘+⇧+7 is required to comment which does work in vscode, but not Codesandbox.

**Comment by SaraVieira** [comment]
I have the same issue with a Portuguese keyboard :(

**Comment by SaraVieira** [comment]
You can override this if you are using vscode win codesanbox now

**Comment by lbogdan** [comment]
Closing this, as the key bindings can now be edited from VSCode:

![image](https://user-images.githubusercontent.com/2083930/55038780-a6df2080-502a-11e9-9a4e-9983096f9eeb.png)

@cloud-walker Feel free to reopen if you still have issues, though.
