### ISSUE TITLE
Raise module limit for patrons (or everyone)?

### ISSUE THREAD

**Issue by ryanpcmcquen** [CompuIves/codesandbox-client#1007]
# 🌈 Feature

Raise the module limit for patrons!

Allow more than 200 modules (250 maybe)?

Our [repo](https://github.com/SurLaTable/slt-ui) used to work on CodeSandbox, but I added one package and now this 'error' happens every time:

```
Only a max of 200 modules is allowed in a sandbox
```
![screenshot 1532551261](https://user-images.githubusercontent.com/772937/43227697-53421c10-9014-11e8-94ef-3684b387c62e.png)

This would be amazing for on-boarding for my team to have CodeSandbox as an option.

https://codesandbox.io/s/github/SurLaTable/slt-ui/tree/master/

**Comment by ryanpcmcquen** [comment]
@CompuIves, any movement on this?

**Comment by SaraVieira** [comment]
Hey!

It was actually bumped to 250 :D

Closing this as fixed, feel free to re open :)

**Comment by wpitallo** [comment]
@SaraVieira why does it matter how many modules there are? I am currently over the 250 mark as well for a project I was hopping to import :(

**Comment by sustained** [comment]
I would gladly pay for unlimited modules in projects, just saying.
