### ISSUE TITLE
Preview looks different next to editor than in new window

### ISSUE THREAD

**Issue by Loilo** [CompuIves/codesandbox-client#1009]
# 🐛 bug report

## Description of the problem
A co-worker just found a weird little inconsistency. In his sandbox, the preview next to the editor looks different than the preview opened to a new window.

## How has this issue affected you? What are you trying to accomplish?
Although my co-worker fixed the issue by using CSS' `backface-visibility` property (now it looks correctly in both scenarios), it might still be worth taking a look and possibly eliminating the inconsistency.

However, we're aware that this might very well be just a weird issue with browsers not rendering multiple elements with CSS 3d transforms correctly.

### A note about browsers
We tested this in various browsers.

* The initial tests were in **Chrome**. It looks like it should there, but with the described inconsitencies. (It seems to only occur in macOS Chrome though.)
* In **Firefox** (vanilla as well as Nightly) the result overall looks broken, but there's an inconsitency between the described scenarios as well. Also, Firefox suddenly completely shakes up the rendered result when inspecting the affected elements with devtools.
* In **Safari** (version 11), the result looks kind of broken but is consistent across scenarios.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1532378173-dcdb416 |
| Browser | Chrome 67 |
| Operating System | macOS 10.13.2

**Comment by lbogdan** [comment]
Hey @Loilo ,

Is this still an issue? I tried to replicate, but the sandbox you provided is not there anymore.

**Comment by Loilo** [comment]
Oh dang, just cleaned up my sandboxes the other day and thought it wouldn't be needed anymore. 🙈

Let me talk back to my coworker and see if he still has a sandbox where this can be reproduced. ☺️

**Comment by Loilo** [comment]
So turns out my coworker actually cleaned up his sandboxes *yesterday*. This is really unfortunate, but that means we've got no more reproduction of the issue.

I'll close this for now, if anyone experiences the same problem, they'll open a new issue anyway. 🤷‍♂️
