### ISSUE TITLE
Vuejs

### ISSUE THREAD

**Issue by AlokJoshi** [CompuIves/codesandbox-client#101]
Is it possible to use this for Vue based projects?

**Comment by vueu** [comment]
https://codesandbox.io/s/pQA0685yr

**Comment by CompuIves** [comment]
Yep! Like @vueu said, certainly possible. There is not 'official' support yet (download function still downloads CRA). I'll work on that this week, hopefully you'll see native support this week 😄 .

**Comment by AlokJoshi** [comment]
@vueu and @CompuIves thanks for your responses. Incidentally I love codesandbox. Looking forward to native support for vue.

**Comment by CompuIves** [comment]
It's here 😄 ! https://codesandbox.io/s/vue

**Comment by AlokJoshi** [comment]
Thanks. That is great news. 


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by AlokJoshi** [comment]
@compulves. Thank you very much. Greatly appreciated.


Sent from my T-Mobile 4G LTE Device

-------- Original message --------
