### ISSUE TITLE
Safari can't change theme

### ISSUE THREAD

**Issue by tobiastimm** [CompuIves/codesandbox-client#1019]
# 🐛 bug report

In Safari you can't change the theme, because the modal isn't scrollable.

![image](https://user-images.githubusercontent.com/10043789/43506741-4b214f68-956b-11e8-830e-8a368ecf9b14.png)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1530978082-067f9fe
| Browser | Safari
| Operating System | macOS High Sierra

**Comment by lbogdan** [comment]
Closing this, as I'm quite confident that all UI changes since, and the switch to VSCode as the default editor, should have fixed it. However, @tobiastimm feel free to reopen if it's still happening for you.
