### ISSUE TITLE
Allow scrolling a sandbox in Safari

### ISSUE THREAD

**Issue by Haroenv** [CompuIves/codesandbox-client#102]
When making bigger things, it's useful to be able to scroll. I think somewhere in the styles `iframe { overflow: hidden;}` is specified, which will disable someone from scrolling through a code sandbox. 

An example is: https://codesandbox.io/s/7LD7EJ14r

**Comment by CompuIves** [comment]
Thanks for reporting this! Hmm, this is strange. I'm able to scroll the
iframe (I'm on phone though). What browser are you using?

**Comment by Haroenv** [comment]
Safari Technology Preview Release 36 (Safari 11.0, WebKit 12604.1.32.0.1), just checked and it's possible to scroll in Chrome

**Comment by Haroenv** [comment]
Found a workaround, by adding this css _inside_ the `<iframe>`:

```css
html {
  height: 100%;
}

body {
  height: 100%;
  overflow: auto;
}
```

Not exactly sure _why_ it's needed, and where I should add it though

**Comment by Haroenv** [comment]
I just realised that this is a bug in Safari Technology Preview and will probably be fixed at the next release. It's not present in the main version, and we can also see this bug on codepen. Let's close this as out of scope for now.

**Comment by Haroenv** [comment]
This magically became fixed a few days ago. 🆒
