### ISSUE TITLE
Show dependency bundle sizes

### ISSUE THREAD

**Issue by camflan** [CompuIves/codesandbox-client#1023]
# 🌈 Feature
To help developers avoid large dependencies, it would be great to see the bundle sizes - both in the dependency list as well as in the npm search box.

Not sure if it's easy/accurate to get these sizes from smooshpack or something like bundlephobia.

**Comment by prateekgoel** [comment]
Hi @CompuIves, I would like to work on this if this is a desired feature. It would be my first PR. Do you have any thoughts on this?

**Comment by SaraVieira** [comment]
Has been added by #1197  :D
