### ISSUE TITLE
[UX issue] Open link in New Tab when CMD or CTRL Clicked on Projects

### ISSUE THREAD

**Issue by deadcoder0904** [CompuIves/codesandbox-client#1024]
# 🌈 Feature

I think this should be common in every website while clicking link with CMD or CTRL it should open in a new tab. I'm on https://codesandbox.io/dashboard/recent page & can't open multiple projects bcz of that.

**Comment by CompuIves** [comment]
Hmm, good one. We should do CMD + Double Click = open in new tab. For now you can right click on a project and select: 'Open in new tab'.

**Comment by deadcoder0904** [comment]
Why the Double Click? Nobody does that. I think CMD+CLICK is common. For windows users its CTRL+CLICK. Double Click you need to teach to the users.

**Comment by deadcoder0904** [comment]
Also @CompuIves the Save issue is still not working

**Comment by CompuIves** [comment]
> Also @CompuIves the Save issue is still not working

I don't know what you mean with this.

> Why the Double Click? 

I learned that applications generally default to double click behavior when you try to mimic file explorer behaviour and items are draggable. This is also done by Google Drive and Figma, to pick two examples.

**Comment by deadcoder0904** [comment]
> I don't know what you mean with this.

It was another issue of Saving Files which is solved now so forget it.

> I learned that applications generally default to double click behavior when you try to mimic a file explorer and items are draggable. This is also done by Google Drive and Figma, to pick two examples.

Cool you're right :)
