### ISSUE TITLE
Manipulating DOM without React

### ISSUE THREAD

**Issue by ritz078** [CompuIves/codesandbox-client#103]
Thanks for your awesome work. codesandbox is really solving problem of many and it has a great UI.

Following up on https://twitter.com/CompuIves/status/896386969755897856

Here is my demo https://codesandbox.io/s/kR3rvmYY6

I am trying to read text from the HTML file, modify it and then render it back. Is there anything I am doing wrong ?

**Comment by CompuIves** [comment]
Ah, I think I know what happens. The rendering happens in a delay, in this case CodeSandbox checks if the DOM has changed, it didn't, show it shows an error. But 500ms after that the DOM gets changed. I'll remove the DOM check, the preview is currently in a rewrite and the new version also doesn't have it. Should work in ~15 min!

**Comment by ritz078** [comment]
That was quick.
Thanks a lot. Let me know when I can check.

**Comment by CompuIves** [comment]
Okay! Deployed, it seems like your sandbox doesn't work yet, but I see an error in the console. Maybe there's something wrong with the code or the dependencies...

**Comment by ritz078** [comment]
Yes I see the error. Thank you for your help. I can take it from here.
