### ISSUE TITLE
Http request wont work

### ISSUE THREAD

**Issue by saya-nel** [CompuIves/codesandbox-client#1033]
Hello, 

I'm using react.
I have strange error, I do a sample http request (with axios but with fetch or others the problem is the same) and try to print the response in the console. I use React for the front and node (listen port 8080) for the back, I precise that work when I do exactly the same with create react app, using npm start (localhost:3000 and http request in http://[public ip]:8080/coucou)

When I just put http://[public ip]:8080/coucou in firefox that work to and I have the good response from server.

Here the error returned by server in codeSandBox (captured by the catch bloc) :

Error {stack: "createError@https://ww28ry45pl.codesandbox.io/node_modules/axios/lib/core/createError.js:16:15
handleError@https://ww28ry45pl.codesandbox.io/node_modules/axios/lib/adapters/xhr.js:87:14
"}

I dont find anything about this problem,

Thank you for your help.

**Comment by EnriqueSalazar** [comment]
Hi. Did you solve it? I am having the same issue.

**Comment by saya-nel** [comment]
Nope :/

Le sam. 1 déc. 2018 à 19:03, Enrique Salazar <notifications@github.com> a
écrit :

**Comment by CompuIves** [comment]
I believe this is not an issue with CodeSandbox. I think these requests fail because of a CORS mechanism (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). What kind of error are you getting?

**Comment by saya-nel** [comment]
i don't know I tried some months ago, you can enable CORS in your server
side but that don't work to. Maybe just work without web browser IDE, if
you can.

Le sam. 1 déc. 2018 à 22:00, Ives van Hoorne <notifications@github.com> a
écrit :

**Comment by CompuIves** [comment]
This works the same way for local code, it's not specific to CodeSandbox. It fully depends on where you host your server/whether you added the right CORS headers.

**Comment by saya-nel** [comment]
Oh, for me that work's with local bot not with codesandbox, very strange

Le sam. 1 déc. 2018 à 22:57, Ives van Hoorne <notifications@github.com> a
écrit :

**Comment by EnriqueSalazar** [comment]
I opened the preview outside the IDE and allowed me to get more info about the error. Express CORS Middleware  fixed it for me. Thanks.

**Comment by lbogdan** [comment]
Closing this, as it's expected browser behavior.
