### ISSUE TITLE
font-variation-settings css property isn't working

### ISSUE THREAD

**Issue by sun2rise** [CompuIves/codesandbox-client#1037]
# 🐛 bug report

## Description of the problem
When using `font-variation-settings` css property i have this error:  
`[css] Unknown property: 'font-variation-settings'`
## How has this issue affected you? What are you trying to accomplish?
I was trying to test variable font following [this article](https://codeburst.io/welcome-to-the-world-of-variable-fonts-98fcbc688d92)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1533293248-4a97495
| Browser | Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
| Operating System | macOS Sierra 10.12.6

**Comment by sun2rise** [comment]
Actually the property is working but the `font-variation-settings` property is linted as error.

**Comment by SaraVieira** [comment]
Heey!

I am gonna close this as it seem changing to VSCode has made this property be recognized :D
