### ISSUE TITLE
CodeMirror/Monaco Editor Emmet/Prettify question?

### ISSUE THREAD

**Issue by aaazureee** [CompuIves/codesandbox-client#1038]
Hi, I'm currenly using CodeSandbox to play around with React. When I'm using the Monaco Editor, I notice that Emmet in JS file does not work (press div + Tab does not create `<div></div>`). When I changed to the CodeMirror editor, Emmet works fine but there is one thing that does not feel right. In long files, when I scroll down, and press Prettify, the cursor jumps to the top of the file, which is very annoying? Is there a way that I can get the best of both worlds?
My OS is Windows 7, I tested this on both Firefox and Chrome.

**Comment by CompuIves** [comment]
Hey! Both issues you mentioned should be fixed by now, I just deployed Emmet support in Monaco/VSCode as well!
