### ISSUE TITLE
Vuex getter won't evaluate

### ISSUE THREAD

**Issue by ColinRCasto** [CompuIves/codesandbox-client#1039]
# 🐛 bug report

In a vue project using vuex for state management, a simple getter is failing to evaluate and is instead 
therfore:

store.js
`import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default {
  state: {
    counter: 10
  },
  getters: {
    counter: state => {
      return state.counter;
    }
  }
};`

when called this getter returns:

`function counter(state) { return state.counter; }`

instead of the value 10
Link to my sandbox  https://codesandbox.io/s/kw2wox9mlr

| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Chrome |  (latest stable release)
| Operating System | (Windows 10)

**Comment by rayfoss** [comment]
Looks like you fixed it?

**Comment by SaraVieira** [comment]
Closing as issue seems to be fixed
