### ISSUE TITLE
Icons misplaced when zoomed

### ISSUE THREAD

**Issue by coryhouse** [CompuIves/codesandbox-client#104]
If you zoom, the "Support Sandbox" link sits over the view selection boxes. Occurs in both Chrome and Safari. 

Thanks for the awesome tool! 💯

**Comment by CompuIves** [comment]
Good one, we definitely need to free up some space in the header. Will work on this today.

**Comment by CompuIves** [comment]
Fixed with https://github.com/CompuIves/codesandbox-client/commit/73aab24d786c605e93c3b92cd20fd5536dad6e9f

**Comment by coryhouse** [comment]
Great! Thanks! 👍
