### ISSUE TITLE
JS files have no content type header or MIME

### ISSUE THREAD

**Issue by rayfoss** [CompuIves/codesandbox-client#1040]
# 🐛 bug report

## Description of the problem
Directly served js files don't have content-type headers
https://ox7popvlnz.codesandbox.io/src/sw.js
![screen shot 2018-08-14 at 4 53 30 pm](https://user-images.githubusercontent.com/876076/44120710-d6f55e68-9fe2-11e8-9160-feb81fbd818c.png)

## How has this issue affected you? What are you trying to accomplish?
I need to use a service worker to use the Web Notifications API. Though I would run into the same problem with many other API's such as Push.

### Your Environment
Сodesandbox  

## Additional details ##
This is a bug without workaround :/ 

```
proxyConsole.js:72 Unhandled promise rejection DOMException: Failed to register a ServiceWorker: The origin of the provided scriptURL ('https://raw.githubusercontent.com') does not match the current origin ('https://xxx.codesandbox.io').
```

**Comment by lg** [comment]
i've got the same problem, though for me this is coming out with a failed ES6 module import. code is:

```html
<script type="module">
import AwesomeModule from "./awesome-module.js"
</script>
```

the error the browser gives is: `Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.` (in Chrome's console). basically all these new ES6 toys are coming with both MIME and CORS requirements. the web server will need proper MIMEs returned for js filetypes.

**Comment by CompuIves** [comment]
Heh, I thought I fixed this some day. Lemme double check!

**Comment by CompuIves** [comment]
Deploying fix for it now!
