### ISSUE TITLE
`CTRL/CMD + W` to close active editor tab

### ISSUE THREAD

**Issue by farskid** [CompuIves/codesandbox-client#1044]
# 🌈 Feature

for now if you use a combination of `CTRL/CMD + W`, it closes the whole browser tab.

I'd rather have it close active editor tab same as my editor.

@CompuIves Would be happy to work on it and send a PR.

**Comment by CompuIves** [comment]
I wish we could have native behaviour here, but Chrome doesn't allow us to override `CMD + W`. This is frustrating for me, for now I 'fixed' it by implementing `CTRL + W` for Mac as alternative...

**Comment by farskid** [comment]
Thanks for the info :) I'll close the issue.
