### ISSUE TITLE
Update default Vanilla template

### ISSUE THREAD

**Issue by montogeek** [CompuIves/codesandbox-client#1045]
# 🌈 Add style link to default Vanilla template

Default vanilla template should have a `<link>` tag that would point to `src/style.css`.

Add `<link href="src/style.css" rel="stylesheet">` to default HTML file.
File `style.css` would be an empty file or since default HTML have an `h1` tag, we could style this element.

Could't find src code of this response https://codesandbox.io/api/v1/sandboxes/vanilla, but it would be add a new entry to `modules` key with `style.css` content and also update `index.html` code.

**Comment by CompuIves** [comment]
What would be the advantage of this?

**Comment by montogeek** [comment]
It is common to need/use styles in your application, specially in a Vanilla project where CSS-in-JS doesn't exist, conceptually Vanilla means that is how things were done before

**Comment by SaraVieira** [comment]
Closing as this has been added in the meantime

https://codesandbox.io/s/vanilla

**Comment by montogeek** [comment]
Thanks @SaraVieira !
