### ISSUE TITLE
disabling prettier

### ISSUE THREAD

**Issue by a-m-dev** [CompuIves/codesandbox-client#1048]
hi there 
this condsandbox is great i do every testing stuff with it 
but every time i save my project , the prettier just shits all over my code , it's becomes a mess !
how can i disable that of my entire project ??????????????????????????????????????????

**Comment by satyarohith** [comment]
Hi! I think you can turn off prettifying. Go to Preferences>editor>prettify on save :)

**Comment by a-m-dev** [comment]
this is my boy @satyarohith , thank you 👍

**Comment by satyarohith** [comment]
Mind closing this? :)

**Comment by CompuIves** [comment]
Yep! This can be closed, thanks for the notice @satyarohith 😄

**Comment by babakness** [comment]
`Go to Preferences>editor>prettify on save :)`

This option isn't there, I have the "VS-Code" experiment feature on, I don't know if that makes a difference. I too dislike prettier as a default and don't like it forced onto each project.

**Comment by sunyatasattva** [comment]
> `Go to Preferences>editor>prettify on save :)`
> 
> This option isn't there, I have the "VS-Code" experiment feature on, I don't know if that makes a difference. I too dislike prettier as a default and don't like it forced onto each project.

@babakness Since no one has replied, and someone else might stumble upon this (like I did), here is what you have to do:

`Settings > User settings > Text Editor`

Find the section saying `Code actions on save`, there is a link to `settings.json`.

Inside that file, change `"editor.formatOnSave": true,` to `false`.

**Comment by phillipkregg** [comment]
Thanks @sunyatasattva !  That's the answer.  A little infuriating that you have to dig so deep to turn off a "feature" that totally jacks up your code by default.

**Comment by TheJaredWilcurt** [comment]
> Settings > User settings (links to a new settings panel) > Text Editor > Code actions on save (links to settings.json) > editor.formatOnSave: false

So intuitive.

I'm really happy they put that setting there, instead of somewhere obscure and difficult to find like:

> Settings > Prettier Settings > Enable Prettier (uncheck)

A+ UX

**Comment by ackvf** [comment]
`Ctrl+shift+P`, type `settings`, there type `save` in the search box. Disable `Editor: Format On Save`
![image](https://user-images.githubusercontent.com/2313018/64620942-17190d00-d3e5-11e9-9449-64e97d42720b.png)

**Comment by jasonmcaffee** [comment]
thank you for opening this issue!  I like codesandbox, but having this enabled by default and no clear way of disabling it almost lost me as a user.

**Comment by Venryx** [comment]
Note: If you want the disabling of Prettier to apply for other users forking your sandbox, you can add a "/.vscode/settings.json" file, with these contents:
```
{
  "editor.formatOnSave": false
}
```

This can be helpful if your code is specially formatted, and you don't want users forking it to get confused when the formatting drastically changes, as soon as they make an edit.

**Comment by gnclmorais** [comment]
It would be cool if we could set a comment at the top of a file to single out only that file from being formatted…

**Comment by dantaylor** [comment]
Yes! that "per" file would be very useful!

**Comment by marcinczenko** [comment]
Format on save does not seem to be a right approach. I do have everything configured correctly in eslintrc file and I do want those to be automatically applied on save. In VSCode you can completely disable prettier in the settings. Here I do not see that option

**Comment by HoldOffHunger** [comment]
Is this ever going to get fixed?

**Comment by ChrisKulesza** [comment]
> # You just need these three super fast steps
> 1. type `user settings` in a command pallete Ctrl+shift+P
> 2. type `save` in the search box.
> 3. Disable `Editor: Format On Save`
> 
> ![image](https://user-images.githubusercontent.com/2313018/64620942-17190d00-d3e5-11e9-9449-64e97d42720b.png)
> 
> You can still format manually later, or you can format code selection. You can also save without formatting right away, without changing settings. `ctrl+shift+p` + `format`
> 
> ![image](https://user-images.githubusercontent.com/2313018/64621116-6b23f180-d3e5-11e9-9000-2a90412e6396.png)

Thank God for posting a picture. The whole internet seems to have no idea of the power of images.

**Comment by HoldOffHunger** [comment]
I solved this by taking one super fast single step:

1. Go to https://playcode.io/react and use a ReactJS environment with a working text environment.

**Comment by OldManMeta** [comment]
Why do you keep adding this junk back in as a default???

For the love of god, disable this type of stuff as default - it is complete garbage.

**Comment by wilsonpinto** [comment]
Hi, new user here.

I can't find a way to disable the `formatOnSave`.  This basically make it hard to use.

**Comment by xgqfrms** [comment]
# vscode solution ✅

![image](https://github.com/codesandbox/codesandbox-client/assets/7291672/6658d061-a7fe-4a7c-8c87-94ebc5ad52a8)


```json
{
  "diffEditor.ignoreTrimWhitespace": false,
  "editor.trimAutoWhitespace": false,
  "files.exclude": {
    "**/vendor/": true,
    // hiiden angular 1.x packages
    "**/.git": true,
    "**/.DS_Store": true,
    "**/jspm_packages": true,
    "**/node_modules": true,
    "**/.zip": true,
    "**/.sh": true
  },
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true
  },
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/*/**": true
  },
  "editor.formatOnSave": false,
  "editor.formatOnPaste": false,
  "editor.renderWhitespace": "all",
  "editor.fontSize": 16,
  "editor.tabSize": 2,
  "editor.multiCursorModifier": "alt",
  "editor.wordWrap": "on",
  "editor.insertSpaces": true,
  "files.encoding": "utf8",
  "[typescript]": {
    "editor.formatOnSave": false,
    "editor.formatOnPaste": false
  },
  "[javascript]": {
    "editor.formatOnSave": false,
    "editor.formatOnPaste": false,
    "editor.renderWhitespace": "all",
    "editor.foldingStrategy": "indentation",
    // "editor.foldingStrategy": "auto"
    // "editor.getOutliningSpans": ""
  },
  "[javascriptreact]": {
    "editor.formatOnSave": false,
    "editor.formatOnPaste": false,
    "editor.renderWhitespace": "all",
    "editor.foldingStrategy": "indentation"
  },
  "[markdown]": {
    "editor.formatOnSave": false,
    "editor.formatOnPaste": false,
    "editor.renderWhitespace": "all",
    "editor.acceptSuggestionOnEnter": "off"
  },
  "[html]": {
    "editor.formatOnSave": false,
    "editor.formatOnPaste": false,
    "editor.renderWhitespace": "all",
    "editor.acceptSuggestionOnEnter": "off"
  },
  "files.associations": {
    "*.jsx": "javascriptreact",
    "*.js": "javascriptreact"
  },
  "editor.snippetSuggestions": "top",
  // HTML & overwrite User settings.json
  "html.format.extraLiners": "",
  "html.format.enable": false,
  "html.format.contentUnformatted": "body, div, section, script, pre,code,textarea"
}

```
