### ISSUE TITLE
babel error Could not find module classCallCheck

### ISSUE THREAD

**Issue by eldyvoon** [CompuIves/codesandbox-client#1049]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?
I got this error using https://www.npmjs.com/package/material-ui-pickers

Could not find module in path: '@babel/runtime/7.0.0-beta.54/helpers/builtin/classCallCheck' 

Link to sandbox: https://codesandbox.io/s/o7m2lk4916

**Comment by CompuIves** [comment]
Hmm, that's very interesting. Do you also get this error when you install locally?

**Comment by eldyvoon** [comment]
It's working fine on my local, I used create-react-app.

**Comment by SaraVieira** [comment]
Hey!

This seems to have been fixed in the meantime. I still get an issue saying `cannot read proprety date of undefined` but I think that's unrelated

Feel free to reopen
