### ISSUE TITLE
Move "preferences" button to Sandbox header 

### ISSUE THREAD

**Issue by Arthelon** [CompuIves/codesandbox-client#105]
Current location of the "Preferences" button in the user dropdown is un-intuitive and hard to find. This can be remedied by moving the button toggle to the right side of the Sandbox header.

**Comment by Tushkiz** [comment]
Did you mean moving it between '+' and user dropdown?
Also can I take this up?

**Comment by CompuIves** [comment]
@Tushkiz That would be awesome! 😄 . Indeed between the + and the user dropdown. You don't have to remove the preferences from the dropdown itself, let's keep that one for better UX on other pages.

**Comment by Tushkiz** [comment]
Cool, I will create a PR.
Do we have label for "someone working on this"?
