### ISSUE TITLE
"ModuleNotFoundError: Could not find module in path: 'globalize/number' relative to '/node_modules/devextreme/localization/globalize/number.js'"

### ISSUE THREAD

**Issue by groshenkovamarina** [CompuIves/codesandbox-client#1051]
Hi!
I found this error when importing another devextreme module. Could you check if it's related to the [previous problem](https://github.com/CompuIves/codesandbox-client/issues/888)? 

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  
| Browser |  Chrome 68.0.3440.106 |
| Operating System |  Win 10 |

**Comment by CompuIves** [comment]
Hmm, it seems like the file refers to a module that doesn't exist (`globalize/number`). I just double checked and I couldn't find the module either (https://unpkg.com/globalize@1.4.0/number).

I think in this case CodeSandbox is showing the right behaviour!

**Comment by groshenkovamarina** [comment]
Yes, you right. In our project we have the alias  'globalize': 'npm:globalize/dist/globalize'. Is it possible to set the alias in the codesandbox?

**Comment by SaraVieira** [comment]
Hey!

We don't currently support that :/

I will though close this issue because the main problem has been solved.

Please create an issue for alias if you want :)
