### ISSUE TITLE
Autofocus steals cursor from the editor pane on every change

### ISSUE THREAD

**Issue by MatejBransky** [CompuIves/codesandbox-client#1057]
# 🐛 bug report

## Description of the problem

I'm building a form with an autofocus and I have enabled a live preview. Everytime I change something in the code then cursor jumps into the autofocused input in live preview so I must to click into the code again.

## How has this issue affected you? What are you trying to accomplish?

I'm trying to build an example with form and autofocus.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1535156273-be44bc6 (is it this?)
| Browser | Chrome 68
| Operating System | Kubuntu 18.04

**Comment by CompuIves** [comment]
Hmm, how would you think this can be fixed? I'm not sure if we can disable a focus in an iframe, but I'm also not sure if we want to alter behaviour of a sandbox. Otherwise the next issue will be a question from someone asking why autofocus doesn't work 😅.

**Comment by YoungElPaso** [comment]
I feel like (I can't really remember) that this is a Chrome(ium) issue but not present on Firefox. I did most of my stuff on Firefox recently, but switched back to Chrome in the last month.  Is there a work-around to re-focus on the editor?

**Comment by lbogdan** [comment]
Closing this, as it's expected browser behavior.

I'd probably disable the auto-focusing of form fields while working on something like that.

**Comment by elijahmanor** [comment]
I was wondering about this as well...

I ended up adding a local function (that I found from StackOverflow https://stackoverflow.com/a/326076). Now, when I click the "Open in New Window" button it'll get `autoFocus` and when I'm in the native iframed view it'll not `autoFocus`

```
function isInIframe () {
  try {
    return window.self !== window.top;
  } catch (e) {
    return true;
  }
}
```

```
<input
  type="text"
  value={name}
  autoFocus={!isInIframe()}
  placeholder="What's your name?"
  onChange={e => onChange(e.target.value)}
  onKeyPress={e => e.key === "Enter" && onExit()}
  onBlur={onExit}
/>
```
