### ISSUE TITLE
Make "+" button in Sandbox header a dropdown

### ISSUE THREAD

**Issue by Arthelon** [CompuIves/codesandbox-client#106]
To reduce space occupied in the header, the github import, default new sandbox, and cli upload behaviour should be combined into a single dropdown.

**Comment by CompuIves** [comment]
The idea is that the + icon will open a dropdown, An example mockup is this:

![screen shot 2017-08-16 at 15 23 31](https://user-images.githubusercontent.com/587016/29365375-16fdf1e2-8297-11e7-9951-b4c0507e7c68.png)

This will give us more space in the header and lets the user know that we have more than 'New Sandbox' (I think no one knows of the CLI...)

The New Sandbox should go to `/s/new`, the Import from Github should go to `/s/github` and the CLI option should go to `/s/cli`. We need a page for the latter one, if there's no time I can make it.

**Comment by CompuIves** [comment]
Assigned @Tushkiz to it!

**Comment by Tushkiz** [comment]
Great, Thanks 😅
