### ISSUE TITLE
Script tag in index.html does not run(REACT) in the owner point of view?

### ISSUE THREAD

**Issue by edwardfhsiao** [CompuIves/codesandbox-client#1060]
# ❔ Question
Script tag in index.html does not run(REACT) in the owner point of view.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Сodesandbox
| Browser | chrome
| Operating System |mac os

**Comment by lbogdan** [comment]
Seems to be working if you have a "proper" `index.html`: https://codesandbox.io/s/m42zx4k3v8 .

**Comment by edwardfhsiao** [comment]
@lbogdan I think I found the problem. It only works if it visited by others. If you open up it with your own account, it won't run. For example, you visit my link https://codesandbox.io/s/yj9l62nqw1 as a visitor, it alerts. I visit this link by Incognito window, it alerts. However, it won't work while I am creating or editing it as the owner. You can try to create a new react sandbox of your own see if it alerts.

**Comment by CompuIves** [comment]
Hmm, this may be related to HMR? For me it also works when I fork the sandbox.

**Comment by edwardfhsiao** [comment]
@CompuIves create a new one and see if it works

**Comment by edwardfhsiao** [comment]
that is very odd, today it works.
