### ISSUE TITLE
Documentation for deploying to Zeit?

### ISSUE THREAD

**Issue by tsongas** [CompuIves/codesandbox-client#1061]
# ❔ Question

Is there any documentation at all for deploying to Zeit? I'd like to have beginner students create projects with CodeSandbox and deploy to Zeit but I'm not seeing any instructions for that anywhere.

**Comment by CompuIves** [comment]
Hmm that's a good one, we don't have any docs about it yet. Would be good to have something for this!

You can make a deployment by clicking on the rocket icon in the sidebar and clicking 'Deploy'. You need to sign in with your ZEIT account before you can do that though.
