### ISSUE TITLE
Github sync connection error 409 - can't reconfigure which repo to sync to

### ISSUE THREAD

**Issue by mishabruml** [CompuIves/codesandbox-client#1062]
# 🐛 bug report

## Description of the problem

I deleted my sandbox repo on github. 

Sandbox Github tab does not allow re-configuration of which github repo to sync to, it just tries to connect to initial repo, which now does not exist, causing the 409 connection error.

## How has this issue affected you? What are you trying to accomplish?

Was trying to configure my sandbox to sync with a repo on my Github and I did this successfully then deleted the repo.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | site accessed 28/08/2018
| Browser | Firefox Quantum 61.0.2 (32-bit)
| Operating System | Windows 7 Professional

**Comment by SaraVieira** [comment]
Hey!

This is the expected behavior, we don't save anything so if you try to connect to a repo you deleted it will give you an error.

You will need to import the new one here: https://codesandbox.io/s/github

Closing as this is expected
