### ISSUE TITLE
Option to still show file tabs in zen mode

### ISSUE THREAD

**Issue by johnhamm** [CompuIves/codesandbox-client#1064]
# 🌈 Feature

I really like zen mode, except I would still want to more easily switch between my active documents by clicking on their tabs.

**Comment by arthurdenner** [comment]
I was trying ZenMode and noticed that besides the tabs, it doesn't show the options to Prettify, Toggle Console, etc.

@CompuIves is this something you would consider, a config to show the Tabs component instead of FilePath in ZenMode?

**Comment by SaraVieira** [comment]
Hey!

Zen mode has been updated with VSCode so now it uses their zen mode and still shows tabs and toggle browser button

![Screenshot 2019-04-05 at 16 44 09](https://user-images.githubusercontent.com/1051509/55635945-25be2100-57c2-11e9-99d1-09bf04340a1a.png)
