### ISSUE TITLE
Failing to load CSS resources

### ISSUE THREAD

**Issue by johnhamm** [CompuIves/codesandbox-client#1067]
# 🐛 bug report

## Description of the problem
External CSS resources in my index.html are now failing to load - even though I see HTTP requests for them with status 200.  They worked fine yesterday til about 8 or 9pm EST.

## How has this issue affected you? What are you trying to accomplish?
My HTML is not rendering styles correctly now since they aren't found.  I noticed in the network tab that a 404 is happening when trying to load /api/v1/sandboxes/[forked address here] cache (it appears to be loading cache from the private sandbox it was forked from)

Here is the contents of my index.html:

```
<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Test</title>
	<base href="/">

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<link href="https://cdn.jsdelivr.net/npm/@progress/kendo-theme-default@latest/dist/all.css" rel="stylesheet" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Arimo|Source+Sans+Pro|Roboto+Mono|Roboto:300" rel="stylesheet">
	<link href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" rel="stylesheet" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
</head>

<body>
	<app-root></app-root>
</body>

</html>
```

(Coincidentally, this sandbox also gets the "ModuleNotFoundError
Could not find module in path: '@angular/animations/browser' relative to '/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js'" error too.  To see that, edit index.html and save.  It seems to appear once every four or five saves?)

Also getting about 50 or so warnings that it couldn't load the source maps for rxjs.

![2018-08-30 16_42_51-devtools - codesandbox io_s_jljyv26o23](https://user-images.githubusercontent.com/3343496/44878025-cc15d700-ac73-11e8-9125-29b4c3b63d66.png)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Browser | Chrome 68.0.3440.106 (Official Build) (64-bit)
| Operating System |Windows 10

**Comment by SaraVieira** [comment]
Hey!

Sorry for the long time to reply but it seems to have been a weird bug that is now fixed

Feel free to reopen if any other issues appear :)
