### ISSUE TITLE
Parcel sandbox not working in firefox

### ISSUE THREAD

**Issue by bobylito** [CompuIves/codesandbox-client#1070]
# 🐛 bug report

## Description of the problem
We have a project that is based on Parcel which does not run on firefox but is working correctly in other browsers. The "weird" thing is that we load our library outside of parcel.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | firefox 62 (developer edition)
| Operating System | MacOS

There is probably something stupid I fail to see here :( Thanks :) (for the project that is just amazing and the time looking at my bug)

**Comment by CompuIves** [comment]
Oh man that's super bad. I think this is related to #1050 and that issue should get a lot more attention now if this blocks Firefox. Thanks for letting me know!

**Comment by sansnom** [comment]
I've the same problem with a dead simple "Hello World" with AngularJS which is not working on Firefox 62: [https://codesandbox.io/s/7v6z1j0yq](https://codesandbox.io/s/7v6z1j0yq). I spent one hour wondering why it was not working until I switched to chrome. :D

**Comment by SaraVieira** [comment]
Hey!

This is still an issue I am gonna close it as the reason is the one mentioned in https://github.com/CompuIves/codesandbox-client/issues/1050 and it has been bumped
