### ISSUE TITLE
Add tags (like next or latest) in version list when adding a dependency

### ISSUE THREAD

**Issue by etienne-dldc** [CompuIves/codesandbox-client#1071]
# 🌈 Feature

## What is this feature?

Currently when you add a dependency you can choose the version but you can't see tags like `next` or `latest`

<img width="742" alt="screen shot 2018-09-04 at 03 17 48" src="https://user-images.githubusercontent.com/14336608/45005057-936a5a80-aff1-11e8-88f1-c6959f53e751.png">

## How the feature should ~~work~~ look like ?

Maybe something like this:
<img width="781" alt="screen shot 2018-09-04 at 03 22 50" src="https://user-images.githubusercontent.com/14336608/45005120-e8a66c00-aff1-11e8-8208-7c72f50924f7.png">

**Comment by melanieseltzer** [comment]
Added via #1110 😄

**Comment by etienne-dldc** [comment]
Closing because It has been implemented by @melanieseltzer (thanks 😊)
