### ISSUE TITLE
Crashing Chrome Browser

### ISSUE THREAD

**Issue by Mohammad-Quanit** [CompuIves/codesandbox-client#1078]
# 🐛 bug report
Crashing chrome browser

## Description of the problem
Crashing chrome browser and show black screen
## How has this issue affected you? What are you trying to accomplish?
I am doing a react project on codesandbox and after a while my browser crashes and my laptop screen goes blank. I restart my laptop but then after opening my project again, it again crashes and screen goes black again.Don't know what is the problem? If anyone here is relate able to this?

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | https://codesandbox.io/s/2vk81xqm2j
| Browser | google chrome 
| Operating System | windows 10

**Comment by Komar0ff** [comment]
Hello! I check you main.js and see wrong import with strange name 
```js
import BulbOn from "";
```
For this reason, the application crashes.
If you change the name or add a normal path, everything will work.
But this is a very strange bug in which I have not yet found patterns.

**Comment by CompuIves** [comment]
Very good find @Komar0ff! Thank you! I'm now creating a commit with a check for this.

**Comment by CompuIves** [comment]
<img width="1680" alt="screenshot 2018-09-07 18 35 31" src="https://user-images.githubusercontent.com/587016/45234174-d0be3900-b2cc-11e8-83ff-f3d44a13595e.png">

This will be the new error.
