### ISSUE TITLE
Better flow for dependency installation

### ISSUE THREAD

**Issue by ritz078** [CompuIves/codesandbox-client#108]
Currently if you want to load any dependency, it asks if you want to add it and adds the latest stable dependency. If I want to change the version I have to go to the dependencies tree and then remove it and then add it with new version. This flow is a bit tedious.

<img width="1379" alt="screen shot 2017-08-14 at 8 43 01 pm" src="https://user-images.githubusercontent.com/5389035/29278302-f35dfea0-8131-11e7-8028-578b427675ff.png">

It will be great if we can select the version before clicking on add dependency. If I click on "Add dependency" without selecting any version, it can default to latest stable branch.

**Comment by CompuIves** [comment]
This is a really nice suggestion, and would fit really well with the new suggestions (since we can now add multiple suggestions).

**Comment by tansongyang** [comment]
I'm interested in helping with this issue. I took a look at the code, and it seems like `src/sandbox/errors/dependency-not-found-error.js` and `src/sandbox/react-error-overlay/components/suggestions.js` are the relevant files.

A couple of questions:

1. Do you want to actually list every available version? Or do you want to just present a text input to let the user type the version in? The second option would be more consistent with the existing behavior of the Dependencies section in the left menu.
2. Is there documentation on the `codesandbox-api` methods. I see that, currently, `DependencyNotFoundError` calls `dispatch(actions.source.dependencies.add(parsedName)`. Is there another argument that takes the version?

**Comment by CompuIves** [comment]
Great @tansongyang!! I think best scenario would be to show list of all major semver versions (eg. React has `15.5.6` and `16.0.0` etc.).

The api is a documented in the docs folder (https://unpkg.com/codesandbox-api@0.0.6/dist/docs/index.html). The second argument can be a version, if it's omitted it will install latest version. You can give it any kind of version (`latest`, `^16.0.0`, etc.)

I recommend to start on it from tomorrow. I'm going to merge a pretty hefty PR in this field that can open some merge conflicts (small change though).

**Comment by tansongyang** [comment]
OK. I want to clarify what "all major semver versions" means.

Let's say `package` has versions 0.0.1, 0.0.2, 0.1.0, 1.0.0, 1.0.1, 2.0.0, 2.1.0, 2.2.0. Would we only list 0.1.0, 1.0.1, and 2.2.0?

I will hold off on my other questions until after your PR.

**Comment by ritz078** [comment]
I would rather prefer an autosuggest input box with all the versions available and sorted with latest version at the top.

**Comment by CompuIves** [comment]
Hmm, I think that would be best as well. Though the error layout is currently behind an API with suggestions, this way others can easily add suggestions as well. Suggestions only support buttons currently, not inputs. So we could either expand the current API or use buttons.

**Comment by tansongyang** [comment]
Here's an alternative I just thought of. What if, when the user clicks the current add button, Codesandbox expands the left menu, fills out the name of the package, and puts your focus on the version input. From here, you can easily type your desired version, or just tab to the "Add Package" button.

Pros

* We can leverage the existing control.
* We don't have to change the existing suggestions API.

Cons

* The user might not realize what happened. We'd have to make it very obvious to the user to look at the left menu.

**Comment by CompuIves** [comment]
I like your suggested solution, I'm working on autocompleting dependencies and versions there, so you get that for free too. In that case I'd suggest to show 2 suggestions: 'add latest version of dependency' and 'add custom version'.

Hmm, now that I think of it... Maybe we could rework dep adding in general. I'm thinking that we should make 'Add Dependency' just a button, and show an input overlay modal when pressed. When you type into this modal we show suggestions (using Algolia). Good inspiration is how https://ellie-app.com/new handles it, but then in an overlay.

**Comment by CompuIves** [comment]
I mean this with overlay:

![screen shot 2017-10-12 at 14 48 37](https://user-images.githubusercontent.com/587016/31496636-7bc1d2b4-af5c-11e7-9f9d-ef7989ecbd07.png)

This allows us to easily show dropdown autocompletions with dependency names/descriptions/download counts.

**Comment by tansongyang** [comment]
I like this idea as well. I don't know Algolia, but some preliminary searching reveals [algolia/npm-search](https://github.com/algolia/npm-search), which seems like it could be useful.

**Comment by CompuIves** [comment]
Yah, they provide the search for yarnpkg.com and we use them for codesandbox.io/search. They already gave me they API codes to use the yarn search, so we could actually already start implementing it 😄 .

**Comment by tansongyang** [comment]
Sounds good. I plan to start on it this weekend.

**Comment by CompuIves** [comment]
We got the overlay now, so I think we can close this 😄.
