### ISSUE TITLE
Unable to link css file in React

### ISSUE THREAD

**Issue by SquidAnan** [CompuIves/codesandbox-client#1084]
# 🐛 bug report

## Description of the problem
I created a new sandbox and chose React
I try to link css file by adding a link tag in `index.html`
And put the css file in the `public` folder
But it seems like the css file isn't loaded

It did work a while ago.
Perhaps there were some updates related to Codesandbox?

(I deleted/commented some part of the code.)

## How has this issue affected you? What are you trying to accomplish?
The style doesn't work

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1536432595-55d2418
| Browser | Chrome / 69.0.3497.81
| Operating System | Windows10

**Comment by CompuIves** [comment]
Found the bug for this! Writing fix now.

**Comment by CompuIves** [comment]
Fixed!

**Comment by ar-naseef** [comment]
seems like its not fixed..!
