### ISSUE TITLE
Mouse scrolling does not work in Monaco or the CodeMirror in VIM mode

### ISSUE THREAD

**Issue by nemtsov** [CompuIves/codesandbox-client#1087]
# 🐛 bug report

## Description of the problem

Mouse scrolling does not work in Monaco or the CodeMirror in VIM mode. Scrolling with the trackpad works as expected.

## How has this issue affected you? What are you trying to accomplish?

I can't scroll in the editor with my mouse.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  PROD-1536623422-8794c0e |
| Browser | Chrome 69.0.3497.81 |
| Operating System | Mac 10.13.6 |

**Comment by SaraVieira** [comment]
Issue closed as we dropped the monaco editor and also codemirror in the latest release
