### ISSUE TITLE
Don't change the case of author username.

### ISSUE THREAD

**Issue by ritz078** [CompuIves/codesandbox-client#109]
I think people want their username to remain in the case they want as its their online identity.

<img width="257" alt="screen shot 2017-08-14 at 8 51 02 pm" src="https://user-images.githubusercontent.com/5389035/29278455-6c8477d2-8132-11e7-8736-ac3b25e96bf0.png">

**Comment by CompuIves** [comment]
Hmm, you could be right. I agree that we should disable it in that case.

**Comment by tcosentino** [comment]
I think this has already been fixed? 

<img width="262" alt="screen shot 2017-08-25 at 8 27 38 pm" src="https://user-images.githubusercontent.com/1531641/29736923-f85655a6-89d3-11e7-9bd0-a65b68412f0f.png">

**Comment by chakrihacker** [comment]
yes @tcosentino

**Comment by CompuIves** [comment]
Oh yep right, marking as fixed.
