### ISSUE TITLE
Loader 'coffee-loader' could not be found.

### ISSUE THREAD

**Issue by zew13** [CompuIves/codesandbox-client#1090]
https://codesandbox.io/s/zkzvrv73op

i write script lang="coffee" in components/reply.vue

![image](https://user-images.githubusercontent.com/802607/45581718-cd7f0a80-b8d5-11e8-8227-788aa66095a9.png)

i already add coffee-loader to dependencies and config my webpack config

![image](https://user-images.githubusercontent.com/802607/45581699-82fd8e00-b8d5-11e8-9c28-49b413ea1630.png)

**Comment by SaraVieira** [comment]
Closed by https://github.com/CompuIves/codesandbox-client/pull/1467
