### ISSUE TITLE
there is no response in the sandbox

### ISSUE THREAD

**Issue by MuYunyun** [CompuIves/codesandbox-client#1091]
# ❔ Question

I use `webpack-dev-server --open` to run my app normally in my local enviroment, and I use the same webpack config and other codes to copy in the sandbox, but there is no response in the sandbox. I wonder if it don't suppor webpack-dev-server or there is some wrong operation in other place.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | [link](https://codesandbox.io/s/0xk1r2zmk0) (optional) |
| Browser |  chrome 69 |
| Operating System | mac 10.13.2 |

and when I click the project view, it shows as follow:
![image](https://user-images.githubusercontent.com/19354791/45582659-543be380-b8e6-11e8-9ab1-9af6ec8cd53f.png)

and click the current module view:
![image](https://user-images.githubusercontent.com/19354791/45622485-b8ad9d00-bab6-11e8-87b9-e0afc770a285.png)

**Comment by SaraVieira** [comment]
Hey!

You are using a client sandbox and in those, we do not support it that is correct :/

I would advise you to start a new node container and try there: https://codesandbox.io/s/node

In here the npm start command will be run so it will support webpack :)

Closing as this is expected, feel free to reopen :)
