### ISSUE TITLE
how to run codesandbox-client

### ISSUE THREAD

**Issue by dkypooh** [CompuIves/codesandbox-client#1095]
I want to run the project, clone from master branch, run `npm run start`, dependence environment always fail。 then I feel the project needs install package in different folder
Can you write a tutorial， thx @CompuIves

**Comment by arthurdenner** [comment]
Hey @dkypooh. :wave: 

I don't think `npm run start` works because the project uses Yarn workspaces.

Try following the [contribution guideline](https://github.com/CompuIves/codesandbox-client/blob/master/CONTRIBUTING.md) to run the project locally.

**Comment by lbogdan** [comment]
Closing this, as @arthurdenner mentioned, following the contributing guidelines should get you started in no time! 🙂
