### ISSUE TITLE
ModuleNotFoundError Could not find module in path

### ISSUE THREAD

**Issue by joelnet** [CompuIves/codesandbox-client#1098]
# 🐛 bug report

## Description of the problem

Error:
```
ModuleNotFoundError
Could not find module in path: 'mojiscript/utils/tap' relative to '/node_modules/mojiscript/console/log.js'
```

Line: `import log from "mojiscript/console/log";`

Running `npm start` locally works without any problems. Error only appears on CodeSandbox.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Web
| Browser | Chrome 68.0.3440.106 (Official Build) (64-bit)
| Operating System | OSX
| Node | v10.3.0

**Comment by CompuIves** [comment]
Hey! We were thrown of with the space right after the require there. I committed a fix and will deploy it today!

**Comment by joelnet** [comment]
lol people code crazy. Can't predict that. I never would have guessed at white space as the issue. Cheers!
