### ISSUE TITLE
Manually set font always resets to dank

### ISSUE THREAD

**Issue by Haroenv** [CompuIves/codesandbox-client#1099]
# 🐛 bug report

## Description of the problem

While I do like Dank, I didn't buy it and prefer to have the same font everywhere. Because of that I set the custom font to Fira Code in my settings.

While the settings do say `Fira Code` under custom font, the font will always be Dank upon a reload. I can make it back the font I want by going to settings, deleting a character in the custom font and adding it back. 

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1536623422-8794c0e |
| Browser | Safari (Release 63 (Safari 12.1, WebKit 13607.1.2.1)) |
| Operating System | MacOS High Sierra (10.13.6 (17G65)) |

**Comment by shahzaibkhalid** [comment]
Is there any update regarding this?

It's very annoying to open settings dialog every time and save it just to load the custom font.

**Comment by CompuIves** [comment]
Interesting, this issue slipped me. I was not aware of the behaviour. I'll take a look at this tomorrow.
