### ISSUE TITLE
Search on the docs

### ISSUE THREAD

**Issue by Haroenv** [CompuIves/codesandbox-client#1100]
# 🌈 Feature

## What is this feature?
adding [DocSearch](https://community.algolia.com/docsearch) to [/docs](https://codesandbox.io/docs).
## How the feature should work?

If you type in the search bar, you will find answers in the docs.

## You have examples or an idea how it can be implemented?

Adding an input to the sidebar, an input and a similar lazy loading strategy as on the react docs: 

https://github.com/reactjs/reactjs.org/blob/master/src/components/LayoutHeader/DocSearch.js

You have to apply (as site owner) on the DocSearch website first :)

**Comment by SaraVieira** [comment]
@Haroenv 
![Screenshot 2019-04-01 at 18 02 40](https://user-images.githubusercontent.com/1051509/55342133-5e02ee00-54a8-11e9-990b-95a31f20d416.png)

I may have not read the last sentence 😂

**Comment by s-pace** [comment]
Thanks @SaraVieira for applying. I have replied to your application by email, you can check the details.

You're now a few steps away from having it working on your website

- Copy the following CSS/JS snippets and add them to your page 

```html
<!-- at the end of the HEAD --> 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" /> 

<!-- at the end of the BODY --> 
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script> 
<script type="text/javascript"> docsearch({ 
apiKey: '45db7de01ac97a7c4c673846830c4117', 
indexName: 'codesandbox', 
inputSelector: '### REPLACE ME ####', 
debug: false // Set debug to true if you want to inspect the dropdown 
}); 
</script> 
```
- Add a search input in your page. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field. 
- Optionally customize the look and feel by following [the DocSearch documentation](https://community.algolia.com/docsearch/styling.html) 
- You can also [check your configuration in our GitHub repo](https://github.com/algolia/docsearch-configs/blob/master/configs/codesandbox.json).

**Comment by SaraVieira** [comment]
Thank you both @Haroenv and @s-pace :D

I made a PR to add it worked out of the box 💯 

https://github.com/CompuIves/codesandbox-client/pull/1692
