### ISSUE TITLE
Ligatures on Dank font enable those that change cursor position

### ISSUE THREAD

**Issue by Haroenv** [CompuIves/codesandbox-client#1101]
# 🐛 bug report

## Description of the problem

The ligatures enabled in the dank mono font when ligatures are enabled also enable those ligatures that are destructive (i.e. `fl`), just like in #728. I suspect this might be a wrong `font-feature-settings` for Dank? 

## How has this issue affected you? What are you trying to accomplish?

![2018-09-21 09-18-43 2018-09-21 09_19_31](https://user-images.githubusercontent.com/6270048/45866128-1294b800-bd80-11e8-8adb-7ac93920b57c.gif)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1536623422-8794c0e |
| Browser | Safari (Release 63 (Safari 12.1, WebKit 13607.1.2.1)) |
| Operating System | MacOS High Sierra (10.13.6 (17G65)) |

**Comment by lbogdan** [comment]
Closing this, as I can't replicate, I'm thinking it was fixed with the switch to VSCode as the default editor.

However, @Haroenv feel free to reopen if you still experience this behavior.
