### ISSUE TITLE
Sidebar Resizer handle's style is out of order

### ISSUE THREAD

**Issue by cooljith91112** [CompuIves/codesandbox-client#1104]
# 🐛 bug report

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser |  69.0.3497.100
| Operating System | Windows 10

![resizer-issue](https://user-images.githubusercontent.com/2651484/45946340-4127c280-c00e-11e8-8bf8-a781baf9a4fc.png)

**Comment by SaraVieira** [comment]
Hey!

I am gonna close as in the latest version you can't move the preview to the bottom anymore
