### ISSUE TITLE
Is there a way to run custom scripts in react codesandbox?

### ISSUE THREAD

**Issue by kstulgys** [CompuIves/codesandbox-client#1106]
I want to go through some tutorials where I need to create a server and use express and mongoose. Is it possible to run some custom scripts in codesandbox like **server: "nodemon server.js"**. I want to use it with react.

**Comment by CompuIves** [comment]
Hey! This is perfect timing, we're releasing something this week that allows you to do this. It's a new kind of sandbox that's evaluated on the server and allows you to run any scripts defined in the `package.json`.

You can play and test with it on staging: https://codesandbox.stream/s/gatsby. Note that sandboxes aren't persisted here though, we're releasing it most probably within the next 2 days.

**Comment by CompuIves** [comment]
Oh yep! We can close this one, we go through a list of scripts (like `start`, `dev`) to find what to run first.

**Comment by vzaidman** [comment]
is it documented somewhere?
is there a plan to add it as a config in `sandbox.config.json` ?
