### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by gyoshev** [CompuIves/codesandbox-client#111]
Do you plan on supporting sandboxes based on TypeScript? At first glance it appears that it can be achieved by compiling TypeScript files through the sandbox eval, not unlike SystemJS does.

**Comment by CompuIves** [comment]
Yep, I'm implementing TypeScript this week. 😃

**Comment by niieani** [comment]
Hey @CompuIves, any news on this? :) Would love to use TS in CodeSandbox!

**Comment by CompuIves** [comment]
Hey @niieani, TS support has been added. It's only in the Vue template at this moment, because the Vue cli supports it natively. 

I'm adding template ejecting (so you can customize CRA) next week, so it'll probably be supported in CRA next week!

**Comment by niieani** [comment]
That's great news indeed! Thanks. Does ejecting mean we will be able to make our own, custom presets? Also, what's a CRA?

**Comment by CompuIves** [comment]
> Does ejecting mean we will be able to make our own, custom presets? 

Exactly, you'll be able to specify if you use sass, css modules, typescript, babel config, etc. 

> Also, what's a CRA?

Sorry for being a bit unclear! I mean `create-react-app` with that.

**Comment by niieani** [comment]
Fantastic. Some time ago I've hacked-in Aurelia support by removing React defaults here: https://codesandbox.io/s/2w8J7n9W. It would be nice to have a template/preset for it too!

**Comment by CompuIves** [comment]
Wow, nice @niieani! I'll add Aurelia to the list.

**Comment by CompuIves** [comment]
This is landing tomorrow. There, I said it!

**Comment by CompuIves** [comment]
Almost merging it in, PR is here: https://github.com/CompuIves/codesandbox-client/pull/192

**Comment by CompuIves** [comment]
Hah, just in time for the deadline! 😄 

TypeScript support is now available:

https://codesandbox.io/s/react-ts

**Comment by tkrotoff** [comment]
Would be nice to list the TypeScript template on the front page

**Comment by davidm-public** [comment]
trying to create a vue typescript sandbox, not seeing how to do that?

**Comment by davidm-public** [comment]
struggling with Vue Typescript, looks like `<script lang="ts">`is being ignored.

see:  https://codesandbox.io/s/vy8923vpq0

Also not sure what the file `index.js` is doing, seems to be marked as 'main', and undeletable?

Hoping to get Vue and Typescript working, because that's beyond the capabiity of other online sandboxes!

Thanks 
David

**Comment by CompuIves** [comment]
Hey @davidm-public! I just noticed that we only checked for `lang="typescript"` for Vue templates, I added `lang="ts"` as viable option with this PR: https://github.com/CompuIves/codesandbox-client/compare/fix/vue-ts?expand=1.

I will also add the option to change the `main` entry somewhere this or next week.
