### ISSUE TITLE
Editor font is reset to default when loading sandbox in new browser window

### ISSUE THREAD

**Issue by evgeniyp** [CompuIves/codesandbox-client#1111]
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | https://codesandbox.io/s/2x0vv41voj |
| Browser | Version 69.0.3497.100 (Official Build) (64-bit) |
| Operating System | Microsoft Windows [Version 10.0.17134.286] |

There is a workaround: enable "use codemirror" in settings.

**Comment by SaraVieira** [comment]
Issue closed as we dropped the Monaco editor in the latest release and this appears to have been a Monaco issue
