### ISSUE TITLE
Gatsby template won't serve uploaded images

### ISSUE THREAD

**Issue by jimthedev** [CompuIves/codesandbox-client#1114]
# 🐛 bug report

## Description of the problem

In the Gatsby SSE when loading images that have been uploaded to a sandbox they do not seem to be able to be loaded by Gatsby. The gatsby-icon.png which comes included in the sandbox does seem to be able to be loaded.

## How has this issue affected you? What are you trying to accomplish?

I am trying to upload an image to codesandbox then have gatsby serve it out. You can reproduce the issue by changing line 14 of src/components/layout.js from `/sandbox/src/images/gatsby-icon.png` to `/sandbox/src/images/gatsby-icon-new.png` (which is the same file, just uploaded by me. Hit save, then hit refresh in the fake browser. You will see that the image ends up being null in the props. 

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1538077445-546871f
| Browser | Chrome 69.0.3497.92
| Operating System | OSX

**Comment by lbogdan** [comment]
Hey @jimthedev , thanks for opening this issue, and sorry for the late reply!

This was a known issue since we launched CodeSandbox Containers, which was finally fixed in the quite big update we deployed last night. Please test and close this if it works as expected.
