### ISSUE TITLE
🐛Typescript theme error

### ISSUE THREAD

**Issue by babakness** [CompuIves/codesandbox-client#1115]
When using generic, unless two generics are used, the theme breaks. See repo

https://codesandbox.io/s/v049qzxmp5

<img width="754" alt="v049qzxmp5_-_codesandbox" src="https://user-images.githubusercontent.com/2024235/46185438-adb0f480-c28e-11e8-852a-4898ae6650d5.png">

This is on Chrome 69, MacOS 10.13.5

**Comment by lbogdan** [comment]
Closing this, as I can't replicate, and I'm quite confident it was fixed with the switch to VSCode as the default editor.

However, @babakness feel free to reopen if you still experience this behavior.
