### ISSUE TITLE
🌈 Terminal changes to files in sync in file browser on codesandbox

### ISSUE THREAD

**Issue by babakness** [CompuIves/codesandbox-client#1117]
# 🌈 Feature

## What is this feature? 
Currently there seems to be a disconnect between the files created on the terminal and the files that show up on the side panel. 
## How the feature should work? 
When a file is created in the terminal, ie `touch foobar` the same files appears in the sidebar file browser.

**Comment by olegdovger** [comment]
I can create a file using commands from CLI, and I even could see results using commands - `ls` and `cat` BUT I cannot see any changes in directories visually.

**Comment by CompuIves** [comment]
Fix will land coming week for this!

**Comment by lbogdan** [comment]
We just deployed this, please see the discussion in #1137 .
