### ISSUE TITLE
Private environment variables in terminal

### ISSUE THREAD

**Issue by babakness** [CompuIves/codesandbox-client#1119]
It could be interesting if keys or secrets could be in a private area of the users profile; these variables could be present in the terminal area--one could, for example, make git commits from the web terminal. Would be insane!

**Comment by lbogdan** [comment]
Closing this, as we not have the possibility of defining secrets for server sandboxes. Feel free to reopen if that's not quite what you want, and maybe detail your use-case a bit more.
