### ISSUE TITLE
 can't select all code 

### ISSUE THREAD

**Issue by Vill3m** [CompuIves/codesandbox-client#112]
Hi! Why can't select all the code and how to disabled minimap? This problem is in chrome, firefox works well
![codesandbox](https://user-images.githubusercontent.com/12127927/29351391-34e3c3e8-826b-11e7-9f34-49707cee9077.gif)

**Comment by Radi123** [comment]
Yes I saw this problem for first time yesterday on 11 PM UTC +03:00
Actually if you copy it (CTRL+C) All'll be copied. The problem is in the cursor and selection. They're three positions left.

**Comment by Radi123** [comment]
View this: https://www.youtube.com/watch?v=tY2w5NAlvLM&feature=youtu.be

**Comment by Vill3m** [comment]
@Radi123  yes all code'll be copied, but work is not comfortable

**Comment by Radi123** [comment]
@Vill3m I'm trying to find the problem in the source & fix it, but we need expert in the sandbox.
Please help - @CompuIves

**Comment by Radi123** [comment]
I think the problem is around lines 332 & 625 of `/src/app/components/sandbox/CodeEditor/Monaco.js`
https://github.com/CompuIves/codesandbox-client/blob/master/src/app/components/sandbox/CodeEditor/Monaco.js#L332
https://github.com/CompuIves/codesandbox-client/blob/master/src/app/components/sandbox/CodeEditor/Monaco.js#L625

**Comment by CompuIves** [comment]
Looking into it.

**Comment by CompuIves** [comment]
This is good info, thanks for the clear examples @Vill3m and @Radi123. What operating systems are you using?

**Comment by CompuIves** [comment]
Okay, deployed a new version with minimap disabled. Could you verify if the issue has been fixed?

**Comment by Radi123** [comment]
I'm using Windows `10.0.15063`, Chrome 60 (`v60.0.3112.101  64-bit`)

**Comment by CompuIves** [comment]
Ah I see, I think this issue only happens on Windows. Does it also happen without the minimap?

**Comment by Radi123** [comment]
Yes @CompuIves https://www.youtube.com/watch?v=3wkSvNjNlFk

**Comment by CompuIves** [comment]
Aii, hmm. What does your console show after load? Also, could you take screenshot of this? Thanks for the quick responses! Really valuable.
![screen shot 2017-08-16 at 16 25 40](https://user-images.githubusercontent.com/587016/29368289-93c259c2-829f-11e7-9c8f-5127e31db52e.png)

**Comment by Radi123** [comment]
@CompuIves 
![image](https://user-images.githubusercontent.com/12954909/29368397-4466f49c-82a8-11e7-9b61-2d8b9aa8e626.png)

![image](https://user-images.githubusercontent.com/12954909/29368442-65fbbbf6-82a8-11e7-9d04-7e600ef39189.png)

**Comment by Vill3m** [comment]
@CompuIves win7x64 chrome last version and chrome canary have this bug

**Comment by CompuIves** [comment]
Okay, I'm able to reproduce it using BrowserStack. Will find out what's causing this.

**Comment by CompuIves** [comment]
Think I found the cause, has to do with font families. Trying to fix it...

**Comment by CompuIves** [comment]
That's it! Deploying new version for now that disables font family editing.

**Comment by CompuIves** [comment]
Deployed, could you verify that it's fixed @Vill3m?

**Comment by Vill3m** [comment]
@CompuIves It's working)

**Comment by CompuIves** [comment]
Great!! Marking 'fixed' with https://github.com/CompuIves/codesandbox-client/commit/d45ff5cc8c4ffc172107b491bafe2124f3516d58.

**Comment by Radi123** [comment]
Working! @CompuIves Now you can try to return the mini map by default - it was cool.

**Comment by CompuIves** [comment]
Will come as an option @Radi123 😄

**Comment by Radi123** [comment]
Cool
