### ISSUE TITLE
🌈 Add Support for Environment Variables

### ISSUE THREAD

**Issue by Saeris** [CompuIves/codesandbox-client#1122]
As discussed in Discord earlier this morning, this is a request for a new feature which would add environment variable support to CodeSandbox. In this issue we'll be looking at this feature using `.env` as a metaphor for how this feature may work.

First let's get a broad overview of how this would be implemented:

- **User Interface:**
For each sandbox, a user would be able to use a new tab in the console tray ( ie: console / problems / tests / terminal / _environment_ ) to add/remove/edit key/value pairs which will be injected into `process.env`, each with two additional check boxes for "Make Public" and "Required". Variables marked "Make Public" will have their values shared with all users (ie: the value field would become the "default" value for it's key). "Required" would pause preview evaluation until a value is set. When a required variable is missing a value, the console tray tab would display an error indicator with a count for the number of missing required fields to draw a user's attention. While preview evaluation is paused, information should displayed in the preview pane which explains 1) that there are missing required fields and 2) warning users to be cautious about entering sensitive data such as API keys, advising them to first take a look through the code.

- **API:**
All of these values will be persisted to CodeSandbox's servers on a per Sandbox + per Account basis, meaning that every user will have a different set of environment variables for every individual sandbox they open. At no point would a user have access to another user's environment variables. Variable keys, default values, and flags should be saved to a file. Anonymous users will have empty/default values every time they visit a sandbox. When a Sandbox is forked, the new fork will have their values cleared and reset to their default values. This is to ensure that you and only you have access to the environment variables you set. Environment variables are not global, so no sandbox will have access to variables set in another sandbox.

- **Other Considerations:**
To best support existing projects, keys/values may be imported from a project's `.env` and `.env.default` files, however the UI should not ever save changes out to these files. This would be to prevent accidental publishing of sensitive information. Keys/defaults/flags may best be persisted to `sandbox.config.json` under an `environment` key, which would support exporting/re-importing/forking of sandboxes. If possible, it may be advantageous to persist values to localstorage for anonymous users in the event that the user accidentally navigates away from the page, which would otherwise wipe any changes they've made to a sandbox. However, that may come with additional security concerns. Additional support for Teams/Live code sessions could be added as well, allowing users to share environment variables with members of their team or participants in a live coding session.

As for a technical implementation, I imagine that on opening a sandbox, keys/values/flags would be read from `sandbox.config.json`, `.env.default`, and `.env`,  then if a user is logged in, keys/values/flags previously persisted to their account for this sandbox would be merged, overwriting any existing variables, and finally any keys/values in `.env` will be merged, ensuring that `.env` always takes priority as the single source of truth for a project's environment variables. The resulting variables would then be stored in the client's state and would be merged into `process.env`, making those variables available to the sandbox preview itself. When the user makes any changes via the environment UI, those variables will be persisted to the server and any changes to keys/defaults/flags would be written to `sandbox.config.json`. For anonymous users, the server persist step would be skipped.

Overall I think with the addition of server sandboxes something like this will be needed to support non-trivial use cases. It would greatly expand the range of projects users can create while helping to protect their data.

If you think I've left out something important, please leave a comment!

**Comment by Saeris** [comment]
@jbolda tagging you as requested!

**Comment by ValentinH** [comment]
Being able to have private environment variables is the first thing I thought about when I learnt about the containers feature. I came here to look for issues and I'm so glad you already provided such a nice and detailed solution!

A good inspiration for a less ambitious start could be taken from what is done on glitch.com with the `.env` file: basically, the values are stripped for non-contributors.

**Comment by Saeris** [comment]
I think it should certainly be possible to to tie sandbox specific variables to both individual user accounts and teams. Team variables would take precedent, as if I understand teams correctly, sandboxes belonging to a team are different than sandboxes belonging to an individual user. Any member of a team would be able to use and change those variables when they open the sandbox, and forking a team's sandbox would wipe the variables just like forking any other sandbox would, though the fork would then belong to that individual user.

A more complicated consideration would be for live sharing. In that situation I think it's reasonable that environment variables would be shared with all participants for the session, but only the host of the session would be able to change those variables. All participants besides the host (the owner) would have those variables cleared once the live session ends. That would require that server persistence is skipped for participants whenever a change is made.

The problem with keeping the values in a file is it becomes more difficult to restrict unauthorized publishing. A check would need to be added to the github publishing or deployment process to strip those values from the file. Without such checks, it would be too easy to accidentally publish those values.

That in mind, two other considerations to make that I didn't cover in the original post are that a) would we want to support publishing environment variables as part of the deployment process (ie: to ZEIT Now)? The API for those services would need to support that in order for it to work. And b) would it be a good idea to write the environment variables to a file when downloading an archive of the sandbox (to streamline the process of running the code locally). That may be subject to permissions checks.

**Comment by CompuIves** [comment]
We recently got this in! Documentation will follow.
