### ISSUE TITLE
Window resize event listener does not work with React.createRef(), requires page refresh

### ISSUE THREAD

**Issue by ryanirilli** [CompuIves/codesandbox-client#1126]
# 🐛 bug report

## Description of the problem

When adding the `resize` event listener to window, accessing the React `ref` in the callback returns `null` instead of the element. 

If you save and refresh the page it works as expected.

## How has this issue affected you? What are you trying to accomplish?

I would like to redraw a D3 chart on window resize to maintain scale/aspect ratio.

### Repro Steps
- create a fresh React Codesandbox
- you can't just copy/paste the code from [this sandbox](https://codesandbox.io/s/llkmmo86j7) into it, you have to add the ref and resize handlers by typing (copy and paste results in expected behavior)
- resize the window to see the callback returning null for the ref value
- save and refresh to see it working correctly

| Software         | Name/Version|
| ---------------- | ---------- |
| Browser | Chrome Version 69.0.3497.100 (Official Build) (64-bit)
| Operating System | macOS v10.13.6 (17G65)

**Comment by lbogdan** [comment]
Hey @ryanirilli ,

I can't seem to replicate this, is it still happening for you?

**Comment by ryanirilli** [comment]
No actually thanks for checking, it no longer is!
