### ISSUE TITLE
[bug] Dependencies of ambient type packages are ignored

### ISSUE THREAD

**Issue by mike-north** [CompuIves/codesandbox-client#1127]
# 🐛 bug report

## Description of the problem

Dependencies of TypeScript types (`@types/*`) packages are provided as type information for sandbox editor.

## How has this issue affected you? 
When using ambient types that have dependencies, my sandbox indicates false type-check errors due to missing (ignored by CSB) type information 

## What are you trying to accomplish?
I'm trying to use CSB for TypeScript development, and having parity in terms of ability to use ambient type information is a core feature I'd depend on.

Here's a concrete example. I have a sandbox with `package.json` like
```json
  "devDependencies": {
    "@types/jest": "^22.1.3",
    "@types/node": "^9.4.6",
    "@types/react": "^16.0.0",
    "@types/react-dom": "^16.0.0",
    "typescript": "^2.7.2"
  }
```
the `@types/react` package has a dependency on `@types/prop-types`
![screen shot 2018-09-29 at 10 56 49 am](https://user-images.githubusercontent.com/558005/46249097-3be4c200-c3d8-11e8-9f33-8ea348943843.png)

If I download this CSB and `npm install`, I'll get a types folder like this
![screen shot 2018-09-29 at 11 02 10 am](https://user-images.githubusercontent.com/558005/46249102-5159ec00-c3d8-11e8-86c9-dd0cce7113d1.png)

and because `node_modules/@types` [is regarded as a default typeRoot](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)
> By default all visible “@types” packages are included in your compilation. Packages in node_modules/@types of any enclosing folder are considered visible; specifically, that means packages within ./node_modules/@types/, ../node_modules/@types/, ../../node_modules/@types/, and so on.

I should be able to use the type information from `@types/prop-types`. CSB seems to completely ignore these transitive dependencies

![screen shot 2018-09-29 at 11 26 53 am](https://user-images.githubusercontent.com/558005/46249239-a696fd00-c3da-11e8-9c4b-e98c33dedd0a.png)
![screen shot 2018-09-29 at 11 17 08 am](https://user-images.githubusercontent.com/558005/46249240-ac8cde00-c3da-11e8-855f-b15d0bab904d.png)

### Workaround

In this example, adding `@types/prop-types` to `package.json` and refreshing solves the problem

![screen shot 2018-09-29 at 11 29 00 am](https://user-images.githubusercontent.com/558005/46249251-e1993080-c3da-11e8-9316-2ae3302cc84f.png)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  `PROD-1538077445-546871f`
| Browser | Brave `Version 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)`
| Operating System | `OS X 10.14.1 Beta (18B45d)`

**Comment by CompuIves** [comment]
This is a very good one! We should check for transient dependencies and add those too. This happens in `fetch-dependency-typings`. I'll mark it as bug.

**Comment by CompuIves** [comment]
Fixed!
