### ISSUE TITLE
Main editor doesn’t take all settings in account

### ISSUE THREAD

**Issue by Haroenv** [CompuIves/codesandbox-client#113]
The new Monaco editor is really cool, I love using it, but since it probably has a bunch of settings, it might be nice to take more of them in account. 

- show minimap (especially on a smaller screen, this takes a lot of space)
- fontFamily (it seems to only apply in vim mode)

There are some other settings I use in VS Code on desktop, and would be nice if I could set some of those here too.

**Comment by Arthelon** [comment]
The editor uses monaco-editor by default but when you switch to vim mode it switches back to the old codemirror editor. Seems like the `fontFamily` preference isn't properly setup with the new editor implementation. 

As for the minimap, it can be configured with monaco's [editor options](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html#selectonlinenumbers) using [ICodeEditor#updateOptions](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.icodeeditor.html#updateoptions). Default options are provided [here](https://github.com/CompuIves/codesandbox-client/blob/master/src/app/components/sandbox/CodeEditor/Monaco.js#L683).

**Comment by CompuIves** [comment]
Good info @Haroenv, will make the changes now. It seems like `fontFamily` broke along the way. Minimap should be an easy option to add thanks to the nice preferences system built by @viankakrisna.

**Comment by CompuIves** [comment]
Oh nice @Arthelon! You're making my job really easy 😄 .

**Comment by CompuIves** [comment]
Disabled the minimap by default for now, seems to have more issues than anticipated atm.

**Comment by CompuIves** [comment]
Related: https://github.com/CompuIves/codesandbox-client/issues/126

**Comment by Haroenv** [comment]
handled in #126
