### ISSUE TITLE
[bug] Changes to SSE filesystem are not synchronized to the DB or editor

### ISSUE THREAD

**Issue by mike-north** [CompuIves/codesandbox-client#1137]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?
I was trying to work on a project and use a CLI tool (through the terminal) that creates new JS/TS modules, rather than relying on the CSB interface to create each file manually

### To Reproduce
1. Create a fork of the above sandbox, wait for the sse sandbox to start. You should see a welcome screen
2. Create a new terminal pane, and run this command
```sh
./node_modules/.bin/ember generate component x-foo
```
You should see an indication that new files have been created
```
installing component
  create app/components/x-foo.js
  create app/templates/components/x-foo.hbs
installing component-test
  create tests/integration/components/x-foo-test.js
```
These files do not show up in the editor's file tree at all. This could mean that the DB is appropriately updated, but the UI is just out of sync.

3. Reload the page

These files still do not show up in the editor's file tree. This may be an indication that the DB is not appropriately updated.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1538077445-546871f
| Browser | Brave Version 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
| Operating System | OS X 10.14.1 Beta (18B45d)

**Comment by lbogdan** [comment]
Hey @mike-north , thanks for creating this issue!

Just wanted to let you know this is an outstanding issue on which we'll be focusing this week, so expect it to be fixed by the beginning of next week!

**Comment by mike-north** [comment]
@lbogdan the various tests I've tried now work as expected. Thanks for the fix!

**Comment by jkjustjoshing** [comment]
This still appears to be broken. I'm trying to access the output of a `next export` command and nothing is showing up in the explorer, and the files don't download when I export to ZIP.

To get to my files, I had to resort to initializing a git repo, adding an SSH key to the codesandbox, pushing the files to Github, and then downloading them to my machine.

**Comment by lbogdan** [comment]
@jkjustjoshing There are use cases in which our current container file syncing approach doesn't work, please see [my answer in this Spectrum thread](https://spectrum.chat/codesandbox/help/codesandbox-container-is-not-handling-package-changes-well~e42fa1e1-53b3-420f-9335-ae5e8a8422fa?m=MTU2ODM3NzkwNzAxNw==).
