### ISSUE TITLE
Zen Mode

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#114]
A mode that removes all save buttons, side bar details. Ideal for presentations.

**Comment by Arthelon** [comment]
Maybe something like this? ![](https://i.gyazo.com/f61e8727c8a059702e5afacda13c569e.png)

**Comment by Arthelon** [comment]
Another iteration without the Editor header (containing filepath) and the Project section in the sidebat:
![](https://i.gyazo.com/61aed3b21a488dd7ad9a2b4bf920b489.png)

**Comment by Arthelon** [comment]
It would also be cool if Zen mode toggled fullscreen, just like with VSCode's zen mode.

**Comment by CompuIves** [comment]
Wow, 😱  that looks really good. That's exactly what we need, fullscreen mode with it would be ultimate!
