### ISSUE TITLE
problem in run codes 

### ISSUE THREAD

**Issue by hosseinmh** [CompuIves/codesandbox-client#1140]
hi 
i want to run source and using contribute file to install 
when i use yarn command to install dependences  i give this error
<img width="1439" alt="screen shot 2018-10-02 at 5 48 43 pm" src="https://user-images.githubusercontent.com/12621753/46354581-cb55d380-c66b-11e8-829b-8c2e0e51de64.png">
<img width="1440" alt="screen shot 2018-10-02 at 5 49 02 pm" src="https://user-images.githubusercontent.com/12621753/46354582-cbee6a00-c66b-11e8-9c4c-5f564318142e.png">

thanks for helping :)

**Comment by CompuIves** [comment]
Hmm, I think I've seen this before. WHich version of node/yarn are you running? Does `yarn start:fast` work for you?

**Comment by hosseinmh** [comment]
hi 
I fix this issue by updating node 
I have another question that is how to change some part of code  ?? 
thanks a lot

**Comment by CompuIves** [comment]
Nice! You can now just change any file to see the editor update, I'd recommend checking out pages/Sandbox.js as that's the entry point of the editor.

I'll close this one now, you can check our Discord for more questions on this!
