### ISSUE TITLE
Cannot find path: @babel/runtime/core-js/object/get-prototype-of

### ISSUE THREAD

**Issue by AjayPoshak** [CompuIves/codesandbox-client#1142]
# 🐛 bug report

## Description of the problem
I am using this codesandbox and I have run into this issue.
`Cannot find path: @babel/runtime/core-js/object/get-prototype-of`

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Google Chrome 69.0.3497.100 (Official Build) (64-bit)
| Operating System | Mac OS High Sierra

**Comment by karlkras** [comment]
Yeah, same here... have a create-react-app based sandbox and trying to define a basic React.Component class.

**Comment by Mohammad-Quanit** [comment]
Ok @CompuIves  We are waiting...

**Comment by CompuIves** [comment]
Should be live in 10min

**Comment by CompuIves** [comment]
You can downgrade react-scripts to v1 in the meantime to 'fix' it.

**Comment by ex7r3me** [comment]
@CompuIves Thanks it's working for me now

**Comment by CompuIves** [comment]
👍
