### ISSUE TITLE
Cannot delete permanently from trash

### ISSUE THREAD

**Issue by taranvohra** [CompuIves/codesandbox-client#1148]
# 🐛 bug report
## Description of the problem
Trying to delete a sandbox permanently from trash gives a `405` in console
## How has this issue affected you? What are you trying to accomplish?
[GIF](http://g.recordit.co/RXavAYChsL.gif)
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1538502683-656f795
| Browser | Chrome 69.0.3497.100
| Operating System | Windows 7

**Comment by taranvohra** [comment]
But the cache should be destroyed on page reload no? I see the sandbox being fetched everytime in the api response

**Comment by arthurdenner** [comment]
The cache should be updated, removing the deleted sandboxes, but currently it's mutating the object, which doesn't trigger the rereload on the page. This behaviour is what my PR fixes.

**Comment by arthurdenner** [comment]
@tansongyang is this error still happening to you? If not, could you close the issue? My PR was merged and now the grid is updates as expected.

**Comment by tansongyang** [comment]
Hi @arthurdenner , did you mean to tag me or someone else?

**Comment by arthurdenner** [comment]
Hahaha sorry, I meant to tag @taranvohra.

**Comment by taranvohra** [comment]
@arthurdenner the error is still there.

**Comment by CompuIves** [comment]
Just got deployed. I did a test and it seems to work! Don't hesitate to reopen if it happens again.
