### ISSUE TITLE
Doesn't update URL when using React Router 4 and HashRouter

### ISSUE THREAD

**Issue by donavon** [CompuIves/codesandbox-client#115]
see this [sandbox](https://codesandbox.io/s/73756zzk46)

Click on the links and the app works, but you don't see this reflected in the URL.

In `index.js` change this:
```js
import { HashRouter as Router} from 'react-router-dom'
```
to this:
```js
import { BrowserRouter as Router} from 'react-router-dom'
```
and the app still works PLUS the URL properly updates.

**Comment by CompuIves** [comment]
Good one, I remember adding this but then net deploying it for some reason, should've documented it.

Should be fixed by updating this code

https://github.com/CompuIves/codesandbox-client/blob/master/src/sandbox/url-listeners.js#L34-L48

To add hash, also a deduplication might be in order 😅 .

**Comment by chakrihacker** [comment]
I tried logging document.location but it's not working with hashrouter, any idea??
