### ISSUE TITLE
Regarding sandpack code

### ISSUE THREAD

**Issue by shiv15** [CompuIves/codesandbox-client#1150]
# ❔ Question
Hello,
       I have been looking through sandpack code and want to understand it better. My question is where does the bundling takes place ,if not in sandpack? Sandpack and smooshpack are same right? Is the bundler source code available?

### Your Environment
| Software        | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 0.1.0
| Browser | Chromium 69.0.3497.100
| Operating System | Ubuntu 17

**Comment by CompuIves** [comment]
> My question is where does the bundling takes place ,if not in sandpack? 

We do the bundling in the browser. Sandpack is an API that allows you to communicate with the bundler of CodeSandbox, but the bundler executes in the browser. You can try it by loading a project, going offline and by making changes.

We do have one step on servers, which is preprocessing of npm dependencies. We check those out in a lambda function and cache the results on S3. This allows for snappier sandbox loading.

**Comment by shiv15** [comment]
I am trying to use the bundler in thimble by mozilla (and deploy on dat) and I used smooshpack to bundle the code (which as you said acts as an api to sandpack) and was able to bundle my code which is happening online on codesandbox servers. Is manager responsible for bundling? Can you point me in the right direction?

**Comment by shiv15** [comment]
Is manager responsible for bundling? My assumption is that sandpack based bundling is same as running my code from codesandbox.io editor. Can you point me in the right direction?
P.S. I want to deploy it as a webpage editor application(thimble by mozilla, separately hosted on decentralised `dat` network) but instead sandpack is making it tightly coupled with codesandbox.io( it is getting deployed on sandpack-xxx.codesandbox.io )

Also - my earlier approach was without sandpack. I was previously working on setting up `babel-worker` related logic from `codesandbox-client`. I'm grateful for you open-sourcing it. Learnt a lot in it, but still having some questions unanswered on how the initial `Manager` object can be constructed (in context of a separate editor app being able to use the same code to transpile and get the bundle)

**Comment by CompuIves** [comment]
The sandpack-xxx.codesandbox.io just is a proxy to https://unpkg.com/smooshpack@0.0.52/sandpack/, so if you want to host that yourself you can do that and link to it 😄.

The application that you find there does the actual bundling, we load that application in an iframe and let Manager communicate to it with postMessage. So in this case the manager sends all the files and the bundler in the iframe does the actual bundling.

**Comment by shiv15** [comment]
Thank you so much. This definitely solves the bundler in my thimble. Thanks a Lot. Closing the issue now.
