### ISSUE TITLE
Support for preferences's fontSize expressions (like "calc(16px + 1vh)")

### ISSUE THREAD

**Issue by cloud-walker** [CompuIves/codesandbox-client#1152]
## Why
I personally have different pc's during my work week and I often have to tweak manually the fontSize of the Editor.

## What
We can support the fontSize preference not only as a number field, but leaving to the user the ability to use every fontSize css expression possible, this way I can hack the font size formula to automatically adapt to my screen resolutions.

## How
I think it should be possible to infer the fontSize value type (if numeric or not) and add a `px` at the and if is numeric, or nothing if is a string!

**Comment by SaraVieira** [comment]
I can take a stab at it as I have an hd monitor and a retina screen and can test this.

By default it should be px if parseInt of what you wrote is a number , right ?

**Comment by cloud-walker** [comment]
Yes, thats my thought, but I'm open to other solutions.

I also think I could make the change myself, but I'm not familiar with the codebase yet 🤔

**Comment by SaraVieira** [comment]
Hey!

I looked into this and this is a constrain of Monaco itself :(

https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html#fontsize

You can only pass a number to it and it always assumes px: https://github.com/Microsoft/monaco-editor/blob/3a22d5d/monaco.d.ts#L2955


:(
