### ISSUE TITLE
create-reacte-app svg import support.

### ISSUE THREAD

**Issue by karlkras** [CompuIves/codesandbox-client#1157]
# 🐛 bug report

## Description of the problem
Inability to load svg image in react component from a create-react-app sandbox.

## How has this issue affected you? What are you trying to accomplish?
Getting errors when attempting to import an svg image, ex:
`import calendarImg from 'svg-react-loader!./resources/calendar.svg';
`
###  Link to sandbox: 
[https://codesandbox.io/s/o5x2061zxy](https://codesandbox.io/s/o5x2061zxy)

###  Background: 
So I've added svg-react-loader as a dependency to my project, and had found references to using the above import syntax when working with react-create-app based applications (so the project doesn't have to be ejected).

**Comment by js-mode** [comment]
Showing the same issue -- looks like there may be an issue with the codesandbox server? 

@CompuIves - any advice on how to get the console in the sandbox working again? 

<img width="1727" alt="screen shot 2018-10-03 at 6 56 22 pm" src="https://user-images.githubusercontent.com/29901608/46448910-29eb8200-c73e-11e8-8453-d207ed75b858.png">

**Comment by CompuIves** [comment]
Heyo! We have the svg loader built in in CRA v2, so this should work: https://codesandbox.io/s/5k8xxkxjpl.

Hopefully that fixes your issue!

**Comment by karlkras** [comment]
well, that's much cleaner too. thanks!

**Comment by karlhorky** [comment]
What about importing SVGs or other image paths just using the `import img from './img.svg'` syntax?

I guess I'll make a new issue for this.
