### ISSUE TITLE
When installing dependencies - latest tag should be selected by default

### ISSUE THREAD

**Issue by Andarist** [CompuIves/codesandbox-client#1160]
# 🐛 bug report

What's in the title - right now if I try to install a dependency (i.e. react-textarea-autosize) its beta version gets selected (probably, because it has higher semver number) - it doesnt seem to affect what version gets installed, but is still confusing.

EDIT:// actually it seems to affect what version is installed - so it's dangerous. I was having problem with installing beta over latest (when I have already installed latest in the sandbox), but that's separate issue

**Comment by lbogdan** [comment]
Closing this, as I can't replicate with `react-textarea-autosize`, so I'd guess it was fixed. Please feel free to reopen if you still get this behavior.
