### ISSUE TITLE
How to use enzyme and snapshot feature  (RegisterForm.jsx hasn't been transpiled yet.)

### ISSUE THREAD

**Issue by Ridermansb** [CompuIves/codesandbox-client#1162]
# ❔ How to use enzyme and snapshot feature?

I'm trying to write an test but I receive

> /src/RegisterForm.jsx hasn't been transpiled yet.

Link to sandbox: [link](https://codesandbox.io/s/42jmpo5qkw?autoresize=1&hidenavigation=1&module=%2Fsrc%2FRegisterForm.test.js&previewwindow=tests)

**Comment by lbogdan** [comment]
Closing this, as we only support `jest` for tests at the moment. Feel free to open a feature request for `enzyme`.

You can also try to use a [server sandbox](https://medium.com/@compuives/codesandbox-containers-out-of-beta-improvements-be79679df4cc), which basically supports anything you could do in a local development environment.
