### ISSUE TITLE
Automatic installation of typings broken for scoped packages

### ISSUE THREAD

**Issue by j2L4e** [CompuIves/codesandbox-client#1164]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

When a package dependency is added to a sandbox it tries to fetch a corresponding typings package from DefinitelyTyped. DT's naming convention for scoped package types is `@types/scope__package`, but codesandbox tries to install `@types/@scope/package` which doesn't work.

You can try this with `@feathersjs/feathers`. Typings are available as `@types/feathersjs__feathers` but codesandbox is unable to automatically find those.

Codesandbox should detect scoped packages and try to install types using the double underscore naming.

### Your Environment
Codesandbox `PROD-1538077445-546871f`

**Comment by CompuIves** [comment]
Fixed!
