### ISSUE TITLE
electron-create-react sandbox has issues importing electron library

### ISSUE THREAD

**Issue by bernatfortet** [CompuIves/codesandbox-client#1166]
# 🐛 bug report

## Description of the problem
Electron create react sandbox has problems with electron dependency.

```Electron failed to install correctly, please delete node_modules/electron and try installing again```

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | ??
| Browser | Chrome 69
| Operating System | MacOS Mojave

**Comment by CompuIves** [comment]
Hmm, this one is hard to solve I think. We execute the code in the browser, so there isn't really permissions to open a program directly from the editor. I could be mistaken though, what are you trying to build in this sandbox?

**Comment by bernatfortet** [comment]
I was just trying to present an issue coming from some libraries interacting with Electron. Not super important though.

Thanks for answering.

**Comment by SaraVieira** [comment]
Hey @bernatfortet !

I'm gonna close this issue as codesanbox does not support adding libraries that need electron :/
