### ISSUE TITLE
Images not accessible in nuxt projects

### ISSUE THREAD

**Issue by husayt** [CompuIves/codesandbox-client#1167]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?
Trying to use an image in .nuxt project. Tried both `assets` and `static` folders

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | 
| Operating System |

**Comment by CompuIves** [comment]
Heya! Do you have an example sandbox? I'm not able to reproduce the issue.

**Comment by husayt** [comment]
Hi @CompuIves It seems, you have done some magic and now all the images work:

https://31v6l067mm.sse.codesandbox.io/
