### ISSUE TITLE
Unable to Use Generators in Sandboxes

### ISSUE THREAD

**Issue by pahund** [CompuIves/codesandbox-client#1169]
# 🐛 bug report

## Description of the problem

I define a generator function in a code sandbox, like this basic example:

```javascript
function* generator(i) {
  yield i;
  yield i + 10;
}
```

Code sandbox immediately shows an error message:

> Cannot find path: @babel/runtime/regenerator

Adding [babel/runtime](https://www.npmjs.com/package/@babel/runtime) as dependency does not help.

It seems to be caused by the fact that [create-react-app](https://github.com/facebook/create-react-app) / _react-scripts_ uses Babel 7 now, I did not have the problem with previous Codesandbox versions that used Babel 6.

If I downgrade the dependency to _react-scripts_ to version 1.1.5, the problem goes away.

## How has this issue affected you? What are you trying to accomplish?

I'm working on an application that uses [Redux Saga](http://redux-saga.js.org), which is heavily based on generators. This is currently only possible with Codesandbox if I use an older version of react-scripts.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1538647316-8e4cd41 |
| Browser | Firefox Developer Edition 63.0b11 (64-Bit) |
| Operating System | MacOS High Sierra 10.13.6 (17G65) |

**Comment by CompuIves** [comment]
Fixed with the next deploy!

**Comment by pahund** [comment]
👍 Thanks – keep up the great work!
