### ISSUE TITLE
Error Overlay styling

### ISSUE THREAD

**Issue by johann-sonntagbauer** [CompuIves/codesandbox-client#117]
The error indicator is positioned absolute which makes is very hard to see the indicator at all. Also because of the positioning it doesn't scroll.

![problem](https://user-images.githubusercontent.com/1239401/29381173-9e61671e-82c8-11e7-8453-c51dfc8825cc.png)

My suggestion would be to style it the following way which makes it very clear where the error is and also no special positioning is needed.

![suggestion](https://user-images.githubusercontent.com/1239401/29381207-bd689254-82c8-11e7-9aa0-d5a6e464eea4.png)

I could formalize an PR if you approve the suggestion or have better ideas to visualize that case.

**Comment by CompuIves** [comment]
Completely agree, really good suggestion @johann-sonntagbauer. Would love to see a PR for this!
