### ISSUE TITLE
Angular project goes into hanging state with infinite error loop

### ISSUE THREAD

**Issue by brihaspati** [CompuIves/codesandbox-client#1170]
# 🐛 bug report

## Description of the problem
Sandbox for angular goes into hanging state and becomes unresponsive due to infinite errors in the console 
## How has this issue affected you? What are you trying to accomplish?
Developing an angular project and was playing around with a very basic directive
###  Link to sandbox: [link]() (optional)
https://codesandbox.io/s/ll087n02pz
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome
| Operating System | Mac OS High Sierra 
<img width="1318" alt="screen shot 2018-10-07 at 20 36 53" src="https://user-images.githubusercontent.com/3582818/46583278-cdf06880-ca71-11e8-8102-eddb912d0656.png">

**Comment by CompuIves** [comment]
Heyo! Thanks for reporting the issue!

Do you still have this issue? I can't reproduce it currently. What do the console errors say?

**Comment by CompuIves** [comment]
That sounds good! I pushed some other fixes so it may have fixed this too. Feel free to reopen if it happens again!
