### ISSUE TITLE
Layout isue opening the console

### ISSUE THREAD

**Issue by elrumordelaluz** [CompuIves/codesandbox-client#1171]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

Layout issue opening the `console`.
![codesanbox-issue](https://user-images.githubusercontent.com/784056/46602733-4ba78900-caf1-11e8-8f04-1fe092fc1deb.gif)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1538647316-8e4cd41 |
| Browser | Firefox 62.0.3 | 
| Operating System | OSX 10.11.6 |

**Comment by SaraVieira** [comment]
This is a firefox issue :(

I'll try to look into it

**Comment by elrumordelaluz** [comment]
Awesome Sara!
I initially thought was related on the big string logged after loading an image in [that specific snadbox](https://codesandbox.io/s/momwrp78xj) that set the `width: calc(100% - ${very-big}px)`.

![codesandbox](https://user-images.githubusercontent.com/784056/46634833-90afd780-cb52-11e8-9e0e-28145bc6f57d.gif)

Probably [this PR](https://github.com/samdenty99/console-feed/pull/6) solves that part of the _issue_ instead.

**Comment by SaraVieira** [comment]
This has also been fixed by moving the console under the browser :)
