### ISSUE TITLE
422 error on Vue CLI 3 project from GitHub

### ISSUE THREAD

**Issue by Haroenv** [CompuIves/codesandbox-client#1172]
# 🐛 bug report

## Description of the problem

https://codesandbox.io/s/github/algolia/vue-instantsearch/tree/feat/connectors/examples/media

Will throw an error in CodeSandbox 

```json
{
  "errors": {
    "detail": [
      "Request failed with status code 422"
    ]
  }
}
```

This is returned from the backend.

## How has this issue affected you? What are you trying to accomplish?

I can't see anything, since there's a 422 error

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1534913825-2619708 |
| Browser | any |
| Operating System | any |

**Comment by Haroenv** [comment]
looking forward to the fix ❤️

**Comment by CompuIves** [comment]
Deployed 😄
