### ISSUE TITLE
TypeError when setting react-scripts to a npm tag

### ISSUE THREAD

**Issue by eps1lon** [CompuIves/codesandbox-client#1174]
# 🐛 bug report

## Description of the problem
Setting the version string in `package.json` to a npm tag causes codesandbox to crash with
```
TypeError
Invalid comparator: latest
```
## How has this issue affected you? What are you trying to accomplish?
We have the versions of our examples in material-ui always set to `latest`. npm and yarn are able to resolve this but codesandbox requires a valid semver range in that field:
https://github.com/CompuIves/codesandbox-client#/blob/master/packages/app/src/sandbox/eval/presets/create-react-app/index.js#L23

###  Link to sandbox: [link](https://codesandbox.io/s/github/mui-org/material-ui/blob/173a729dfaf6d298dd5c7551c01dd24dd9a6b1e8/examples/create-react-app) (optional)

Fixable with the following diff:
```diff
-"react-scripts": "latest"
+"react-scripts": "^2.0.0"
```
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | master
| Browser | Version 69.0.3497.100 (Official Build) (64-bit)
| Operating System | Ubuntu 16.04.5 LTS

**Comment by CompuIves** [comment]
Hey! Sorry for that, fixed now!

**Comment by eps1lon** [comment]
@CompuIves Thank you! How can I subscribe to deployed changes?

**Comment by CompuIves** [comment]
We show the version you're on in the bottom left (in the sidebar), it will
update to the latest commit sha on every deploy. Other than that it would
be good to build something for this.
