### ISSUE TITLE
React template errors on @babel/plugin-transform-object-rest-spread

### ISSUE THREAD

**Issue by JonShort** [CompuIves/codesandbox-client#1178]
# 🐛 bug report

## Description of the problem
The latest react template errors at random, requesting `'@babel/plugin-transform-object-rest-spread'`, despite spread/rest not being used in codebase.

![image](https://user-images.githubusercontent.com/21317379/46663198-67746300-cbb5-11e8-8811-434349daf157.png)

This error seems to appear sporadically when:
- changing project name
- changing project description
- changing project tags
- creating a file
- moving a file

Occasionally it will fix itself when one of the actions above completes.

Having searched, there may be a link between this issue and [issue 5310 in create-react-app](https://github.com/facebook/create-react-app/issues/5310)

## How has this issue affected you? What are you trying to accomplish?
I was trying to create a React sandbox to investigate handling video metadata in React.

I do not feel confident sharing the sandbox with peers knowing they may hit the babel issue.

I would be interested to hear if others are facing this problem with the base `create-react-app` template.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1538647316-8e4cd41|
| Browser | Chrome Version 69.0.3497.100 (Official Build) (64-bit)|
| Operating System | MacOS High Sierra 10.13.6|

**Comment by CompuIves** [comment]
I just pushed a fix for this 😄.

Feel free to reopen this if it occurs again!

**Comment by JonShort** [comment]
🎉 Excellent! Apologies for the duplicate issue, I did not see 1177 😱
