### ISSUE TITLE
Babel error on Vue CLI 3 template

### ISSUE THREAD

**Issue by Haroenv** [CompuIves/codesandbox-client#1179]
# 🐛 bug report

## Description of the problem

This is likely because some mismatch of Babel versions?

## How has this issue affected you? What are you trying to accomplish?

<img width="562" alt="screen shot 2018-10-09 at 14 05 50" src="https://user-images.githubusercontent.com/6270048/46668406-9f3ad500-cbcc-11e8-9d46-00d1e3109644.png">

```
[BABEL] /src/main.js: The 'useBuiltIns' option has been removed. The @babel/runtime module now uses builtins by default. (While processing: "base$0$7")
```

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1534913825-2619708 |
| Browser | Safari (tech preview Release 63 (Safari 12.1, WebKit 13607.1.2.1)) |
| Operating System | MacOS High Sierra 10.13.6 (17G65) |

**Comment by Haroenv** [comment]
I think it has something to do with one of these dependencies: 

```
    "@vue/cli-plugin-babel": "^3.0.5",
    "@vue/cli-plugin-eslint": "^3.0.3",
    "@vue/cli-service": "^3.0.3",
    "vue-template-compiler": "^2.5.17"
```

**Comment by Haroenv** [comment]
Maybe it's because the cli-plugin-babel has babel 7 alpha, and you might have the released version?

**Comment by lbogdan** [comment]
@Haroenv Meanwhile you can play around with (most probably) the prototype to the Vue CLI 3 server / container template here: https://codesandbox.io/s/github/lbogdan/cs-vue-cli-3 . 🙂

**Comment by Haroenv** [comment]
thanks @lbogdan, did you fix it by adding `"vue-template-compiler": "^2.5.17"`?

**Comment by Haroenv** [comment]
Seems like this is still happening, but now a different error message:

```
Invalid preset specified in Babel options: "env"
▼ 9 stack frames were expanded.
C
https://codesandbox.io/static/js/sandbox.616011f0.js:1:228358
(anonymous function)
https://codesandbox.io/static/js/sandbox.616011f0.js:1:231365
g
https://codesandbox.io/static/js/common-sandbox.730613df.chunk.js:1:207996
(anonymous function)
https://codesandbox.io/static/js/common-sandbox.730613df.chunk.js:1:207781
u
https://codesandbox.io/static/js/common-sandbox.730613df.chunk.js:1:2891
a
https://codesandbox.io/static/js/common-sandbox.730613df.chunk.js:1:2981
(anonymous function)
https://codesandbox.io/static/js/common-sandbox.730613df.chunk.js:1:3020
r
https://codesandbox.io/static/js/common-sandbox.730613df.chunk.js:1:71367
(anonymous function)
https://codesandbox.io/static/js/common-sandbox.730613df.chunk.js:1:2827
▲ 9 stack frames were expanded.
```

**Comment by Haroenv** [comment]
(reproducible with https://github.com/algolia/vue-instantsearch-v2-starter/tree/fb3476a9b24c604035a36e8a1a59052a02a5a0ce) or https://github.com/algolia/vue-instantsearch-v2-starter/tree/fb3476a9b24c604035a36e8a1a59052a02a5a0ce

**Comment by CompuIves** [comment]
There's a fix on master for this, should be live within 3 hours!

**Comment by Haroenv** [comment]
Yay! Did I ever tell you that you're the best @CompuIves? ❤️

**Comment by CompuIves** [comment]
Hahaha, thank you @Haroenv :smil

**Comment by Haroenv** [comment]
Aww yeah, glad to make them all back frontend implementations!
