### ISSUE TITLE
Rawgit is closing down

### ISSUE THREAD

**Issue by Haroenv** [CompuIves/codesandbox-client#1180]
# 🐛 bug report

## Description of the problem

There are some links on rawgit, which will be closed down (see [main page](https://rawgit.com)). These should be replaced with regular GitHub links and forcing the mime type somehow; or with an alternative like https://raw.githack.com

## How has this issue affected you? What are you trying to accomplish?

Not yet, but there's [5 places](https://github.com/CompuIves/codesandbox-client/search?q=rawgit&unscoped_q=rawgit) rawgit is referenced in the code.

### Your Environment
| Software             | Name/Version|
| ---------------- | ------------- |
| Сodesandbox  | PROD-1534913825-2619708 |
| Browser | all |
| Operating System | all |

**Comment by CompuIves** [comment]
Good one. We should either create a mime type proxy ourselves or we should use another service. raw.githack.com looks very similar to rawgit. We'd need to check how reliable they are with hosting, rawgit was really good.

**Comment by Haroenv** [comment]
Note that rawgit is open source, so that's an option to run it on codesandbox' servers instead :) https://github.com/rgrove/rawgit

**Comment by lbogdan** [comment]
Closing this, since we switched to [raw.githack.com](http://raw.githack.com/).
