### ISSUE TITLE
Console/Problems not working

### ISSUE THREAD

**Issue by marko-invision** [CompuIves/codesandbox-client#1181]
# 🐛 bug report

## Description of the problem

Sandbox console/problems window not working (no outputs). This starts 10 minutes ago. 
Browser console still working. If the browser-preview-window is open in a new window, the sandbox console works. 🤔

## How has this issue affected you? What are you trying to accomplish?

Nothing changed. All React Projects Sandboxes are effected.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | |
| Browser | Chrome/Firefox |
| Operating System | Mac OSX |

**Comment by CompuIves** [comment]
Working on a fix!

**Comment by CompuIves** [comment]
Fix is live!
