### ISSUE TITLE
Babel doesn't work well with Vue

### ISSUE THREAD

**Issue by boonyasukd** [CompuIves/codesandbox-client#1182]
# 🐛 bug report

## Description of the problem
There are several instances which I tried to use Vue in Codesandbox, but encountered problems:

- I first created a [sandbox](https://codesandbox.io/s/j3qqqx88mv) to play around. I found that things work mostly okay, until I tried to use spread operator, in which the system starts throwing out error. Removing spread operator brings application back to normal:

![capture01](https://user-images.githubusercontent.com/8109816/46685641-2cf3e000-cc20-11e8-840e-6fb2366aa509.PNG)

- To avoid that error, I tried to create the same project in Github (using Vue 3 CLI) then imported it to [codesandbox](https://codesandbox.io/s/kxzxl8wqx7). However, I faced the same error message as in #1179.

![capture02](https://user-images.githubusercontent.com/8109816/46685671-38dfa200-cc20-11e8-8a59-af39638ec7f7.PNG)

- As a last resort, I then tried to fork an [existing project](https://codesandbox.io/s/xpl8x520vo), and planned to use it as a starting point. However, even though the original sandbox seems to work just fine, my [forked project](https://codesandbox.io/s/62kw2722rz) dies when it attempts to build.

![capture03](https://user-images.githubusercontent.com/8109816/46685686-3f6e1980-cc20-11e8-883d-9dd616c58248.PNG)

## How has this issue affected you? What are you trying to accomplish?
I think there's something wrong with Babel configuration. Forked project shouldn't die on first load. All attempts I tried seem to fail.

###  Link to sandbox(es):
- https://codesandbox.io/s/j3qqqx88mv
- https://codesandbox.io/s/kxzxl8wqx7
- https://codesandbox.io/s/62kw2722rz

or see them as a list [here](https://codesandbox.io/u/boonyasukd/sandboxes)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  PROD-1539089703-4b74200
| Browser | Firefox 62.0.3 (64-bit)
| Operating System | Win 10

**Comment by lbogdan** [comment]
Hey @boonyasukd , thanks for opening this issue!

Looks like there was a babel issue (probably from when we switched to babel 7) which seems fixed now (@CompuIves, do you know anything about this?). Here's your forked initial sandbox using `...mapGetters()`: https://codesandbox.io/s/8574q0z2j?module=%2Fsrc%2Fcomponents%2FLogin.vue . Can you confirm it also works for you?

About Vue CLI 3, we don't support it just yet, we'll probably support it as a [server / container](https://hackernoon.com/codesandbox-containers-5864a8f26715) template soon. Until then you can make it work using the `nuxt` template, I'll make an example GitHub repo and get back to you later today.

**Comment by lbogdan** [comment]
As promised, here's an example repo / sandbox with Vue CLI 3: https://codesandbox.io/s/github/lbogdan/cs-vue-cli-3 .

**Comment by boonyasukd** [comment]
@lbogdan Thanks for looking into this. My original sandbox, and the one that you forked, seems to work fine now. :+1: 

One quick question: in order to import Vue CLI 3 from github as a container sandbox, I just need to add `sandbox.config.json` to the root of the project, right? We just need tell the system that we're using `nuxt` (though we might/might not really need it).

**Comment by lbogdan** [comment]
@boonyasukd Right now you need both `sanbox.config.json` and the config from my `vue.config.js` (that fixes an HMR issue that will hopefully be fixed in the next release of Vue CLI 3 - see https://github.com/vuejs/vue-cli/pull/2795).

I'm closing this for now, if you have other related issues please reopen.
