### ISSUE TITLE
How does the 'pr deployment' check work?

### ISSUE THREAD

**Issue by peterschussheim** [CompuIves/codesandbox-client#1183]
Hi Ives,

Is the source available for the PR check that deploys each PR to `prXXXX.cs.lbogdan.tk/s/new`?  I am trying to do that same workflow and I am curious how you implemented it in this repo.

best,
Peter

**Comment by SaraVieira** [comment]
CC @lbogdan

**Comment by lbogdan** [comment]
Hey @peterschussheim , it is not available (mostly because it was put together in a hurry and the code is ugly 🙂 ), but it's just a [github webhook](https://developer.github.com/webhooks/) that listens for PR create / update and builds and deploys that PR in a docker container.

**Comment by peterschussheim** [comment]
Thank you both 🙂

**Comment by lbogdan** [comment]
@peterschussheim Btw, I'm `BogdanL` on [CodeSandbox Discord](https://discord.gg/KE3TbEZ), if you need any kind of guidance (or just wanna talk 🙂).

**Comment by peterschussheim** [comment]
Thanks @lbogdan <https://github.com/lbogdan>, I will talk to you soon on Discord :)

On Tue, Oct 16, 2018 at 12:13 PM Bogdan Luca <notifications@github.com <mailto:notifications@github.com>> wrote:
@peterschussheim <https://github.com/peterschussheim> Btw, I'm BogdanL on CodeSandbox Discord <https://discord.gg/KE3TbEZ>, if you need any kind of guidance (or just wanna talk 🙂).
