### ISSUE TITLE
ModuleNotFound when other people view the sandbox.

### ISSUE THREAD

**Issue by deecewan** [CompuIves/codesandbox-client#1191]
# 🐛 bug report

## Description of the problem

When looking at the sandbox from the edit view, everything works normally. If I go to [the direct link](https://815z28rpp8.codesandbox.io/) it works, too.

However, if I open either the sandbox or the page in Incognito, or I send the sandbox link to someone else, I get a ModuleNotFoundError.

![image](https://user-images.githubusercontent.com/4755785/46993107-eab32d00-d150-11e8-8eae-def04f521ed8.png)

## How has this issue affected you? What are you trying to accomplish?

Trying to show a demo of the way different locales work with pluralization in `react-intl`. I can't show anyone else the demo, because it only works on my machine.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | ? |
| Browser | Chrome |
| Operating System | macOS Mojave |

**Comment by deecewan** [comment]
Hmm. So. Forking it maintains the problem. It seems to be fixed if I edit the line that is importing it.

If I remove the `import { IntlProvider, FormattedMessage, addLocaleData } from "react-intl";` line, save, and re-add, it seems to work.

**Comment by amanmahajan7** [comment]
Running into the same

**Comment by CompuIves** [comment]
Hey! I created a fix for this. This fix is quite intrusive so I'll need to do a bit more testing and deploy it when I have a bit more time.
