### ISSUE TITLE
Possibility to expose editor in embed mode

### ISSUE THREAD

**Issue by jadjoubran** [CompuIves/codesandbox-client#1193]
# 🌈 Feature

## What is this feature?
It would be cool to allow an embedded codesandbox to expose the code that is being written in it to the original page (feature should be opt-in of course) as this allows new use cases to built on top of codesandbox.

## How the feature should work?
Not entirely sure but communication between iframe and main page (different domain) should work using `postMessage` and people can opt-in to it by adding a new query string to the embed string

**Comment by lbogdan** [comment]
Hey @jadjoubran , this sounds a bit vague, can you maybe detail such a use-case?

**Comment by jadjoubran** [comment]
Hey! I personally don't need this anymore, so I will close the issue and explain the original use case

The original usecase was to allow embedding a codesandbox on a page, while also letting that page read the contents of the code editor (the one that's embedded via codesandbox)
