### ISSUE TITLE
Add options to choose the template for import from GitHub

### ISSUE THREAD

**Issue by artalar** [CompuIves/codesandbox-client#1202]
# Add options to choose the template for import from GitHub

Right now (by my experience) import from GitHub always set "create-react-app" template
(for example https://codesandbox.io/s/github/rtcad/rtcad), but what if I need `node` template or other for an imported project?

Please, add the ability to choose a template for import from GitHub

**Comment by artalar** [comment]
I was trying to add `sandbox.config.json` (after import) and set `"template": "node"`, but nothing was change

**Comment by artalar** [comment]
BBy the way I was not found `"node"` case here https://github.com/codesandbox-app/codesandbox-importers/blob/master/packages/import-utils/src/create-sandbox/templates.ts

**Comment by lbogdan** [comment]
Hey @artalar , it should work with a `sandbox.config.json` with `"template": "node"`- I forked your repo and added it here: https://github.com/lbogdan/rtcad/blob/master/sandbox.config.json / https://codesandbox.io/s/github/lbogdan/rtcad . Also, you don't have a main script in `package.json`, which should be one of `dev`, `develop`, `serve` or `start`.

**Comment by artalar** [comment]
@lbogdan thanks! But will be greate if the type of template can be switched after import - for import and inspect others repos

**Comment by lbogdan** [comment]
The template gets updated as soon as you add / update `sandbox.config.json` in the repo (as you can see with your rtcad/rtcad repo, which now is seen as a node sandbox: https://codesandbox.io/s/github/rtcad/rtcad .

**Comment by lbogdan** [comment]
Closing this since it works as expected.

**Comment by artalar** [comment]
@lbogdan 
Yes, i see the project template with preadded sandbox.config.json works fine. But what if i want clone and play with other repo with node based code? I need fork it, add sandbox.config and only then add to the _sandbox_? It is not UX friendly. Can u add some modal dialog for the GitHub import to choose template?

**Comment by maxfi** [comment]
@lbogdan is your example still meant to be working? I get a 502: Bad Gateway on https://codesandbox.io/s/github/lbogdan/rtcad
