### ISSUE TITLE
If you show all commands (⇧⌘P) and then escape, the editor loses focus

### ISSUE THREAD

**Issue by jasepellerin** [CompuIves/codesandbox-client#1204]
# 🐛 bug report

## Description of the problem

Showing all commands, and then using escape to go back to the editor causes focus loss.

## How has this issue affected you? What are you trying to accomplish?

Was just playing around and noticed that when I accidentally opened all commands instead of the file opener (⌘P), then quickly escaped and pressed the correct key command, it tried to print the page. This also seems to happen if you use any of the commands in the first dialog.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  PROD-1539792341-79905c0 |
| Browser | Google Chrome Version 69.0.3497.100 (Official Build) (64-bit) |
| Operating System | macOS High Sierra 10.13.6 |

**Comment by CompuIves** [comment]
Heya! Is this on the VSCode version or on the Monaco version?

VSCode is enabled if you go to preferences and then click on 'Experimental VSCode'.

**Comment by jasepellerin** [comment]
Hey, there. This is on the Monaco version.

**Comment by SaraVieira** [comment]
Issue closed as we dropped the monaco editor in the latest release
