### ISSUE TITLE
Typings files not initially found

### ISSUE THREAD

**Issue by nicknisi** [CompuIves/codesandbox-client#1205]
# 🐛 bug report

## Description of the problem

Typings are not initially found by the editor. This seems to be affecting both Monaco and VSCode editors. After a file is edited, the red underlines go away for the node_modules typings in Monaco, and everything in VSCode. This seems to be occurring on both the Dojo and React+TS templates.

![screen shot 2018-10-18 at 3 26 23 pm](https://user-images.githubusercontent.com/293805/47182068-32b98780-d2ea-11e8-9ef5-6391bfdd9d30.png)

## How has this issue affected you? What are you trying to accomplish?

The editor seems to not know about modules loaded, causing confusion.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1539886201-8ea3d55 |
| Browser | Firefox 62, Chrome 72 |
| Operating System | macOS Mojave |

**Comment by CompuIves** [comment]
Interesting. It seems to me we should delay the type checking until we made sure that all the types have been downloaded. Definitely something in VSCode, I can fix it tomorrow!

**Comment by CompuIves** [comment]
Whooh I have improved this a lot! You can now also view/edit typing files in the editor, we also download peer dependencies of types and we don't show errors initially. Exciting! Will deploy it today.

Also fixes #819 #1127 #1164.

![image](https://user-images.githubusercontent.com/587016/47221062-c4d99280-d3b3-11e8-8903-3479e9f95cca.png)

**Comment by nicknisi** [comment]
Amazing! Thanks so much!

**Comment by CompuIves** [comment]
It's live!
