### ISSUE TITLE
Support creating projects

### ISSUE THREAD

**Issue by ritz078** [CompuIves/codesandbox-client#121]
When I make demos I would like to group them. Something called 'Project'. Also I would like a shareable URL for a project.

**Comment by Arthelon** [comment]
Being able to group your sandbox sounds like a good idea, stick with using tags for now. As for getting shareable urls, you can find them in the 'Share' popover in the header.

**Comment by CompuIves** [comment]
I had a similar request recently by @kentcdodds. A feature that allows you to create public (or private) collections, and add sandboxes to the collection. Then the collection is sharable.

Is that the same as your proposal @ritz078?

**Comment by ritz078** [comment]
Yes that is a similar proposal.

**Comment by gautamarora** [comment]
I've started an issue that summarizes recent discussions on this feature here: https://github.com/CompuIves/codesandbox-client/issues/609

@ritz078 @Arthelon - please leave your comments and feedback in that issue.

if you want to jump in and help build/test this feature, that will be great too

**Comment by lbogdan** [comment]
Closing this as duplicate of #609 .
