### ISSUE TITLE
Initialize CSB on nested routes (not only when accessing index)

### ISSUE THREAD

**Issue by manniL** [CompuIves/codesandbox-client#1211]
# 🌈 Feature

If you currently access a nested route of an **inactive CSB**, a 404 will be thrown (example: https://1rmqv4xkx3.sse.codesandbox.io/reactivity/wrong).

It'd be great if the sandbox would start initializing (similar like when you access the root/index page).

**Comment by lbogdan** [comment]
This has been added. Please test and close this if it works as expected.

**Comment by manniL** [comment]
Whoop, that was fast! 
Works as expected, thank you ☺️ 👍
