### ISSUE TITLE
Prompt on saving frozen sandbox

### ISSUE THREAD

**Issue by dance2die** [CompuIves/codesandbox-client#1212]
# 🌈 Feature

## What is this feature?
Prompt a user before forking a `frozen` sandbox.

## How the feature should work?
A user should be notified before forking a frozen sandbox.

## You have examples or an idea how it can be implemented?
Hovering over `?` button shows that saving frozen`

>  ...sandBox will fork on save

![image](https://user-images.githubusercontent.com/8465237/47271167-e7021a80-d543-11e8-8277-e7fb28d2def4.png)

But the transition (when you click `ctrl + s`) is so subtle (and fast on a fast connection), it's hard to tell if you are working on a frozen SandBox or a forked on as you can see below.

![2018-10-21_15-20-09](https://user-images.githubusercontent.com/8465237/47271241-db632380-d544-11e8-983c-eec1c8aa8b3e.gif)

We can prompt a user with a modal dialog to confirm if s/he wants to fork the frozen sandbox.

**Comment by SaraVieira** [comment]
Hey !

You are completely right ! It was an oversight to not include an alert for that .

Is the alert that shows up when you click to fork your own sandbox something that would work here ?

**Comment by dance2die** [comment]
> Is the alert that shows up when you click to fork your own sandbox something that would work here ?

The easiest way to implement this is to **disable** `ctrl+s` keyboard shortcut.
But yes, an alert to prevent you from forking accidentally would work better 
_(as the intention is more explicit and leave people hanging why it's not saving/forking)_

**Comment by JonShort** [comment]
Hi both 👋 

I've submitted a PR adding in this functionality, like Sara suggested above I added a browser alert when the user is trying to save edits to a frozen sandbox which they own.

I'd be interested in getting opinions on the message we should display to the user, or other approaches to solving this problem 👍
