### ISSUE TITLE
"Open in New Window" Experience

### ISSUE THREAD

**Issue by pshrmn** [CompuIves/codesandbox-client#1213]
# 🌈 Feature

Currently, the experience with opening a sandbox in a new window is a bit wanting. In particular, there are two issues that I feel it has:

1. The new window uses the fake `window.history` (from `url-listeners`) for navigation. This uses `history.replaceState` for all navigation, so the browser's forward/back buttons do not work.
2. Opening the sandbox in a new window does not hide the preview in the sandbox editor. The preview is in a weird state where the location changes, but the app is not usable.

### The New Window

My basic understanding of what happens when you open the sandbox in a new window is that CodeSandbox can communicate with that window. This lets the window automatically update when the sandbox is updated; navigating directly to the same URL does not automatically re-render when the sandbox is updated. Part of this communication is intercepting `window.history` method calls, which is why the back/forward buttons do not work in the window.

#### Possible Solutions?

The "easy" fix would be to treat the sandbox opened in a new window as standalone. This would break instant updates, so it is not ideal.

A more targeted fix would detect when the sandbox is being run in an external window and fallback to the real `history` methods. I haven't tested this out to see if it works, but I think that it should.

The `isStandalone` variable is used to track if the sandbox is a standalone (direct navigation, no dispatch) or not (in sandbox or opened in a new window and can dispatch). Is there a way to detect if a sandbox is opened in a new window, but can still dispatch?

### Hiding the Preview

This is probably a relatively simple fix, but Cerebral looked a bit magical so I haven't tried to see what would be required to change this.

**Comment by CompuIves** [comment]
Oh wow, I wasn't aware of this issue. Thanks for mentioning it!

> A more targeted fix would detect when the sandbox is being run in an external window and fallback to the real history methods. I haven't tested this out to see if it works, but I think that it should.

Yep, this seems like the best and quickest solution.

> Is there a way to detect if a sandbox is opened in a new window, but can still dispatch?

That is an interesting one, I just did a quick check (https://codesandbox.io/s/1q7m8qmy5l) and it seems that in editor `window.opener` and `window.referrer` are `null` and `undefined` respectively. Opened externally they are `Window` and `undefined`. It seems like we could use that as check?

**Comment by lbogdan** [comment]
The first part was fixed in https://github.com/CompuIves/codesandbox-client/commit/64297e142c61040edc3edd59601db8a21418a0a6 .

As for the second part, I can't say I agree - I usually open the preview in a new window to look at something, only to close it shortly after and continue to work in the editor; I would find it annoying to have to show the in-editor preview each time I do this.

**Comment by pshrmn** [comment]
@lbogdan this can be closed; the first part was the main purpose for the issue, so if that is fixed I'm good. For the second part, I don't really use the pop-out very often, so I'll defer to you for the ideal behavior.

**Comment by lbogdan** [comment]
Can you please check the first part is working for you, though? And if so, also close this? Thanks!

**Comment by pshrmn** [comment]
Looks good to me!
