### ISSUE TITLE
Emmet

### ISSUE THREAD

**Issue by smdimagerie** [CompuIves/codesandbox-client#1215]
# 🌈 Feature

An emmet implementation would be nice for writing static assets

**Comment by CompuIves** [comment]
Just deployed Emmet support in JSX, is this what you were looking for? 😄

**Comment by smdimagerie** [comment]
1) I dont know if that is supposed to work, but it doesn't seems to work

2) Emmet is more important when developping static assets; 
in css: writing br:nr is way faster that background-repeat: no-repeat; so... more productive
in html .class is faster than <div class="class"></div>
of course that translate to JSX

**Comment by CompuIves** [comment]
It should show as an autocompletion, like here: 
![image](https://user-images.githubusercontent.com/587016/47498471-a82ed600-d85d-11e8-92f5-2d17a2e35385.png). Does that happen for you? Maybe it works after clearing caches.

**Comment by smdimagerie** [comment]
Cool, i've made test, it seems to work in JSX (unfortunatly for some), LESS, CSS, .....but not in HTML (! -> tab should bring a template)

**Comment by quangv** [comment]
Related to #194

**Comment by amarvukovic** [comment]
Anyone solve problem of using Emmet in html files. When you want to type a.class-name*3 the tab does not work. It works for JSX files, but not .html.

**Comment by SaraVieira** [comment]
Hey!

I am gonna close so we can keep track in an issue specifically for this: https://github.com/CompuIves/codesandbox-client/issues/1476

I commented to bring it up

**Comment by marcosvillabasa** [comment]
how to use emmet in codesandbox ???'

**Comment by GuerrillaCoder** [comment]
For anyone that comes across this googling why it's not working in `.js` files.  You will need to rename them to `.jsx`
