### ISSUE TITLE
Less and sass compilation

### ISSUE THREAD

**Issue by smdimagerie** [CompuIves/codesandbox-client#1216]
# 🌈 Feature
Less and sass compilation would be cool

**Comment by cardiv** [comment]
Hey @smdimagerie,

what's your use case for that? Which environment do you use?

Primarily I work on Gatsby projects which has drop-in support for `less` with [gatsby-plugin-less](https://www.gatsbyjs.org/packages/gatsby-plugin-less/).

**Comment by lbogdan** [comment]
Closing this, as it's very vague, and we already support `less` and `sass` compilation in several templates. Please reopen with more details if you have a very specific use case.
