### ISSUE TITLE
Dank Mono is a bad font!

### ISSUE THREAD

**Issue by badass-icon** [CompuIves/codesandbox-client#1222]
# 🐛 bug report

## Dank Mono is a bad font!

![333](https://user-images.githubusercontent.com/857949/47353242-6cacd400-d6c4-11e8-9a6a-76ff1dcd64e2.png)

Just check the screenshot, especially 'f' character looks ugly. 
Windows 10 / Chrome 70 

### Solution:
Remove 'dm' from the Code Mirror theme / font families
```font-family: dm, Menlo, "Source Code Pro", monospace;```

**Comment by CompuIves** [comment]
You can disable it if you want, it's a preference in your settings.

**Comment by badass-icon** [comment]
@CompuIves thanks! changing settings helped, but for me it still looks like default font is really wrong. 
Was it chosen intentionally? Can we have a poll if people like it?

**Comment by lbogdan** [comment]
Closing this, as it's the only complaint we got about the default font.

**Comment by kenlyon** [comment]
I also think the "f' looks weird. I think it's the kind of thing most people put up with, and there's not much incentive to change it unless people are _really_ vocal about it.

**Comment by MauroNavaLuevanos** [comment]
Put Dank Mono in your preferred font and to make it most fancy, enable an italic theme as 1984
