### ISSUE TITLE
Frozen Github authentication

### ISSUE THREAD

**Issue by carloslfu** [CompuIves/codesandbox-client#1224]
# 🐛 bug report

## Description of the problem
I get the screen frozen on "Signing in..." when trying to authenticate with Github.
![screen shot 2018-10-23 at 10 37 48 am](https://user-images.githubusercontent.com/5993168/47372791-19c92180-d6b0-11e8-804a-9cd0ab8e3943.png)
## How has this issue affected you? What are you trying to accomplish?
I was trying to sign in with Github with this account (@carloslfu).
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Latest
| Browser | Chrome 70.0.3538.67 (Official Build) (64-bit)
| Operating System | MacOS 10.13.4 (17E199)

**Comment by carloslfu** [comment]
It's weird, it sometimes happens and it sometimes not. Right now, I'm not able to reproduce. But I noticed the button doesn't change when you "sign in with Github" from a sandbox (sometimes).

**Comment by CompuIves** [comment]
This might be related to the recent GitHub downtime, we'll need to keep an eye on it.

**Comment by lbogdan** [comment]
@carloslfu Does this issue still persist? Can we close it?

**Comment by lbogdan** [comment]
Closing this, as no complaints since last comment.
