### ISSUE TITLE
Hash link click interceptor

### ISSUE THREAD

**Issue by pshrmn** [CompuIves/codesandbox-client#1226]
# 🐛 bug report

## Description of the problem

Clicking a link with a hash should be intercepted by the [hash link interceptor](https://github.com/CompuIves/codesandbox-client/blob/f885a183963cd881c8025ac0e115caf4aac6104f/packages/sandbox-hooks/url-listeners.js#L109-L136). However, the event listener is never called, so the location does not change.

I have also tried adding other event listeners to the `document` (from within the `url-listeners` module), but they don't work either. (Also, calling `getEventListeners(document)` in Chrome's dev tools shows no event handlers on the `document`.)

I'm a bit confused as to why this is happening. If I attach a variable to the `document`, it exists on the `document` in the console, so it should be the same `document` that the event listeners are added to. Could some part of the render process wipe out the event listeners?

To be safe, I checked out a commit prior to my recent history changes and verified that they have no effect on this.

###  Link to sandbox: [link](https://codesandbox.io/s/vqw1mnnl9y)

Clicking on the "Hash Link" link has no effect and clicking on the "Push Hash" button changes locations, but popping to the hash location (clicking back, then forward) does not get detected by the `hashchange` listener event though a `hashchange` event is dispatched.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | DEV-1538629163-1a00522c |
| Browser | Chrome |
| Operating System | Linux Mint |

**Comment by lbogdan** [comment]
@pshrmn Can you confirm this isn't an issue for you anymore?

As you can see from the PR that fixed it, the root issue was that we used to do `document.[open|write|close]()` to set the html, and this had the side-effect of removing all previously set `document` event handlers.

**Comment by pshrmn** [comment]
Looks good to me.
