### ISSUE TITLE
Calls to navigator.mediaDevices.getUserMedia fail

### ISSUE THREAD

**Issue by katranci** [CompuIves/codesandbox-client#1242]
# 🐛 bug report

## Description of the problem
Calls to `navigator.mediaDevices.getUserMedia` fail

## How has this issue affected you? What are you trying to accomplish?
I'm trying to acquire camera stream

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1540564451-5ce2475 |
| Browser | Chrome Version 69.0.3497.100 (Official Build) (64-bit) |
| Operating System | macOS 10.13.6 |

**Comment by Komar0ff** [comment]
**Hi @katranci!**
you forgot brackets in addEventListener
try this: `.addEventListener("click", getUserMedia())`

**Comment by katranci** [comment]
Hey @Komar0ff 👋 `getUserMedia` is the event handler and it gets invoked if you click on the button. So the problem is not parentheses.

**Comment by CompuIves** [comment]
Hey @katranci, thanks for sending this issue! I believe browsers don't allow iframes to access camera/microphone streams. You can open it by opening the iframe externally (next to the address bar there is an 'Open Externally' button).

I'll close this one as this one is unfixable without changing browser behaviour.

**Comment by katranci** [comment]
Thanks @CompuIves, I've found out that [Chrome deprecated permissions in cross-origin iframes in C64 release](https://dev.chromium.org/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes). However, they can be enabled by specifying a Feature Policy. Example `<iframe allow="camera microphone geolocation midi encrypted-media">`
