### ISSUE TITLE
Creating sandbox from modal doesn't close modal

### ISSUE THREAD

**Issue by pshrmn** [CompuIves/codesandbox-client#1243]
# 🐛 bug report

## Description of the problem

When on the dashboard page, clicking the "New Sandbox" button opens a modal. When a sandbox type is selected, CS goes to the new page for the template, but the modal is not closed.

This also happens when opening the new sandbox modal from the profile, but doesn't happen when creating a sandbox from codesandbox.io/s. I haven't looked at the code, but I assume /s is the same form that the modal uses, but not actually a modal.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1540564451-5ce2475 |
| Browser | Chrome |
| Operating System | Linux Mint |

**Comment by CompuIves** [comment]
This one will be fixed today!

**Comment by pshrmn** [comment]
I didn't spot which commit fixed this, but it looks like this can be closed.
