### ISSUE TITLE
Gatsby Starter Sandbox shows 502

### ISSUE THREAD

**Issue by sairam** [CompuIves/codesandbox-client#1244]
# 🐛 bug report

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1540564451-5ce2475 |
| Browser |  Chrome 70 |
| Operating System | Mac OS X 10.12 |

![image](https://user-images.githubusercontent.com/163584/47647376-d0d80800-db9c-11e8-9741-2c77fee7bdc0.png)

**Comment by cardiv** [comment]
Hey @sairam,

I stumbled upon the same bug. Forking the sandbox solves this issue.

Look at this example: https://codesandbox.io/s/q3ypqyv3n9

**Comment by sairam** [comment]
@cardiv , just able to confirm forking this works. I think something should be done to fix the error since users may hesitant not to try gatsby on Codesandbox website

**Comment by lbogdan** [comment]
Should be fixed now, please check and close if it works.

**Comment by edm00se** [comment]
I’m seeing this again. What was the fix the first time @lbogdan?

![image](https://user-images.githubusercontent.com/622118/60377713-baf63d80-99de-11e9-8a47-3db9416a3061.png)

**Comment by apolopena** [comment]
I cant seem to fork a gatsby sandbox I get `502: bad gateway` and a ton of `Error: Input file is missing or of an unsupported image format` errors during the build.

**Comment by garethx** [comment]
@apolopena please share the URL of the Gatsby project you're trying to fork. Thanks.
