### ISSUE TITLE
TypeScript support from CRA 2 does not work

### ISSUE THREAD

**Issue by brunolemos** [CompuIves/codesandbox-client#1245]
# 🐛 bug report

## Description of the problem

CRA 2 with `react-scripts@next`supports TypeScript, but it doesn't work on codesanbox. It is not recognizing ts or tsx files.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1540564451-5ce2475
| Browser | Chrome
| Operating System | macOS Mojave

**Comment by CompuIves** [comment]
Fixed by #1239. Will deploy that tomorrow!

**Comment by brunolemos** [comment]
It works now!
