### ISSUE TITLE
the new Create React APP Release 2.1 does not work with typecript

### ISSUE THREAD

**Issue by soufDev** [CompuIves/codesandbox-client#1250]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

I have a probleme when I installed the new CRA 2.1 using typecript it tells me there is not file and I have to add a main property in package.json specifying the index.tsx I did it, but there is no render any more

###  Link to sandbox: [link]() (optional)
https://codesandbox.io/s/github/soufDev/testing-hooks-typescript
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | don't know 
| Browser |  Chrome verion 70.0.3538.77
| Operating System | Ubuntu 16.04

**Comment by eps1lon** [comment]
Duplicate of #1245

**Comment by CompuIves** [comment]
Thanks for the notice @eps1lon!
