### ISSUE TITLE
Codesandbox not working when using certain dependencies (Angular)

### ISSUE THREAD

**Issue by bengry** [CompuIves/codesandbox-client#1251]
# 🐛 bug report

## Description of the problem
I tried to create a sandbox with a bit of a complex setup, but one that should still work (works locally).
The base of the Sandbox is an Angular template, with all the dependencies upgraded to their latest versions.
As soon as I use any module from one of the packages, the whole app crashes.
![image](https://user-images.githubusercontent.com/260431/47719601-5c60a000-dc54-11e8-9d83-a9548268e3cb.png)

## Reproduction steps:
1. Fork the [sandbox](https://codesandbox.io/s/p5yq41qxvj?module=%2Fsrc%2Fapp%2Fapp.module.ts)
2. Comment in line 3 and the commented out part in line 8 (`FabButtonModule`)
3. Refresh the browser preview
4. App crashes with above error

## How has this issue affected you? What are you trying to accomplish?
I can't have a live demo of my library online, and require users to clone the repo to use the demo and play around with it.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1540898576-f6c614f
| Browser | Firefox 64b4, Chrome 70
| Operating System | MacOS 10.14

## More info
[`@angular-react`](https://github.com/microsoft/angular-react) is a set of libraries that enable embedding React components inside Angular applications.
It's comprised of two parts:
1. `@angular-react/core` - the core engine that runs things, replaces `BrowserModule` with its own (`AngularReactBrowserModule`).
2. `@angular-react/fabric` - a wrapper around the [`office-ui-fabric-react`](https://github.com/OfficeDev/office-ui-fabric-react) UI components package, written in React, to allow usage in Angular applications.
3. _(`@angular-react/semantic-ui` - a wrapper around [`Semantic UI React`](https://react.semantic-ui.com/) - not actively maintained, but demonstrates and ensures that the core library isn't coupled to the Fabric library)_

The sandbox linked above is an Angular 7.0 application, with `@angular-react/core` (and its peer dependencies - `react` and `react-dom`) and `@angular-react/fabric` (and its peer dependencies - `office-ui-fabric-react`).

**Comment by lbogdan** [comment]
Hey @bengry ,

This indeed looks like a complex package structure. What I'd suggest is using a [server sandbox](https://hackernoon.com/codesandbox-containers-5864a8f26715) - and until we add an Angular server template, I have a starter here https://codesandbox.io/s/github/lbogdan/cs-angular-starter , which you can fork and play with.

**Comment by bengry** [comment]
Hey @lbogdan,
Thanks for taking the time to look at this. I tried to [fork the sandbox](https://codesandbox.io/s/pkj24qln9m) you provided and add the functionality from the original (broken) one I linked to it, but it also fails with the following error (in the terminal):
> error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I'm not sure what's going on there. Would appreciate if you could take a look.

**Comment by bengry** [comment]
Got it, that's pretty odd that it gets up this high though, don't you think?
I tried a more complete example (same dependencies, just one with more components going on etc.) and it used ~500MB memory, so the above should be well under 1GB.

I am referring to the backend (`node`) server's memory, not the client's. I assume the later is a non-issue, or is it? Anyway, I still presume the client I ran was under 500MB.

**Comment by lbogdan** [comment]
It's whatever's running inside the sandbox (which in this case is the `ng serve`). As odd as it seems, I'm pretty sure it's actually trying to use more than 1GB than being a bug in Kubernetes. 🙂

**Comment by bengry** [comment]
I agree. I haven't watched the moment during boot (locally), maybe it's doing above 1GB when compiling, then drops to 500MB afterwards. I'll have a look.
Unfortunately, I'm not sure how I can reduce the memory usage here, since the app is pretty basic (functionality-wise), but compiling down the node_modules seems to be killing it.

Any suggestions?

Also, why 1GB? Is there a chance you'll increase it?

**Comment by lbogdan** [comment]
> Also, why 1GB? Is there a chance you'll increase it?
Because my estimation was that any well-behaved web development environment shouldn't use more than that - and as I mentioned above, this proved to be accurate... until now. Also, we don't have infinite system resources. 🙂

**Comment by lbogdan** [comment]
Also, just took a look at the process, and it's indeed getting to 1GB memory usage:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
26065 1001      20   0 1997456 952928  26600 R  67.0  1.4   0:38.87 ng serve --disa
```
(see the `RES` column, which is in kB)

**Comment by bengry** [comment]
Yea, I totally get the limitation, just 1GB seems like an arbitrary number (i.e. could've been 500MB all the same).
Too bad that we wouldn't be able to showcase this project there, but online IDEs like Codesandbox have their limitations drawn at some point, I guess this project is just beyond that. No worries, fantastic product otherwise 👍.

Thanks for the help. I'm closing the issue even though it wasn't "resolved" per-se. I'd appreciate it if you could update here in case you increase the limit in the future, so I can re-visit this.
