### ISSUE TITLE
Dojo 4 with tsx not working

### ISSUE THREAD

**Issue by MarvDann** [CompuIves/codesandbox-client#1258]
# 🐛 bug report

## Description of the problem
While using the Dojo 4 template, we should be able to use tsx as an alternative to hyperscript for rendering widgets. When we try to use tsx by renaming the widget file to a .tsx extension and using the '@dojo/framework/widget-core/tsx' import, we get an error which looks like it is trying to transpile to react code.

```
ReferenceError
React is not defined
App.render
https://nwxl5q953j.codesandbox.io/src/widgets/App.tsx:22:9
  19 |     return _super !== null && _super.apply(this, arguments) || this;
  20 | }
  21 | App.prototype.render = function () {
> 22 |     return (React.createElement("div", null,
     |     ^
  23 |         React.createElement(Hello_1.default, { name: "CodeSandbox" }),
  24 |         ",",
  25 |         React.createElement(DialogPane_1.default, null),
...
```

## How has this issue affected you? What are you trying to accomplish?
We use code sandbox when reporting issues to the Dojo team to illustrate any problems we are having.
###  Link to sandbox: [link]() (optional)
https://codesandbox.io/s/nwxl5q953j
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | https://codesandbox.io/s/nwxl5q953j
| Browser | Chrome / 70
| Operating System | Windows / 10 Pro 64 Bit

**Comment by CompuIves** [comment]
Hmm, it seems like this is a configuration in the template @nicknisi?

**Comment by nicknisi** [comment]
Yeah, it looks like it's not using the right factory. I'll dig into why!
