### ISSUE TITLE
React Hooks linting rules are triggered in Vue component

### ISSUE THREAD

**Issue by tesla3327** [CompuIves/codesandbox-client#1261]
# 🐛 bug report

## Description of the problem
The rules around usage of `useXXXX` methods are linting Vue components as well.

## How has this issue affected you? What are you trying to accomplish?
It is annoying.

###  Link to sandbox: [link](https://codesandbox.io/s/4jk8o314kx)

<img width="561" alt="screen shot 2018-11-01 at 8 21 34 am" src="https://user-images.githubusercontent.com/3078446/47851498-2f74d000-ddaf-11e8-9f95-25a0ac87db36.png">

**Comment by CompuIves** [comment]
Are `useXXX` methods common in Vue?

**Comment by vivek12345** [comment]
@CompuIves I think we can close this issue now. Thanks 🎉

**Comment by lbogdan** [comment]
Fixed in #1276 .
