### ISSUE TITLE
Directory title length increase

### ISSUE THREAD

**Issue by dance2die** [CompuIves/codesandbox-client#1263]
# 🐛 bug report

## Description of the problem

[Importing from a GitHub](https://codesandbox.io/s/github) repository [dance2die/JavaScript30](https://github.com/dance2die/JavaScript30) displays `should be at least 32 character(s)` messages.

![codesandbox import error](https://user-images.githubusercontent.com/8465237/47910866-7ecc0680-de6a-11e8-9875-1eb6fc3bb8de.gif)

## How has this issue affected you? What are you trying to accomplish?

Unable to import GitHub repository in CodeSandbox thus wasn't able to import the repository.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | [Import from GitHub](https://codesandbox.io/s/github)

### Additional Context

This is a reminder for @CompuIves as requested in Discord.

![image](https://user-images.githubusercontent.com/8465237/47911275-6c9e9800-de6b-11e8-83c1-bdf65f504ede.png)

**Comment by CompuIves** [comment]
Just deployed an update that doubles the max length!

**Comment by CompuIves** [comment]
Oh, new problem... I think the directory/module titles don't pass our format validation: `/^[^<>:;,?"*|\/]+/`. I believe I took this one from the Windows format validator, so it's interesting that the file is correctly hosted on GitHub 🤔

**Comment by CompuIves** [comment]
I think this is the name with the issue (because of the `,`): "25 - Event Capture, Propagation, Bubbling and Once"

**Comment by dance2die** [comment]
Thank you @CompuIves. 👊 

The repo was originally forked from Wes Bos's [JavaScript 30 repo](https://github.com/wesbos/JavaScript30). 
He uses a Mac so would it have something to do with it?

**Comment by davefollett** [comment]
I can confirm that the commas were indeed the issue so I removed them from my fork.
