### ISSUE TITLE
DependencyNotFoundError: Could not find dependency: '' relative to '/src/main.js'

### ISSUE THREAD

**Issue by OculusMode** [CompuIves/codesandbox-client#1264]
# 🐛 bug report

## Can't run sandbox which has no issue
Details:
DependencyNotFoundError
Could not find dependency: '' relative to '/src/main.js'

Note: if i try to add dependency, it adds some blank dependency and generates another error
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome (all though generated on all browsers)
| Operating System | MacOS(all though generated on all OS)

**Comment by marskid** [comment]
The same issue [https://codesandbox.io/s/rmykx7k5rn](https://codesandbox.io/s/rmykx7k5rn)

**Comment by ParsonsProjects** [comment]
Same issue happening here https://codesandbox.io/s/84vpkojoxl

**Comment by snirp** [comment]
Same here https://codesandbox.io/s/zr070m9vjp for a Vue project. Attempted to publish from Github and from the npm commandline tool.

**Comment by snirp** [comment]
Anyone found a workaround? Would be much appreciated.

**Comment by SaraVieira** [comment]
Wow! This is really weird and a nasty one. I will try to take a look at it with Ives. Thank you for letting us know

**Comment by CompuIves** [comment]
We fixed this one! Should be live around tomorrow morning.

**Comment by shubham-rocko** [comment]
Same here https://codesandbox.io/s/angular-8df8d for an Angular project. I'm using froala editor version 3.0.5

**Comment by benprofitt** [comment]
I am currently experiencing this error on a react-ts project imported from a github repo

**Comment by dialoguewise** [comment]
Spend time worrying about what I'm doing wrong. Looks like I'm not alone :).  I'm getting the same issue.

```
DependencyNotFoundError
Could not find dependency: 'jsSHA' relative to '/node_modules/dialogue-wise/bundles/dialogue-wise.umd.js'
```

https://codesandbox.io/s/dialoguewise-demo-fjd67

**Comment by heri16** [comment]
Not able to import from an ObjectUrl for me: https://codesandbox.io/s/svelte-count-variable-occurrence-3zq51?file=/src/App.js

**Comment by SaraVieira** [comment]
Hey!

If you are experiencing something like this please create a new issue so we can keep better track as it possibly another issue on our end 

Thank you
