### ISSUE TITLE
Formatter Error in `Vue` Porject

### ISSUE THREAD

**Issue by sudazx** [CompuIves/codesandbox-client#1271]
# 🐛 bug report

# Document Formatter in Vue 

### Repeat Procedure

Open the console, and right click the menu option: ***FormatDocument***,  you will see the error like following
```
TypeError: Cannot read property 'insertSpaces' of null
```
i'm taking some time to find the root cause, and find the origin is the `monaco-vue` plugin which used in codesandbox.

### Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |           latest         |
| Browser |  chrome 60 |
| Operating System |  MacOS |

**Comment by sudazx** [comment]
If you want to immediate solve this problem, you can moneypatch or just fix the following three pieces of code in `vue-worker.js ` which under the path `monaco-vue/release/min`

```
t.insertSpaces?t.tabSize:1
```
```
indent_char:t.insertSpaces?" ":"\t"
```
```
t.insertSpaces?c.repeat(" ",t.tabSize*h):c.repeat("\t",h)
```
remove `t.insertSpaces` and use the default setting which you desire.

I hope the official team could offer a better solution. 

Thansk!

**Comment by SaraVieira** [comment]
Issue closed as we dropped the monaco editor in the latest release and we now support vetur :D
