### ISSUE TITLE
Cannot extract value at path "sandbox.id" error

### ISSUE THREAD

**Issue by luisherranz** [CompuIves/codesandbox-client#1272]
# 🐛 bug report

## Description of the problem

I've forked this sandbox and I cannot access the original anymore: https://codesandbox.io/s/oqrn065pw5

Console error is `Uncaught Error: Cannot extract value at path "sandbox.id" ("id" is not defined).`

## How has this issue affected you? What are you trying to accomplish?

If I access it in incognito (no login) it works fine. Logging out and refreshing seems to fix the problem, like incognito mode. But if I log in again and refresh, the problem reappears so it's definitely related to a login state.

Disabling VS Code fixed it as well. VS Code and incognito still work. Seems related to both login and VS Code.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  PROD-1541378538-cfd11b5 |
| Browser | Chrome/70 |
| Operating System | macOS/11 |

**Comment by CompuIves** [comment]
Hey! Thanks for the report, looking into it now. Do you know which line this happened on?

**Comment by CompuIves** [comment]
Sentry issue: [FRONTEND-91E](https://sentry.io/codesandbox/frontend/issues/673732357/)

**Comment by luisherranz** [comment]
I can't reproduce that error anymore 😅

Did you catch it?

**Comment by SaraVieira** [comment]
@luisherranz Can I close and then you can reopen if it happens again ? :)

**Comment by luisherranz** [comment]
Sure! 👍
