### ISSUE TITLE
Embed sandbox breaks when switching files repeatedly

### ISSUE THREAD

**Issue by KaneFreeman** [CompuIves/codesandbox-client#1277]
# 🐛 bug report

## Description of the problem
The sandbox loads just fine, but if you click between the two typescript files (`App.tsx` and `main.ts`) a couple of times the sandbox silently dies.

## How has this issue affected you? What are you trying to accomplish?
I am trying to embed a dojo 4 sandbox on a static webpage.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Latest |
| Browser | Chrome 70 |
| Operating System | Windows 10 |

**Comment by lbogdan** [comment]
Closing this, as I can't replicate, and I'm quite confident it was fixed with the recent switch to VSCode as the default editor.

However, @KaneFreeman feel free to reopen if you still experience this behavior.
