### ISSUE TITLE
clarify transition behavior and side effects when cancelling patron subscription

### ISSUE THREAD

**Issue by knksmith57** [CompuIves/codesandbox-client#1278]
# ❔ Question

When a patron subscriber cancels a subscription:
1. Are privacy and sharing features of private sandboxes preserved?
2. What happens to sandboxes if the patron has more than the free limit (currently documented as 50)?
3. What happens to static hosting assets / resources if the patron is using more than the free limit (currently documented as 20Mb)?
4. Are there any additional consequences / side effects?

I've searched for documentation outlining the transition behavior and side effects of cancelling a [patron subscription](https://codesandbox.io/patron) but have been unable to find anything on [the docs site](https://codesandbox.io/docs). Generally speaking, I think it'd be a good idea to get this stuff in writing on the site.

Thanks!

**Comment by CompuIves** [comment]
I completely agree, I will focus on our pricing system for the coming weeks and will take this with that.

**Comment by knksmith57** [comment]
@CompuIves thanks for the speedy reply!

If it's not too much to ask, I'd very much appreciate clarification for the provided questions ASAP, even if that means simplified answers in this thread vs comprehensive documentation on the site.

I am a current subscriber and am rebalancing my monthly donations and evaluating whether or not I will keep my codesandbox subscription. Before I suspend payment, I'd like to know what's going to happen to my account and the private sandboxes I've already created.

thanks for your time!

**Comment by CompuIves** [comment]
Absolutely!

> Are privacy and sharing features of private sandboxes preserved?

Yes, we don't make all the sandboxes public. You'll lose the option to change privacy of your sandboxes.

> What happens to sandboxes if the patron has more than the free limit (currently documented as 50)?

You won't be able to create new sandboxes until you've deleted some.

> What happens to static hosting assets / resources if the patron is using more than the free limit (currently documented as 20Mb)?

Same story as sandboxes, you won't be able to upload until you've deleted uploads.

> Are there any additional consequences / side effects?

Not that I know of. I have to admit that I haven't tested this thoroughly. So any feedback is appreciated!

**Comment by knksmith57** [comment]
excellent, thanks so much for clarifying! 🙏
