### ISSUE TITLE
Feature: Increased capacity for server CSBs

### ISSUE THREAD

**Issue by manniL** [CompuIves/codesandbox-client#1279]
Hey all!

I know that the functionality is still in beta but I hit my limit for recently (and have to delete the "less important" ones).

Is there a plan to update the capacity?

**Comment by SaraVieira** [comment]
Hey!

There are plans to increase it in the coming weeks as soon as it leaves beta :)

Thank you for other issues, good points :)

**Comment by manniL** [comment]
@SaraVieira Thanks for the info! In case there won't be a large announcement (or similar but I guess there will be ☺️ ), I'd appreciate a ping.

**Comment by manniL** [comment]
@SaraVieira are there any news with regards to the end of SSE beta? ☺️

**Comment by SaraVieira** [comment]
Not yet :(

**Comment by manniL** [comment]
@SaraVieira Too bad :|
Could we reopen that issue then to signal that the change will happen in the future? :smile:

**Comment by SaraVieira** [comment]
Ofc :)

I also have a PR to put this info on the patreon page :)

**Comment by manniL** [comment]
Closed via. https://medium.com/@compuives/codesandbox-containers-out-of-beta-improvements-be79679df4cc

Thanks :pray:
