### ISSUE TITLE
Feature: "Empty trash" button

### ISSUE THREAD

**Issue by manniL** [CompuIves/codesandbox-client#1280]
Heya! :wave: 

As the trash becomes more important with server-side CSBs, as the limit is fairly lower in comparison to client-side ones and the trashed ones count as well, I'd love to see a "delete all from trash" button (with an extra confirmation dialog or so).

**Comment by zixuan75** [comment]
Trash?

**Comment by SaraVieira** [comment]
ohhhhh

This has actually been fixed https://github.com/CompuIves/codesandbox-client/pull/1592
