### ISSUE TITLE
Can’t sign into Codesandbox

### ISSUE THREAD

**Issue by calebmer** [CompuIves/codesandbox-client#1287]
# 🐛 bug report

## Description of the problem

When trying to sign into Codesandbox using GitHub I get redirected to https://codesandbox.io/signin/... and I get stuck there. I tried revoking my GitHub access token then signing in again. No dice.

<img width="1680" alt="screen shot 2018-11-06 at 6 30 12 pm" src="https://user-images.githubusercontent.com/8282507/48106888-44f45a80-e1f2-11e8-804e-f80352a09232.png">

## How has this issue affected you? What are you trying to accomplish?

I was trying to see my dashboard to continue working on a sandbox.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Browser | Chrome |
| Operating System | MacOS |

**Comment by CompuIves** [comment]
Hey! Does the console say anything on that page? Normally the page should open in a window, so that could be the cause of the issue maybe.

It could also be something with the server. I wonder if it's still happening right now.

**Comment by calebmer** [comment]
It worked today. Sorry for the noise.

**Comment by misterhtmlcss** [comment]
I've had this happen just now in latest chrome 74 on latest macos and I also revoked on github to try something and it failed. Then I read this article and for no particular reason tried it again (2nd try after revoking it) and it finally logged in. 

Sorry to those who follow if this doesn't help you, but it's just another random way to get it working that I've found.

**Comment by tarath** [comment]
having similar issue, trying to log in with github, put in username and password and now am stuck on a grey screen.

**Comment by henryarbolaez** [comment]
```vendors~app.58180fdb.chunk.js:28 TypeError: Pe[e] is not a function
    at Object.removeListener (app.d007e9be.js:438)
    at Object.Ki [as function] (app.d007e9be.js:438)
    at e.value (vendors~app.58180fdb.chunk.js:80)
    at vendors~app.58180fdb.chunk.js:80
    at vendors~app.58180fdb.chunk.js:80
    at t (vendors~app.58180fdb.chunk.js:80)
    at vendors~app.58180fdb.chunk.js:80
    at vendors~app.58180fdb.chunk.js:80
    at t (vendors~app.58180fdb.chunk.js:80)
    at vendors~app.58180fdb.chunk.js:80
    at a (vendors~app.58180fdb.chunk.js:80)
    at t.value (vendors~app.58180fdb.chunk.js:80)
    at t.value (vendors~app.58180fdb.chunk.js:50)
    at run (vendors~app.58180fdb.chunk.js:50)
    at app.d007e9be.js:438
    at ps (common.9e266ddd.chunk.js:191)
    at common.9e266ddd.chunk.js:191
    at Us (common.9e266ddd.chunk.js:191)
    at Object.enqueueSetState (common.9e266ddd.chunk.js:191)
    at n.setState (common.9e266ddd.chunk.js:199)
    at app.d007e9be.js:438
    at g (common-sandbox.0ef63883.chunk.js:15)
    at Generator._invoke (common-sandbox.0ef63883.chunk.js:15)
    at Generator.next (common-sandbox.0ef63883.chunk.js:15)
    at o (common-sandbox.0ef63883.chunk.js:15)
    at u (common-sandbox.0ef63883.chunk.js:15)```

**Comment by dylan904** [comment]
dmvendor.css:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
browserfs.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
 Uncaught ReferenceError: BrowserFS is not defined
    at 
app.77eff064.js:438 Uncaught TypeError: Cannot read property 'BFSRequire' of undefined
    at Object../src/app/store/index.js (app.77eff064.js:438)
    at a (app.77eff064.js:1)
    at Module../src/app/index.js (app.77eff064.js:438)
    at a (app.77eff064.js:1)
    at Object.0 (app.77eff064.js:438)
    at a (app.77eff064.js:1)
    at t (app.77eff064.js:1)
    at app.77eff064.js:1
    at app.77eff064.js:1

**Comment by MrPotatoLord** [comment]
not working for me either, and im on firefox.

**Comment by ruucm** [comment]
same here. tested on safari & chrome

**Comment by atchuta168** [comment]
Still i am facing the same issue, when i try to login it is showing login again and again

**Comment by nthorn-adam** [comment]
I also just faced this issue. Logging in thru Google, it popped up the modal, went thru the flow, and finally at the end just showed some text `something went wrong`. I refreshed the page, tried to use GitHub sign in, and it seemed like it worked from GitHub's end, but on CodeSandbox itself nothing happened & the GitHub button's text / icon was replaced with three dots.

Finally, I hard reloaded & cleared cache, and then GitHub sign-in worked fine.

**Comment by minbelapps** [comment]
I got the message after Google sign-in "We found an existing account, please sign in with GitHub instead." ??????

**Comment by CodeSandboxTeam** [comment]
Hey @minbelapps, 


Please could you message us at ***@***.***, we'll get this sorted for you!

—
James
Support
CodeSandbox.io

--- original message ---
On January 25, 2022, 10:25 AM GMT ***@***.*** wrote:



I got the message after Google sign-in "We found an existing account, please sign in with GitHub instead." ??????

—

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
--- end of original message ---

**Comment by bablu1921** [comment]
When i tried to signin on codesandbox it says "we found an existing account pls sign in with google"

**Comment by JamesACS** [comment]
Please could you email support @bablu1921 ? We can then look into this for you

**Comment by marcelotrivinos** [comment]
> 

Same problem, but  I was able to enter using the email (CodeSandbox gets your email from OAuth when you create your account)

**Comment by DuboisCecile** [comment]
Hi,

I have the same problem, I can't connect anymore to my codesandbox account.
I revoked the access from Github to codesandbox, hoping I would be able to create a new one, but it didn't change anything.

I still have the same message : "We found an existing account, please sign in with instead." (Note that there is nothing between with and instead, as if codesandbox was unable to find how I could connect ?).

What can I do ?

**Comment by aj-foster** [comment]
HI @DuboisCecile, please reach out to our support team and provide any GitHub users and associated email addresses you might have used to log in with CodeSandbox in the past.

**Comment by marcelotrivinos** [comment]
> Codesandbox has your github email, try to login with that email in Codesandbox.

**Comment by marcelotrivinos** [comment]
@DuboisCecile 
Codesandbox has the email you use on github, try to log in with that email on Codesandbox.

**Comment by leonbloy** [comment]
Same problem 

I tried also with a Incognito window, when I sign with Github, i enter my credentials, it authenticates me ok, but
in codebox I get the cryptic (and dead-end.. and gramatically wrong) message 
"We found an existing account, please sign in with instead."

Very annoying

**Comment by W4yneChen** [comment]
Same problem
When I sign in with Github,  i get message "We found an existing account, please sign in with instead."
![image](https://user-images.githubusercontent.com/29047653/209783906-d28b98f7-3874-42f4-8d7d-9f3934ba3159.png)

**Comment by sannek** [comment]
@W4yneChen can you email `support@codesandbox.io` with your username / email address? Then i can have a look to see what is going on with your account.

**Comment by CheezItMan** [comment]
I had the same issue, will also email in.

**Comment by gbowne1** [comment]
I can't sign in either. Been trying for a week or so.  It's just a totally black screen.

**Comment by rcbevans** [comment]
Broken for me.  Neither oauth to github, nor google result in a login happening.

**Comment by rcbevans** [comment]
@sannek  this is related to brand new users who don't have a profile yet.

As a brand new user, logging in from a sandbox editor did not work.

I then went to the main code sandbox homepage, logged in via oauth, and a profile create ui was triggered which I completed.

I was then able to log in successfully from the sandbox editor.
