### ISSUE TITLE
Prettier prettify package.json on save after update

### ISSUE THREAD

**Issue by vadimshvetsov** [CompuIves/codesandbox-client#1289]
# 🐛 bug report
Hi, there is an issue with Prettier after Codesandbox update.
It prettifies `json` on every save if it's not disabled.

**Comment by phiter** [comment]
Same. I disabled prettier in the configs in order to save package.json. Then I enabled it again.

**Comment by lbogdan** [comment]
Hey guys, this should be fixed, can you please test and let us know?

**Comment by lbogdan** [comment]
Ok, closing this.

Regarding #924, @CompuIves is the "master of the bundler", so you'll have to talk to him about that.
