### ISSUE TITLE
Jest test times out

### ISSUE THREAD

**Issue by oleersoy** [CompuIves/codesandbox-client#1290]
# 🐛 bug report

The following RxJS Jest test times out:
https://codesandbox.io/s/nk6rv45oz4

Thoughts?

**Comment by oleersoy** [comment]
Hmmm - Strange - I switched tabs, came back later and then back and now it no longer times out.  The same type of thing would happen with my imports..."rxjs" would have red squiggly lines under it, and when I opened the same project in a different tab they disappeared.   This can be closed if need be.

**Comment by SaraVieira** [comment]
We will still see if we can make this happen again but closing for now

Thank you
