### ISSUE TITLE
Unexpected token 

### ISSUE THREAD

**Issue by bang88** [CompuIves/codesandbox-client#1293]
# It looks like `codesandbox` does not use our version of `react-scripts`.

## Description of the problem

We have a `react-native` example want render it to the web platform use` react-native-web`. it works 
well on local computer but after uploaded to `codesandbox` it fails to at `Transpiling` node_modules files.

We use a custom `react-scripts` which support transpiling files under node_modules. The problem was what's the difference between local env and `codesandbox`? does codesandbox allow us transpiling node_modules's files.
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | https://codesandbox.io/s/8nrznvjl2?from-embed
| Browser | Chrome
| Operating System | macOS

**Comment by bang88** [comment]
Ping @CompuIves

**Comment by CompuIves** [comment]
Fixed this just now! Will be live within an hour.

**Comment by bang88** [comment]
Thanks
