### ISSUE TITLE
GitHub : can only create PR instead of starting a fresh github repository

### ISSUE THREAD

**Issue by desirelabs** [CompuIves/codesandbox-client#1298]
Hello,

I noticed that for container sandbox, I cannot Export Sandbox to my GitHub account. I can only create PRs to the original project. Example : with Nextjs

Is this the only available behaviour ?

Thanks

**Comment by sudoris** [comment]
Also suddenly can not export to my Github (area where you enter new repo name is greyed out). I was able to export sandboxes to Github fine just a few weeks ago.

**Comment by desirelabs** [comment]
Hi, some news about this issue ?

**Comment by CompuIves** [comment]
Oh wow, this is a good point. We should allow you to create a new repo too. I will fix this today!
