### ISSUE TITLE
Is it planned to support webcomponents?

### ISSUE THREAD

**Issue by tonykiselis** [CompuIves/codesandbox-client#1300]
I'm let to believe that due to typescript compilation,
```
window.customElement.define()
```
is being called twice, which throws an error. Are the any plans to address this? I mean, is it even possible? Perhpas there is a workaround while you're mingling in codesandbox for time being to play with webcomponents around. 

Now it's kinda a bummer.

**Comment by SaraVieira** [comment]
Can you create an example sandbox pls? I don't have webcomponents experience

**Comment by tonykiselis** [comment]
https://codesandbox.io/s/8n2kyx0xn8

Interestingly enough it worked when I saved and reloaded it. 
However, if you even attempt to change code and force codesandbox to recompile it it fails on `::define()`

I'm let to believe that it has something to do with typescript compilation re-evaluating the function twice, which goes against the customElement api which does not allow it to happen twice.

This prevents any tools which use `customElement.define()` to be worked on codesandbox.io too. Like ionic's Stencil.js.

**Comment by SaraVieira** [comment]
This is super weird, I don't know if it's a parcek thing because with the static template it works: https://codesandbox.io/s/ry5x3k03vp

The thing is that this template does not reload when you make changes :(

I think this template was actually created because of google and web components but it should reload

**Comment by tonykiselis** [comment]
Hmm, when it's parcel problem I suppose. My bad.
Shadow dom prevents css being applied from global scope. It's supposed to work that way.

**Comment by SaraVieira** [comment]
Oh yay!!!


Can I close this ? :D

**Comment by tonykiselis** [comment]
Sure. My bad. Thanks for explaining though. I'll try to make stencil js work though.

**Comment by SaraVieira** [comment]
Let me know your progress here or on twitter at @NikkitaFTW pls :)
