### ISSUE TITLE
Sandbox Does Not Load When Logged In

### ISSUE THREAD

**Issue by AureliaEffect** [CompuIves/codesandbox-client#1308]
# 🐛 bug report

## Description of the problem

I have a sandbox located here: https://codesandbox.io/s/zw9zjy0683 When logged out or logged in from a different account, the Sandbox loads. When logged into the account that created the sandbox, it gets stuck while loading.

## How has this issue affected you? What are you trying to accomplish?

I'm trying to fork my own sandbox to create some new samples. However, I can't even load the sandbox anymore while logged into my account.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Chrome | 70.0.3538.102 (Official Build) (64-bit) |
| MacOS | Mojave 10.14 |

**Comment by AureliaEffect** [comment]
I should also point out that I've tried clearing all site data and then logging in again. It works before logging in (anonymous) but not after logging into my account.

**Comment by SaraVieira** [comment]
Get any errors in the console ?

Btw thanks for a ton of Sandboxes in the past while

**Comment by EisenbergEffect** [comment]
I tried it again today and it was working again. Not sure what the issue was. I close this for now and let you know if I see it again.
