### ISSUE TITLE
zeit version 2 support

### ISSUE THREAD

**Issue by sushruth** [CompuIves/codesandbox-client#1309]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

I am trying to use zeit version 2. the API needs updating. Please update to ZEIT version 2. it results in lower cost for people using it.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1542488100-217ee75
| Browser | chrome 72
| Operating System | windows 10 dev preview

**Comment by SaraVieira** [comment]
This was added in https://github.com/CompuIves/codesandbox-client/pull/1417 🎉
