### ISSUE TITLE
Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by NoahZinsmeister** [CompuIves/codesandbox-client#1316]
# 🐛 bug report
NPM package using the [`React.lazy`](https://reactjs.org/docs/code-splitting.html#reactlazy) API is broken on CodeSandbox.

## Description of the problem
I'm using the new `React.lazy` API in [one of my npm packages: web3-react](https://github.com/NoahZinsmeister/web3-react/blob/master/src/index.js#L163). When I try to use this package in CodeSandbox, it throws a `Failed to fetch dynamically imported module` error.

## How has this issue affected you? What are you trying to accomplish?
Cannot use CodeSandbox to demonstrate how my package works. Is this because `React.lazy` doesn't support SSR?

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1542548194-f91f152 |
| Browser | Chrome Version 70.0.3538.102 (Official Build) (64-bit) |
| Operating System | macOS Mojave 10.14.1 (18B75) |

**Comment by Infi-Knight** [comment]
React.lazy is not yet available for SSR. React docs suggest using React Loadable to achieve code splitting in a ssr app. The [sandbox](https://codesandbox.io/s/3x9mvl51yq) which you forked contains the workaround.

**Comment by NoahHydro** [comment]
Cool, thanks @Infi-Knight !

**Comment by NoahZinsmeister** [comment]
Cool, thanks @Infi-Knight !
