### ISSUE TITLE
How do your turn live mode off?

### ISSUE THREAD

**Issue by johncokos** [CompuIves/codesandbox-client#1322]
# ❔ Question

I've got a couple of sandboxes that I turned on live mode for, but I don't see how to turn sharing off. Very often I'll share during a class, and then afterwards just want my sandbox back ... Sometimes, you can't open them as the live server thing is trying to connect.  

Is there a button or a link that I'm just too old to see?

**Comment by SaraVieira** [comment]
![screenshot 2018-11-24 at 13 37 12](https://user-images.githubusercontent.com/1051509/48968322-1c3fd380-efee-11e8-810e-c3fc7fe48689.png)

It's called close session :)

**Comment by SaraVieira** [comment]
Never did it so I am not sure it closes the session

**Comment by zixuan75** [comment]
I think so.

**Comment by CompuIves** [comment]
@johncokos Is this for a team sandbox or for a live session that's explicitly created?

**Comment by camflan** [comment]
@CompuIves related -- is there a way to disable live sessions for sandboxes in a team? I don't see the `Stop Session` button on my team sandboxes

**Comment by CompuIves** [comment]
> is there a way to disable live sessions for sandboxes in a team?

Not right now, I am hesitant of enabling that because it will make collision between saves pretty hard. Eg. a user changes a file and saves, then someone else changes that same file and saves, the initial changes are overwritten.

What's the reason that you're looking for a button like this?

**Comment by camflan** [comment]
Ohhh, I see. I didn't think about that. I just figured it would be a sandbox with access to anyone from my team. I understand now why you'd always have live mode on with it.

I guess I'd like to be able to turn it off until someone else opens the file, mostly because it seems like (in the past, not sure about the current version) that live reload is less reliable when live mode is running.

**Comment by johncokos** [comment]
Sorry ... stepped away for about a month ;)

This is definitely on a team sandbox. The button showed in the above image is NOT there 

![screen shot 2018-12-29 at 12 31 45 pm](https://user-images.githubusercontent.com/1766332/50541947-c10d7d80-0b65-11e9-8e90-39fc475c436f.png)

**Comment by CompuIves** [comment]
Live should be much more stable now, I think I can close this one. Don't hesitate to reopen if there's something amiss!
