### ISSUE TITLE
React-Sandpack example: CSS styles not loaded.

### ISSUE THREAD

**Issue by sitaramshelke** [CompuIves/codesandbox-client#1323]
# 🐛 bug report

## Description of the problem
Following the [Readme](https://github.com/CompuIves/codesandbox-client/blob/master/packages/react-sandpack/README.md) from `react-sandpack` project, I have created a new CRA App and added `react-smooshpack` as a dependancy. I copied the example code. But it seems the CSS styles are not loaded.

## How has this issue affected you? What are you trying to accomplish?
Unable to setup `react-sandpack`

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Environment  |   Node 
| Browser | Chrome
| Operating System | Ubuntu

**Comment by SaraVieira** [comment]
Hey !

It's an issue with the docs that I will create PR for. You need to also import the CSS:

You can see it here: https://codesandbox.io/s/l552ox9qo7

Thank you for letting us know :D

**Comment by SaraVieira** [comment]
https://github.com/CompuIves/codesandbox-client/pull/1328
