### ISSUE TITLE
vim mode can't work

### ISSUE THREAD

**Issue by mysteryven** [CompuIves/codesandbox-client#1338]
# 🐛 bug report

When I create a new React sandbox, and I set the mode to vim, but it doesn't work.

![屏幕快照 2018-11-29 下午4.33.05.png](https://i.loli.net/2018/11/29/5bffa4630e8f0.png)

**Comment by johhansantana** [comment]
I'm having the same issue.

**Comment by weima** [comment]
I have the same issue. I am running firefox on a Fredora box

**Comment by sandqvist** [comment]
Same issue on Chrome and Edge

**Comment by mysteryven** [comment]
> Same issue on Chrome and Edge

now It's fine to me, maybe some wrong with compatibility, which version of your chrome ?
