### ISSUE TITLE
default app can only be set once;  error

### ISSUE THREAD

**Issue by serdartkm** [CompuIves/codesandbox-client#1339]
# 🐛 bug report

### My Environment is
| React js        | 16|
| Сodesandbox  | 
| Browser | 
| Operating System |
![mongodb atlas stitch error](https://user-images.githubusercontent.com/7867827/49210868-fea0ae80-f3df-11e8-83e9-d0bfbec58d38.png)

**Comment by lbogdan** [comment]
Hey @serdartkm ,

I try looking at the sandbox you provided, but it looks like you changed it in the meanwhile.

Is this still an issue? If not, can you please close it? Thanks!

**Comment by serdartkm** [comment]
Hi @lbogdan, thank you for asking. It is not an issue any more.

**Comment by Emperoni** [comment]
How was this problem solved?
