### ISSUE TITLE
Action tooltips are not consistently aligned.

### ISSUE THREAD

**Issue by jseminck** [CompuIves/codesandbox-client#134]
If you compare the tooltip for Feedback and the tooltip for Contact, you can see they are not properly aligned.

![old_feeback](https://user-images.githubusercontent.com/9586897/29486728-d15cdad4-84f5-11e7-9b23-e19ea09f4e02.png)

![old_contact](https://user-images.githubusercontent.com/9586897/29486729-d36bf90e-84f5-11e7-9c80-1d721a789a6a.png)

I suspect that Contact tooltip is incorrect. It's placed relative to the icon, instead of the full action item. 
I assume that, because the blue border that gets added on hover is not visible in this way. Also, the "Save" tooltip has the same y position as the feedback tooltip.

![save_tooltip](https://user-images.githubusercontent.com/9586897/29486741-187febea-84f6-11e7-881e-ea200483a60f.png)

I played around with the code a bit, and simply using the `ActionTooltip` component instead of `Tooltip` directly in `Action.js` fixes this issue for all header tooltips which are mis-aligned.

![contact_new](https://user-images.githubusercontent.com/9586897/29486755-4a945ddc-84f6-11e7-93ed-5f6f72836144.png)

If you are happy with that change, I can make a PR for it.

**Comment by CompuIves** [comment]
Closing thanks to your fix! Fix!
