### ISSUE TITLE
 Simple two page sandbox not working

### ISSUE THREAD

**Issue by fieg** [CompuIves/codesandbox-client#1340]
I have a simple 2-page sandbox with a link to page2 on the index. When the sandbox runs it shows page2 instead of the index page.

Am I doing something wrong? Please advise.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | parcel |
| Browser | Safari |
| Operating System | MacOs |

**Comment by fieg** [comment]
@CompuIves I see you referenced this issue in your commit. When will the fix be released?

**Comment by CompuIves** [comment]
In about an hour!

**Comment by fieg** [comment]
Thank you for the fix and release. It now works as expected 👍
