### ISSUE TITLE
ModuleNotFound broadcast-channel/leader-election

### ISSUE THREAD

**Issue by jimthedev** [CompuIves/codesandbox-client#1341]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

I have been trying to use the module broadcast-channel/leader-election.

The issue presents similar to #1058 in that you randomly get ModuleNotFound and refreshing fixes it sometimes. Interestingly it seems only to happen when bring in leader-election. This issue does not happen locally so I think it has to do with using it in codesandbox specifically. Link included below. Glad to be a patreon, keep up the good work!

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1543470635-82872a5d
| Browser | Version 70.0.3538.102 (Official Build) (64-bit)
| Operating System | OSX 10.13.6

**Comment by jimthedev** [comment]
For reference, here is the same thing working in Stackblitz: https://stackblitz.com/edit/react-wuuunj?file=index.js

**Comment by CompuIves** [comment]
Hmm, I can see what's happening here. We're forgetting to cache something. So for the first run it works (tested it here https://codesandbox.io/s/pw8m3nm480), but for the run with the cache it doesn't. I'll fix this now.

**Comment by jimthedev** [comment]
Thanks!

**Comment by CompuIves** [comment]
It's live!

**Comment by jimthedev** [comment]
Thanks!
