### ISSUE TITLE
[Question] Is babel 7 supported?

### ISSUE THREAD

**Issue by kt3k** [CompuIves/codesandbox-client#1345]
# ❔ Question

I'm trying to use new decorators implementation which has been added in babel 7.1.

I created parcel settings for transpiling new decorators but it shows the error like the below:
<img width="555" alt="2018-12-02 13 38 11" src="https://user-images.githubusercontent.com/613956/49335772-93511980-f637-11e8-8077-5592cfd4160e.png">

The path shown in error message seems strange. It doesn't seem handled in the way babel 7 handles it.

###  Link to sandbox: [link](https://codesandbox.io/s/github/kt3k/parcel-babel7-decorators-example)

source repo: https://github.com/kt3k/parcel-babel7-decorators-example

The same repo builds without error in [glitch](https://glitch.com/edit/#!/kt3k-parcel-babel7-decorators-example).

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1543715511-2cf33c46
| Browser | Chrome 70
| Operating System | macOS 10.13

**Comment by CompuIves** [comment]
I forgot to add the right code to detect Babel 7 in parcel. I fixed it and will deploy it today!
