### ISSUE TITLE
Add a shortcut for toggling zen mode

### ISSUE THREAD

**Issue by fawmi** [CompuIves/codesandbox-client#1348]
# 🌈 Feature

Add a shortcut to toggle zen mode
In vs code cmd+k+z is used to toggle zen mode.
I usually switch between normal and zen mode, and right now the only way to go zen mode is going to settings and activating it. I would love a button in interface or a shortcut to toggle zen mode.

**Comment by CompuIves** [comment]
Hmm, I think we already have this:

<img width="914" alt="screenshot 2018-12-03 at 10 41 02" src="https://user-images.githubusercontent.com/587016/49365840-1b8ef780-f6e8-11e8-934b-4b5247a745ef.png">

**Comment by fawmi** [comment]
Oh, sorry. I should have searched setting beside documentation.

**Comment by Slapbox** [comment]
Hotkey doesn't work on Windows and you're left with no way to get out except to open the console and use `localStorage.clear()` unless I'm overlooking something. `Cmd` is the Windows Key on Windows, and using `Ctrl` instead does nothing - trapped in "Zen."

**Comment by davisi3** [comment]
Yes, I'm trapped in Zen too :(

**Comment by Slapbox** [comment]
@CompuIves I think this issue should be re-opened. I'm guessing the dev team doesn't use Windows, but this should really be addressed.

**Comment by davisi3** [comment]
just hit esc twite ;)

**Comment by learyjk** [comment]
Also stuck in zen mode... command + k + z didn't work neither did esc twice.
<img width="652" alt="Screen Shot 2022-10-21 at 9 16 22 AM" src="https://user-images.githubusercontent.com/35752455/197242101-ab4ee498-1b1e-43ba-9cbe-7a5d70b4b9ec.png">
