### ISSUE TITLE
Comments not adjusting properly in embedded languages

### ISSUE THREAD

**Issue by christosnc** [CompuIves/codesandbox-client#1353]
Hello,

When you are in a language mode that has embedded modes (ex. html -> css, js) the "toggle comment" functionality works according to the configuration of the parent mode no matter if you are in a block with an embedded language mode.

**To reproduce and understand better:**
1) Go to [codesandbox.io/s/new](https://codesandbox.io/s/new)
2) Open index.html file
3) Paste somewhere
`<script>`
`var a = 5;`
`</script>`
4) Select the `var a = 5;` line
5) Press the "toggle comment" shortcut (Cmd + \ on mac)

Although we are in JS, the comments are `<!-- -->`. This also affects `<style>` tags in the same way.

| Browser: Chrome - Latest
| Operating System: macOS - Latest

**Comment by lbogdan** [comment]
Closing this, as I can't replicate, and I'm quite confident it was fixed with the switch to VSCode as the default editor.

However, @christosnc feel free to reopen if you still experience this behavior.
