### ISSUE TITLE
Puppeteer support

### ISSUE THREAD

**Issue by jeandat** [CompuIves/codesandbox-client#1354]
# 🌈 Feature

It would be cool being able to use puppeteer in codesandbox.io

It can be installed but chrome doesn't start when using the api (browser.launch()).

I think at least one system dependency is missing. See err message:

```
(node:372) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/sandbox/node_modules/puppeteer/.local-chromium/linux-588429/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
```

**Comment by berstend** [comment]
I get this error instead:

```ModuleNotFoundError: Could not find module in path: 'ws' relative to '/node_modules/puppeteer/lib/WebSocketTransport.js'```

**Comment by SaraVieira** [comment]
Hey!

Puppeteer relies on chrome binaries, so lots of assembly and reason code. This makes it hard to support it right now. Maybe in the future with containers but we're not even close to it honestly

It would be amazing and we will keep it in mind :)

**Comment by karlhorky** [comment]
For anyone else looking for this, it looks like there are some sandboxes that have tried to make this work, but they don't work (anymore? maybe they did work at one point?):

Puppeteer Demo:
https://codesandbox.io/s/48xpqk3n89

React + Puppeteer:
https://codesandbox.io/s/jnn9867qy
