### ISSUE TITLE
Browsers freeze on opening sandbox

### ISSUE THREAD

**Issue by Blanen** [CompuIves/codesandbox-client#1356]
# 🐛 bug report
Codesandbox completely freezes my browsers since today.

Tested on firefox and chrome

Had to block the embeds with Ublock
## Description of the problem
Complete freeze of web page in the tab. Console also less responsive (synchronous code blocking UI).
Get's stuck on the following regex somehow: (.*)<\w(.|\n)*?\/?>

## How has this issue affected you? What are you trying to accomplish?
Using codesandbox

###  Link to sandbox:
One sandbox where it breaks: 
https://codesandbox.io/s/y3504yr0l1?initialpath=%2F%23%2Fmodels&module=%2Fsrc%2Fcomponents%2FModels.vue
### Your Environment

| Software         | Name/Version|
| Сodesandbox  |  Latest
| Browser |  chrome: 70.0.3538.110 firefox: 63.0.3 
| Operating System | Windows 10 16299.248
| Ublock origin | 1.17.4

stack:
https://imgur.com/a/ldkAbyH

The regex goes on for around a minute.

Can supply the json log for chrome.

**Comment by lbogdan** [comment]
Hey there, thank you for reporting this!

Looks to be an issue introduced by https://github.com/CompuIves/codesandbox-client/commit/47419bccc8d2bb716606463aada35534f038fefd , I already pinged @CompuIves , he'll take a look at it and fix it as soon as possible!

**Comment by lbogdan** [comment]
As it was kind of high priority, I went ahead, reverted that commit and deployed. It seems to work fine now, please test and let us know!

**Comment by Blanen** [comment]
@lbogdan Seems to be working

**Comment by lbogdan** [comment]
Nice, closing.
