### ISSUE TITLE
Editor crashes when pasting long strings.

### ISSUE THREAD

**Issue by LimeWub** [CompuIves/codesandbox-client#1358]
# 🐛 bug report
First of all, thank you very much for your work on CodeSandbox, it is a great project and I've used it a bunch this year. Just encountered this issue this past few days and it has caused me to lose some code so I think it's worth bringing up.

## Description of the problem
When pasting very long strings to the editor, the whole website hangs and stops responding. Refreshing tries to open the same file again, which causes the editor to re-hang.
The only way to escape the crash loop is to try to delete the string ASAP before the client becomes unresponsive (1-2 seconds after the page loads.)

The string I am trying to paste comes from https://adventofcode.com/2018/day/5 's input. (log in needed to get the input.) It is basically a 1,5 page long string with no spaces.

### For the record: 

- I have had no problem pasting long arrays in before. (from previous days of the aoc)
- I have had no problem pasting the same long string on other website's text areas.
- The hanging tab does not consume more memory than usual (which is the case when a for loop has gone crazy eg).
- (Update) If I add line breaks to the long string every 50 chars and past inside backquotes (``) it works like a charm. No lag.
- (Update) If I do not add line breaks and paste in backquotes it still crashes.

## How has this issue affected you? What are you trying to accomplish?
Trying to get the exercise input where it needs to be to start solving for the day.
It affects me because my code is kept hostage every time I refresh unless I clutch-delete.

###  Link to sandbox: [link]() (optional)
https://codesandbox.io/s/7w1qvz79p0
Although I'll probably clutch-fix it before anyone manages to have a look.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Unsure(?) Current live version.
| Browser | Chrome Version 70.0.3538.102 (Official Build) (64-bit)
| Operating System | macOS Mojave

**Comment by lbogdan** [comment]
Closing this, as I can't replicate, and I'm quite confident it was fixed with the switch to VSCode as the default editor.

However, @LimeWub feel free to reopen if you still experience this behavior.

**Comment by paomancia** [comment]
Hey there. 

I'm still experiencing this issue with a minified HTML code. 

In my case I only changed the format of the file from **.html** to **.txt** and works fine for me.

Also, there seems to be a setting you can tweak to increase the line length in the settings of the editor and it should work too. I just searched for "length" and it showed up. It's called **Max Tokenization Line length** . Here's a screenshot: http://i.imgur.com/7cN6l81.png
