### ISSUE TITLE
Forked container sandbox doesnt update files

### ISSUE THREAD

**Issue by haxxxton** [CompuIves/codesandbox-client#1361]
# 🐛 bug report

## Description of the problem
I forked a container sandbox [here](https://codesandbox.io/s/github/lbogdan/aurelia-webpack-bare/tree/master/), and then went about changing/removing/adding a bunch of files to the sandbox. When i `ls` in the terminal, all of the files listed, are from the original forked sandbox, not the files i have made changes to.

## How has this issue affected you? What are you trying to accomplish?
I am trying to run a container sandbox, forked from another sandbox, after changing a number of files. I may be missing some big glaring button that says 'update server files' or something, but i cant for the life of me see one.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Browser
| Browser | Chrome 70.0.3538.102
| Operating System | OSX

**Comment by lbogdan** [comment]
Hey @haxxxton ,

The files you change and save in the editor are automatically updated to the container the sandbox runs in (only on save, not on type), so you should be able to see the changed files in the terminal.

Can you please try again and check if this is still happening for you?

**Comment by haxxxton** [comment]
@lbogdan it appears there is some lag time between the console files and those displayed in the editor. I saved the project, waited a while, then came back to the project and the file in the console then DID match that in the editor. I saved the project multiple times, and even closed and opened the tab several times to see if it was some caching bug. It appears time was the only factor that made any change

**Comment by lbogdan** [comment]
How much time are we taking about?

**Comment by haxxxton** [comment]
@lbogdan at least an hour :(

**Comment by lbogdan** [comment]
Can we maybe jump on a Slack and try to debug this in real-time?

**Comment by haxxxton** [comment]
@lbogdan absolutely, the sandbox in question is from more than 4 months ago, but ill try to remember the steps i took. email for slack is james at gaandder dot com

**Comment by lbogdan** [comment]
Oh, sorry, I meant Skype 🙂 (or whatever other IM you prefer). It's gotten pretty late here (already 3AM), so maybe leave it for tomorrow?

**Comment by haxxxton** [comment]
@lbogdan sure, im Australia based, so any time in the next 9-10 hours is good for me xD my discord tag is the same as my github username :)

**Comment by lbogdan** [comment]
Ok, I'm up, where do you want to chat?

**Comment by haxxxton** [comment]
Thanks for the help tonight, will let you know if i can find any way to replicate in the future
