### ISSUE TITLE
Right click menu displays underneath sidebar

### ISSUE THREAD

**Issue by gc** [CompuIves/codesandbox-client#1365]
# 🐛 bug report

## Description of the problem

When right clicking near the line numbers on the left side, the popup menu is hidden underneath the sidebar. Maybe display it on other side of mouse if it cant fit there, or just render it ontop of the sidebar?

![chrome_2018-12-10_22-03-09](https://user-images.githubusercontent.com/30398469/49728679-8384a580-fcc7-11e8-922a-c795bcff2f6e.png)

## How has this issue affected you? What are you trying to accomplish?

Just trying to right click in a sandbox.

###  Link to sandbox

Applies to any sandbox.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1544204875-e2323368
| Browser | Version 70.0.3538.110 (Official Build) (64-bit)
| Operating System | Windows 7 64-bit

**Comment by lbogdan** [comment]
Closing this, as I can't replicate, and I'm quite confident it was fixed with the switch to VSCode as the default editor.

However, @gc feel free to reopen if you still experience this behavior.
