### ISSUE TITLE
Scrolling does not work properly in .prettierrc file

### ISSUE THREAD

**Issue by noobling** [CompuIves/codesandbox-client#1370]
# 🐛 bug report

## Description of the problem
Scrolling is not reliable in the `.prettierrc` file

## How has this issue affected you? What are you trying to accomplish?
When you scroll to the bottom then try to scroll upwards it does not work anymore. You can work around this by using the side bar to scroll upwards.

###  Link to sandbox: [link]() (optional)
Just the default create-react-app project

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1544451712-7bdc536f |
| Browser | Version 70.0.3538.110 (Official Build) (64-bit) |
| Operating System | macOS Mojave v10.14.1

**Comment by lbogdan** [comment]
Closing this, as I'm quite confident it was fixed with the switch to VSCode as the default editor.

However, @noobling feel free to reopen if you still experience this behavior.
