### ISSUE TITLE
Multiple code panes

### ISSUE THREAD

**Issue by noobling** [CompuIves/codesandbox-client#1371]
# 🌈 Feature

Have multiple code panes.

Like the split editor button in vscode 

Like this
![](https://media.giphy.com/media/1fhGq0Ni5vLgbwsxsd/giphy.gif)

**Comment by lbogdan** [comment]
Closing this, as we already have this feature when using VSCode (but be warned, this is still experimental), which you can enable from Preferences -> Experiments -> Use VSCode in the browser:
![image](https://user-images.githubusercontent.com/2083930/49799625-1405c900-fd4e-11e8-8a61-ea53e79ccaec.png)
