### ISSUE TITLE
Could not fetch dependencies, please try again in a couple seconds: Failed to fetch

### ISSUE THREAD

**Issue by cristiano-belloni** [CompuIves/codesandbox-client#1377]
# 🐛 bug report

## Description of the problem
Getting `Type Error - Could not fetch dependencies, please try again in a couple seconds: Failed to fetch` repeatedly. This happened after I tried to install `date-fns`

## How has this issue affected you? What are you trying to accomplish?
Trying to install the `date-fns` NPM package

###  Link to sandbox: [link](https://codesandbox.io/s/kx6n86myv7) (optional)

Private sandbox, though

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1544624037-7324e6bc
| Browser | Version 63.0.3239.132 (Official Build) (64-bit)
| Operating System | Windows 7

**Comment by lbogdan** [comment]
@cristiano-belloni Can you reproduce this in a public sandbox?

**Comment by cristiano-belloni** [comment]
@lbogdan - it seems to do the same in https://codesandbox.io/s/4q35ol586x (I didn't get to the error part, but installing is taking a lot of time like in the other)

It might also be related to the fact that I'm using `react@next` for hooks support and installing `date-fns` just re-triggered a yarn install, but that's strange, because it worked perfectly in many other sandboxes in the past month.

**Comment by cristiano-belloni** [comment]
What I see in the browser console is a 422 response to `https://codesandbox.io/api/v1/dependencies/react-dom@16.7.0-alpha.2%20-%20next`. It seems you're using the dropdown label value to generate the dependency and that corrupts package.json. If I change package.json by hand, it works. so I guess it's a bug on your dependency wizard.

**Comment by lbogdan** [comment]
@cristiano-belloni Yeah, looks like it, thanks for investigating this. We'll fix this ASAP!

**Comment by cristiano-belloni** [comment]
@lbogdan Thanks!

**Comment by lbogdan** [comment]
Fixed in https://github.com/CompuIves/codesandbox-client/commit/a946e07a0cee9a529fece09c4cee20be3b2e6e3b and deployed. Please test and close this if it works as expected.
And thanks for reporting this! 🙂

**Comment by cristiano-belloni** [comment]
Confirmed working from here 👍 . Thanks for fixing!

**Comment by Saheb2002** [comment]
This package also doesn't fetch, error is the same 
 @mui/icons-material

error is 

Could not fetch dependencies, please try again in a couple seconds: Could not fetch dependencies, please try again in a couple seconds: Could not fetch dependencies, please try again in a couple seconds: Could not fetch https://cdn.jsdelivr.net/gh/mui/icons-material/package.json

To require

import DeleteIcon from '@mui/icons-material/Delete';

**Comment by JamesACS** [comment]
Hey @Saheb2002 - If you're encountering an issue please could you open a new bug report with a full set of details (including an example sandbox)? This issue was closed in 2018 :)

**Comment by DamengRandom** [comment]
Sometimes, might need to select one of dependencies from dropdown list and re-install it. (It works for me when I try to load codesandbox demo from browser)
