### ISSUE TITLE
VS Code Dark + (default dark) Color theme

### ISSUE THREAD

**Issue by parwat08** [CompuIves/codesandbox-client#1378]
# 🌈 Feature

It would be great to see VS code Dark + theme.

**Comment by parwat08** [comment]
You could get the file

https://stackoverflow.com/questions/35165362/how-to-edit-default-dark-theme-for-visual-studio-code/44470364#44470364

**Comment by lbogdan** [comment]
Closing this as we recently switched to VSCode as the default editor, and comes with quite a lot of popular themes. You can also configure your own theme in Preferences -> Appearance -> Custom VSCode Theme.
