### ISSUE TITLE
Autofocus when the add dependency modal pops up

### ISSUE THREAD

**Issue by SaraVieira** [CompuIves/codesandbox-client#1379]
# 🌈 Feature

👋

When you create on add a dependency the modal input should autofocus so that a user can just start typing.

I think a simple autofocus attr on the input could fix this

**Comment by steventsao** [comment]
Hi, did you mean the "Add Dependency" button on the left pane of the editor? I'm probably wrong, but Is it working as expected? See video: https://youtu.be/2owrI8ZOpBQ

**Comment by dance2die** [comment]
@steventsao Sorry but the video seems unavailable... 🤔 

![image](https://user-images.githubusercontent.com/8465237/50037793-f309d600-ffe2-11e8-8276-0aed2696a095.png)

**Comment by CompuIves** [comment]
I think this should fix it; https://github.com/CompuIves/codesandbox-client/commit/9e2451871638645235298ce9f27e863a8421a153

**Comment by dance2die** [comment]
Woohoo it works~ Thank you~

**Comment by chantastic** [comment]
you all ate beautiful 🤩

**Comment by SaraVieira** [comment]
So are you 🤩

**Comment by steventsao** [comment]
> Auto-focus doesn't seem to occur on my machine (Chrome Version 71.0.3578.98 (Official Build) (64-bit) on Windows 10) either.
> 
> @chantastic also had to put a focus after selecting the "Add Dependency" button
> https://youtu.be/CfV4EDqes38?t=95
> 
> @steventsao Sorry but the video seems unavailable... ??
> 
> ![image](https://user-images.githubusercontent.com/8465237/50037793-f309d600-ffe2-11e8-8276-0aed2696a095.png)

=o It might've defaulted to private. Good to know that it's fixed now tho!
