### ISSUE TITLE
ESLint complains about decorators, even though everything works.

### ISSUE THREAD

**Issue by jseminck** [CompuIves/codesandbox-client#138]
Example project: https://codesandbox.io/s/w0op701mn5

The linter complains about not being able to parse decorators. Yet the project runs without issues.

<img width="530" alt="screen shot 2017-08-21 at 16 49 36" src="https://user-images.githubusercontent.com/9586897/29522143-ec8fc0b8-8690-11e7-8420-7f51e3d6d9dd.png">

**Comment by CompuIves** [comment]
Right, I need to finish this pr: https://github.com/eslint/eslint/pull/9119. So we can define `babel-eslint` as parser and it should work.

**Comment by CompuIves** [comment]
Fixed with https://github.com/CompuIves/codesandbox-client/commit/994bbcb92d60af17eb1403ad3c321dd94bddeadc
