### ISSUE TITLE
react-map-gl > v4.0.0 doesn't work in sandbox

### ISSUE THREAD

**Issue by SamSamskies** [CompuIves/codesandbox-client#1381]
# 🐛 bug report

## Description of the problem
There seems to be some kind of dependency resolution error when using react-map-gl > v4.0.0 in a sandbox. Things work fine locally if I download the sandbox.

<img width="565" alt="screen shot 2018-12-14 at 12 00 55 pm" src="https://user-images.githubusercontent.com/3655410/50024654-f1ff8700-ff97-11e8-9d18-f969ebd202e4.png">

## How has this issue affected you? What are you trying to accomplish?
Can't update react-map-gl demos to latest version.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Browser | Chrome Version 71.0.3578.98 (Official Build) (64-bit) |

**Comment by CompuIves** [comment]
Interesting, for some reason it doesn't detect a require statement and thus doesn't download the necessary file. Taking a look at it now!

**Comment by CompuIves** [comment]
Found the fix! It will be live in a couple hours.
