### ISSUE TITLE
Message of error ocurred in sandbox is not displayed in Firefox

### ISSUE THREAD

**Issue by blikblum** [CompuIves/codesandbox-client#1382]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

When a sandbox fails due to an error in its code or its dependencies, e.g. TypeError, the error is not show in Firefox. For example the sandbox linked below, the "regeneratorRuntime is not defined" message is show in the preview and in problems tab in Chrome but not in Firefox.

In the console, the following error is shown:

    Error: "Promise did not implement oncancel"

    _cancelAction editor.main.js:142
     enter editor.main.js:138 
     _run editor.main.js:140 

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1544733234-776a0967 
| Browser |  Firefox 64
| Operating System | Windows 10

**Comment by blikblum** [comment]
I've found that the "Promise did not implement oncancel" also occurs on Chrome 71

Got this error in  https://codesandbox.io/s/k2w94no31v while reloading the page

**Comment by cef62** [comment]
I'm experiencing the same issue.
As workaround I'm importing `core-js` into my sandbox.

**Comment by lbogdan** [comment]
Looks like the error in https://codesandbox.io/s/k2w94no31v went away in Chrome, but it doesn't render anything in Firefox. Maybe related to #1335 .

@blikblum Can you please give a status update?

**Comment by blikblum** [comment]
The message error does not occurs in Chrome anymore, so this specific issue (message not showing) can not reproduced anymore with my sandbox.

There's still a issue with this sandbox not working at all in Firefox reported at #1630 

By my side, this issue can be closed. If i can reproduce i will reopen

**Comment by lbogdan** [comment]
Closing this in favor of #1630 .
