### ISSUE TITLE
CoffeeScript not working

### ISSUE THREAD

**Issue by AlexGrafe** [CompuIves/codesandbox-client#1384]
# 🐛 bug report

## Description of the problem

CoffeeScript does not appear to work (e.g. using the vanilla template), although ParcelJS and Babel support it out of the box.

Below is the snippet which should/could work – it does work exactly like that for TypeScript, but not for CoffeeScript. ParcelJS itself mentions on its website how it packages everything up through an HTML file that references a .coffee file as per below.

###### package.json
```
{
	"name": "coffeescript-exploration",
	"version": "1.0.0",
	"description": "Attempt to use CoffeeScript within CodeSandbox.",
	"main": "index.html",
	"scripts": {
		"start": "parcel index.html --open",
		"build": "parcel build index.html"
	},
	"dependencies": {},
	"devDependencies": {
		"parcel-bundler": "^1.10.3"
	},
	"keywords": []
}
```

###### index.html

```
<!DOCTYPE html>
<html>
	<head>
		<title>Parcel Sandbox</title>
		<meta charset="UTF-8" />
	</head>

	<body>
		<div id="app"></div>
		<script src="src/index.coffee"></script>
	</body>
</html>
```

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | current
| Browser | Chrome
| Operating System | CodeSandbox in browser (on macOS)

**Comment by shreeve** [comment]
Would love to see if there's any update here...

**Comment by SaraVieira** [comment]
Hey!

No updates so far

**Comment by shreeve** [comment]
Would love to get CoffeeScript support added to: https://github.com/CompuIves/codesandbox-client/tree/master/packages/app/src/sandbox/eval/transpilers

I know that the normal `webpack.config.js` file is not processed within Codesandbox, so I'm assuming that a new `coffeescript` transpiler is needed to be added to the above listed directory.

Does anyone have the ability to add this?

**Comment by SaraVieira** [comment]
This is really not high in our priority list since it's not a very requested feature and not a lot of people use coffeescript now a days.

It will probably be added in the future but we don't have any dates for this 

A PR would be amazing

**Comment by SaraVieira** [comment]
It would also go on the parcel template because that's the one that makes sense to add coffeescript too since parcel already supports it

**Comment by shreeve** [comment]
@SaraVieira, here's a first stab at trying to add support for CoffeeScript to vue-cli. If this is an ok starting point, I can make a PR to the official repo.

For now, I just have it as a PR to my fork of the repo at https://github.com/shreeve/codesandbox-client/pull/1/files

Also, I see that @zew13 is interested in something pretty similar at https://github.com/CompuIves/codesandbox-client/issues/1090

Could someone else take a quick look to see if this is at least the right direction to go?

Thanks!

**Comment by shreeve** [comment]
Check out #1467 - CoffeeScript support for vue-cli template

**Comment by shreeve** [comment]
CoffeeScript support for vue-cli template #1467

**Comment by SaraVieira** [comment]
Fixed by the amazing @shreeve

**Comment by shreeve** [comment]
Lol!

**Comment by SaraVieira** [comment]
I'm closing issues
