### ISSUE TITLE
Can’t extract a custom React hook

### ISSUE THREAD

**Issue by doasync** [CompuIves/codesandbox-client#1389]
**Do you want to request a *feature* or report a *bug*?**
bug maybe

**What is the current behavior?**
https://codesandbox.io/s/km21z2l2rv

**What is the expected behavior?**
I extracted my utils.js to a package. When I replace imports from "./utils" with a real npm package, I get an error: `Hooks can only be called inside the body of a function component.` (see codesandbox)
Since files are identical, I expect my external file to work the same.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.7.0-alpha.2
Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by doasync** [comment]
I solved this issue by **removing the caret** for React dependency in my `package.json`:
```json
    "react": "16.7.0-alpha.2",
    "react-dom": "16.7.0-alpha.2",
```
See this comment for more info: https://github.com/facebook/react/issues/14454#issuecomment-449585005

**Comment by CompuIves** [comment]
Ahh, so that was it! Glad that it's resolved now 😄.
