### ISSUE TITLE
Imports like 'import React from "react";' not working for JSX parsing

### ISSUE THREAD

**Issue by fabb** [CompuIves/codesandbox-client#1390]
# 🐛 bug report

## Description of the problem
When using an import style like `import React from "react"`, then JSX cannot be parsed. `import * as React from "react"` works though.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Current version as of 2018-12-18
| Browser | Chrome 70
| Operating System | macOS Mojave

**Comment by CompuIves** [comment]
Isn't this intended behaviour from TypeScript? (Correct me if I'm wrong)

**Comment by fabb** [comment]
I yet need to compare the TS configs, but in our company‘s webapp, which is based on next.js, this works fine. Bit maybe it‘s because next.js uses babel-preset-typescript. I need to check.

**Comment by fabb** [comment]
Ok, when I add `"esModuleInterop": true` to `tsconfig.json`, it works fine in Codesandbox 🎉
Related issue: https://github.com/Microsoft/TypeScript-React-Starter/issues/8

Interestingly, when checking out the repo locally, and trying to run it, I run into additional errors that don't happen in Codesandbox:
1. `(1,8): Module '"[...]/node_modules/@types/react/index"' has no default export.` which is fixed by adding `"allowSyntheticDefaultImports": true` to `tsconfig.json`, and
2. A tslint error `[...]/src/Hello.tsx (1,24): " should be '` which is fixed by doing the according style fixes, or adapting `tslint.json`

No idea why these errors don't happen when running locally. Maybe because I use `npm` instead of `yarn`? I don't know. And it seems `tslint` errors are not shown.

Anyways, since I resolved my original issues, I'm closing this ticket.
