### ISSUE TITLE
Embedded client does not work with third-party cookies disabled

### ISSUE THREAD

**Issue by timfish** [CompuIves/codesandbox-client#1392]
# 🐛 bug report

## Description of the problem
Codesandbox client embedded in another page does not work with third-party cookies disabled in Chrome. 

In Chrome 70 (and probably many before that), if third-party cookies are disabled, the codesandbox demos on [aurelia.io](aurelia.io) do not load and `localStorage` access denied/not available is shown in the console.

**Comment by CompuIves** [comment]
Thanks for the report! I pushed a fix and will deploy it this hour.

**Comment by timfish** [comment]
Many thanks for the fix!
❤️❤️❤️❤️❤️❤️❤️
