### ISSUE TITLE
Could not find module in path: 'immutable/4.0.0-rc.12'

### ISSUE THREAD

**Issue by cristiano-belloni** [CompuIves/codesandbox-client#1394]
# 🐛 bug report

## Description of the problem
When I link [this library](https://github.com/zambezi/caballo-vivo), which depends on `immutable@4.0.0-rc.12`, and I install the same `immutable@4.0.0-rc.12` dependence in my package.json, the app blows up with this message:

```
Could not find module in path: 'immutable/4.0.0-rc.12' relative to '/node_modules/@zambezi/caballo-vivo/src/location.js'
```

## How has this issue affected you? What are you trying to accomplish?

This doesn't happen if I run the same exact code in a shell. I wonder if I'm doing something wrong, something's wrong on the library or something's wrong in codesandbox.

###  Link to sandbox: 
[Minimal example](https://codesandbox.io/s/mmrzrv3oo9)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1545225755-acb62362
| Browser | 63.0.3239.132 (Official Build) (64-bit)
| Operating System | Windows 7

**Comment by CompuIves** [comment]
Found the problem! Deploying fix now.

**Comment by cristiano-belloni** [comment]
Thanks!!
