### ISSUE TITLE
Flex layout issue

### ISSUE THREAD

**Issue by georapbox** [CompuIves/codesandbox-client#1398]
# 🐛 bug report

## Description of the problem

It seems that there is an issue with flex layout that prevents the right pane from filling the rest of the available viewport.

Please see the attached screenshot below:

![img_0033](https://user-images.githubusercontent.com/6596039/50348532-b9d0e900-0541-11e9-92ed-61e62d97f9cc.PNG)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Current version as of 2018-12-21 | 
| Browser | Firefox 14.0, Brave 1.7.1 |
| Operating System | iOS 12.1 |

**Comment by lbogdan** [comment]
Hey @georapbox , are you still experiencing this? We recently had a UI update with the switch to VSCode as the default editor, maybe this was fixed in the process?

**Comment by georapbox** [comment]
Hi @lbogdan , it seems that the issue has been fixed after the UI update. Testing with Firefox 15.1 and Brave 1.8 on iOS 12.2 and everything seems to be working as expected, so closing the issue. 👍
