### ISSUE TITLE
Cannot omit "presets" option in ".babelrc"

### ISSUE THREAD

**Issue by Lodin** [CompuIves/codesandbox-client#1400]
# 🐛 bug report

## Description of the problem
If I omit `presets` option in the `.babelrc` file, sandbox fails with following error: 
```
Cannot read property 'map' of undefined
``` 
## How has this issue affected you? What are you trying to accomplish?
I'm trying to work with Web Components without compiling code to ES5. Due to `presets` error I'm unable to get it working. I also tried to set the latest Chrome version, but these settings still aren't respected (#1286)

###  Link to sandbox:
[link](https://codesandbox.io/s/1zkrxmk584)
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  Vanilla
| Browser |  Chrome 71
| Operating System | Windows 10

**Comment by SaraVieira** [comment]
Hey !

For webcomponents I would advise you to use the static template that doesn't have any build system 

You can also leave presets as an empty array while I look into that

**Comment by Lodin** [comment]
It works now! Thanks!
