### ISSUE TITLE
JavaScript run error when HTML been saved before

### ISSUE THREAD

**Issue by lzxxxxx** [CompuIves/codesandbox-client#1402]
# 🐛 bug report

I'm working with a vue project, when i save the JavaScript file before HTML, the Console will show something wrong , it looks like my JavaScript haven't run after i save my html.

Link to sandbox: [link](https://codesandbox.io/s/qk92rlzk0q) (optional)

you can make some Insignificant  changes in HTML and have a look at the Console.
After that make some other Insignificant  changes in JavaScript file and save, the error disappear.

**Comment by lbogdan** [comment]
Closing this, as I can't replicate, so it was probably fixed in the meanwhile.

@lzxxxxx Feel free to reopen if you still have issues.
