### ISSUE TITLE
Go to file (Cmd-P / Ctrl-P) doesn't focus on the text box

### ISSUE THREAD

**Issue by JoelCodes** [CompuIves/codesandbox-client#1404]
# 🐛 bug report

## Description of the problem

In VS Code (and other IDE's), when you use Cmd-P / Ctrl-P to go to a specific file, there is a text box that automatically gains focus.  In CodeSandbox, it does not.

## How has this issue affected you? What are you trying to accomplish?

When I use CodeSandbox, I expect it to behave like my IDE.  I either remember that CodeSandbox is different and have to make a click, or forget and end up accidentally writing into my code.

### Your Environment

| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome |
| Operating System | Mac OSX|

**Comment by CompuIves** [comment]
Hmm, interesting. Seems like the functionality broke, I remember it working before. I'll fix this today.

If you're looking for the same editor experience as local I recommend to enable "VSCode Experiment" (in the preferences). That's VSCode ported to the browser, and has the auto focus for CMD+P.
