### ISSUE TITLE
Prettify Current File Not Work

### ISSUE THREAD

**Issue by caiyanhu** [CompuIves/codesandbox-client#1406]
I've set "Prettify Current File" to "Alt+Command+L" in PREFERENCES, but this short key binding is not work in editor.

### My Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome 71.0.3578.98
| Operating System | macOS 10.14.2

**Comment by lbogdan** [comment]
Closing this for now, as we recently switched to VSCode as the default editor, and the (auto-)formatting / prettifying experience is much improved.

@caiyanhu Feel free to reopen this if you still have issues.
