### ISSUE TITLE
Disabling prettier 

### ISSUE THREAD

**Issue by babakness** [CompuIves/codesandbox-client#1407]
# 🌈 Feature

OPTION TO COMPLETELY DISABLE PRETTIER.

What is this feature?
Please make it easy to completely disable prettier. I don't see a way to get rid of it in preferences under editor

![image](https://user-images.githubusercontent.com/2024235/50405032-a7ce9080-0763-11e9-8bfd-0b5db60a61c7.png)

or under prettier settings

![image](https://user-images.githubusercontent.com/2024235/50405037-b87f0680-0763-11e9-84cd-234c45b4c6e4.png)

It can become super annoying. 

How the feature should work?
NO PRETTIER.

**Comment by babakness** [comment]
This doesn't work:

https://stackoverflow.com/questions/48082446/how-do-i-make-a-prettierrc-file-that-completely-disables-prettier

**Comment by lbogdan** [comment]
Hey @babakness , it's already there, in `Preferences > Editor > Prettify On Save`:

![image](https://user-images.githubusercontent.com/2083930/50405429-1be95280-07bd-11e9-9a3c-d2d30aa9ebec.png)

What version of the client do you have? You can see it in the bottom of the sidebar, current one is `PROD-1545599226-24458ae4`.

**Comment by babakness** [comment]
I'm on the same build, the problem seems to be having the experimental "Use VS Code in the browser" setting turned on under Experiments. Turning it off and the problem is resolved. Hopefully the ability to turn off prettify is maintained in the future VS Code editor as well.

![image](https://user-images.githubusercontent.com/2024235/50406899-d5c2cd80-0781-11e9-8da3-741acc781f7a.png)

**Comment by CompuIves** [comment]
You can also turn on "Prettify on Save" in VSCode settings (`CMD+,`). I'll close this one, we'll make it more clear for VSCode once we fully made the move (we have an issue open for that).

![image](https://user-images.githubusercontent.com/587016/50406939-15afa200-07ce-11e9-9ac8-07611acf28c7.png)

**Comment by ackvf** [comment]
For anyone stumbling upon this
# You just need these three super fast steps

1. type `user settings` in a command pallete <kbd>Ctrl+shift+P</kbd>
2. type `save` in the search box.
3. Disable `Editor: Format On Save`  
   

![image](https://user-images.githubusercontent.com/2313018/64620942-17190d00-d3e5-11e9-9449-64e97d42720b.png)

You can still format manually later, or you can format code selection. You can also save without formatting right away, without changing settings. `ctrl+shift+p` + `format`

![image](https://user-images.githubusercontent.com/2313018/64621116-6b23f180-d3e5-11e9-9000-2a90412e6396.png)

[disabling prettier #1048](https://github.com/codesandbox/codesandbox-client/issues/1048)

**Comment by JoshMcCullough** [comment]
Thank you. I'm so tired of prettier destroying my beautiful code!
