### ISSUE TITLE
where is the sandpack bundler's source code?

### ISSUE THREAD

**Issue by shaozj** [CompuIves/codesandbox-client#1408]
# ❔ Question

Thanks for your great work. I wonder where is the sandpack bundler's source code. I can only find APIs in sandpack repo. Could you open source sandpack bundler's source code rather than server the compiled code in a host?

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 0.1.0|
| Browser |  Chrome  71.0.3578.98|
| Operating System | macos Mojave 10.14.2|

**Comment by CompuIves** [comment]
It's already open source, all code is here: https://github.com/CompuIves/codesandbox-client/tree/master/packages/app/src/sandbox.

It's part of the app, sandpack only functions as an API that communicates with the bundler. When we bundle a new version of sandpack, we create a build of the app and move the sandbox related files to the sandpack dist folder.

I'll close this one now as I think it's been answered!
