### ISSUE TITLE
How to run with Docker?

### ISSUE THREAD

**Issue by greggmojica** [CompuIves/codesandbox-client#1411]
Trying to run this in a docker container, have used docker build and docker run the nothing is outputted. Any ideas?

**Comment by greggmojica** [comment]
The Docker file seems incomplete??

**Comment by greggmojica** [comment]
The Docker file seems incomplete??

**Comment by lbogdan** [comment]
Hey @greggmojica , what are you trying to do? If you want to contribute, please read https://github.com/CompuIves/codesandbox-client/blob/master/CONTRIBUTING.md .

**Comment by greggmojica** [comment]
I'm trying to run the codebase using Docker. The project runs fine locally, but using the provided Dockerfile it fails. Any idea why this is the case? It appears the Dockerfile is incomplete... @lbogdan

**Comment by lbogdan** [comment]
That Dockerfile is used for creating the deployment image that runs in production, so it has nothing to do with contributing / development.

**Comment by lbogdan** [comment]
Closing this, as there's no actionable here.

@greggmojica If you want to discuss things further, please join us on [Spectrum](https://spectrum.chat/codesandbox).
