### ISSUE TITLE
SWF files won't work

### ISSUE THREAD

**Issue by TheChosensW0rld** [CompuIves/codesandbox-client#1413]
# 🐛 bug report

I'm trying to upload a .SWF file and it's refusing to upload.

The issue is preventing me from putting GameBoy-Online onto my website, I was able to upload SWF files yesterday but now it won't work at all, it's even rejecting some low res images.

Using the static environment
| Сodesandbox  | 
| Browser: Chrome | 
| Operating System: ChromeOS |

**Comment by CompuIves** [comment]
Hey! Sorry to hear that, what error message are you getting?

**Comment by TheChosensW0rld** [comment]
**Error uploading XAudioJS.swf: Something went wrong while uploading the file.**

**Comment by lbogdan** [comment]
Closing this, as it looks like there was an isolated issue with uploading files at the time. @TheChosensW0rld Please feel free to reopen it, though, if you still have issues with uploading files.
