### ISSUE TITLE
Button to "Toggle File Watching" for tests not working

### ISSUE THREAD

**Issue by vyadh** [CompuIves/codesandbox-client#1414]
# 🐛 bug report

## Description of the problem

Tests in CodeSandbox kick in while writing code, which is great for TDD, but it does cause some lag/distraction while typing (maybe the run on pause functionality is a bit short?), so I thought I would try turning this auto-run feature off for concentrated work.

Note: Since tests are run while typing, I interpret the "Toggle File Watching" button not to kick in on save, but on live changes. Clearly, running it on save is a bit pointless if it's running on active changes anyway.

However, this button doesn't seem to do anything. Whether I open the dedicated tests panel or the Console / Problems / Tests panel, the tests run if I change something whether the refresh symbol is highlighted or not.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1546090293-e2e33184 |
| Browser | Chrome |
| Operating System | Windows |

**Comment by vyadh** [comment]
Just in case it helps, here is a link to my "Modern Intro to JavaScript" course:
https://codesandbox.io/s/n5qj8pklw4

This has nearly 100 tests across 20 files. The idea was to allow students to write tests to help them learn JavaScript, getting near real-time feedback on their progress. However, the typing became so laggy that I somewhat gave up on that idea and I'll probably split it out into multiple projects, or just get students to hide the test window until they want the test feedback, that makes it work great.

**Comment by sylvainpolletvillard** [comment]
Got the exact same issue for my JS training course: https://codesandbox.io/s/github/SDCOAdvocates/JS-Training ;  Tests continue to auto-reload even when "Toggle File Watching" is disabled.

The only workaround so far has been to hide the Tests panel while typing.

**Comment by CompuIves** [comment]
Got a fix for this! Should be live today. Sorry for the inconvenience!

**Comment by sylvainpolletvillard** [comment]
Amazing, my training group will appreciate this tomorrow. Thank you for your reactivity !
