### ISSUE TITLE
The piece of code was come from importers is visible for the end user.

### ISSUE THREAD

**Issue by Piterden** [CompuIves/codesandbox-client#1415]
# 🐛 The piece of code was come from importers is visible for the end user.

When I enter to the sandbox by a [`https://codesandbox.io/embed/github/Piterden/vue-crossword/tree/master`](https://codesandbox.io/embed/github/Piterden/vue-crossword/tree/master) link, I see the piece of code was come from API of importers. I use stable Chrome but I had tried Firefox too.
![image](https://user-images.githubusercontent.com/5930429/50556671-35265d80-0ced-11e9-9454-b2e548142f45.png)
![image](https://user-images.githubusercontent.com/5930429/50556716-cdbcdd80-0ced-11e9-95a0-804afef52ce2.png)

| Ubuntu         | 18.04 LTS |
![image](https://user-images.githubusercontent.com/5930429/50556760-56d41480-0cee-11e9-8771-db0f7b223442.png)
![image](https://user-images.githubusercontent.com/5930429/50556753-4754cb80-0cee-11e9-8fb0-4dd0aa90a807.png)

**Comment by Piterden** [comment]
Don't know what it was. Now good in Chrome.

Happy New Year, Ives!

**Comment by CompuIves** [comment]
Hah, weird... Happy New Year!
