### ISSUE TITLE
connection dashboard codesandbox impossible????  https://codesandbox.io/dashboard

### ISSUE THREAD

**Issue by 1NCUBE** [CompuIves/codesandbox-client#1416]
# 🐛 bug report

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | 
| Operating System |

**Comment by SaraVieira** [comment]
Hey!

Can you please explain your issue better ? I can access it

**Comment by 1NCUBE** [comment]
bonjour, 
merci beaucoup pour votre réactivité! 
je ne sais pas pourquoi mais l'interface utilisateur fonctionne à nouveau!!!
merci.
