### ISSUE TITLE
Unrecoverable error

### ISSUE THREAD

**Issue by RichardJJacobs** [CompuIves/codesandbox-client#1419]
# 🐛 bug report

Trying to load my angular program into a container (sandbox.config.json) but get -
An unrecoverable sandbox error occurred. :-( Try refreshing the page

https://codesandbox.io/s/ww9jzym318

**Comment by lbogdan** [comment]
Hey @RichardJJacobs ,

I just tested the sandbox you provided, and it seems to be working now. I'm gonna close this, feel free to reopen if you still have issues.
