### ISSUE TITLE
Monaco: Typings not found when file edited

### ISSUE THREAD

**Issue by nicknisi** [CompuIves/codesandbox-client#1420]
# 🐛 bug report

## Description of the problem

When using the default Monaco editor (not the experimental VS Code) with a TypeScript file, the editor does not report any errors with imports. However, as soon as the file is edited, none of the imports can be found (the red squigglies show up). This only seems to be affecting Monaco, currently. I was looking at #1217 and I don't think it's related to that, but the problem can be seen in the example sandbox provided [there](https://codesandbox.io/s/50yz11838k) as well.

## How has this issue affected you? What are you trying to accomplish?

This makes it seem like there are errors with TypeScript files in the default editor when there really aren't.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1546261819-450afd67 |
| Browser | Chrome (latest) |
| Operating System | macOS Mojave |

I'm happy to help track this error down, but any insight you might have would be appreciated! Thanks!

**Comment by nicknisi** [comment]
Here's a screenshot of the issue I'm seeing. ![2019-01-02 21 35 20](https://user-images.githubusercontent.com/293805/50622880-60b86c00-0ed6-11e9-808d-47e7d3e05d88.gif)

**Comment by q463746583** [comment]
Its good to me

**Comment by agubler** [comment]
Any update on this issue? It wouldn't be so bad if VSCode was the default editor (which work nicely) but as most new users land on the default Monaco editor it can cause quite a bad experience 🙁
