### ISSUE TITLE
Can't upload images to ZEIT

### ISSUE THREAD

**Issue by q463746583** [CompuIves/codesandbox-client#1421]
I want to deploy the file from sandbox editor: https://codesandbox.io/s/p564212ryx
to ZEIT: https://csb-p564212ryx-wamcpavoor.now.sh/home
But I found the images cannot upload to the server, I put imgs in public/img.\

**Comment by SaraVieira** [comment]
Hey !

Can you please try to move your images to src and try again?

**Comment by lbogdan** [comment]
Closing this, as it should've been fixed in https://github.com/CompuIves/codesandbox-client/pull/1396 . Please reopen if you have further issues.

I forked your sandbox, deployed it, and the images are there, e.g. https://csb-l9o9nyz7vq-dygamfyzbg.now.sh/images/loading.gif .
