### ISSUE TITLE
Cannot run a basic Vue.js project with TypeScript when exporting with CLI

### ISSUE THREAD

**Issue by builder7777** [CompuIves/codesandbox-client#1422]
# 🐛 bug report

## Deploying to codesandbox with CLI does not work for VueJS project with TypeScript
Steps to reproduce:

1. Create a new Vue.js project:
`vue create test`
2. Select the following:
```
Please pick a preset: Manually select features
? Check the features needed for your project: Babel, TS, Linter, Unit
? Use class-style component syntax? Yes
? Use Babel alongside TypeScript for auto-detected polyfills? Yes
? Pick a linter / formatter config: TSLint
? Pick additional lint features: Lint on save
? Pick a unit testing solution: Jest
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In package.json
? Save this as a preset for future projects? No
```
3. Deploy to codesandbox:
`codesandbox ./test`

### Expected result
Code deploys and runs default application

### Actual result

Error: "Could not find entry file: /index.js. You can specify one in package.json by defining a `main` property."

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 1.3.8 
| Browser | Chrome Version 70.0.3538.110 (Official Build) (64-bit
| Operating System | Mac OS X 10.13.6

**Comment by lbogdan** [comment]
Hey @builder7777 , we currently don't support `@vue/cli` v3 apps. You can still run that in a [server sandbox](https://hackernoon.com/codesandbox-containers-5864a8f26715), if you create a `sandbox.config.json` in your project root folder having
```json
{
  "template": "nuxt"
}
```
(`nuxt` is just to say that you want your sandbox to be a server one, and also have `.vue` file support in the editor).

**Comment by builder7777** [comment]
@lbogdan I just tried that, it runs now, however the test suites never finishes (basically stuck in running state). https://codesandbox.io/s/q7mrzmvkmw

**Comment by lbogdan** [comment]
Which tests, the unit or the end-to-end? (running them directly in the container, they both return errors)

**Comment by builder7777** [comment]
the unit test. it's supposed to return error, as i'm trying to replicate a bug in vuetify

**Comment by lbogdan** [comment]
Closing this, as everything is working as expected. Please reopen if you have further issues.
