### ISSUE TITLE
Dependencies are compiled down to ES5 even is sandbox is configured to output ES6

### ISSUE THREAD

**Issue by blikblum** [CompuIves/codesandbox-client#1427]
# 🐛 bug report

## Description of the problem

It's a follow up to https://github.com/CompuIves/codesandbox-client/issues/1286

The dependencies of a sandbox are being compiled to ES5 even if the sandbox is configured to output ES6. It causes problems with dependencies that expect to not be compiled to ES5 like lit-element.

It affects both babel and typescript setup and seems to be a regression because, previously, was working with typescript like in this [sandbox](https://codesandbox.io/s/l28p1lrj0m). 

## How has this issue affected you? What are you trying to accomplish?

The sandbox does not work because an incompatibility of native HTMLElement with compiled ES5 classes. When using babel 7 the issue is not show because it wraps the HTMLElement class to make compatible with ES5 compiled code.

typescript does not wraps HTMLElement, so the issue is evident

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  PROD-1546261819-450afd67
| Browser |  Chrome latest
| Operating System | Windows 10

**Comment by CompuIves** [comment]
Hey! Good point, I just committed a fix. Will deploy it in a minute!

**Comment by blikblum** [comment]
Thanks. Fixed
