### ISSUE TITLE
Adding initialpath to sharing URL doesn't have any effect

### ISSUE THREAD

**Issue by nikolasburk** [CompuIves/codesandbox-client#1434]
I want to share an example of a REST API in a server sandbox, you can find it here: https://codesandbox.io/s/github/prisma-csb/rest-example-js/tree/master

My goal is that the `/feed` route is loaded initially, instead of the the default route `/`.

In the share options, I set `Project Initial Path` to `/feed` and copied the resulting sharing URL: `https://codesandbox.io/s/github/prisma-csb/rest-example-js/tree/master/?initialpath=%2Ffeed`.

However, when going to that URL, the embedded browser inside the CSB still loads `/` by default:

![image](https://user-images.githubusercontent.com/4058327/50781443-ae055680-12a5-11e9-96f1-71c9a393cd02.png)

**Comment by CompuIves** [comment]
Hmm, it seems like this is overruled by SSE. It does work for other sandboxes. I'll  take a look.

**Comment by nikolasburk** [comment]
Is this resolved @CompuIves? Going to [https://codesandbox.io/s/github/prisma-csb/rest-example-js/tree/master/?initialpath=%2Ffeed](https://codesandbox.io/s/github/prisma-csb/rest-example-js/tree/master/?initialpath=%2Ffeed) still loads the `/` route for me.

**Comment by CompuIves** [comment]
It still needs to be built and deployed, should be live in about 10 min!

**Comment by CompuIves** [comment]
Deploying now! 1 min  left.
