### ISSUE TITLE
GitHub repo not syncing with CodeSandbox

### ISSUE THREAD

**Issue by cmatschiner** [CompuIves/codesandbox-client#1435]
I'm just getting started with CodeSandbox.  I just created a new sandbox. After pushing a local test file to GitHub, I noticed that the new file does not show up in CodeSandbox, despite latter giving me a "There are no changes" message in the gitHub section.

### Your Environment
| Software         | Name/Version|
| Сodesandbox  | 
| Chrome | 
| MacOS |

**Comment by lbogdan** [comment]
Hey @cmatschiner , the [current workflow](https://codesandbox.io/docs/git) de-syncs a forked sandbox from the github repo it was imported from, so only https://codesandbox.io/s/github/cmatschiner/eloquent-javascript-bernhard/tree/master/ is updated when your push new commits to the repo.

**Comment by cmatschiner** [comment]
Okay, that's why. Thanks for the prompt reply.
