### ISSUE TITLE
Explore Page: Switching between sandboxes doesn't update the code

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#1439]
When having a sandbox open on the explore page and switching between sandboxes the code of the embed doesn't change.

This is probably a componentDidUpdate that we need to change in the embed.

**Comment by lbogdan** [comment]
What do you mean by "the code of the embed"? The URL that's copied to the clipboard when you click "Copy Link"? If so, it's changing for me, so maybe you fixed it in the meanwhile?

Buuut, I get another weird behavior - for me, the **preview** never changes. 😞

**Comment by samrith-s** [comment]
Any way I can run the Explore page? I just get this some errors in the console.

![image](https://user-images.githubusercontent.com/9032162/55367499-09dd2580-550b-11e9-9e9e-94377e6891ae.png)

**Comment by CompuIves** [comment]
Hey! You can start it by going to `packages/homepage` and running `yarn start:dev`. I think the origin of this issue is in the preview component (`packages/common/components/Preview`), so if you work on that component you also need to run `yarn start` in `packages/common`.

**Comment by samrith-s** [comment]
Hey, got it. I’ll do that and check out this issue. Faced the same thing yesterday. Thanks!

**Comment by CompuIves** [comment]
Hey @samrith-s, did you find anything here? I'm thinking on taking a stab today.

**Comment by samrith-s** [comment]
Hey @CompuIves, I’m gonna have a stab at it later tonight! You can try as well, would love to know how you approach it!

**Comment by CompuIves** [comment]
This (https://github.com/CompuIves/codesandbox-client/pull/1715) fixed this as well, so we can close this one!
