### ISSUE TITLE
TypeError - Could not fetch Dependencies: Failed to fetch

### ISSUE THREAD

**Issue by Tiriel** [CompuIves/codesandbox-client#144]
Hi!

Since this morning, I have the following error on all sandboxes I use, on every browser:
```
TypeError 
Could not fetch Dependencies: Failed to fetch
```

The console displays this:
```
Fetch API cannot load https://webpack-dll-prod.herokuapp.com/v6/react%4015.5.3+react-dom%4015.5.3/manifest.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://93q17orrow.codesandbox.io' is therefore not allowed access. The response had HTTP status code 503. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Needless to say I didn't touch anything remotely linked to headers that I know of.
Anything I'm doing wrong?

**Comment by Tiriel** [comment]
Closing the issue as it seems to be back to normal.
But if anyone has an explanation, I'd be glad to have it!

**Comment by CompuIves** [comment]
Yap, this morning was quite hectic.

Tonight the MongoDB responsible for the cache reached its max capacity and started throwing. Also simultaneously our backup server went down. So both servers stopped responding.

I added more packagers and cleared the cache. I'm working on a Google cloud function version of the packager and from then on we won't ever have this particular issue again.

**Comment by Tiriel** [comment]
Oh boy. Well, I'm glad you managed this so quickly!

Thanks!
