### ISSUE TITLE
Not able to submit feedback

### ISSUE THREAD

**Issue by fraindz** [CompuIves/codesandbox-client#1450]
# 🐛 bug report
Not able to submit feedback
## Description of the problem
I tried to provide feedback via Profile Icon -> Submit feedback menu. On pressing send button to submit feedback, it just got stuck. Analyzing network it shows 2 requests for feedback, one of which is rejected with error code 422 Unprocessable entity
## How has this issue affected you? What are you trying to accomplish?
Not able to submit feedback
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome  71.0.3578.98|
| Operating System |Windows 10|

**Comment by SaraVieira** [comment]
My bad!

A fix is incoming and should be deployed either today or tomorrow! Thank you for letting us now
