### ISSUE TITLE
Social Facebook Community Homepage!

### ISSUE THREAD

**Issue by desenvolvedorIcotrade** [CompuIves/codesandbox-client#1453]
# 🌈 Feature

**Comment by lbogdan** [comment]
Hey @desenvolvedorIcotrade ,

I'm gonna close this, as we're not big fans of Facebook (the site, not the company and its open-source contributions 🙂 ). But if you want to chat, you can always join us - and the community - on [Spectrum](https://spectrum.chat/codesandbox).
