### ISSUE TITLE
File Explorer glitch - Duplicate folders

### ISSUE THREAD

**Issue by manniL** [CompuIves/codesandbox-client#1455]
# 🐛 bug report

## Description of the problem

![codesandbox-glitch](https://user-images.githubusercontent.com/640208/51005243-f9ce2f00-1535-11e9-815d-459195cb5a25.gif)

Related issue #1136 (I **don't** have the VSCode experiment enabled)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | current | 
| Browser | Firefox 64 (x64) |
| Operating System | Ubuntu LTS (18.04) |

**Comment by CoderSudaWuda** [comment]
Operating system is ChromeOS and browser is Chrome, and I experience these problems as well.

**Comment by raae** [comment]
I experienced this today in Chrome on a Mac.

**Comment by lbogdan** [comment]
Note for self: this is a bug in the way the SSE (server-side evaluation) manager handles file updates from VSCode, wasn't that big of an issue back when Monaco was the default editor, but now that we went full-VSCode, this needs fixing ASAP!

**Comment by CompuIves** [comment]
I'm going to fix this this week,  expect it to not happen anymore on Monday!

**Comment by lbogdan** [comment]
Sorry, didn't want to close this just yet, github did it without asking. 🙂 

This should be fixed now, please test and let me know if you still experience unwanted behavior, together with the sandbox id.

Cc @Saeris

**Comment by Saeris** [comment]
@lbogdan I don't appear to be experiencing duplicate files now, though I've been running into a lot of errors on saving new files recently. I'll make an issue for that later once I've got a solid grasp of how to reproduce the error.

**Comment by lbogdan** [comment]
@Saeris What kind of errors? Something along the lines of #1641 ?

It would be great if you could provide with steps to replicate this consistently, as I couldn't successfully replicate it so far. You can also buzz me on Discord whenever you're experiencing issues, and I can take a look.

**Comment by lbogdan** [comment]
Closing this, as I'm pretty confident I fixed it. Please reopen if you're still experiencing issues.
