### ISSUE TITLE
VSCode Explorer is not working

### ISSUE THREAD

**Issue by martinxxd** [CompuIves/codesandbox-client#1464]
# 🐛 bug report

## Description of the problem
VSCode's file explorer is not working. 

## Steps to reproduce
1. Open VSCode within CodeSandbox
2. Press `cmd-shift-p` to open the command box
3. Type in `View: Show Explorer`

## Error that occurs
```
Error: [createInstance] t depends on UNKNOWN service viewsService.
```

## How has this issue affected you? What are you trying to accomplish?
Using VSCode's file explorer instead of the one CodeSandbox provides.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1547050396-ff3eec3b
| Browser | Google Chrome Version 72.0.3626.53 (Official Build) beta (64-bit)
| Operating System | macOS

**Comment by SaraVieira** [comment]
Hey!

We didn't implement their explorer. Only the editor interface really so it's not possible to do that

The max we can do is either remove the option or make that open the codesandbox explorer

**Comment by martinxxd** [comment]
Thanks @SaraVieira, will close this issue then.
