### ISSUE TITLE
Ability to specify version of Node in server templates

### ISSUE THREAD

**Issue by nmoinvaz** [CompuIves/codesandbox-client#1469]
This issue is a feature for the ability to specify the version of Node used on the server template. Currently, it only uses version 8.14.0 which is missing some important features.

I'm not quite sure. I believe packages.json supports the use of "engines". But some other method would be acceptable too.

**Comment by nmoinvaz** [comment]
I think this might be supported through dependencies in package.json:
```
  "dependencies": {
    "jws": "3.1.5",
    "node": "11.6.0",
    "npm": "6.5.0"
  },
```

The sandbox probably wasn't reloaded properly after adding the dependency. Closing.

**Comment by riongull** [comment]
If anyone is here trying to figure out how to change the version of Node used in the server container feature of codesandbox.io, unfortunately you [can't according to this response](https://spectrum.chat/codesandbox/help/how-do-i-upgrade-the-node-version-from-the-cli~42a816f2-2b51-47ac-a614-cbcbd340d2e2?m=MTU3ODQwMDYwNzEzOA==).

**Comment by garethx** [comment]
The node as a dependency workaround does work though: https://codesandbox.io/docs/faqs#can-i-change-the-node-version-used-in-a-container-sandbox

**Comment by riongull** [comment]
Thanks for the quick reply, and link to the documentation, @garethx.  That worked for me.

For the lazy, just do update your `package.json` to include:
```
"scripts": {
  "start": "./node_modules/node/node_modules/.bin/node ./src/index.js"
},
"dependencies": {
  "node": "14.3.0"
},
```
Click the link @garethx shared above to see usage with `nodemon`.

Now we just need Google to return the docs page above this issue when searching for how to "change node version in codesandbox" :)

**Comment by jagreehal** [comment]
The link to the documentation has changed it should be https://codesandbox.io/docs/start#can-i-change-the-node-version-used-in-a-container-sandbox

The solution is set the node property in `sandbox.config.json`

```js
{
  "node": 14
}
```

**Comment by marcandrews** [comment]
This still isn't working for me in this Sandbox https://codesandbox.io/s/twitch-js-typescript-example-tnnys?file=/sandbox.config.json

`sandbox.config.json`:
```json
{
  "infiniteLoopProtection": true,
  "hardReloadOnChange": false,
  "template": "node",
  "view": "terminal",
  "container": {
    "node": "12"
  },
  "node": "12"
}
```

A dependency has `{ "engines": { "node": ">12" } }` and I'm getting the following error when I run the sandbox:
```
error twitch-js@2.0.0-beta.41: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.23.0"
```

I can open a new terminal and switch to Node 12 with `nvm` and run the code just fine though.

Any ideas?

**Comment by lbogdan** [comment]
Hey @marcandrews ,

For me it works with both node 12 and 14 in a [fork of your original sandbox](https://codesandbox.io/s/pensive-thompson-tkmi8?file=/sandbox.config.json):

![image](https://user-images.githubusercontent.com/2083930/103773131-453b4b00-5033-11eb-8ca6-4d663d20c09e.png)

Might be that you didn't restart the container after you changed the version in `sandbox.config.json`?

**Comment by marcandrews** [comment]
@lbogdan, I was having a lot of issues in general with Codesandbox that day, but they all seemed to be resolved the next day.

Thanks for following up :heart:

**Comment by slorber** [comment]
Hey!

Was just wondering if anyone can explain the difference between node and container.node? Reading the doc it's not really clear to me which one I want to set.

**Comment by lbogdan** [comment]
Hey @slorber ,

It's `container.node`. I agree that from the [docs](https://codesandbox.io/docs/configuration#sandbox-configuration) it's not obvious that `port`, `startScript` and `node` are under `container`, we should probably make that clearer.

**Comment by slorber** [comment]
@lbogdan actually the most confusing is that "node" is documented as "node" and also inside "container" (as "node"):

![image](https://user-images.githubusercontent.com/749374/113901123-d48d0180-97ce-11eb-9325-1be60cade256.png)


Maybe just removing the top-level node would make this less confusing?

**Comment by DisListMe** [comment]
> The node as a dependency workaround does work though: https://codesandbox.io/docs/faqs#can-i-change-the-node-version-used-in-a-container-sandbox
> 
> I've updated my response in the linked thread.

Links dead m8

**Comment by sairion** [comment]
For future ref, the docs link is moved to: https://codesandbox.io/docs/learn/sandboxes/configuration#sandbox-configuration

**Comment by ShaMan123** [comment]
> For future ref, the docs link is moved to: https://codesandbox.io/docs/learn/sandboxes/configuration#sandbox-configuration

These seem to be the correct links: 
https://codesandbox.io/docs/learn/environment/devcontainers#examples
https://codesandbox.io/docs/learn/environment/vm#configuring-nodejs-version

**Comment by ShaMan123** [comment]
I can confirm that adding `.codesandbox/Dockerfile` is all that is needed to make it work:
```
FROM node:18
```

**Comment by Tofandel** [comment]
The issue with

FROM node:xx

Is that it seems some libraries are not available compared to the default image of codesandbox. So for example you can't run expo

```node_modules/@react-native/debugger-shell/bin/react-native-devtools: error while loading shared libraries: libnspr4.so: cannot open shared object file: No such file or directory```

While this worked fine in the default image
