### ISSUE TITLE
Renaming at top of sandbox doesn't seem to work anymore

### ISSUE THREAD

**Issue by alanbuchanan** [CompuIves/codesandbox-client#1470]
# 🐛 bug report

## Description of the problem
Rename a sandbox while in it from the top bar. It seems to save it but on refresh, regresses back to its previous name.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1547565458-388b7905 |
| Browser | Chrome Version 71.0.3578.98 (Official Build) (64-bit) |
| Operating System | MacOS High Sierra |

**Comment by SaraVieira** [comment]
This seems to have been fixed in the meantime 🎉

Please reopen if it happens again :D
