### ISSUE TITLE
Option to disable minimap?

### ISSUE THREAD

**Issue by elektronik2k5** [CompuIves/codesandbox-client#1472]
First and foremost: thank you for creating such an awesome service and experience. Thanks for sharing it for free, for open sourcing it and writing about it! :bowing_man: :bowing_man: :bowing_man: 

# 🌈 Feature

## What is this feature?
I know the minimap is popular with some (most?) people. Personally, I can't stand it. For me it only takes precious real-estate and gives absolutely no value.

Every editor which has a minimap feature also has a way to disable it for people like me :). I'm proposing to introduce such a toggle for codesandbox.

It should be a new, persistent option/preference to disable the minimap.
 
## How the feature should work? 
Either a button/checkbox/toggle next to "Toggle preview", or in the three dot menu next to it - or in the user settings.

## You have examples or an idea how it can be implemented?
KILL IT WITH FIRE. Or a button, whichever is easier :).

**Comment by lbogdan** [comment]
Hey @elektronik2k5 , you can disable it from VSCode settings, though: Ctrl-Shift-P -> "Preferences: Open Settings" -> search for "minimap" -> uncheck checkbox -> done! Does that address your minimap phobia? 🙂

**Comment by elektronik2k5** [comment]
Yes, it does! Thank you very much :)
