### ISSUE TITLE
GitHub export: PNGs aren't encoded/transferred properly

### ISSUE THREAD

**Issue by manniL** [CompuIves/codesandbox-client#1478]
# 🐛 bug report

## Description of the problem

When you try to export a codesandbox to GitHub, PNGs (and maybe also other file types) aren't properly encoded. An example can be found [here](https://github.com/manniL/nuxt-pixijs-example/blob/8c1bfb2d17ffa3e55dc2b60382f17b7e89e6413f/static/bunny.png), coming directly from a CSB export (via UI).

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Latest 
| Browser | FF 64.0.2
| Operating System | Win 10

**Comment by durkinio** [comment]
+1, I've been having issues with builds failing on netlify, and it always seems to relate to a "missing PNG" error, so this could be the reason ^

**Comment by CompuIves** [comment]
I created a fix for this!

**Comment by manniL** [comment]
Fix @ https://github.com/CompuIves/codesandbox-client/pull/1483

Will check and report back!

**Comment by manniL** [comment]
@CompuIves Does not work for me.

`Unhandled promise rejection TypeError: "can't convert imageUrl to string"`

Repo I try to export: https://codesandbox.io/s/q8wrrv6wp9

**Comment by CompuIves** [comment]
Hmmm, that's weird. Do you still have this issue? For me it's working: https://github.com/CompuIves/test-export2

**Comment by manniL** [comment]
@CompuIves You are right! Tried it a few times and after receiving a `409` twice it worked :relaxed:
