### ISSUE TITLE
Cannot find "common/config/env'" module when starting this project

### ISSUE THREAD

**Issue by TongDaDa** [CompuIves/codesandbox-client#1484]
I'm trying to start this project because I need to use it to make another project. but thrown this errros.

my steps:

`npm i` in the root directory.

`lerna boostrap` --- bootstrap all dependencies using Lerna.

`npm run start:fast` --- to start this project.

<img width="746" alt="2019-01-22 8 10 23" src="https://user-images.githubusercontent.com/23241188/51536096-67a71e80-1e85-11e9-92a7-3960562c64c0.png">

```
app: > app@0.1.1 start /Users/liutong/Desktop/projects/source_code/codesandbox-client/packages/app
app: > cross-env LOCAL_SERVER=1 LOCAL_DEV=1 node scripts/start.js
app: internal/modules/cjs/loader.js:582\n    throw err;\n    ^
app: Error: Cannot find module 'common/config/env'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:506:25)\n    at Module.require (internal/modules/cjs/loader.js:636:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/Users/liutong/Desktop/projects/source_code/codesandbox-client/packages/app/config/webpack.common.js:10:13)\n    at Module._compile (internal/modules/cjs/loader.js:688:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)\n    at Module.load (internal/modules/cjs/loader.js:598:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:529:3)\n    at Module.require (internal/modules/cjs/loader.js:636:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/Users/liutong/Desktop/projects/source_code/codesandbox-client/packages/app/config/webpack.dev.js:3:22)\n    at Module._compile (internal/modules/cjs/loader.js:688:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)\n    at Module.load (internal/modules/cjs/loader.js:598:32)
app: npm ERR! code ELIFECYCLE
app: npm ERR! errno 1
app: npm ERR! app@0.1.1 start: `cross-env LOCAL_SERVER=1 LOCAL_DEV=1 node scripts/start.js`
app: npm ERR! Exit status 1
app: npm ERR!
app: npm ERR! Failed at the app@0.1.1 start script.
app: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
app: npm ERR! A complete log of this run can be found in:
app: npm ERR!     /Users/liutong/.npm/_logs/2019-01-22T11_56_45_334Z-debug.log
```

**Comment by lbogdan** [comment]
Hey @TongDaDa , can you please give us the link to your sandbox?

**Comment by TongDaDa** [comment]
I have no link, that is My forked project, I want to change the codeSandbox project to my self-editor, It will support Python and other languages. @lbogdan

**Comment by TongDaDa** [comment]
I just don't know, the `common` module where require from? I cannot find in this node_modules of app directory...

**Comment by TongDaDa** [comment]
I don't understand why It is unable to start this project after I forked it and install some dependencies by the above steps.

Could it be said that you don't use it to develop your own function in this project?

**Comment by lbogdan** [comment]
Hey @TongDaDa ,

If you'll take a look the the [contributing document](https://github.com/CompuIves/codesandbox-client/blob/master/CONTRIBUTING.md), you'll see that we're only using `yarn`, while you used `npm`.

I'll close this for now, if you need further assistance please find us on [Spectrum](https://spectrum.chat/codesandbox).
