### ISSUE TITLE
Make referenced SVGs editable 

### ISSUE THREAD

**Issue by waruyama** [CompuIves/codesandbox-client#1485]
We have imported a project from GitHub which demonstrates colorizable SVGs:

https://codesandbox.io/s/github/iconfu/css-colorizable-icons/tree/master/examples/example_1

Unfortunately the most interesting part of this project, the SVG, is only referenced and the markup cannot be viewed or edited in Codesandbox. We usually consider SVGs source code, because we do a lot of manual editing and inspection, so it would be great to have an option for importing SVG files as text, instead of referencing them as images.

I would be satisfied with either an option that makes SVG behave like other source code, or a tab that allows switching between image view and code view.

**Comment by CompuIves** [comment]
Hmmmm yes I completely agree, svg files should be handled as source code. I'll take a look now.

**Comment by CompuIves** [comment]
I'll deploy the fix in the importer and client in 5 minutes, then it should work for every new commit you make (so making an empty commit should fix it).

**Comment by waruyama** [comment]
You sir, ...you rock!
