### ISSUE TITLE
Delete multiple sandboxes permanently from trash wrong selected count

### ISSUE THREAD

**Issue by pieterbergwerff** [CompuIves/codesandbox-client#1486]
# 🐛 bug report

## Description of the problem
When selecting multiple sandboxes for deleting permanently, and e.g. I select 4 sandboxes, a wrong count number is showed when clicking on delete. See screenshot.

<img width="1406" alt="screenshot 2019-01-22 at 14 10 09" src="https://user-images.githubusercontent.com/1438112/51537822-dff2ed00-1e4f-11e9-9912-d997cc54f93a.png">

## How has this issue affected you? What are you trying to accomplish?
I didn't affect anything I wanted to do, deleting sandboxes works as expected.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome
| Operating System | Mac

**Comment by pieterbergwerff** [comment]
I user command + click to select multiple items. I didn't know one could use the shift also :)

**Comment by lbogdan** [comment]
@pieterbergwerff Is this still happening? (although I don't think we did anything to fix it)
If not, please help us lower the number of opened issues by one! Thanks! 🙂

**Comment by pieterbergwerff** [comment]
Hi Bogdan, I don't know for sure.
I will test it :) I will get back on this.

**Comment by pieterbergwerff** [comment]
Can't reproduce the bug on the moment. So I think it's fixed then :)
![Screenshot 2019-03-25 at 15 34 29](https://user-images.githubusercontent.com/1438112/54928054-9ab46f80-4f13-11e9-8971-c44a64c7ec5e.png)

**Comment by lbogdan** [comment]
Nice! I'll close this for now, feel free to reopen if the issue comes back.
