### ISSUE TITLE
Unable to create server sandboxes

### ISSUE THREAD

**Issue by mohsinulhaq** [CompuIves/codesandbox-client#1488]
On your patron page, I see that the limit on the number of server sandboxes for free users is 5. But I am getting the error: "You reached the limit of server sandboxes, you can create more server sandboxes as a patron." for even my first save. Is the limit 5 or 0?

**Comment by lbogdan** [comment]
Hey @mohsinulhaq , as the patron page says, the limit for non-patrons is 5. Did you use server sandboxes in the past, and deleted them? If so, they might have remained in [Trash](https://codesandbox.io/dashboard/trash), delete them from there and you should be ready to go!

**Comment by mohsinulhaq** [comment]
Got it! They were in my trash. Thanks!
Is there any way to bulk delete them? I have 145 sandboxes in the trash right now.

**Comment by lbogdan** [comment]
Not really, but I use a trick: when in dashboard, zoom out a few times (`Ctrl` + `-`), until you get (most of) the sandboxes in view, and then select them by dragging the mouse. If everything works as expected, please close the issue, too. And have fun using CodeSandbox! 🙂

**Comment by mohsinulhaq** [comment]
Thanks a lot. It worked. 👍

**Comment by CompuIves** [comment]
Hahahaha, another trick would be to select the first sandbox, then shift
click the last one. We should add a button for this though!

**Comment by mohsinulhaq** [comment]
Thanks @CompuIves! you guys really have thought of everything. Such an awesome app. Keep rocking!

**Comment by mohsinulhaq** [comment]
One more question. Does it always execute `node src/index.js localhost 8080`
I have changed the start script to `nodemon --exec babel-node -w src/server -w webpack.config.js ./src/server` but it seems that it's not getting picked up.

https://codesandbox.io/s/6463pxzx2n

**Comment by lbogdan** [comment]
Whenever you change the main script in `package.json`, you have to restart the sandbox: "Server Control Panel" in the sidebar -> "Restart Sandbox". Also, I forked your sandbox, and I get an error (you can see that it the command defined in `start`):
![image](https://user-images.githubusercontent.com/2083930/51560896-7d6d1180-1e8e-11e9-845c-c8116af1e7a9.png)

**Comment by mohsinulhaq** [comment]
OMG, thanks once again! 😊
