### ISSUE TITLE
ZEIT deployment "An unknown error occurred when connecting to ZEIT" 

### ISSUE THREAD

**Issue by reflash** [CompuIves/codesandbox-client#1493]
# 🐛 bug report

## Description of the problem
Trying to deploy my sandbox to ZEIT I get "An unknown error occurred when connecting to ZEIT" message. Authorization step was passed successfully, only when I try to deploy I get this error.

## How has this issue affected you? What are you trying to accomplish?
That prevents me from deploying my test sandbox.

### Your Environment
| Software         | Name/Version|
| Сodesandbox  | 
| Browser | Microsoft Edge 44.17763.1.0 
| Operating System | Windows 10

**Comment by lbogdan** [comment]
Hey @reflash , can you please open the devtools before trying to deploy, and look for any errors in either the console or network tab after you get the error?

**Comment by reflash** [comment]
@lbogdan yeah, sure. Here's the output:

`POST https://api.zeit.co/v3/now/deployments?forceNew=1 403
raven.js:55 `

`Error: {"error":{"code":"legacy_deployment_not_allowed","message":"You tried to create a Now 1.0 deployment. Please use Now 2.0 instead: https://zeit.co/upgrade"}}
    at t (HttpProviderError.js:17)
    at new t (HttpProviderError.js:51)
    at Object.onResponse (DEFAULT_OPTIONS.js:65)
    at XMLHttpRequest.<anonymous> (utils.js:26)
    at XMLHttpRequest.d (raven.js:418)`

**Comment by SaraVieira** [comment]
Hey!

Can you point me to the sandbox you are trying to deploy please ?

**Comment by reflash** [comment]
@SaraVieira hmm, okay that explains why it fails. Is version 2 supported in any way ?

**Comment by SaraVieira** [comment]
Yeah, you need to create a now.json with the version key set to 2.

You can follow along here:
https://zeit.co/docs/v2/deployments/basics/#introducing-a-build-step

And have a ton of now 2 examples: https://zeit.co/examples/

It is weird that they default to something they don't support :/

**Comment by SaraVieira** [comment]
Yeah, you need to do all manually now in version 2.

What are you trying to deploy?

If it's create react app: https://zeit.co/examples/create-react-app/

**Comment by SaraVieira** [comment]
It's super complicated now and we will add support for netlify in the future

**Comment by reflash** [comment]
I did follow the example tutorial, but it still fails with the same error as previous. At the same time if I just load ZEIT CLI and deploy from local machine it works fine.

**Comment by SaraVieira** [comment]
Can I get the sandbox link?

**Comment by reflash** [comment]
Sure. https://codesandbox.io/s/xl193voklo

**Comment by SaraVieira** [comment]
I managed to deploy it without a hitch :/

https://tiles-board-game-nzy8ijyq1.now.sh/

**Comment by reflash** [comment]
Hm, I have tried it and on my laptop it works fine. I will check tomorrow on my work computer. It seems it was either somehow fixed by my cli deployment or it was something specific to my environment.

**Comment by SaraVieira** [comment]
Maybe it's an old service worker issue :(

That pc didn't have the new code that supported zeit 2 :(

**Comment by reflash** [comment]
I've tried it on my work laptop and it works fine either with my sandbox or newly created one. I assume it was some problem on the ZEIT site and it was somehow solved by deploying via CLI 🤣

**Comment by SaraVieira** [comment]
Well, it was a fart ahah

I am gonna close and please ping me on this issue if you have any problems with zeit again

**Comment by lfkwtz** [comment]
I'm having this same issue on my Vue sandbox that I created last week. Just created a new one and same issue.

Creating a now.json didn't do the trick for me. Any ideas @SaraVieira ?

https://codesandbox.io/s/ry532l5x1q
