### ISSUE TITLE
Editor shortcuts

### ISSUE THREAD

**Issue by xiechao06** [CompuIves/codesandbox-client#1494]
# ❔ Question

I've found some shortcuts when editing in codesandbox(I use mac and use the default monaco editor), for example:

CMD+x - delete current line
CMD+enter - goto the next line and open a new line

But I can't find a comprehensive editor shortcuts list (I does not mean the shortcuts like open preferences, just the shortcuts of editing code), could you please give one? thank you very much!

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | chrome |
| Operating System | macos 10.14.2 |

**Comment by SaraVieira** [comment]
Hey!

Monaco uses the vscode ones so you can refer to this PDF: https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf
