### ISSUE TITLE
Patreon accounts and private repos

### ISSUE THREAD

**Issue by babakness** [CompuIves/codesandbox-client#1511]
Hello, if someone has private repos and is a Patreon user; if someone forget to renew their subscriptions do all their private repos go public and expose all their secrets? What about their repos which are over the storage quota for a free account?

Thanks

**Comment by lbogdan** [comment]
Hey @babakness ,

The private sandboxes will remain private, and the over-quota sandboxes will not be deleted. The only difference is that you won't be able to create any new private sandboxes, or any new sandboxes until you remove some old ones and get under the 50 sandbox limit for regular users.

I'll close this for now, if you need any additional information, please join us on [Spectrum](https://spectrum.chat/codesandbox/)!
