### ISSUE TITLE
How does CodeSandbox actually deploy your project?

### ISSUE THREAD

**Issue by tangert** [CompuIves/codesandbox-client#1516]
I'm curious from an architectural perspective. 

When I open up my project, how is CodeSandbox creating an instance of my React app at "https://RANDOM_PROJECT_ID.codesandbox.io/"? How does CodeSandbox create a unique URL and host each project that you make?

**Comment by lbogdan** [comment]
Hey @tangert ,

Not going too much into details, we are using nginx, we define a `server {}` block with a `server_name` that matches `*.codesandbox.io`, we extract the sandbox id from that name and forward the requests together with the sandbox id to the API, which responds with the requested sandbox resource.

I'll close this for now, but if you want to discuss more about CodeSandbox, please join us on [Spectrum](https://spectrum.chat/codesandbox)!
