### ISSUE TITLE
Tries to load @types when package has included it's own

### ISSUE THREAD

**Issue by MartynasZilinskas** [CompuIves/codesandbox-client#152]
![image](https://user-images.githubusercontent.com/562658/29822135-1fcf9e4c-8cd3-11e7-9e1f-4d51d2a6f8ab.png)

I have noticed that it tries to load types from https://unpkg.com/@types/@simplr/react-forms-dom/index.d.ts. 

Expected behavior:
- Checks if package has `types` property and load from relative path [reference](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)
- If it doesn't have it, try to load `@types/*`

Simple package example: `react` -> `@types/react`.
Scoped package example: `@simplr/react-forms` -> `@types/simplr__react-forms` [reference](https://github.com/DefinitelyTyped/DefinitelyTyped/#what-about-scoped-packages)

On side note: Can't wait for TypeScript support. Keep up the good work. :tada:

**Comment by CompuIves** [comment]
Fixed with https://github.com/CompuIves/codesandbox-client/commit/6728a5190ce30916d48f662fe805baf15782543e.

TS support is reaaaally close! 😄
