### ISSUE TITLE
Hide the output panel by default

### ISSUE THREAD

**Issue by arunkumar413** [CompuIves/codesandbox-client#1526]
# 🌈 Feature

Hide the output panel by default. 

The output should open in a new tab only when the user clicks on a small button/link 

Use css `display: none` property to hide the output panel as shown in the below screenshot.

![screenshot from 2019-02-08 22-08-21](https://user-images.githubusercontent.com/7776779/52492009-5fbddd00-2bee-11e9-92e7-575f6b53510a.png)

**Comment by SaraVieira** [comment]
Hey!

This is kind of the ideia of codesandbox. To have the view always there.

You can hide it by clicking this button:

![screenshot 2019-02-10 at 13 40 39](https://user-images.githubusercontent.com/1051509/52533808-8d636d00-2d39-11e9-8f1c-c82a0f7afe35.png)

But as for hiding by default that doesn't make sense to most our use cases

You will in a future feature be able to always hide it for you

**Comment by arunkumar413** [comment]
Instead of hiding, make that button to directly open the output panel in a new tab and hide it in the editor by default. 

Let user focus on what they're trying to do one at a time. Either editing or viewing the output and have the full width for editing.
