### ISSUE TITLE
How can I link to an image?

### ISSUE THREAD

**Issue by misterhtmlcss** [CompuIves/codesandbox-client#1527]
# ❔ I can't view an uploaded image.

When I click upload file I try to add it eg src="image.jpg" but it won't recognize it. I clicked on the image and it shows a URL, so I copied and pasted that into the src="really long URL" and it still didn't working.

> `
> import React from "react";
> import ReactDOM from "react-dom";
> 
> import "./styles.css";
> 
> function App() {
>   return (
>     <div className="box">
>       <img src="unsplash1.png" alt="unsplash" />
>     </div>
>   );
> }
> const rootElement = document.getElementById("root");
> ReactDOM.render(<App />, rootElement);
> `

### Your Environment
| MacOS (latest)         | Using latest Safari (Not tech preview though)|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Safari
| Operating System | MacOS

**Comment by CompuIves** [comment]
Hey! You can put the image in the  public folder to make it work: https://codesandbox.io/s/x9n0prlp2w. I hope this solves your  problem!

**Comment by misterhtmlcss** [comment]
Me too. I gave up and deleted it, but since it was such an early stage I'm trying it again and it works already. Thank you!

**Comment by LegoMaster6410** [comment]
It didn't work because i'm on JavaScript.

**Comment by FezVrasta** [comment]
Is there any way to do that with the Parcel template?

**Comment by garethx** [comment]
@FezVrasta Yes, see https://codesandbox.io/s/kind-glade-sqf6y?file=/src/index.js for an example

**Comment by FezVrasta** [comment]
Thanks!
