### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by PAEz** [CompuIves/codesandbox-client#1531]
# 🐛 bug report

## Description of the problem
I think some unicode in my source is getting messed up by the time it reachs the preview.

## How has this issue affected you? What are you trying to accomplish?
I had a list of strings and one of them is just three symbols (🐎👱❤) that are unicode (utf something, sorry not totally up on the jargon here).  They are displayed correctly in the editor.  But once it reaches the preview it isnt that any more its ðŸŽðŸ‘±â¤

###  Link to sandbox: [link]() (optional)
https://codesandbox.io/s/k5vv06737v

### Your Environment
FireFox for the editor and Chrome for the preview.
Windows 10

**Comment by Haroenv** [comment]
<img width="170" alt="screenshot 2019-02-11 at 15 29 55" src="https://user-images.githubusercontent.com/6270048/52569609-e43c7580-2e11-11e9-968f-8f66037ea058.png">


I wonder if this might be FF or Windows only. My screenshot was done on Safari on mac

**Comment by PAEz** [comment]
Doesnt matter what browser I tried Chrome or FireFox.  
It shows up in the editor fine, but try copying the first icon (🐎) into the search and nothing comes up because 🐎👱❤ has turned into ðŸ�ŽðŸ‘±â�¤  
Now try pasting that first icon into the search box here....  
http://plnkr.co/edit/IvdOVx?p=preview  
...and it works as expected coz its still 🐎👱❤

**Comment by PAEz** [comment]
The problem wasnt codesandbox it was simply because I didnt have `<meta charset="UTF-8" />` in the head of the html, adding that fixed everything.  
Sorry about that, all this unicode stuff does my head in.  Oh well at least now I can go back to using codesandbox,  Now Ive got my paste back Im loving this site, well done to all involved.
