### ISSUE TITLE
codesandbox ./ doesn't work

### ISSUE THREAD

**Issue by zeitamin** [CompuIves/codesandbox-client#1537]
I want to make my local project uploaded to sandbox via cli, after entering `codesandbox ./` it asks me if i want to login and i type `y` , then after prining the below text nothing happen and no borwser tab will be opened:

```
$ codesandbox ./

  CodeSandbox CLI
  The official CLI for uploading projects to CodeSandbox

> You need to sign in before you can deploy applications
? Do you want to sign in using GitHub? Yes
> We will open CodeSandbox and show an authorization token.
> You'll need enter this token in the CLI to sign in.
```
I have also tried `codesandbox login` but after opening a brwoser tab the cli can not be written and i can not type anything 

```
codesandbox login

  CodeSandbox CLI
  The official CLI for uploading projects to CodeSandbox

> We will open CodeSandbox and show an authorization token.
> You'll need enter this token in the CLI to sign in.
? We will open CodeSandbox to finish the login process. Yes

> Opening https://codesandbox.io/cli/login

```

tested on powershell, command prompt and git bash cli the same result in all of them ...
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  2.1.1
| Browser |  chrome
| Operating System | windows 10

**Comment by lbogdan** [comment]
Hey @zeitamin ,

Is this still an issue for you?

**Comment by sajithneyo** [comment]
@lbogdan  happening same here

**Comment by YaroslavW** [comment]
I have such a problem. It seems that our problems do not interest anyone here. I am going to delete this shit away from my computer.

**Comment by CompuIves** [comment]
Do you have the same problem as the original issue? Impossible to put something in the CLI? I just tested it and it works for me, might be worth it looking into the dependencies.

**Comment by BDMayhem** [comment]
I'm experiencing the same with CodeSandbox CLI 2.1.1 on Windows 10 Build 17763.

It works for me as expected in Ubuntu 18.04.2.

**Comment by lbogdan** [comment]
Unfortunately I can't reproduce on any of my 3 Windows 10 systems. @zeitamin @sajithneyo @BDMayhem  Would any of you be interested in doing a TeamViewer session to debug this live on your system?

**Comment by CompuIves** [comment]
It could perhaps be related to the terminal? I've been testing with `iTerm` and `Terminal.app`.

**Comment by lbogdan** [comment]
All symptoms seem to point to a terminal issue, yeah. Although I tested with `powershell`, `cmd`, `cmder` and `Git Bash`, and couldn't reproduce with any of them.

**Comment by BDMayhem** [comment]
@lbogdan I can do TeamViewer

**Comment by lbogdan** [comment]
@BDMayhem Nice! Can we do a Skype to exchange connection details?

**Comment by BDMayhem** [comment]
Yes.  Also bdmayhem

**Comment by lbogdan** [comment]
We just published [codesandbox@2.1.3](https://yarnpkg.com/en/package/codesandbox), which should fix this. Please update, and if you still have issues, reopen to let us know.

**Comment by arunkumar413** [comment]
I'm facing this issue. The signin page auto opens in the browser. But It doesn't generate the token when the I click on signin with github.

I'm using a Linux mint system OS

**Comment by CompuIves** [comment]
Sorry about this! A refactor caused the cli login page to break, I've deployed a fix and it will be live within an hour.
