### ISSUE TITLE
How do you upgrade dependencies?

### ISSUE THREAD

**Issue by inf3rno** [CompuIves/codesandbox-client#1538]
I just released a new version of one of your dependencies, which fixes a bug. You added it here as dependency: https://github.com/CompuIves/codesandbox-client/blob/096366fdf8543474c2ccea049920749b748d46f5/packages/common/package.json#L12
As far as I understand the npm "^0.1.1" will automatically upgrade to the new version "0.1.2", but I want to be sure if that's the case by yarn too. Thanks!

**Comment by SaraVieira** [comment]
Hey!

That is the case with yarn too. It will update it too but I can also do it manually :)

We run this pretty constantly :)

Thank your fixing the bug :D

**Comment by inf3rno** [comment]
@SaraVieira Okay, thanks!
