### ISSUE TITLE
The context menu does not seem to have the proper z-index

### ISSUE THREAD

**Issue by inf3rno** [CompuIves/codesandbox-client#1539]
# 🐛 bug report

https://codesandbox.io/s/vanilla

win 7 x64
firefox 65, chrome 72, but I guess it is cut in half on every browser

![nevtelen](https://user-images.githubusercontent.com/408911/52777256-a6269800-3043-11e9-8c64-4ba4ed89b15f.jpg)

**Comment by SaraVieira** [comment]
Hey!

Just to set up for future fixes:

This is because .monaco-workbench has an overflow of hidden

**Comment by SaraVieira** [comment]
Issue closed as we dropped the monaco editor in the latest release
