### ISSUE TITLE
No error reported on invalid syntax

### ISSUE THREAD

**Issue by BTMPL** [CompuIves/codesandbox-client#1541]
# 🐛 bug report

The following syntax does not produce expected SyntaxError:

```
  handleClick = () => {
    const value = 42;
    this.setState(this.value: value);
    console.log('No SyntaxErrors')
  }
```

Clicking the element will trigger the function call and evaluate it properly. If you inspect the generated code you will see it's transpiled to

```
this.handleClick = function () {
      var value = 42;

      _this.setState(_this.value);

      console.log('No SyntaxErrors');
};
```

so it looks like the invalid part is being thrown away by the transpiler.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | current? :)
| Browser | Chrome
| Operating System | Win10

**Comment by lbogdan** [comment]
Hey @BTMPL ,

Closing this, as it seems to now error as expected (although I have no idea what fixed it). Please reopen if you don't agree. 🙂
