### ISSUE TITLE
How does JS autocompletion work in the editor?

### ISSUE THREAD

**Issue by zxti** [CompuIves/codesandbox-client#1544]
It's so awesome, and seems to be above and beyond what I've seen in any other editor.

To take a random vanilla sandbox of mine:

https://codesandbox.io/s/31oz3nqwpm

When I type:

```
document.querySelectorAll('script')[0].
```

I see the completion suggesting src, type, etc. - properties available to script tags.

Similarly for other tag types, I see properties specific to them.

Is there runtime introspection going on?

If it makes a difference I am using the experimental VS Code editor.

Thanks, mostly this is a burning curiosity!

**Comment by CompuIves** [comment]
Heyo! We use the TypeScript Language Service in a web worker to generate autocompletions. It works very similar to VSCode right now, and this month we're releasing VSCode Extension support, so then it works exactly like VSCode 😄
