### ISSUE TITLE
Using Vue's new "v-slot" attribute does not work

### ISSUE THREAD

**Issue by Loilo** [CompuIves/codesandbox-client#1545]
# 🐛 bug report

## Description of the problem
Vue 2.6 brought [the new `v-slot` directive](https://medium.com/the-vue-point/vue-2-6-released-66aa6c8e785e#f509) for using slots. While Vue 2.6 is used in CodeSandbox, this new directive is not recognized in compiled `.vue` files.

## How has this issue affected you? What are you trying to accomplish?
I tried to use `v-slot` because it's a much nicer API than the previous `slot-scope`. 😁

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | `PROD-1549895067-bab5c8d3`
| Browser | This should be a server-side issue, successfully reproduced in latest versions of Chrome, Firefox and Safari
| Operating System | macOS 10.14

**Comment by Haroenv** [comment]
I assume this might be because an older version of vue-template-compiler is used here?

**Comment by Loilo** [comment]
Sounds plausible to me.

**Comment by Haroenv** [comment]
https://github.com/CompuIves/codesandbox-client/blob/bab5c8d395d9239d6b55ba38aad9fbe9d7816b06/packages/app/package.json#L247

Seems to confirm my thoughts

**Comment by NJM8** [comment]
Can anyone comment on a similar issue here: https://codesandbox.io/s/yppozpw0z9. I'm using the newest version of Vue, and static default and named slots are working just fine with the new syntax. However attempting to pass a value and function out to the slot for use is failing. I have this same exact code working in a local application just fine.

**Comment by lbogdan** [comment]
@NJM8 Regardless of your sandbox `vue` version, like @Haroenv said, the CodeSandbox browser bundler uses a specific version of `vue-loader` (and implicitly of `vue-template-compiler`), which you can find [here](https://github.com/CompuIves/codesandbox-client/tree/master/packages/app/src/sandbox/eval/transpilers/vue), and which was last updated somewhere around `2.5.10`. We'll (well, mostly @CompuIves) try to update the vue loader and template compiler to `2.6.x` as soon as possible.

**Comment by jhnns** [comment]
Same issue with dynamic attributes which were also added with 2.6.0: https://codesandbox.io/s/lp39q1r6zq

Vue tries to set `[dynamicAttribute]` as attribute name which kind of confirms the previous assumption that the `vue-template-compiler` is outdated.

**Comment by lbogdan** [comment]
Hey there,

This is indeed long standing, I just opened #1640 and marked it `ASAP`, @Loilo I'd suggest closing this and following that instead.

**Comment by Loilo** [comment]
Alright. Thanks. :)
