### ISSUE TITLE
 Vue: assest image hasn't been transpiled yet.

### ISSUE THREAD

**Issue by Bensigo** [CompuIves/codesandbox-client#1546]
# 🐛 bug report

## Description of the problem
Trying to import images I uploaded but getting an error that image hasn't be transpiled
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | 
| Operating System |

**Comment by SaraVieira** [comment]
Hey

Can you please provide a sandbox where this happens?

**Comment by Bensigo** [comment]
Hey, thanks for the feedback, i fixed my issues with string literal 😃.

**Comment by natnael-wubet** [comment]
guys it is not working for me even i tried using require but nothing works

**Comment by garethx** [comment]
Can you please provide a sandbox where this happens?
