### ISSUE TITLE
Installation on local machine

### ISSUE THREAD

**Issue by evanoralph** [CompuIves/codesandbox-client#1547]
# ❔ Hi I want to install codesandbox on my local machine is it possible ?
if yes what are the requirements ?

sorry for the question cant see on the docs how i can intergrate it on my machine all I know its open source 

thanks

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  latest
| Browser | chrome
| Operating System | macos

**Comment by mikstur** [comment]
Hi @evanoralph 

I have recently started playing with this awesome project locally.

Ensure you have [yarn installed](https://yarnpkg.com/lang/en/docs/install). Then, clone the repo to your local machine. I created a separate `codesandbox` directory and cloned it into there using terminal on Mac:

```
mkdir codesandbox
cd codesandbox
git clone https://github.com/CompuIves/codesandbox-client.git
cd codesandbox-client
```

Then install all of the dependencies by running the following command in the `codesandbox-client` directory:
```
yarn install
```

You can see which commands you need to run by looking at the [package.json file](https://github.com/CompuIves/codesandbox-client/blob/master/package.json#L12).

```
yarn start
```

Then navigate to _http://localhost:3000_ and you should be good to go.

**Comment by lbogdan** [comment]
Hey, @evanoralph ! There's also https://github.com/CompuIves/codesandbox-client/blob/master/CONTRIBUTING.md#setting-up-the-project-locally .

**Comment by evanoralph** [comment]
@mikstur @lbogdan Thanks for the help already deploy it thanks !!!

**Comment by shrestharthghosh** [comment]
have any of you seen this issue -  Error occurred while trying to proxy request /api/v1/sandboxes/templates/official from localhost:3000 to https://codesandbox.io (ETIMEDOUT) (https://nodejs.org/api/errors.html#errors_common_system_errors after deploying, i am see a bunch of similar proxy failures

**Comment by sebibhutta** [comment]
I have cloned codesandbox.
when i run it on local it run smoothly. but when i make build of this project and upload it on xampp it shows error on clicking routes like signin file not found. because it thinks that it is a directory. please help

**Comment by chatranjan7865** [comment]
codesandbox cloud architecture did you guys have ?

**Comment by kishoreandra** [comment]
Man, In 2024 with all latest changes we see ... How do I run it downloading locally 😕
I'm trying to download locally - https://codesandbox.io/p/sandbox/quick-start-example-forked-zjk5jm and run this example .... But how do I
