### ISSUE TITLE
"Error fetching Sandbox" - repo public or repo private 

### ISSUE THREAD

**Issue by durkinio** [CompuIves/codesandbox-client#1548]
# 🐛 bug report

## Description of the problem

Having an issue "Error fetching sandbox." repeatedly for sandboxes based on a Git repo - regardless of whether that repo is public or private. Last night I successfully managed to get some work done through a Sandbox, but it error'd today, and any Sandbox I try to create based on that repo generates the same error, whether I made the repo public or private.

## How has this issue affected you? What are you trying to accomplish?
Can't get anything done 😢 

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  PROD-1550236301-af43adc5
| Browser | ChromeOS Version 71.0.3578.127 (Official Build) (64-bit)
| Operating System | ChromeOS Version 71.0.3578.127 (Official Build) (64-bit)

**Comment by lbogdan** [comment]
Hey @durkinio , can you please provide the sandbox URL?

**Comment by durkinio** [comment]
@lbogdan hmmm seems to have righted itself. Will keep this thread open in case it happens again. Thanks 👍

**Comment by SaraVieira** [comment]
@durkinio  Do you mind if I close it and if it happens again you open it?

It helps us to keep track of issues :/

**Comment by durkinio** [comment]
👍
