### ISSUE TITLE
Error in CodeSandbox on Android

### ISSUE THREAD

**Issue by donavon** [CompuIves/codesandbox-client#1549]
# 🐛 bug report

## Description of the problem

I'm getting an error in CodeSandbox when running on a mobile device

## How has this issue affected you? What are you trying to accomplish?

When I run [this sandbox](https://3y02owx21q.codesandbox.io/) on desktop, it works fine.
Burt when I run in on Android, all I get is a white screen. 

When I hook up a remote debugger via Chrome, I see that there is a 404 loading a resource, which is uncaught. (see screen shot below)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  |
| Browser | Brave |
| Operating System | Android Pixel 3 XL |

![image](https://user-images.githubusercontent.com/887639/52979577-30546080-33a4-11e9-9a61-f5f45b1ff83a.png)

**Comment by lbogdan** [comment]
Hey @donavon , are you still experiencing this issue? If not, we'd be very grateful for you to help us lowering the number of opened issues with one! 🙂

**Comment by donavon** [comment]
it went away. thx. closing

**Comment by lbogdan** [comment]
Thanks! 😃
