### ISSUE TITLE
Not sure this regex does what you want

### ISSUE THREAD

**Issue by LouisMichael** [CompuIves/codesandbox-client#1551]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?
Was looking at some of the project regex and [this one](https://github.com/CompuIves/codesandbox-client/blob/af43adc5300978573c63b48d4ed87a41e98628e3/standalone-packages/monaco-editor/release/esm/vs/basic-languages/rust/rust.js#L83) seemed odd. 

\h is not supported in javascript it simply matches literal h.

Example:
```
compulves-codesandbox-client $ cat t.js
if (/\\([nrt0\"''\\]|x\h{2}|u\{\h{1,6}\})/.exec("\\xhh")) {
	console.log("Matches xhh");
}
compulves-codesandbox-client $ node t.js
Matches xhh
```
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | 
| Operating System |

**Comment by davisjam** [comment]
Perhaps it should be 

`/\\([nrt0\"''\\]|x[0-9a-fA-F]{2}|u\{[0-9a-fA-F]{1,6}\})/`

?

**Comment by SaraVieira** [comment]
Hey!

This is actually not of our code but of the monaco editor. it's in our codebase because it's heavily edited but that part we don't use as it's for rust

We will most likely also remove monaco.

You can make an issue on the editor's github: https://github.com/Microsoft/monaco-editor
