### ISSUE TITLE
Support for the experimental syntax 'decorators-legacy' isn't currently enabled

### ISSUE THREAD

**Issue by vegarringdal** [CompuIves/codesandbox-client#1554]
# ❔ Question

I get this on sandboxes that have been working for months
- Support for the experimental syntax 'decorators-legacy' isn't currently enabled
Is it a bug ?

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | create-react-app-typescript (not using react)
| Browser | Chrome
| Operating System | windows10

**Comment by vegarringdal** [comment]
@SaraVieira Noticed this is fixed.
Great if tests are added so this cant happen again.
Thx for fixing it btw :-)

**Comment by SaraVieira** [comment]
Amazing! The issue is that we don't have that template anymore so some code was deleted 

Won't happen again

**Comment by vegarringdal** [comment]
Np just happy it could be fixed.

> The issue is that we don't have that template anymore so some code was deleted

Is there a clean new TS template that support decorators and import() with html files?

**Comment by SaraVieira** [comment]
The new react ts one I may support it 
https://codesandbox.io/s/react-ts

We basically removed the old one in favor of the new create react app supports ts by just changing the extension

**Comment by vegarringdal** [comment]
@SaraVieira 
Looks like react typescript template is still broken

If you take this sample
https://codesandbox.io/s/github/mframejs-codesandbox-samples/sample0005

Replace index.ts with this code
```ts
import {
  configure,
  IElement,
  template,
  customAttribute,
  bindable
} from "mframejs";

@customAttribute("custom-attribute")
export class CustomElement {
  public $element: HTMLElement;
  @bindable() public value: string;

  public created() {
    this.$element.innerHTML = this.value;
  }
}

// our dummy app to simplify parts
export class App implements IElement {
  public $element: any;
  public something = "test value";

  public created() {
    this.$element.$ref = this;
  }
  public loadTemplate() {
    return template`<div class="no1" custom-attribute.bind="something"></div>`;
  }
}

configure(App).then((mf: any) => {
  mf.start(document.body);
});

````

you will get 

![image](https://user-images.githubusercontent.com/2901416/53273956-dcc07a80-36f5-11e9-8cb3-a3614958b71e.png)


but if you edit this to the parcel/vanilla template in the sandbox.config.json and **refresh browser** page you get

![image](https://user-images.githubusercontent.com/2901416/53274063-332db900-36f6-11e9-9850-63a7f3c063c0.png)


its like the template breaks if someone makes edits

**Comment by SaraVieira** [comment]
Hey!

I think that one makes sense because you are building a parcel app, it's not react. The build is done with something else other than react-scripts from what I can tell :/

correct me if i am wrong

**Comment by vegarringdal** [comment]
@SaraVieira 
Thanks for replying 👍 
My last post did not show the issue very good.

> think that one makes sense because you are building a parcel app, it's not react.

its just a typescript silly frameword project Im making 😂 
I was using the react template since it was working better then parcel template where codesandbox breaks usage of `import('./somefile.html')`
Would be really nice if that was fixed.
https://github.com/CompuIves/codesandbox-client/issues/1196
Parcel locally works fine, so feel its a bug, but might have been overlooked since I put it inside sourcemap issue.

**But back to thread issue/decorator issue:**
Ive made a sample [link](https://codesandbox.io/s/github/mframejs-codesandbox-samples/sample0007)
Here you can see I get better error of the problem.
![image](https://user-images.githubusercontent.com/2901416/53298384-94a47380-382d-11e9-970a-6853068eead3.png)



This is a bug right ?
But again if this react-ts template is not going to be supported I can switch over to parcel. I figured it was nice to know about the bug if other stared asking

**Comment by SaraVieira** [comment]
I am gonna ping @CompuIves here because this is where my typescript knowledge ends :(

@CompuIves

**Comment by vegarringdal** [comment]
Np :-)
I will start using the vanilla template too. Since Im using using a old react template.

**Comment by feedm3** [comment]
@SaraVieira, @CompuIves: Any updates on this? It looks like this issue is still not resolved.

I just started a new react templated and transfered it to a typescript project. In the `tsconfig.json` I added `"experimentalDecorators": true` but I still get "Support for the experimental syntax 'decorators-legacy' isn't currently enabled". 
I also tried it with a react-ts template, same error.

Link to the sandbox: https://codesandbox.io/s/xvkvo3xmqz

**Comment by hug0b** [comment]
Same here my local Create-react-app with ts project works fine but the CRA + TS sandbox with identical dependencies and tsconfig throws 
`SyntaxError: Support for the experimental syntax 'decorators-legacy' isn't currently enabled`

**Comment by linonetwo** [comment]
My typescript rewired CRA run into this issue https://codesandbox.io/s/github/linonetwo/react-encompass-ecs-example

**Comment by vguleaev** [comment]
I have the same problem, is it possible to fix it?

**Comment by deadcoder0904** [comment]
Same issue. How to use Decorators without using TS?

I did the following to fix the warning in CodeSandBox

```
under File >> Preferences >> Settings

search for "javascript.implicitProjectConfig.experimentalDecorators" & enable it
```

Then I installed `@babel/plugin-proposal-decorators` & added the following to `.babelrc`

```js
{
  "plugins": ["@babel/plugin-proposal-decorators"]
}
```

It's still giving me error -

> Support for the experimental syntax 'decorators-legacy' isn't currently enabled

**Comment by deadcoder0904** [comment]
So this was fixed this morning. Source: https://twitter.com/CompuIves/status/1146743224679239681

It works with TS. Source: https://codesandbox.io/s/mobx-typescript-working-q0j1n
