### ISSUE TITLE
React sandbox doesn't work with typefaces

### ISSUE THREAD

**Issue by simoneb** [CompuIves/codesandbox-client#1555]
# 🐛 bug report

## Description of the problem

Using fonts from the `typefaces` project doesn't work in the React sandbox.

## How has this issue affected you? What are you trying to accomplish?

When trying to load a font, the font files are not loaded properly. They result in HTTP requests to the codesanbox.io server, which returns the page HTML rather than the font files.

###  Link to sandbox: [link](https://codesandbox.io/s/6lm97ov3or)

**Comment by IneoO** [comment]
use 
```
import 'typeface-roboto/index.css'
```
instead of 
```
import 'typeface-roboto'
```

https://codesandbox.io/s/0vpn9l2zo0

**Comment by SaraVieira** [comment]
Hey!

Like @IneoO said being specific works 
They may not have a index property in their package json

**Comment by amirsaa** [comment]
> # 🐛 bug report
> ## Description of the problem
> Using fonts from the `typefaces` project doesn't work in the React sandbox.
> 
> ## How has this issue affected you? What are you trying to accomplish?
> When trying to load a font, the font files are not loaded properly. They result in HTTP requests to the codesanbox.io server, which returns the page HTML rather than the font files.
> 
> ### Link to sandbox: [link](https://codesandbox.io/s/6lm97ov3or)

This is my issue too. no any typefaces work on CRA codesandbox.

**Comment by garethx** [comment]
@amirsaa Please link to a sandbox where this is happening for you that isn't resolved by the advice above? Thanks

**Comment by amirsaa** [comment]
@garethx Here is my [Link](https://codesandbox.io/s/typeface-problem-in-codesandbox-73b4g)

I also raised this problem to [stackoverflow](https://stackoverflow.com/questions/62096494/typeface-dependencies-not-worked-on-react-codesandbox) but I didn't get an answer.

**Comment by garethx** [comment]
INeoO's comment addresses this: https://github.com/codesandbox/codesandbox-client/issues/1555#issuecomment-465665919

**Comment by amirsaa** [comment]
@garethx It probably didn't help that I raised this issue buddy!
