### ISSUE TITLE
No syntax highlighting for .mjs files in vscode

### ISSUE THREAD

**Issue by warwickgrigg** [CompuIves/codesandbox-client#1559]
# 🐛 bug report

## Description of the problem
When using experimental vscode editor option there is no syntax highlighting for .mjs files

## How has this issue affected you? What are you trying to accomplish?

With vscode option enabled, I'd like the same syntax highlighting etc for .mjs files as with the default codesandbox editor.

PS. Thank  you for all your great work creating Codesandbox. Superb!

###  Link to sandbox:

[link](https://codesandbox.io/s/1v7kv153jj)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Chrome | 
| ChromeOS |

**Comment by lbogdan** [comment]
Closing this, as it should be fixed by the recent switch to VSCode as the default editor. Feel free to reopen if you still have issues.
