### ISSUE TITLE
HTML Autocomplete

### ISSUE THREAD

**Issue by jrock2004** [CompuIves/codesandbox-client#1561]
# 🌈 Feature

When working in html files or even things lilke hbs files, I want to be able to auto complete html elements

Type h1 hit tab and it should convert to `<h1>|</h1>`

No

**Comment by SaraVieira** [comment]
Hey

We are aware of this and will be fixed soon in a new release 

I will close it as it's a duplicate of https://github.com/CompuIves/codesandbox-client/issues/1476

**Comment by bentalgad** [comment]
Codesandbox doesn't have autocomplete for basic languages like html / css / js ?

**Comment by CompuIves** [comment]
Hey @bentalgad, you should see autocompletions in html/css/js. Can you see this?

![image](https://user-images.githubusercontent.com/587016/77634548-6f62c700-6f51-11ea-8412-b9463e420ed7.png)

**Comment by bentalgad** [comment]
I see it now, but it works very strange, and also i don't syntax colors
like you...

[image: 2020-03-26 12.10.00.gif]

‫בתאריך יום ה׳, 26 במרץ 2020 ב-12:03 מאת ‪Ives van Hoorne‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by CompuIves** [comment]
I'm not able to see the gif, but could you try to run CodeSandbox in an incognito window and see if there's a difference? It might be related to having an old version or a corrupt cache.

**Comment by hcrufio88** [comment]
i have the same problem. I try it in an incognito window and it works fine.
I updated chrome and cleared the navigation data, but it give me the same issue in normal window.
Any suggestion?

**Comment by garethx** [comment]
If it works in an incognito window, then it suggests that it might be a problem with a plugin. Try disabling them and turning them on until you've identified the culprit.

**Comment by KarnTech** [comment]
Hey do we have this autocomplete in Codesandbox??
