### ISSUE TITLE
Ways of updating screenshot

### ISSUE THREAD

**Issue by jenniredfield** [CompuIves/codesandbox-client#1563]
# 🌈 Feature
![image](https://user-images.githubusercontent.com/21988368/53246034-6bf27180-36a7-11e9-8cb3-45377a775abf.png)

Can we update the screenshot on dashboard so I get a prettier screenshot and not this old error?

**Comment by SaraVieira** [comment]
Hey!

Can you send me the sandbox link ?

**Comment by jenniredfield** [comment]
https://codesandbox.io/s/0or73or250

**Comment by lbogdan** [comment]
Hey @jenniredfield , you can regenerate the screenshot by accessing `https://codesandbox.io/api/v1/sandboxes/$sandboxId/screenshot.png`. I regenerated the screenshot for your sandbox:
![](https://screenshots.codesandbox.io/0or73or250.png)

**Comment by jenniredfield** [comment]
That's a weird way of doing this but thanks!

**Comment by jenniredfield** [comment]
Sara you work is amazing! Keep it up. Do you go to the web summits in Lisbon?

**Comment by SaraVieira** [comment]
@jenniredfield We never thought of making an endpoint but it could be interesting actually 🤔

Also thank you!!

I think this year I will only be going to http://reactjsgirls.com in london and will stop there for two days on my way to the US in june :)

**Comment by Mannaio** [comment]
Hi, how can i regenerate the screenshot by accessing https://codesandbox.io/api/v1/sandboxes/$sandboxId/screenshot.png.  ?
