### ISSUE TITLE
Syntax highlighting is broken on first load with custom theme

### ISSUE THREAD

**Issue by atomiks** [CompuIves/codesandbox-client#1565]
# 🐛 bug report

## Description of the problem

Whenever I first load up CodeSandbox, the syntax highlighting is broken or half-loaded:

![broken](https://i.gyazo.com/2e8487deab50b83bf5ccab1e4d65cc88.png)

After refreshing the page, it works:

![fixed](https://i.gyazo.com/1650a402b18b85d20835cf8ac9e75436.png)

The theme I'm using is: https://github.com/atomiks/moonlight-vscode-theme/blob/master/themes/moonlight-italic.json

(with the empty `""` foreground ones removed since that was a problem)

This happens on any sandbox, I'm not sure how long it takes to "re-break", when I paste a link into a new tab it seems to work after the refresh

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1550925883-24de5d4b
| Browser | Chrome 72
| Operating System | macOS 10.14.2

**Comment by CompuIves** [comment]
Hey! I noticed this one too, good point. I fixed this one in my branch, which will probably be deployed this week or early next week.

**Comment by atomiks** [comment]
Still seems to be happening for me

**Comment by CompuIves** [comment]
I expanded the scope quite a bit, sorry for the delay! Same message: will probably be deployed this week or early next week.

**Comment by lbogdan** [comment]
Closing this, as I'm fairly certain the recent switch to VSCode as the default editor should have fixed this. Please reopen if that's not the case.

**Comment by atomiks** [comment]
From a few uses of v3 it indeed oesn't seem to be a problem anymore 💯

**Comment by lbogdan** [comment]
Glad to hear, I'll close this for now, feel free to reopen if it somehow happens again!

**Comment by lbogdan** [comment]
Haha, I completely forgot I have already closed it, hopefully closing it for good now!
