### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by dekz** [CompuIves/codesandbox-client#1572]
# 🐛 bug report

## Description of the problem
Building dependencies I run into a disk space issue

## How has this issue affected you? What are you trying to accomplish?
Cannot build the sandbox due to the disk space issue.

Any thoughts on the best way to resolve this issue? Some of the dependencies that are pulled in can be marked as optional, I have attempted to set a local `.yarnrc` to ignore-optional dependencies but I don't believe this is respected.

```
mkdir -p /tmp/1155242446 && cd /tmp/1155242446 && HOME=/tmp node /var/task/node_modules/yarn/lib/cli add 0x.js@6.0.2 --ignore-scripts --no-lockfile --non-interactive --no-bin-links --ignore-engines --skip-integrity-check
```

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | 
| Operating System |

**Comment by lbogdan** [comment]
Hey @dekz , I can't see any (relevant) errors in the sandbox you linked to, is this still an issue? If so, can you paste / screenshot exactly what the error is?

**Comment by dekz** [comment]
@lbogdan looks to be running better now. I'll re-open if it occurs again.
