### ISSUE TITLE
Puppeteer error while loading shared libraries

### ISSUE THREAD

**Issue by MatteoGioioso** [CompuIves/codesandbox-client#1574]
# 🐛 bug report

Not sure if it is a bug, is Puppeteer currently supported in Codesandbox?

## Description of the problem

I am trying to run Puppeteer in Codesandbox but I get this error

```UnhandledPromiseRejectionWarning: Error: Failed to launch chrome! error while loading shared libraries: libX11-xcb.so.1 codesandbox``` 

Looks like those are Debian libraries or something.

### Your Environment

| Сodesandbox  | https://codesandbox.io/s/rm822yo91p
| Browser | Chrome Version 72.0.3626.119 (Official Build) (64-bit)
| Operating System | Windows 10 64

PS: thanks for creating Codesandbox, an amazing piece of software.

**Comment by SaraVieira** [comment]
Hey!

Puppeteer relies on chrome binaries, so lots of assembly and reason code. This makes it hard to support it right now. Maybe in the future with containers but we're not even close to it honestly

It would be amazing and we will keep it in mind :)
