### ISSUE TITLE
Firefox issue with MutationObserver

### ISSUE THREAD

**Issue by Wraithraiser** [CompuIves/codesandbox-client#1576]
# 🐛 bug report

## Description of the problem

Hello,

I have a problem using MutationObserver on Firefox but it's working fine on Chrome.

Just click to "Dynamic", it should print in the console on Chrome but nothing on Firefox. There's no error and I can't find the problem...

Thanks for the help 😄 

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome and Firefox
| Operating System | Win 10

**Comment by CompuIves** [comment]
Interesting... This might be related to our vanilla template using `document.write`. Thanks for letting me know! I can work on this either this weekend or next week.
