### ISSUE TITLE
Gridsome Starter

### ISSUE THREAD

**Issue by danvega** [CompuIves/codesandbox-client#1577]
# 🌈 Feature

Gridsome is a static site generator for Vue. It would be great if we could use this as a starting client template. 

This should work just like the Gatsby or Nuxt client template.

I would be willing to contribute this but I am not sure how to go about it. I am fairly new to CodeSandbox (I love it) so I am not sure what makes a starter template.

**Comment by lbogdan** [comment]
Hey @danvega ,

Thanks for the willingness to contribute! Maybe [this write-up](https://github.com/CompuIves/codesandbox-client/blob/master/contributor-docs/adding-template.md) might help you to get started?
