### ISSUE TITLE
Regression: Decorator problem surfacing in my template

### ISSUE THREAD

**Issue by jtheisen** [CompuIves/codesandbox-client#1579]
# 🐛 bug report

## Description of the problem

I'm using this sandbox as my template for new stuff, it used to work but no longer:

https://codesandbox.io/s/3r50xp9x9m

I'm now getting "Decorators transform is necessary." which I googled and found to be Babel-related.

`experimentalDecorators` is switched on in `tsconfig.json` of course.

**Comment by CompuIves** [comment]
Sorry for that! Committed a fix, will be either live today or tomorrow morning.

**Comment by jtheisen** [comment]
Hmm, it's still happening.

**Comment by CompuIves** [comment]
Forgot to deploy - it should work now!

**Comment by jtheisen** [comment]
Thanks, works now!
