### ISSUE TITLE
Theme isn't taken in account in sidebar anymore

### ISSUE THREAD

**Issue by Haroenv** [CompuIves/codesandbox-client#1583]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

1. pick the light theme
2. dark themed sidebar, with light theme text

###  Link to sandbox: [link]() (optional)

<img width="1440" alt="screenshot 2019-03-06 at 10 52 56" src="https://user-images.githubusercontent.com/6270048/53872391-6e858d00-3ffe-11e9-9e30-ff7c8a446055.png">

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1551787756-5ab389f8
| Browser | Safari TP Release 75 (Safari 12.2, WebKit 14608.1.3.0.2)
| Operating System | MacOS Mojave 10.14.1 (18B75)

Thanks!

**Comment by Haroenv** [comment]
happens on VS Code light theme, not others :)

**Comment by CompuIves** [comment]
Interesting, I have an update that will fix this. This should be live around ~Wednesday.

**Comment by CompuIves** [comment]
It's live 😄

**Comment by lbogdan** [comment]
Closing, as this now works as expected. Please reopen if you have further issues.
