### ISSUE TITLE
Is it possible for a sandbox to be deleted automatically?

### ISSUE THREAD

**Issue by kt3k** [CompuIves/codesandbox-client#1585]
# ❔ Question

We can't access one of our sandboxes https://codesandbox.io/s/3412r5nkzm which was a part of our documentation. Is it possible for a sandbox to be removed automatically?

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1551808138-15f6f3fe
| Browser | Chrome 72
| Operating System | macOS 10.12.2

**Comment by CompuIves** [comment]
Interesting, we don't normally delete sandboxes automatically. It seems that the sandbox was removed at "2019-02-10 20:40:25.59433 UTC".

**Comment by kt3k** [comment]
> Interesting, we don't normally delete sandboxes automatically.

Thank you for your quick answer! But then I don't see what causes the deletion... Maybe it was a misoperation of the owner of it. Is that sandbox anonymous one, or owned by a registered user? (If it's latter, maybe it's misoperation...)

**Comment by kt3k** [comment]
Anyway the original question is answered. Closing the issue.

**Comment by CompuIves** [comment]
Yes, it's owned by someone!
