### ISSUE TITLE
When adding a server template to github the template is converted to client template and the sandbox no longer works

### ISSUE THREAD

**Issue by wpitallo** [CompuIves/codesandbox-client#1586]
# 🐛 bug report

## I am trying to get server template (node express) linked to github

**Comment by lbogdan** [comment]
Hey @wpitallo , right not we don't automatically detect node specific sandboxes, although we're working to improve that soon-ish! Until then, you can create a `sandbox.config.json` inside your github repository root, and explicitly set `template` to `node` in it:
```json
{
  "template": "node"
}
```
For more details, also see [the documentation](https://codesandbox.io/docs/configuration#sandbox-configuration).

**Comment by wpitallo** [comment]
Thanks I tried this but it doe not seem to work.

I have also been browsing a few other express sandboxes and they seem to be having the same issue:

https://codesandbox.io/s/github/JSNavey/Node-Express-Lab/tree/master/

https://codesandbox.io/s/github/ruhaim/node-express-sample/tree/master/

**Comment by wpitallo** [comment]
@lbogdan "node" is also not seem to be in the documentation: https://github.com/codesandbox/codesandbox-importers/blob/master/packages/types/index.d.ts#L24-L39

**Comment by lbogdan** [comment]
Here's a working example: https://codesandbox.io/s/github/lbogdan/cs-node .

Also, you're right, that's not the exhaustive list of templates, just of the ones that need special configurations. You can get the list of all supported templates when you create a new sandbox, [here](https://codesandbox.io/s/) .

**Comment by wpitallo** [comment]
Awesome thanks, I forked yours and it worked. 

Thanks very much!

**Comment by lbogdan** [comment]
@wpitallo You're welcome! Like I said, it's only a matter of adding that `sandbox.config.json` file to an already existing github repo.
