### ISSUE TITLE
Update on github changes are not pulling though to codesandbox

### ISSUE THREAD

**Issue by wpitallo** [CompuIves/codesandbox-client#1587]
# 🐛 bug report

**Comment by CompuIves** [comment]
Hey! Could you send me the link of the GitHub repository? I'll take a look.

**Comment by wpitallo** [comment]
Hi its a private repo, has some authentication configuration in it :(

**Comment by wpitallo** [comment]
Nevermind I made it public:

https://github.com/wpitallo/AzureNoServerFunctions

**Comment by wpitallo** [comment]
This is the sandbox:
https://codesandbox.io/s/6v2x4lz9wr

**Comment by lbogdan** [comment]
Is that supposed to be a server sandbox? Because if it does, we don't currently support private server sandboxes, exactly for that kind of security / privacy reasons.

**Comment by wpitallo** [comment]
Ahh yes it is a server sandbox :(

**Comment by wpitallo** [comment]
Is it something you might do in the future?

**Comment by lbogdan** [comment]
Private server sandboxes are on our road map, we just didn't completely figure out a way to fully secure them.

On the other hand, if the code is public, and you only need secrets, you can define them in the "Server Control Panel":

![image](https://user-images.githubusercontent.com/2083930/54030215-894d3280-41b3-11e9-9fd9-f9e3d9067b7d.png)

This only works for sandboxes you own, so it won't work with a github imported sandbox, though.

**Comment by wpitallo** [comment]
Ok cool thanks! Not sure how exacly your sandboxes work but could you not just re-clone private sandboxes every time you connect and then not persist the files and destroy them when the container is destroyed?

**Comment by lbogdan** [comment]
The main issue with private server sandboxes is that the preview is publicly available at `https://sandbox-id.sse.codesandbox.io/`, so if you have sensitive data there, anyone could access it, even if the sandbox itself is not accessible.

**Comment by wpitallo** [comment]
Just interested whats the difference between the client and the server sandbox's? How come the clint ones can be secure but the server ones not?

**Comment by lbogdan** [comment]
The client sandboxes only evaluate inside your browser, so if you don't have access to the sandbox files, you can't see the preview, either.

**Comment by wpitallo** [comment]
Ah ok thanks so much for the info appreciate the help!
