### ISSUE TITLE
Iframe title attribute

### ISSUE THREAD

**Issue by pshrmn** [CompuIves/codesandbox-client#1598]
# 🌈 Feature

For accessibility, it is [recommended](https://dequeuniversity.com/tips/provide-iframe-titles) that `iframe`s have a `title` attribute. To help support this, the `iframe` embed code should include the sandbox's title.

**Comment by CompuIves** [comment]
Good point! I made a commit.

**Comment by pshrmn** [comment]
Oh, I was actually thinking of something slightly different. I just tracked the code down to here:

https://github.com/CompuIves/codesandbox-client/blob/5523e2cc7588c990e07ae976b79183bbb1283861/packages/app/src/app/pages/common/Modals/ShareModal/getCode.js#L66-L71
