### ISSUE TITLE
Opening a terminal

### ISSUE THREAD

**Issue by neunygph** [CompuIves/codesandbox-client#1608]
Hi, I'm new to codesandbox and I"m wondering how to open a terminal in order to run a npm command. I looked about my sandbox but I couldn't find any option to open a terminal. 

Thanks,

**Comment by lbogdan** [comment]
Hey @neunygph , you can only open a terminal in a server sandbox, you can read [this article](https://hackernoon.com/codesandbox-containers-5864a8f26715) for more info.

**Comment by neunygph** [comment]
Ah I see, thank you.

**Comment by lbogdan** [comment]
In other news, [CodeSandbox Containers is out of beta](https://medium.com/@compuives/codesandbox-containers-out-of-beta-improvements-be79679df4cc) as of today! 🙂

Closing this, if you're interested in more details about this feature, you can also find us on [Spectrum](https://spectrum.chat/codesandbox) .

**Comment by zommerfelds** [comment]
In case this helps anyone: to enable containers for an existing project you need to create a `sandbox.config.json` file with the following content *before* creating the sandbox:
```
{
  "template": "node"
}
```
I'm not sure if there is a way to change the sandbox once it's created.

**Comment by djnorrisdev** [comment]
Terminal is not showing up in codesandboxes for me, and this is long after the containers update. How can I get a terminal in a sandbox now?

**Comment by lbogdan** [comment]
Hey @djnorrisdev ,

In order to open a terminal you need a server sandbox that you own - meaning that you created it by forking an existing sandbox / template (as a note, you don't own GitHub imported sandboxes, even if you own the repository).

For example, go to the `node` template - https://codesandbox.io/s/node , fork it, and to open a terminal, press on the right `+` icon in the "Terminal" pane:

![image](https://user-images.githubusercontent.com/2083930/61462681-b38dd880-a97b-11e9-9ae6-06009f5bcb13.png)

**Comment by lbogdan** [comment]
@zommerfelds 

> I'm not sure if there is a way to change the sandbox once it's created.

There isn't one for now, but it's definitely high up on our roadmap!

**Comment by djnorrisdev** [comment]
@Ibogdan,

Thanks, I was trying to get access to be able to npm or yarn install a privately hosted npm package. I’m guessing that’s not possible yet?

**Comment by JoeEarly** [comment]
Any update on this, especially Terminal access on imported GitHub projects? Surely if I import my own GitHub project I should have the ability to run npm/yarn commands from a terminal window.

**Comment by garethx** [comment]
@JoeEarly You can already use a terminal on imported GitHub projects and do that - it's just that the terminal is only available to container sandboxes - See https://codesandbox.io/docs/environment for more info.

**Comment by JoeEarly** [comment]
@garethx I imported a GitHub project last night and it seems to have defaulted to client. How do I ensure an imported github project starts as a Container? Your link stats **Currently it is not possible to convert a Client Sandbox to a Container Sandbox.**

**Comment by lbogdan** [comment]
Hey @JoeEarly ,

You can add a `sandbox.config.json` to the root of the repository with the contents:

```json
{
  "template": "node"
}
```

Example: https://github.com/lbogdan/csb-vue-vite/blob/master/sandbox.config.json .

**Comment by JoeEarly** [comment]
Ok tried that but for some reason using the CodeSandbox UI, I don't have a node option in the dropdown and when editing with the editor, placing in node, it has no effect.

**Comment by lbogdan** [comment]
You can't change non-imported GitHub sandboxed from client to container. In case of GitHub imported sandboxes adding the `sandbox.config.json` file and re-importing the repo should change the sandbox environment.

**Comment by tatethurston** [comment]
> You can't change non-GitHub imported sandboxes between client and container environments. In case of GitHub imported sandboxes, adding the `sandbox.config.json` file and re-importing the repo should update the sandbox environment.

How do you re-import the repo?

**Comment by alexnitta** [comment]
I think "re-import the repo" really means add the `sandbox.config.json` file to the repo, delete the original sandbox, create a new one, and then import the repo. 

Steps that worked for me to ensure that a sandbox has a terminal:

1. Add `sandbox.config.json` to the root of the GitHub repo with the contents:
    ```
    {
        "template": "node"
    }
    ```
    Make sure change this is pushed up to the GitHub repo before you proceed.
2. Create a new sandbox, select **Import Project** at the left and paste in the URL of the GitHub repo, then click **Import and Fork**.
3. There should now be a terminal available in the tools in the lower right pane, showing that you're in a Container environment.

**Comment by Samia1117** [comment]
But I get a -- 502: Bad Gateway -- and the container fails to start. 
Followed the 3 steps detailed by alexnitta above

**Comment by TresAbhi** [comment]
@alexnitta Thanks, **it works!** It's quite sad that I'll now have to migrate sandboxes, but oh well.

**Comment by didymus707** [comment]
Is it possible to add a terminal to an existing react codesandbox?

**Comment by tresabhi** [comment]
@didymus707 no 😔

**Comment by NickWoodward** [comment]
Pretty sure I'm in a server sandbox, but no terminal access either. If I try to quit with ctrl+c I just get this and it won't let me type:

![image](https://github.com/codesandbox/codesandbox-client/assets/16296682/dc3f8390-4d54-4f24-bd79-b457f5823576)

It's definitely worked before though :shrug:
