### ISSUE TITLE
🐛 "More" Tab asks for Sign-In when already Signed In

### ISSUE THREAD

**Issue by Saeris** [CompuIves/codesandbox-client#1612]
As the title says, when viewing a sandbox as a logged-out user, after clicking the sign-in button in the upper right hand corner and successfully logging in, the "More" tab on the left-hand side still asks for the user to sign in before they can use it. Clicking the sign-in button inside the left-hand sidebar does not solve the issue, and neither does refreshing the page.

Here is a screenshot where you can see that in the upper right-hand corner I'm signed in, but the More panel still asks me to sign-in.

![image](https://user-images.githubusercontent.com/3144549/54621530-1ea6bd00-4a25-11e9-90ae-c75b927d978d.png)

**Comment by SaraVieira** [comment]
Hey!

I can reproduce this but reloading fixes it 

Interesting :/

Some state not getting to the places it should :(

**Comment by CompuIves** [comment]
Hm, we had a `.js` and `.tsx` file in the same place, I'm guessing that it defaulted to the `.js` file...

**Comment by CompuIves** [comment]
Hoping that this will fix it; https://github.com/CompuIves/codesandbox-client/commit/f2a81527206104cca286b6c1e962493aec21193c

**Comment by Saeris** [comment]
Appears to be fixed for me now. Took a bit for the changes to be applied. Strangely I didn't see the familiar "new version available" icon and refreshing the page didn't update my editor. What triggered the client app update was opening another one of my sandboxes to compare client and server sandboxes.

**Comment by lbogdan** [comment]
Just tested and it looks fixed, closing.
