### ISSUE TITLE
Started today - saving .Vue files gives "Formatting failed: TypeError"

### ISSUE THREAD

**Issue by CodeSpartan** [CompuIves/codesandbox-client#1618]
It can be reproduced in a new Vue template - just edit a .Vue file and hit save or ctrl-s. It's really annoying.

**Comment by CompuIves** [comment]
Hey! Which platform do you get this error on? Also, where does the error originate from? You can find that in the console.

**Comment by CodeSpartan** [comment]
Windows, tried two different machines. Attaching two screenshots of the error.
![error](https://user-images.githubusercontent.com/10173914/54643122-d1ffc800-4a9e-11e9-812e-20404dd6d53c.png)
![error2](https://user-images.githubusercontent.com/10173914/54643128-d4622200-4a9e-11e9-9f98-c32707600391.png)

**Comment by CompuIves** [comment]
Hmm yes can confirm, seems like the prettify of Vue doesn't work on Windows. I'm working on a fix.

**Comment by CompuIves** [comment]
I just deployed a fix for this!

**Comment by SaraVieira** [comment]
@CodeSpartan can you test and let us know if it fixed it ?

**Comment by CodeSpartan** [comment]
It's fixed, thanks!
