### ISSUE TITLE
ZEIT Deploy error "An unknown error occurred when connecting to ZEIT"

### ISSUE THREAD

**Issue by roy1210** [CompuIves/codesandbox-client#1620]
# 🐛 bug report

Hi, 
This is Roy.
I'm facing deploy error as per below screeshot.
Kindly advise how to fix the problem, thank you.

**Comment by lbogdan** [comment]
Hey @roy1210 ,

Can you please look for a request to `api.zeit.co` in the devtools "Network" panel, and paste / take a screenshot of the response?

**Comment by JasonGore** [comment]
I'm seeing the same error:

![image](https://user-images.githubusercontent.com/26070760/54855120-5e360900-4cb2-11e9-8b21-d6dd0a008eea.png)

Browsing to https://api.zeit.co/v3/now/deployments results in `{"error":{"code":"forbidden","message":"Not authorized"}}`

I wonder if this could be related to #1647?

**Comment by lbogdan** [comment]
@JasonGore You can't directly access that URL in the browser, as you need an authorization header. Can you please take a look in "Network" at a failed request and check that you're sending an `Authorization` header?

![image](https://user-images.githubusercontent.com/2083930/54858686-e8ac5600-4d0e-11e9-941b-a6e9f3653c7a.png)

If the header is there, and you still get a `403` error, can you please sign out of Zeit and sign in again from inside CodeSandbox's Preferences -> Integrations?

**Comment by roy1210** [comment]
Hi @lbogdan , 
Below is the console when deploy error happen. 
Please help to advice.

...
Screenshot:
https://gyazo.com/5c5693f78989e20f70e6e136daa11a25
...

raven.js:55 HttpProviderError: {"error":{"code":"invalid_files","message":"One or more file definitions contain errors in them","errors":[{"reason":"duplicated_file_path","path":"package.json"}]}}
    at t (https://codesandbox.io/static/js/vendors~app.1348226f.chunk.js:1:1779)
    at new t (https://codesandbox.io/static/js/vendors~app.1348226f.chunk.js:1:2535)
    at Object.onResponse (https://codesandbox.io/static/js/vendors~app.1348226f.chunk.js:1:1296)
    at XMLHttpRequest.<anonymous> (https://codesandbox.io/static/js/vendors~app.1348226f.chunk.js:1:8453)
    at XMLHttpRequest.d (https://cdn.ravenjs.com/3.21.0/raven.min.js:2:4340)

**Comment by lbogdan** [comment]
Yup, this looks like a bug on our part, will take a look at it this week!

Cc @SaraVieira

**Comment by SaraVieira** [comment]
Hey!

This is a bug on our side I will take a look this week, maybe today still

Sorry for the problem

**Comment by roy1210** [comment]
Hi Sara,
Noted. Just FYI, I faced the same bug when deploying Vue.js too.
Let me know once bug fixed.

**Comment by SaraVieira** [comment]
It's a general thing I think

Debugging it now

**Comment by Natetronn** [comment]
This must be the same issue I am getting. I have an open conversation on Spectrum w/ Sara.

**Comment by SaraVieira** [comment]
Yes @Natetronn this seems like its the same issue

I just made a PR that fixes the bug

https://github.com/CompuIves/codesandbox-client/pull/1662

**Comment by SaraVieira** [comment]
This PR should have fixed the issue, I will post vhere when it's live :)

**Comment by SaraVieira** [comment]
@Natetronn @roy1210 it has been deployed, let me know if you still have issues

Also I bumped into the thing that now only recognizes now-build in your package.json , it doesn't use build

**Comment by roy1210** [comment]
@lbogdan  @SaraVieira  Noted, Thank you!

**Comment by Natetronn** [comment]
Thanks, Sara! The Gatsby example is now working as expected.

I'm still getting the same error here, however: https://codesandbox.io/s/6v3v3yxy0k

https://github.com/Natetronn/now-examples/tree/master/static

Works locally and is an example direct from Zeit, with the added package.json to import from Github and work in codesanbox.

**Comment by Natetronn** [comment]
```
POST https://api.zeit.co/v3/now/deployments?forceNew=1 403
raven.js:55 HttpProviderError: {"error":{"code":"legacy_deployment_not_allowed","message":"You tried to create a Now 1.0 deployment. Please use Now 2.0 instead: https://zeit.co/upgrade"}}
    at t (https://codesandbox.io/static/js/vendors~app.76d08125.chunk.js:1:1779)
    at new t (https://codesandbox.io/static/js/vendors~app.76d08125.chunk.js:1:2535)
    at Object.onResponse (https://codesandbox.io/static/js/vendors~app.76d08125.chunk.js:1:1296)
    at XMLHttpRequest.<anonymous> (https://codesandbox.io/static/js/vendors~app.76d08125.chunk.js:1:8453)
    at XMLHttpRequest.d (https://cdn.ravenjs.com/3.21.0/raven.min.js:2:4340)
```

**Comment by adam-acosta** [comment]
![image](https://user-images.githubusercontent.com/1189675/56229844-da6d0380-6048-11e9-90be-50914c92f1f3.png)

**Comment by SaraVieira** [comment]
hey!

These errors mean you need to use version 2 of now and you can't use version one anymore so this means you need a now.json

https://zeit.co/docs/v2/deployments/configuration

**Comment by Natetronn** [comment]
The box contained a version 2 now.json and deployed locally, with zero issues.

![codesandbox](https://user-images.githubusercontent.com/582149/56385250-77f43e80-61d3-11e9-81b1-d2b5d54a37f1.png)

**Comment by maxfi** [comment]
When trying to sign in to Zeit from the _Integrations_ section in _Preferences_ I get the following popups:

```
Invalid request: `redirect_uri` is not a valid URI
```
and

```
Could not authorize with ZEIT
```
