### ISSUE TITLE
Not able to Cancel or Update Patron subscription

### ISSUE THREAD

**Issue by klujanrosas** [CompuIves/codesandbox-client#1622]
# 🐛 bug report

## Description of the problem
A subscription shows up even though I'm pretty sure I'm not being charged the $5 it says in there (**Exhibit A**).

When I try to click Cancel, or Update, I receive the message in **Exhibit B**, and a request like

```
DELETE https://codesandbox.io/api/v1/users/current_user/subscription
```

fails with 
```json
{
  "errors": {
    "detail": [
      "Customer cus_CpD2zdIt78vcDQ does not have a subscription with ID sub_CpD25YpOb5hERV"
    ]
  }
}
```

**Exhibit A**
![image](https://user-images.githubusercontent.com/4474353/54647616-29873f00-4a71-11e9-840c-dc6e135cec74.png)

**Exhibit B**
![image](https://user-images.githubusercontent.com/4474353/54647679-6d7a4400-4a71-11e9-84d1-8b3b92809800.png)

## How has this issue affected you? What are you trying to accomplish?
After today's release(congrats @CompuIves and team btw :tada: ), I wanted to become a Patron, however I am unable to at the moment :disappointed: .

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1553021361-2ab67983
| Browser | 73.0.3683.75 (Official Build) (64-bit)
| Operating System | Pop!_OS 18.04 LTS

**Comment by CompuIves** [comment]
Hey! It should be fixed now, sorry for that! There  was an inconsistency in the database.

**Comment by CompuIves** [comment]
Thank you for becoming a patron!

**Comment by klujanrosas** [comment]
I was able to subscribe again :tada: 
Thanks for all your awesome work @CompuIves
