### ISSUE TITLE
Forking a Vanilla Js template is returning 405

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [CompuIves/codesandbox-client#1623]
# 🐛 bug report

## Description of the problem
Hi, I am trying to fork a vanilla template from the dashboard, but the API is returning 405, attaching screenshots for reference, but when I come back to my dashboard after a hard refresh a template is being created.

<img width="964" alt="Screenshot 2019-03-20 at 11 39 01 AM" src="https://user-images.githubusercontent.com/11075561/54662830-56853180-4b05-11e9-917f-eae880e99ad0.png">
<img width="1280" alt="Screenshot 2019-03-20 at 11 38 00 AM" src="https://user-images.githubusercontent.com/11075561/54662831-571dc800-4b05-11e9-84c2-e89784165228.png">
<img width="1280" alt="Screenshot 2019-03-20 at 11 37 46 AM" src="https://user-images.githubusercontent.com/11075561/54662834-571dc800-4b05-11e9-9ace-69c917ad0fd1.png">

Browser - Chrome 72.0.36 (Official build)

**Comment by lbogdan** [comment]
We had some high load / downtime issues related to the recent switch to VSCode as the default editor, and you probably tried during this period. I'm gonna close this now, please reopen if it's still happening for you.
