### ISSUE TITLE
Not able to see my sandboxes on CodeSandbox website

### ISSUE THREAD

**Issue by GermaVinsmoke** [CompuIves/codesandbox-client#1624]
# 🐛 bug report

## Description of the problem

Server is giving a 504 error

![image](https://user-images.githubusercontent.com/32815509/54663869-b03b2b00-4b08-11e9-8298-16eb8ca16cdd.png)

I'm using Sandbox editor URL on my website that's also not opening up. On embedding the editor using `<iframe>` getting this error `Uncaught SyntaxError: Unexpected token <`

## How has this issue affected you? What are you trying to accomplish?

I am not able to embed the editor or open up the Editor URL from any other website

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  v3
| Browser |  Chrome Version 72.0.3626.121 (Official Build) (64-bit)
| Operating System | Windows 10

**Comment by CompuIves** [comment]
Hey! This one should be fixed now, our server had a spike of traffic and was timing out requests. We've upgraded the server and it shouldn't happen anymore. Sorry for the inconvenience!

**Comment by GermaVinsmoke** [comment]
Thanks, now it's working fine but can you explain the `Uncaught SyntaxError: Unexpected token <` error, getting this error when embedding a Editor on a website. 5 same errors from these files tsMode.js:1 , typescript.js:1, htmlMode.js:1, html.js:1 and jsonMode.js:1
