### ISSUE TITLE
Typings erors on Dojo sandboxes

### ISSUE THREAD

**Issue by nicknisi** [CompuIves/codesandbox-client#1627]
# 🐛 bug report

## Description of the problem

The editor shows errors as if it can't find the typings for Dojo projects. These typings are available inline within the Dojo package. For example, [`@dojo/framework/widget-core/WidgetBase`](https://unpkg.com/@dojo/framework@5.0.3/widget-core/WidgetBase.mjs) has has a sibling file, [`WidgetBase.d.ts`](https://unpkg.com/@dojo/framework@5.0.3/widget-core/WidgetBase.d.ts) that CodeSandbox should be picking up.

This could be related to #1420 but that seemed to only be happening in the Monaco editor and not the experimental VSCode editor.

## How has this issue affected you? What are you trying to accomplish?

This makes Dojo template sandboxes seem like they have errors when they really don't.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1553087764-02c4c7a3f | 
| Browser | Chrome 73.0.3683.75 (Official Build) (64-bit) |
| Operating System | macOS Mojave 10.14.3 |

![image](https://user-images.githubusercontent.com/293805/54699340-d22fb000-4afe-11e9-9452-a41ba1e04224.png)

**Comment by CompuIves** [comment]
Good one! I added a fix, need to update the URL now.

**Comment by CompuIves** [comment]
https://github.com/CompuIves/codesandbox-client/commit/7462a09968c14545a749d5fb445792ab15266eab

**Comment by CompuIves** [comment]
Fix is  live!

**Comment by nicknisi** [comment]
You’re the best! Thanks!
