### ISSUE TITLE
Move to Trash

### ISSUE THREAD

**Issue by Developerayo** [CompuIves/codesandbox-client#1628]
# 🌈 Feature

## Issue
When Move to Trash is clicked on a sandbox, the system should throw a warning instead of deleting the Sandbox straight up, without any warning's, becasuse mistakes can be made.

## How it can work
When Move to Trash is clicked, a popup should load up saying `Once you delete this Sandbox, there is no going back. Please be certain.` then we will have two options, `Delete & Cancle`.

cc @SaraVieira

**Comment by CompuIves** [comment]
Hey! When you move a sandbox to trash you can luckily still recover it! If you right click on the sandbox you can select "Recover Sandbox" and  it  will return to "My Sandboxes".

**Comment by Developerayo** [comment]
Yes that's true, I've seen that feature, but don't you think giving them an option also on the dashboard page would be cool to have?

**Comment by lbogdan** [comment]
If "Move to Trash" was a destructive action (something like "Delete[ Immediately]"), showing a confirmation popup would make sense, but as it's not, and you can always recover moved sandboxes from the "Trash" folder, I also don't think an extra confirmation is needed. Maybe we can show a notification when a user first moves a sandbox to trash that it can be recovered by going to the "Trash" folder etc., but that's a very common UI pattern that I think most users are already used to.

**Comment by Developerayo** [comment]
Alright, that's true, Since a trash folder can easily be found and you can recover, then this feature might not be needed.

**Comment by Developerayo** [comment]
Sanboxes that are deleted and are present in the Trash folder, does it take up space on the bandwidth of the host?
