### ISSUE TITLE
Problem with circular references in Vue.js - but only in CodeSandbox

### ISSUE THREAD

**Issue by PeterC66** [CompuIves/codesandbox-client#1631]
# 🐛 bug report

## Description of the problem

I have developed a public Vue.js package ([vfg-display-fields](https://github.com/PeterC66/vfg-display-fields)). As it is a tree structure, the package has a pair of components (DisplayFields.vue and DisplayGroups.vue) which are circular references.  I have resolved this using one of the methods in the [Vue.js Guide](https://vuejs.org/v2/guide/components-edge-cases.html#Circular-References-Between-Components).

Thus in DisplayGroups.vue I use

    components: {
      'display-fields': () => import('./DisplayFields.vue'),
    },

Within my vfg-display-fields package my test works well.  And then when I publish the package and import it into a separate system it also works well. So I am happy.

**However** when I try to showcase the package within a CodeSandbox (see https://codesandbox.io/s/ykpj1jpxvv) the circular recursion causes a problem. I initially assumed this was a problem with my own code and raised it on StackOverflow but the CodeSandbox problem remained. So I wonder if it is an issue with CodeSandbox itself?

The error I get in CodeSandbox is:

    [Vue warn]: Failed to resolve async component: function displayFields() {
          return _promise.default.resolve().then(function () {
            return require("".concat(function () {
              return require('./DisplayFields.vue');
            }));
          });
        }

    Reason: DependencyNotFoundError: Could not find dependency: 'function () {
              return require('.' relative to '/node_modules/vfg-display-fields/src/DisplayGroups.vue'

When I try the second suggested method of resolving the circular reference, using:

    beforeCreate() {
      this.$options.components['display-fields'] = require('./DisplayFields.vue').default;
    },

Again it works fine in my own system, but in CodeSandbox I get an error:

    [Vue warn]: Unknown custom element: <display-fields> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

This is only my first package and I am feirly new to Vue.js. My package seems to work fine in its intended location but not within CodeSandbox. Is this a bug in CodeSandbox?

## How has this issue affected you? What are you trying to accomplish?

I would like to showcase my package within a CodeSandbox, and at the moment cannot do so.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | (current)
| Browser | Chrome 72.0.3626.121 (Official Build) (64-bit)
| Operating System | Windows 10

**Comment by lbogdan** [comment]
Hey @PeterC66 ,

Best practices when authoring npm packages say that code should be transpiled to ES5. From what I see at https://unpkg.com/vfg-display-fields@0.0.5-d/src/index.js , you published ES6 code, while also using `.vue` files. While some custom webpack configurations can deal with npm packages having ES6 code, and even `.vue` files, most default configurations don't.

I'd suggest reading this [nice article about creating and publishing Vue.js components on NPM](https://medium.com/justfrontendthings/how-to-create-and-publish-your-own-vuejs-component-library-on-npm-using-vue-cli-28e60943eed3) , and maybe also looking at how popular Vue.js packages deal with that.

**Comment by PeterC66** [comment]
Thanks @lbogdan, that is very useful. I had not noticed anything about this in my previous reading, and am new to much of the node/npm/vue.js environment.  I will try it out and hopefully be able to close this issue soon.

**Comment by PeterC66** [comment]
@lbogdan, Consulting the ref you gave and [vue-cli-service build docs](https://github.com/vuejs/vue-cli/blob/dev/docs/guide/cli-service.md#vue-cli-service-build) helped me understand better what I need to do. I will close the issue as it is not about CodeSandbox.

**Comment by lbogdan** [comment]
@PeterC66 Happy to help! I would also suggest you to join the [official Vue.js Discord chat server](https://chat.vuejs.org/), there's an awesome community there (I know cause I'm part of it 🙂 ), and lots of people helping and answering other people questions.

**Comment by lgraziani2712** [comment]
@lbogdan I'm not sure this "bug" is related to not transpiling to es5. Today I have the same bug in a vue sandbox and wasn't dynamically importing a vue component, it was a JS file. The crazy thing is, the same code in a react sandbox works.

Tweeking the babelrc file from the vue sandbox I could make it work. This sandbox fixes the OP's one: https://codesandbox.io/s/j2zojo4ky3
