### ISSUE TITLE
Consider adding a @pika/web based vanilla template

### ISSUE THREAD

**Issue by jhony1104** [CompuIves/codesandbox-client#1634]
# 🌈 @pika/web based vanilla template

Pease consider adding a vanilla template that doesn't use a bundler. This would make it a lot easier to work with eg. Custom Elements.

A way to also provide an easy way to use npm packages, could be something like [@pika/web](https://github.com/pikapkg/web).

related to: #1246

**Comment by lbogdan** [comment]
Hey @jhony1104 , thanks for your feature request.

I left a comment in #1246 , and as they both have the same scope, I'll close this as a duplicate. Please subscribe to the other one to track progress.

It's gonna take a while, though, as we're currently focusing on other things, but we're always opened to contributions! If not with the actual implementation, at least with a design document describing in detail how this should work.
