### ISSUE TITLE
Local hosted - Security error on certain types of projects

### ISSUE THREAD

**Issue by gregrob1** [CompuIves/codesandbox-client#1639]
# 🐛 bug report

## Description of the problem
Running locally and followed the setup given in the CONTRIBUTING file.  Certain types of projects given a `SecurityError
Blocked a frame with origin "http://localhost:3002" from accessing a cross-origin frame.` Of the project types I have tried Vue (CLI) and Angular both get this error.  

![image](https://user-images.githubusercontent.com/48801073/54765248-8993f780-4bcf-11e9-9489-f066151eeab0.png)

React and Static projects do not

![image](https://user-images.githubusercontent.com/48801073/54765266-9284c900-4bcf-11e9-9479-058faed02d54.png)

## How has this issue affected you? What are you trying to accomplish?
Looking at codesandbox for internal equivalent of hosting things that are sensitive

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |   Latest from Github 
| Browser | Does not seem to matter but happening on Chrome 72 and Firefox 65
| Operating System | OSX Mojave 10.14.3

**Comment by lbogdan** [comment]
Hey @gregrob1 , thanks for your bug report!

I'm gonna test this with a clean clone on my machine and get back to you shortly.

**Comment by lbogdan** [comment]
Unfortunately I can't reproduce it. Just for the record, I'm using:
- macOS High Sierra
- latest Chrome (73.0...)
- node 10.15.3
- yarn 1.13.0
- ran `git clone ...`, `yarn`, `yarn start` .

**Comment by gregrob1** [comment]
Hi @lbogdan 

Besides OS version the big difference I see is I'm on node v11.10.1

I am going to pull a prior version of node - and redo the steps

**Comment by gregrob1** [comment]
I used nvm to run run node 10.15.3 and saw the same issue but realized I left out a step

The first time the project runs fine.  However *if* you make a change in a file when it tries to run the second time is when the problem occurs.

For example

Go to http://localhost:3000
It will display fine
Click `components`
Click `HelloWorld.vue`
Start typing next to the text for `Hello Vue in CodeSandbox!`

And then the error appears

You can follow similar steps and modify the components in the other projects (for instance static or react) and you don't get the error

**Comment by lbogdan** [comment]
I can confirm I have the same behavior. Also, from the stack trace, this seems to be related to `console-feed`:
```
Uncaught DOMException: Blocked a frame with origin "http://localhost:3002" from accessing a cross-origin frame.
    at Object.shouldTransform (webpack:////Users/bogdan/Documents/work/codesandbox-client/node_modules/console-feed/lib/Transform/HTML.js?:20:17)
    at EncodingTransformer._handleValue (webpack:////Users/bogdan/Documents/work/codesandbox-client/node_modules/console-feed/lib/Transform/replicator/index.js?:110:27)
    at EncodingTransformer._handlePlainObject (webpack:////Users/bogdan/Documents/work/codesandbox-client/node_modules/console-feed/lib/Transform/replicator/index.js?:75:42)
[...]
```
We'll take a look at this next week.

**Comment by samdenty** [comment]
@lbogdan object getters throwing an error fixed in 2.8.6

**Comment by lbogdan** [comment]
@samdenty That seems to solve it, thanks!

@gregrob1 Can you please try with https://github.com/lbogdan/codesandbox-client/tree/update/console-feed ?

**Comment by gregrob1** [comment]
@lbogdan Can confirm that fixed.  Thank you and @samdenty !
