### ISSUE TITLE
console.log() in manager.js

### ISSUE THREAD

**Issue by lbogdan** [CompuIves/codesandbox-client#164]
There's a `console.log()` in https://github.com/CompuIves/codesandbox-client/blob/master/src/sandbox/eval/manager.js#L45 , which also shows in production. Is this needed?

**Comment by CompuIves** [comment]
Yep, this is on purpose for easier debugging. I'm planning to keep it until next week.

**Comment by lbogdan** [comment]
Roger that. :smile:

**Comment by lbogdan** [comment]
Actually, I'll just leave this opened as a reminder. :smile:

**Comment by CompuIves** [comment]
Put this behind an environment flag 😄
