### ISSUE TITLE
PWA icon not visible

### ISSUE THREAD

**Issue by donavon** [CompuIves/codesandbox-client#1644]
# 🐛 bug report

## Description of the problem

If you install CodeSandbox as a PWA and you are on a dark background, then when you use Cmd-Tab to switch between apps, the CodeSandbox icon is barely visible. There are times when it's completely invisible if you're on the same background color. It works great on lighter backgrounds as the icon is back.

❤️ it as a PWA, BTW! 👏

![codesandbox2](https://user-images.githubusercontent.com/887639/54824750-37f87500-4c82-11e9-9036-eb41b5d7e0cc.gif)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1553202286-33f86d568 |
| Browser | Chrome 73 |
| Operating System | macOS Mojave |

**Comment by SaraVieira** [comment]
Hey @donavon 

Noob question: How did you install it as a PWA? Was that in Chrome?

**Comment by donavon** [comment]
Yes. On Chrome 73+ you can "install" PWAs on macOS.

see: https://medium.com/@dhormale/install-pwa-on-windows-desktop-via-google-chrome-browser-6907c01eebe4#057f

**Comment by SaraVieira** [comment]
That is so weird, I don't get that on codesandbox :/


Can you test this link and see if the icons look better?
