### ISSUE TITLE
'Tests' links stacking up on the preview pane.

### ISSUE THREAD

**Issue by gforceg** [CompuIves/codesandbox-client#1651]
# 🐛 bug report

## Description of the problem

A bunch of 'Tests' links have stacked up on the preview pane obscuring the 'Browser' link. I didn't notice this until after I had forked several sandboxes so now they all have this issue.

![image](https://user-images.githubusercontent.com/14267747/54930262-9ae54880-4edc-11e9-8919-51f3a3e5ed24.png)

## How has this issue affected you? What are you trying to accomplish?

It is difficult to preview the app in the browser. The user must stretch the window beyond the width of the display if they want to click 'browser'.

![image](https://user-images.githubusercontent.com/14267747/54929960-04188c00-4edc-11e9-996c-2bb20c7e7e1b.png)

The folks that will view these sandboxes are students who would not know there is a browser preview link to begin with.

I will have to copy + paste my code into new sandboxes.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome + Brave + Firefox
| Operating System | Fedora 29 + Win 10

**Comment by CompuIves** [comment]
Wooow, so on every fork a new tab is added?

**Comment by gforceg** [comment]
@CompuIves I don't know that forking caused the problem. I just know that forking spread the problem to my other new sandboxes.

As I was working on the original sandbox I vaguely remember seeing two 'Tests' links, then three, etc... I figured that upon refresh / save they would go away. I forgot about the issue until it was too late.
