### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by elrumordelaluz** [CompuIves/codesandbox-client#1657]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

Since the last version of [reactour](https://reactour.js.org/) is shipped as `module`, I am trying in a _codesandbox_ but getting 
```
ModuleNotFoundError
Could not find module in path: 'reactour' relative to '/src/index.js'
```
<img width="1261" alt="Screenshot 2019-03-26 at 11 54 46" src="https://user-images.githubusercontent.com/784056/54991806-fd624580-4fbd-11e9-9d56-ecce644728aa.png">

Seems to work ok using _CRA_ in local _Application_

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1553261537-e53862f6e |
| Browser | Firefox 66.0.1 (64-bit) |
| Operating System | OSX 10.14.4 |

**Comment by lbogdan** [comment]
Hey @elrumordelaluz ,

That's an interesting issue, looks like the `browser` field in `package.json` [points to](https://github.com/elrumordelaluz/reactour/blob/master/package.json#L7) `dist/reactour.umd.js `dist/reactour.umd.js`, which doesn't exist in the npm package: https://unpkg.com/reactour@1.13.2/dist/reactour.umd.js .

As you say it's working locally, webpack probably falls back to `main` if it can't find the files pointed by `browser`, while we don't. Either way, removing `browser`, or adding the UMD build to the npm package should fix this.

**Comment by elrumordelaluz** [comment]
Yup! worked perfect! Updated the _Sandbox_.

Thanks @lbogdan for the input!
