### ISSUE TITLE
reset profile

### ISSUE THREAD

**Issue by domi1kenobi** [CompuIves/codesandbox-client#1666]
# 🐛 bug report

## Description of the problem
deleted the folder with the configuration for the exclude watchfolders and it's not coming back
## How has this issue affected you? What are you trying to accomplish?
trying to exclude a folder from being watched by the process that restarts node.
reproduce:
* go to settings
* editor
* files
* add path folder to be excluded
* in the explorer a new folder was created and in there a file with the exclude statement
* I deleted this folder and file
* try to regenerate the folder / file by adding or removing exclude folders in settings - does not work

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | current version
| Browser | chrome + Edge
| Operating System | win10 64bit

**Comment by domi1kenobi** [comment]
in settings.json the excludes are still present 
![image](https://user-images.githubusercontent.com/11361623/55167210-ce400580-5170-11e9-9431-bcbc39dc65cd.png)

**Comment by domi1kenobi** [comment]
the folder was created after adding the first exclusion via settings was located on top in the explorer 
![image](https://user-images.githubusercontent.com/11361623/55167293-f891c300-5170-11e9-8531-5fe3275db757.png)

**Comment by lbogdan** [comment]
Hey @domi1kenobi ,

It might be a bit confusing, but that VSCode "Watcher Exclude" setting has nothing to do with `nodemon` that's running inside the container. To configure `nodemon` to exclude files from watching, just follow [its configuration documentation](https://github.com/remy/nodemon#config-files).

**Comment by domi1kenobi** [comment]
@lbogdan thanks a lot mate - was really on the wrong track here. You may close this.

**Comment by lbogdan** [comment]
You're welcome! I agree that we certainly need better server sandboxes documentation, hopefully that'll come soon-ish!
