### ISSUE TITLE
codesandbox.io -  homepage - display problem

### ISSUE THREAD

**Issue by MarcoEscaleira** [CompuIves/codesandbox-client#1668]
# 🐛 bug report

### My environment
| Android          | 8.0.0 |

[1 - print](https://ibb.co/K0QGQfy)
[2 - print](https://ibb.co/j3wV5Yk)

**Comment by SaraVieira** [comment]
Added le flex wrap and it does fix it :D 
https://github.com/CompuIves/codesandbox-client/commit/2908c8c3ee09e91c0b9b7091479118b11670d216
