### ISSUE TITLE
Code snippets

### ISSUE THREAD

**Issue by tenjojeremy** [CompuIves/codesandbox-client#1670]
# 🌈 Feature

Ability to create file with code snippets 

Just how VSCode handles them by using a 

VSCode

**Comment by CompuIves** [comment]
Hey! Do you mean creating a new file from a snippet? Right now we support user snippets like VSCode, you can access it by selecting "Configure User Snippet..." in the quick opener.

**Comment by tenjojeremy** [comment]
Okay, found it.

Great job with the project, thanks!

**Comment by SaraVieira** [comment]
Awesome!!

Gonna close as the feature already exists :)

Feel free to reopen with any issues
