### ISSUE TITLE
Share-link for test view no longer opens tests

### ISSUE THREAD

**Issue by tony19** [CompuIves/codesandbox-client#1672]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?
I'm trying to share a link that opens the test view automatically. This used to work, but not sure exactly when it stopped (recent). Right now, it just opens the browser preview.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  `PROD-1553897973-43cec9c83` |
| Browser |  Chrome 73 |
| Operating System | macOS Mojave 10.14.2 |

**Comment by CompuIves** [comment]
Oh hmm, that's indeed weird. I'll try to fix it today. In the meantime you can drag the tests tab to be before the browser tab to make it the default. This way you don't have to change the url to show it.
