### ISSUE TITLE
Prettier config export alongside project

### ISSUE THREAD

**Issue by farskid** [CompuIves/codesandbox-client#1676]
# 🌈 Feature

When the project is exported, if prettier has been configured as well, the prettier config also is exported with the project.

Click on the Export button -> Export whole project -> if Prettier is configured, export `.prettierrc` as well.

I tried to dig into the codebase and find where the export service is implemented, but no luck yet.
Would love to do it and send a PR. just need a hint where to start.

**Comment by farskid** [comment]
@SaraVieira Any hint where I could start adding this?

**Comment by SaraVieira** [comment]
Hey!

Not really :(

We also have the same issue with gitignore, it needs some fixing :(

**Comment by farskid** [comment]
Oh :( I'll try more to dig into this. I'll keep this issue posted.

**Comment by SaraVieira** [comment]
It should be here: https://github.com/codesandbox/codesandbox-importers

And not in the main project I think

**Comment by farskid** [comment]
My latest export does contain .prettier config and .gitignore file. Apparently, .gitignore is only generated once you connect the sandbox to a git repo. .prettierrc is also generated once you enable it from the settings.
Closing this.

**Comment by SaraVieira** [comment]
oh yay!
