### ISSUE TITLE
React Snippets

### ISSUE THREAD

**Issue by SimaAmini** [CompuIves/codesandbox-client#1677]
# 🐛 bug report

## Description
I created a new react project and couldn't use react snippets like cc or imrc. I'm getting these errors in the console. TypeError and 422 error .

`TypeError: Cannot read property 'setAsyncMode' of undefined`

<img width="818" alt="codesandbox" src="https://user-images.githubusercontent.com/12030102/55285013-c1512b00-5397-11e9-92b2-c8b9f487974b.png">

| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1553897973-43cec9c83
| Browser | Chrome 73.0.3683.86
| Operating System | Windows 8.1

**Comment by CompuIves** [comment]
Hey! Did you install the React snippets? We don't preinstall them currently, but that would actually be a good idea.

**Comment by SaraVieira** [comment]
Hey!

Yeah, that error is unrelated, if you want to use snippets for now you need to create you own like this:

https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets

And you can copy the react snippets file
https://github.com/xabikos/vscode-react/blob/master/snippets/snippets.json

'm also gonna close as that is not something we have installed, please reopen if you have any issues creating them
