### ISSUE TITLE
Sandbox imported from Github shows wrong template

### ISSUE THREAD

**Issue by pandemm** [CompuIves/codesandbox-client#168]
After importing a sandbox from Github, the left side pane displays create-react-app as template. As sandboxes imported from Github can't be directly based on template sandboxes, I think the template field should be hidden.
![cra](https://user-images.githubusercontent.com/10899207/29998701-9ae749bc-903a-11e7-96d8-ada9513066ce.PNG)

**Comment by CompuIves** [comment]
This one has been fixed.
