### ISSUE TITLE
FileName not changed on Sandbox name change from sidebar

### ISSUE THREAD

**Issue by farskid** [CompuIves/codesandbox-client#1680]
# 🐛 bug report

## Description of the problem
When changing the name of the Sandbox from the left sidebar, it's expected that the name on top of the Sandbox change as well.

## How has this issue affected you? What are you trying to accomplish?
I changed the name of the Sandbox on the left sidebar, but the name on top of the Editor didn't change at the same time. Refreshing fixes this.

## Screenshot

<img width="975" alt="Screenshot 2019-04-01 at 2 48 40" src="https://user-images.githubusercontent.com/8332043/55296932-f9547e80-5428-11e9-926a-bf5e7fd83fb0.png">

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1553897973-43cec9c83
| Browser | Chrome 73.0.3683.86 (Official Build) (64-bit)
| Operating System | MacOS Mojave

**Comment by samrith-s** [comment]
If no one is taking this, can I pick this up?

**Comment by farskid** [comment]
@samrith-s Go ahead from my side!

**Comment by SaraVieira** [comment]
@farskid I am on this now and I don't know how to react

**Comment by SaraVieira** [comment]
It's in this file @samrith-s https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/pages/Sandbox/Editor/Header/CollectionInfo/index.js

**Comment by farskid** [comment]
@SaraVieira Oh! That's why I said from my side :) I'm truly sorry for the hassle Sara and I don't know what to do now :(

**Comment by samrith-s** [comment]
@SaraVieira Thanks! I'll create a PR soon-ish. Still cloning the fork. 😭
