### ISSUE TITLE
Explore Codesendbox: Second picked sandbox doesn't open

### ISSUE THREAD

**Issue by tinahir** [CompuIves/codesandbox-client#1699]
# 🐛 bug report
In explore codesendbox, second picked sandbox opens first picked sandbox

## Description of the problem
1. Open [https://codesandbox.io/explore](https://codesandbox.io/explore)
2. Select any sandbox
3. Close the current sandbox
4. Open any sandbox except previous selected
5. It will show previous selected sandbox
6. This bug is also is reproduce in left and right navigation of sandbox

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/827497/55458121-b00f5500-5609-11e9-87fc-f0eb5dcb726e.gif)

## How has this issue affected you? What are you trying to accomplish?
Try to open second codesendboc in popup.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  Current version
| Browser | Chrome 73
| Operating System |  macOS Mojave

**Comment by tinahir** [comment]
Can I working on this issue?

**Comment by tinahir** [comment]
I am working on this bug

**Comment by SaraVieira** [comment]
Closed by #1715
