### ISSUE TITLE
ReferenceError in preview panel when running next.js app

### ISSUE THREAD

**Issue by olavgu** [CompuIves/codesandbox-client#1707]
# 🐛 bug report

## Description of the problem
In the preview panel, I get the error message "ReferenceError: dll_7aff549c98b978433226 is not defined". Upon refreshing the browser, the page preview flashes quickly, then is replaced with the error message. The problem started when I tried to add emotion as a dependency, but that could might as well be a coincidence. 
## How has this issue affected you? What are you trying to accomplish?
Not able to preview my page.
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)
| Operating System | Mac OS Mojave 10.14

**Comment by CompuIves** [comment]
Heya! It seems like this is an issue with `next`, what happens when you restart the sandbox?

**Comment by olavgu** [comment]
That fixed it 👍 Thanks, I had no idea you could do a restart!
