### ISSUE TITLE
Option/Alt for menu takes focus away from editor

### ISSUE THREAD

**Issue by fnky** [CompuIves/codesandbox-client#1712]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

When pressing Option/Alt to focus the menubar, while in an editor it will take away the focus when pressing Option/Alt once. This conflicts with moving the cursor by word—using Option/Alt + arrow keys.

A way to solve this could be to make it a preference to enable/disable focus the menubar in settings.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1554195707-bfa032269
| Browser | Chrome 73.0.3683.86
| Operating System | macOS Mojave (10.14.3)

**Comment by CompuIves** [comment]
Hey! This is a very valid request. I'm generating a new VSCode build with the option to disable it.

**Comment by SaraVieira** [comment]
We generated a new build and this should now be available :)
