### ISSUE TITLE
Instruction to add a new template point to 404 files

### ISSUE THREAD

**Issue by RomainLanz** [CompuIves/codesandbox-client#1725]
# ❔ Question

The information provided in the [contributor documentation](https://github.com/CompuIves/codesandbox-client/blob/master/contributor-docs/adding-template.md) (under **App**) are wrong.

The links point to non-existing file (probably moved) or others repository.

**Comment by SaraVieira** [comment]
Hey!

Thank you for pointing it out. Fixed here: https://github.com/CompuIves/codesandbox-client/commit/9d3eef2923b37423cd459abe8dbf7351128de6ac

 :)

**Comment by SaraVieira** [comment]
For an example or container templates look at this PR: https://github.com/CompuIves/codesandbox-client/pull/1684

Also has this PR: https://github.com/codesandbox/codesandbox-importers/pull/32

Ping me on twitter at @nikkitaFTW if you have any issues
