### ISSUE TITLE
Allow choosing a dependency version without removing it

### ISSUE THREAD

**Issue by kitze** [CompuIves/codesandbox-client#1730]
# 🌈 Feature

When clicking the version of a dependency it should show a dropdown and the user should be able to switch a version without removing the dependency and adding the new version.

**Comment by SaraVieira** [comment]
Nifty new github feature

Shame button:
![Screenshot 2019-04-05 at 17 48 44](https://user-images.githubusercontent.com/1051509/55640036-15f70a80-57cb-11e9-9aaf-63b199dc6a14.png)

**Comment by CompuIves** [comment]
This is a really good feature request. I'm thinking that we should show a subtle chevron next to the version, opening clicking the version turns into a dropdown. We can use the Algolia API to find possible versions.

**Comment by kitze** [comment]
> Nifty new github feature
> 
> Shame button:
> ![Screenshot 2019-04-05 at 17 48 44](https://user-images.githubusercontent.com/1051509/55640036-15f70a80-57cb-11e9-9aaf-63b199dc6a14.png)

Yeah I thought the comments will remain but then they disappeared and it looked really stupid without them.

@CompuIves yup, exactly!

**Comment by ValentinH** [comment]
If this is the version you are mentioning, there is already a chevron on the right of the version to expand the row and show the sizes:
![image](https://user-images.githubusercontent.com/2678610/55652162-05ef2300-57eb-11e9-9ef7-4a2d2fdc3b3c.png)
