### ISSUE TITLE
Invariant Violation Target container is not a DOM element in private CRA2 projects

### ISSUE THREAD

**Issue by cristiano-belloni** [CompuIves/codesandbox-client#1737]
# 🐛 bug report

## Description of the problem
All my private sandboxes (and only the private ones) created with Create React App v2 fail with the `Invariant Violation Target container is not a DOM element.` exception. Public one work; I actually tried a working public one and set it private, without changing the code, and it stopped working with the aforementioned error (here's the now-private one: https://codesandbox.io/s/qv84lx1kz4)

## How has this issue affected you? What are you trying to accomplish?
Working with private sandboxes is not possible anymore

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1552372285-96510b09
| Browser | 73.0.3683.86
| Operating System | Mac OS Mojave 10.14.2

**Comment by sebas5384** [comment]
For me all my sandboxes are failing with React create app, but after saving a file it works again 😕

**Comment by CompuIves** [comment]
Sorry for the inconvenience! The fix for this should be live now.
