### ISSUE TITLE
🐛 Adding an additional main file fails to load Sandbox

### ISSUE THREAD

**Issue by dance2die** [CompuIves/codesandbox-client#1739]
# 🐛 bug report

## Description of the problem

For [this Sandbox](https://codesandbox.io/s/jl2qpjn795), I've added an additional file to `main` property within `package.json` file.

`package.json`

```json
{
  ...
  "main": ["index.js", "useCallbackDemo.js"],
  ...
}
```

Doing so **_auto_** reloaded the whole page & started displaying following loading screen with following error page (without loading the sandbox).

> BaseController.js:224 Uncaught TypeError: e.startsWith is not a function
    at Object.t.absolute (path.js:111)
    at t.default.getEntries (template.js:77)
    at t.default.getDefaultOpenedFiles (template.js:95)
    at c (main-module.js:29)
    at Object.wa [as function] (actions.js:138)
    at e.value (FunctionTree.js:98)
    at executeTree.js:77
    at r.executeBranchWrapper (FunctionTree.js:247)
    at t (executeTree.js:13)
    at n (executeTree.js:15)

![error](https://user-images.githubusercontent.com/8465237/55662767-b9084e00-57e4-11e9-9143-255b29552e4c.png)

And I can't seem to get it loading at this point.

## How has this issue affected you? What are you trying to accomplish?

I've tried to create two main entry points and the sandbox has failed to load, thus inaccessible to the source code.

###  Link to sandbox

https://codesandbox.io/s/jl2qpjn795

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1554491263-be5b09e5c
| Browser | Version 73.0.3683.103 (Official Build) (64-bit)
| Windows 10 | Version 1803 (OS Build 17134.648)
| Ubuntu | 18.10

The same error/misbehaviors occur on latest version of Windows 10 & Ubuntu 18.10

## ➕ Addtional Context

Following is the sandbox title, `React Hooks Dependency? and or OR?`.

![sandbox in question](https://user-images.githubusercontent.com/8465237/55662815-21efc600-57e5-11e9-9b1d-1b8556a126d1.png)

**Comment by CompuIves** [comment]
Very good one! I made the `main` file resolvement more robust, the fix will be live in ~20 min.
