### ISSUE TITLE
Google fonts are loaded as <script> instead of <link>

### ISSUE THREAD

**Issue by lbogdan** [CompuIves/codesandbox-client#174]
![](https://i.imgur.com/ta37mjS.png)
![](https://i.imgur.com/3PTpZEX.png)

**Comment by CompuIves** [comment]
Ooh good one, logic for this resides here: https://github.com/CompuIves/codesandbox-client/blob/master/src/sandbox/external-resources.js.

Maybe we should either do a manual check, or do a preflight request to find out the `Content Type`?

**Comment by lbogdan** [comment]
It would be nice if the API could figure out the type when you add a resource (even return an error if it's neither JS, nor CSS), and return it. I don't know about the backwards compatibility, though.

**Comment by tansongyang** [comment]
I'm interested in working on this.

It seems like you could just use a `HEAD` request and then check the returned `Content-Type`. Example pseudocode:

```JavaScript
function addResource(resource: string) {
  const match = resource.match(/\.([^.]*)$/);

  if (match && match[1] === 'css') {
    addCSS(resource);
  } else if (match && match[1] === 'js') {
    addJS(resource);
  } else {
    head(resource).then((response) => {
      // Check reponse
      if (contentType(response) === 'text/css') {
        addCSS(resource)
      } else {
        addJS(resource);
      }
    }).catch((e) => {
      // Should we log an error?
      addJS(resource)
    })
  }
}
```

Some questions:

1. Does calling code expect `addResource` to be synchronous?
2. Is there a standard way of doing resource fetching in this project?

**Comment by CompuIves** [comment]
That's really great @tansongyang! Your proposal sounds great.

Answering the questions:

1. addResource can be asynchronous, everything in the sandbox itself is executed in an asynchronous manner
2. For the sandbox we don't have a standard way of fetching, mostly to keep the bundle size low. I'd use `window.fetch` to fetch the resource.

I think we should log the error using `console.error`, mostly developers use CodeSandbox and maybe they can include it in the bug report when they occur this.

**Comment by tansongyang** [comment]
@CompuIves OK. One possible issue with `fetch` is that it isn't supported in IE11. Are you OK with codesandbox not supporting IE11?

**Comment by CompuIves** [comment]
@tansongyang No problem! We polyfill fetch, so it should also work on IE11.

**Comment by lbogdan** [comment]
Maybe also check for javascript `Content-Type` and error otherwise?

**Comment by CompuIves** [comment]
Sounds good, throwing an error is the best way. This way we can notify the
developer that a external resource isn't available.

**Comment by tansongyang** [comment]
Sounds good. I'll post here when I have a PR.

**Comment by tansongyang** [comment]
Made PR. See the comments and commit messages for more details.

**Comment by eschafer** [comment]
As a workaround, it looks like you can just add '.css' to the end of the url and it'll work: https://fonts.googleapis.com/css?family=Roboto:400,700.css

**Comment by mrchief** [comment]
Same thing happens with Material icons: https://fonts.googleapis.com/icon?family=Material+Icons. ANd adding `.css` to the URL doesn't work.

**Comment by eschafer** [comment]
If you add the weight, it works:
https://fonts.googleapis.com/icon?family=Material+Icons:400.css

**Comment by lbogdan** [comment]
Closing this as we can now load scripts and style-sheets from `index.html`.
