### ISSUE TITLE
selected file isn't  readable in light themes

### ISSUE THREAD

**Issue by Haroenv** [CompuIves/codesandbox-client#1752]
# 🐛 bug report

## Description of the problem

Using the Visual Studio Light theme, the text of the selected file is in white, instead of a more correct color (probably dark grey)

## How has this issue affected you? What are you trying to accomplish?

<img width="263" alt="Screenshot 2019-04-10 at 09 56 35" src="https://user-images.githubusercontent.com/6270048/55861792-6da0c780-5b77-11e9-9c57-d4ab849a8a79.png">

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1554569576-d688a852f
| Browser | Safari Technology Preview Release 78 (Safari 12.2, WebKit 14608.1.9.1)
| Operating System |MacOS Mojave 10.14.1 (18B75)

**Comment by SaraVieira** [comment]
Damn, so close to fixing all the issues with the white themes

Will pick this up tomorrow
