### ISSUE TITLE
New Homepage

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#176]
Coming week I want to put effort in building the new homepage. This homepage will be built using Next, so we can retain our SEO.

The main focus points of this homepage will be:

1. New, more compelling design with headline of 3d flying cubes
  a. Show search bar as well, if users want to search
2. Special view for logged in users
  a. Show sandboxes of user
  b. Show templates (upcoming feature) of user
3. Change our slogan to "Online editor tailored for web application development"
4. Show all templates
5. Show our actual features
  a. Bundling/Transpiling done for you + templates
  b. NPM Support
  c. VSCode (Monaco) editor online
  d. Github/CLI importing
  e. Embedding
  f. Discoverability, search
 g. Patron features
  h. Error suggestions
6. Maybe show popular sandboxes?

We need to give the feeling that this will be a new stage for CodeSandbox: we're expanding from React and will actually show what features we have. A lot of features are still unknown for the majority of our users.

**Comment by Hum4n01d** [comment]
This will be great; it's a bit frustrating to have to click on *Seach for a Sandbox*, my username, profile, *then* find the sandbox I'm looking for. My current solution is to use a bookmark to my profile and go from there.

**Comment by Hum4n01d** [comment]
I could add a link to the user's profile on the homepage, should I do this? Maybe an embed of your most recent project? (This would obviously be temporary but I think it's worth it)

**Comment by CompuIves** [comment]
I started working on this a couple days ago @Hum4n01d. I'm planning to finish it by next week, so I don't think it would be worth the trouble 🙂 .

**Comment by Hum4n01d** [comment]
Ok, great! Great work on the console btw

**Comment by CompuIves** [comment]
I think we can close this one, to allow more specific issues about the homepage.
