### ISSUE TITLE
bundler does not correctly use inline loaders of dependencies raw-loader example

### ISSUE THREAD

**Issue by desean1625** [CompuIves/codesandbox-client#1784]
# 🐛 bug report

## Description of the problem
Attempting to load dependency that uses the !raw-loader!./worker.js to and create a blob for to load the worker

The worker script is [object object] instead of the expected 
```js
this.postMessage("Hello From Worker");
```
## How has this issue affected you? What are you trying to accomplish?
I am trying to load worker scripts from dependencies
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1555328876-ca84dd686
| Browser | Version 73.0.3683.75 (Official Build) Built on Ubuntu , (64-bit)
| Operating System | running on Ubuntu 18.04

**Comment by CompuIves** [comment]
Very sharp! Thanks for the easy reproducible, I've pinpointed the issue. The fix should go live today!

**Comment by desean1625** [comment]
Looks good! Cheers.
