### ISSUE TITLE
Styled Components Unexpected Behavior

### ISSUE THREAD

**Issue by alexvcasillas** [CompuIves/codesandbox-client#179]
Hi there, @CompuIves !
I'm opening this issue as we spoke at Twitter about the unexpected behavior we've been experiencing at CodeSandbox Client with Animated Styled Components.

**Unexpected Behavior**
I drop you here a link to the [Video](https://www.dropbox.com/s/9b6mnzt617yu43t/Animated%20Styled%20Components%20CodeSandbox%20Unexpected%20Behavior.webm?dl=0) to better showcase the unexpected behavior.

**Expected Behavior**
And here is the [Video](https://www.dropbox.com/s/4wjkxjleqqmi8ye/Animated%20Styled%20Components%20Expected%20Behavior.webm?dl=0) of the expected behavior while testing at a local environment.

At CodeSanbox, the components are not getting animated nor the animations are being triggered.

Hope we could find a solution together : )

**Comment by Tushkiz** [comment]
whoever looks into it, here is the link to the sandbox https://codesandbox.io/s/x7nxpw700z

**Comment by alexvcasillas** [comment]
Oh, can't believe I forgot to put a link to the sandbox 😱 
Thanks @Tushkiz !!

**Comment by CompuIves** [comment]
Just tested, this will be fixed with https://github.com/CompuIves/codesandbox-client/pull/225 :D

**Comment by alexvcasillas** [comment]
Awesome!! Wich was the bug causing this? I'm curious 🤔

**Comment by CompuIves** [comment]
Heh, I'm not really sure. I've rewritten the dependency handling and this seemed to work after that 😅 . I have a hunch that it could've been related to a cyclic dependency in styled-components, but not sure.

**Comment by alexvcasillas** [comment]
Haha!
It's awesome anyway that this is fully working ! Keep up with the awesome job you're doing with this project !!
