### ISSUE TITLE
Dependency search not finding the correct module

### ISSUE THREAD

**Issue by michals2** [CompuIves/codesandbox-client#1791]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

- I'm trying to import 2 very common dependencies (`styled-components` and `react-virtualized`)
- When I click on _Add Dependency_, I search for these modules
- Other similar dependencies show up, but not the ones I'm looking for

<img width="613" alt="Screen Shot 2019-04-20 at 8 48 08 AM" src="https://user-images.githubusercontent.com/16494852/56459475-10f89600-6349-11e9-8941-ebbe8cbb3fbf.png">

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | |
| Browser | Chrome |
| Operating System | Mac |

Love the product though!

**Comment by dance2die** [comment]
Same error here. I can't seem to find react-/redux...

software | name/version
-- | --
CodeSandbox | PROD-1555328876-ca84dd686
Browser | Chrome & FireFox
OS | Windows 10 & Ubuntu 18.10


![error demo](https://user-images.githubusercontent.com/8465237/56464850-e85fb300-63bf-11e9-83e1-b6339c5f1d1c.gif)

**Comment by CompuIves** [comment]
Hey! It seems like something went wrong with the Algolia index. But everything is back to normal now!

I was going to suggest that you can 'circumvent' the issue by just pressing enter when you entered the name of the dependency, we'll manually add it to the `package.json`. In case this could occur again!

**Comment by dance2die** [comment]
Thank you @CompuIves.
It works great now.
