### ISSUE TITLE
Missing NPM modules in dependencies search?

### ISSUE THREAD

**Issue by neptunian** [CompuIves/codesandbox-client#1792]
I used to be able to create examples using 'react-photo-gallery' library.  But now when I search to add it as a dependency it isn't there.  What determines this?

**Comment by CompuIves** [comment]
Hey! It seems like something went wrong with the Algolia index. But everything is back to normal now!

I was going to suggest that you can 'circumvent' the issue by just pressing enter when you entered the name of the dependency, we'll manually add it to the `package.json`. In case this could occur again!
