### ISSUE TITLE
Integrated console

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#18]
A console you can expand from the editor pane, should work both in embed view and editor view.

![screen shot 2017-06-07 at 13 33 53](https://user-images.githubusercontent.com/587016/26876373-2cabf6da-4b86-11e7-886a-cee27e6db8e9.png)

**Comment by CompuIves** [comment]
This will be integrated using a custom renderer, issue is here: https://github.com/CompuIves/codesandbox-client/issues/31

**Comment by CompuIves** [comment]
Decided that this will not be done by the custom renderer, this functionality is global.

**Comment by renanpvaz** [comment]
I'd like to help if possible. Do you already have an idea of how this should this be done? In which context should this console execute?

**Comment by lbogdan** [comment]
@renanpvaz Do you want to take this? I already started playing with it, I only got some layout going, no functionality. Let me know, so we don't both work on the same feature. :smile:

**Comment by renanpvaz** [comment]
@lbogdan oh don't mind me, if you've started it then keep it up.

**Comment by Hum4n01d** [comment]
+1 Yes please!

**Comment by varenya** [comment]
is someone still working on this? If any help needed would love to contribute :)

**Comment by lbogdan** [comment]
@varenya You can find the work so far here https://github.com/lbogdan/codesandbox-client/tree/feature/preview-console, if you want to take a look.

**Comment by varenya** [comment]
sure thanks, should I fork this branch repo to contribute? is any help needed :)?

**Comment by CompuIves** [comment]
Ooh, I hope nothing bad! @lbogdan built an implementation, I need to check
it out. I've been a bit busy as well, but I'm going to check and work on it
tomorrow 😃

**Comment by varenya** [comment]
@lbogdan you have used react-console here and it looks to be working what else is pending here? 
@CompuIves any inputs let me know I can help.

**Comment by CompuIves** [comment]
Great to hear that it works! There are 2 things pending (I think):

1. Bit of styling, I want to play with this a bit
2. Right now the console executes code in the editor environment. I think
we should execute it in the sandbox environment so you can inspect eg.
window vars. So we should send a postMessage to the sandbox, execute it
there and postMessage back to the console what to show. Are you interesting
in working on this?

**Comment by varenya** [comment]
No, I just checked he's doing it in Preview/index.js, basically what you just said postMessage and then switching based on the type and logging it on the react-console.

**Comment by CompuIves** [comment]
Oh that's great!! Didn't know @lbogdan already finished that. Then the only
thing left is styling really, I'll can finish that tomorrow then.

**Comment by lbogdan** [comment]
@CompuIves I didn't, the evaluation part is not done yet. For this we should also change `react-console`, which is currently doing the evaluation internally. So **2.** is still pending.

**Comment by varenya** [comment]
@lbogdan what do you mean by eval? but the flow is as @CompuIves mentioned right i.e. postMessage etc..

**Comment by lbogdan** [comment]
I mean when you write something in the console and it evals and displays it:
![](https://i.imgur.com/GRbaM6X.png)
In this example, it should evaluate it in the sandbox preview context and show `href: "http://localhost:3001/"`.

**Comment by varenya** [comment]
hmm understood but any ideas how to go abt it?

**Comment by Hum4n01d** [comment]
You could look at the applicable JSBin code; they do it quite nicely

**Comment by varenya** [comment]
yeah, but they don't need to maintain preview context like in this case. And they are not using iframes either. let me see thanks for your inputs.

**Comment by varenya** [comment]
Can somebody help me with high-level overview of the project as in how parts are connected so that I can hack on it faster?

**Comment by CompuIves** [comment]
I just deployed the new console with this https://github.com/CompuIves/codesandbox-client/pull/266.

I'm sorry for the silence @varenya, I already started working on the styling and thought that it would be quicker to quickly move the eval to the sandbox with it. I hope I'm not discouraging you from any further contributions to CodeSandbox. You can join our Discord (https://discord.gg/KE3TbEZ) if you want a quicker answer or to chat about ideas 😄 .

**Comment by Hum4n01d** [comment]
I just noticed this! Great job on the console @CompuIves

**Comment by Hum4n01d** [comment]
It's really nice to have the errors printed out there since the computer I'm currently using doesn't have access to the dev tools :(

**Comment by IAMtheIAM** [comment]
It would be great if we could have this console open by default on our codesandboxes, right now it's "click to open"
