### ISSUE TITLE
Current Module View does not transpile before viewing

### ISSUE THREAD

**Issue by TrevorSayre** [CompuIves/codesandbox-client#183]
When switching to `Current Module View` and then looking at a module file, the following error is presented:

```
Error
Component.js hasn't been transpiled yet.
```

This can be bypassed by modifying and saving the file.

![](https://media.giphy.com/media/3ohhwD7jI4j4lkss9y/giphy.gif)

Also, if you press the refresh button in the preview area, you can get duplicate render:

![image](https://user-images.githubusercontent.com/421548/30083062-0d998994-925b-11e7-899a-72530a83c705.png)

**Comment by CompuIves** [comment]
Fixed with https://github.com/CompuIves/codesandbox-client/pull/187!
