### ISSUE TITLE
Feature Request: Link to enable Current Module View

### ISSUE THREAD

**Issue by TrevorSayre** [CompuIves/codesandbox-client#188]
When I link to a project, it would help our interview process to have it open in Current Module View instead of Project View.

Perhaps:
* `https://codesandbox.io/s/30r9pxq5zq?view=module`
* `https://codesandbox.io/s/30r9pxq5zq?view=project`

**Comment by CompuIves** [comment]
We have this already in the current version :smile:. You can find it when you click on 'Share' in the editor, for your example: https://codesandbox.io/s/30r9pxq5zq?moduleview=1.

**Comment by TrevorSayre** [comment]
@CompuIves I just now updated the post 😂
