### ISSUE TITLE
Issues with prettier

### ISSUE THREAD

**Issue by varunkumar** [CompuIves/codesandbox-client#19]
I am getting the below error when I try to start a local instance
```
Error in ./~/prettier/src/parser-typescript.js
Module not found: Error: Can't resolve 'fs' in '/home/varunkumar/tmp/codesandbox-client/node_modules/prettier/src'
 @ ./~/prettier/src/parser-typescript.js 1:17303-17316
 @ ./~/prettier/index.js
 @ ./src/app/utils/codemirror/prettify.js
 @ ./src/app/components/sandbox/CodeEditor/index.js
 @ ./src/embed/components/Content.js
 @ ./src/embed/App.js
 @ ./src/embed/index.js
 @ multi react-hot-loader/patch webpack-dev-server/client?/ webpack/hot/only-dev-server ./config/polyfills.js ./src/embed/index.js

Error in ./~/prettier/src/parser-typescript.js
Module not found: Error: Can't resolve 'module' in '/home/varunkumar/tmp/codesandbox-client/node_modules/prettier/src'
 @ ./~/prettier/src/parser-typescript.js 1:17457-17474
 @ ./~/prettier/index.js
 @ ./src/app/utils/codemirror/prettify.js
 @ ./src/app/components/sandbox/CodeEditor/index.js
 @ ./src/embed/components/Content.js
 @ ./src/embed/App.js
 @ ./src/embed/index.js
 @ multi react-hot-loader/patch webpack-dev-server/client?/ webpack/hot/only-dev-server ./config/polyfills.js ./src/embed/index.js
```
The instance is coming up fine though. Issue seems to be similar to https://github.com/prettier/prettier/issues/986

**Comment by CompuIves** [comment]
Thanks for reporting this! It seems related to the issue you mentioned, I'll take a look at it today.

**Comment by donavon** [comment]
Yes, I get that too. I ignored it for now. :)

**Comment by harbin1053020115** [comment]
It seems the problem still exists.

`
Failed to compile.

Error in ./node_modules/_prettier@1.5.2@prettier/parser-typescript.js
Module not found: Error: Can't resolve 'fs' in '/Users/zhangermin/Project/alibaba/github/react-ide/codesandbox-client/node_modules/_prettier@1.5.2@prettier'
 @ ./node_modules/_prettier@1.5.2@prettier/parser-typescript.js 1:17883-17896
 @ ./node_modules/_prettier@1.5.2@prettier/index.js
 @ ./src/app/utils/codemirror/prettify.js
 @ ./src/app/components/sandbox/CodeEditor/index.js
 @ ./src/embed/components/Content.js
 @ ./src/embed/App.js
 @ ./src/embed/index.js
 @ multi react-hot-loader/patch webpack-dev-server/client?/ webpack/hot/only-dev-server ./config/polyfills.js ./src/embed/index.js

Error in ./node_modules/_prettier@1.5.2@prettier/parser-typescript.js
Module not found: Error: Can't resolve 'module' in '/Users/zhangermin/Project/alibaba/github/react-ide/codesandbox-client/node_modules/_prettier@1.5.2@prettier'
 @ ./node_modules/_prettier@1.5.2@prettier/parser-typescript.js 1:18037-18054
 @ ./node_modules/_prettier@1.5.2@prettier/index.js
 @ ./src/app/utils/codemirror/prettify.js
 @ ./src/app/components/sandbox/CodeEditor/index.js
 @ ./src/embed/components/Content.js
 @ ./src/embed/App.js
 @ ./src/embed/index.js
 @ multi react-hot-loader/patch webpack-dev-server/client?/ webpack/hot/only-dev-server ./config/polyfills.js ./src/embed/index.js
`

**Comment by zhhyang** [comment]
+1

**Comment by CompuIves** [comment]
I 'fixed' the issue by mocking `module` and `fs`. I'll look into replacing the `./~/prettier/src/parser-typescript.js` later, but this will do for now 🙂.
