### ISSUE TITLE
Add emmet support

### ISSUE THREAD

**Issue by kenyk7** [CompuIves/codesandbox-client#194]

**Comment by lbogdan** [comment]
There is already support for emmet in the (default) Monaco editor, you can access it with Ctrl+F10.
![](https://i.imgur.com/UjJY8BL.png)

**Comment by kenyk7** [comment]
You can change the keys to use the key tab :)

**Comment by CompuIves** [comment]
Initially I tried binding it to the Tab character, but it overrode the existing behaviour (eg. autocomplete). Maybe there is a way to retain existing functionality and add emmet behind the Tab press, we need to look into this. Would be possible if we can call the functionality behind Tab manually.

**Comment by viankakrisna** [comment]
Ctrl+E would be the alternative, at least on sublime

**Comment by kenyk7** [comment]
For css or sass: Ctrl + F10  it works badly :(

**Comment by HamedPour** [comment]
Hi Van, have to agree with kenyk7 there. I've been trying to us use Ctrl+F10 but its exceptionally cumbersome. Which is a shame coz I really like codesandbox. I'd be much happier with something that can be done with one hand. Crtl + E or even Ctrl + Alt + A  etc

**Comment by CompuIves** [comment]
I completely agree, this is too cumbersome right now. I'll experiment with CTRL+E/CMD+E a bit!

**Comment by CompuIves** [comment]
Some updates on this! I've been experimenting a bit and got it working with Tab, will deploy that today. It only works for HTML now, but I'm working on an vscode like implementation:

![screen shot 2018-02-18 at 16 44 43](https://user-images.githubusercontent.com/587016/36354024-76157f64-14ce-11e8-8928-798d24dc4adb.png)

**Comment by dfsq** [comment]
However Emmer seems to have stopped working for anything else but HTML. For example in JSX I'm no longer able to use abbreviations, nor in CSS.

**Comment by CompuIves** [comment]
I'll deploy the old functionality for in JSX as well to fix that!

**Comment by lbogdan** [comment]
@CompuIves Is this deployed?

**Comment by CompuIves** [comment]
Deployed!

**Comment by cloud-walker** [comment]
Emmet keybinding is broken until last release, pressing `cmd + E` it opens the find component instead 🙈

**Comment by CompuIves** [comment]
This probably happened because of our move to the new Monaco. The functionality is still there, it just needs to be connected again. Reopened the issue for this!

**Comment by satyarohith** [comment]
@CompuIves I'm interested! anything helpful to look into? :)

**Comment by CompuIves** [comment]
Emmet is back!

**Comment by splodingsocks** [comment]
I can't seem to get it to work with either ctrl-e or command-e (editing an HTML file). And control-F10 isn't possible to test on my current keyboard :D, any tips?

**Comment by CompuIves** [comment]
Ahh, it seems like I haven't enabled it in the HTML templates yet. I'll enable that either this or next week with the new VSCode deploy.

**Comment by splodingsocks** [comment]
Thanks!

**Comment by samsch** [comment]
ctrl-e also doesn't work in js(x) contexts, though it will expand with tab if it recognizes an html element name. Meaning emmet doesn't work at all for React components right now.

**Comment by pamcy** [comment]
Anything new this week?  Without emmet tab function is really painful :(

**Comment by quangv** [comment]
Assuming Emmet isn't working atm on Monaco?
