### ISSUE TITLE
Meta Language support in .vue files

### ISSUE THREAD

**Issue by TheJaredWilcurt** [CompuIves/codesandbox-client#199]
https://vuejs.org/v2/guide/single-file-components.html

One feature of Vue is to allow for metalanguage support, such as:

* Markdown, Pug, HAML
* TypeScript, JSX, CoffeeScript
* Sass, SCSS, Less, Stylus

I should be able to write this and have it work:

```
<style lang="sass">
h1
    background: #F00
    border: 2px solid #00F

.thing
    display: inline-block
    padding: 10px
    .stuff
        margin: 30px
</style>
```

**Comment by CompuIves** [comment]
I believe this should already work for TypeScript, Sass, SCSS, Less and Stylus. Which language didn't work for you?

**Comment by CompuIves** [comment]
Ahh, I understand what's happening. We only supported the `scss` syntax, let me write a fix for `sass`.

**Comment by CompuIves** [comment]
Just deployed!

https://codesandbox.io/s/zq613qp63p?module=%2FApp.vue

**Comment by TheJaredWilcurt** [comment]
This is the best day ever!

**Comment by zephraph** [comment]
I know this is closed, but I can't seem to get pug working. Should I open a new ticket for this?

**Comment by shreeve** [comment]
Check out #1467 - CoffeeScript support for vue-cli template
