### ISSUE TITLE
Infer dependencies with new imports

### ISSUE THREAD

**Issue by jsonnull** [CompuIves/codesandbox-client#208]
This is an idea I had for an enhancement. When there's a module import which is not yet a dependency, prompt the user to allow the dependency to be added automatically.

For instance, if I type this line into the default React sandbox:

```import { createStore } from 'redux'```

A dialog may appear which says something along the lines of "Unrecognized module `redux`. Would you like to add this to the project's dependencies?"

I picture this working with up to multiple dependencies at once.

Some scenarios where this could be really great:
 - *Pastes:* With this, a ton of snippets become runnable very quickly with just a copy and paste!
 - *New users:* If you haven't used codesandbox before, you may not know to review dependencies—this makes that feature much more accessible

**Comment by CompuIves** [comment]
Hey! We do have the suggestion to install dependencies already when they're missing:

![screen shot 2017-09-27 at 11 55 58](https://user-images.githubusercontent.com/587016/30907446-eff9de44-a37a-11e7-9bac-800575d2e8cc.png)

Buuut, we only support this for 1 dependency at a time, would be really helpful if we could show 1 error message for all dependencies immediately. We do already have a list of all missing dependencies after all.

**Comment by jsonnull** [comment]
Wow, I missed that somehow. Do you have to refresh the page to see the error? I only saw the error reported in devtools.

**Comment by CompuIves** [comment]
Hmmm, then that must've been a bug! I've seen this before, need to investigate it.

**Comment by jsonnull** [comment]
@CompuIves let me know if you are able to find steps to reproduce, I'm happy to send a PR with a fix.

**Comment by CompuIves** [comment]
@jsonnull Just found how to reproduce it!

If you load a sandbox, you need to make an error before the sandbox has been loaded (eg. `throw new Error('awdaw')`). The error will throw before the react-error-overlay has been ejected which causes it to get in an inconsistent state (at least that's my theory). We inject the error overlay in `src/sandbox/compile.js`.

**Comment by jsonnull** [comment]
I've tried and failed to get the error you found, but it's not happening for me.

This may be unrelated: when introducing a syntax error, the transpiler produces an error but there's a failure in the `ModuleError` class.

```Error.captureStackTrace is not a function```

It looks like this is what's used to report syntax errors by the transpiler but these just result in a white screen for me because the app is unable to gracefully recover from this error state.

Perhaps a try/catch around Error.captureStackTrace and fall back to normal stack reporting? It may even be possible with some string manipulation to preserve the cleaner errors.

**Comment by CompuIves** [comment]
This one should be fixed I believe. We fixed the `Error.captureStackTrace` but forgot to close this!

**Comment by jsonnull** [comment]
Great to hear @CompuIves, hope you're doing well!
