### ISSUE TITLE
Do Not Track warning on embed

### ISSUE THREAD

**Issue by NikxDa** [CompuIves/codesandbox-client#209]
CodeSandbox doesn't seem to comply with the browsers DNT-settings, and Medium will prevent a direct embed:

![screen shot 2017-09-27 at 11 07 38](https://user-images.githubusercontent.com/3141005/30905134-3c7e4522-a374-11e7-9422-27edcea6a3bd.png)

The privacy policy however says:
> We honor Do Not Track signals and Do Not Track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place.

Can this be fixed, or does this happen on purpose?

**Comment by CompuIves** [comment]
Wow, I've never seen this before. We should definitely fix this. Which browser are you using @NikxDa?

**Comment by NikxDa** [comment]
I'm on macOS, and I use Chrome `Version 61.0.3163.100 (Official Build) (64-bit)` - should you need any help with this, feel free to contact me!

**Comment by martenbjork** [comment]
Same on Chrome 63.0.3239.108.

**Comment by lbogdan** [comment]
@NikxDa , @martenbjork Do you still have this issue? If yes, can you give us an URL where this happens?

**Comment by CompuIves** [comment]
I found out that Medium does this for all embeds, regardless of their DNT policies. Nowadays we do follow DNT policies and disable Google Analytics when we detect that DNT is enabled. So I think this one can be closed 😄.
