### ISSUE TITLE
Internal routing capabilities

### ISSUE THREAD

**Issue by alansouzati** [CompuIves/codesandbox-client#217]
Using this codesandbox as an example [https://codesandbox.io/s/r0wXp0Njw](https://codesandbox.io/s/r0wXp0Njw) it would be great to have a way that we can open the simulated browser in a specific page. For example: navigating to `https://codesandbox.io/s/r0wXp0Njw/about` would open the codesandbox in edit mode with that view. The closest I got was to use `https://r0wxp0njw.codesandbox.io/about` which definitely helps, but having the source code available would be great.

**Comment by alansouzati** [comment]
Also it would be great if we could open the view in a specific folder. I don't know how to do that in a clean way though 😢 

Maybe something like?

`https://codesandbox.io/s/r0wXp0Njw/about?view=components/about.js`

**Comment by alansouzati** [comment]
or keep the two arguments as a query param: `https://codesandbox.io/s/r0wXp0Njw?r=/about&v=components/about.js`

**Comment by CompuIves** [comment]
Hey! I believe we support this already, though it's hidden away. If you open the Share modal in the header you can select these options, example:

https://codesandbox.io/s/r0wXp0Njw?initialpath=%2Fabout&module=%2Fcomponents%2FAbout.js

**Comment by alansouzati** [comment]
Thank you!!! I will try this ;)

**Comment by alansouzati** [comment]
hey @CompuIves how you doing? 😄 

Is the `module` param still working? I cannot get this URL to open in the Button module.

https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=button&module=%2FButton.js

**Comment by alansouzati** [comment]
never mind we need src now.

https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=button&module=%2Fsrc%2FButton.js
