### ISSUE TITLE
Empty (non-framework) template for JavaScript and TypeScript

### ISSUE THREAD

**Issue by niieani** [CompuIves/codesandbox-client#219]
Hey @CompuIves. Again, awesome work with CodeSandbox!

It would be great if we could have an empty (non-react/non-framework) templates for both plain JavaScript and TypeScript. I often just want to try out or share pure data-based JavaScript, like RxJS concepts and I don't need any visual representation for that, yet CodeSandbox is great for this use case too. Even better, perhaps the View part in such cases could be replaced with a visual `console.log`.

Cheers!
Bazyli

**Comment by CompuIves** [comment]
A vanilla template sounds very appealing! The big question is what we should include in this template in terms of webpack loaders, maybe we should just add everything and turn them on dynamically, but I don't want this template to be a catch-all template...

This is some tricky situation, would love to discuss this more.

Regarding the console, we have support for it very 🔜  thanks to the work of @lbogdan 😄 .

**Comment by niieani** [comment]
Hmm, I propose to have these two rows of big button choices when creating a new sandbox.

Select your framework:
- react (default)
- preact
- ... (whatever other framework)
- empty project

Select your language/transpiler:
- JavaScript + Babel (default)
- TypeScript
- Reason
- ... (whatever other transpiler)

And lastly, you'd have a tick box/button:
- Customize

and that last option would allow one to customize the config, turn on/off loaders, as needed.

**Comment by CompuIves** [comment]
Ooooh I like this! Will think some more about this.

**Comment by CompuIves** [comment]
We can close this with the vanilla template 😄
