### ISSUE TITLE
Could not find 'history'

### ISSUE THREAD

**Issue by pshrmn** [CompuIves/codesandbox-client#22]
Currently, CodeSandbox fails to import the [`history`](https://www.npmjs.com/package/history) package even if it is an imported dependency.

Demo: https://codesandbox.io/s/wpRWxgNxz

This is not an issue for projects that have implicit `history` dependencies, such as React Router v4 (https://codesandbox.io/s/r0wXp0Njw).

**Comment by pshrmn** [comment]
As a slight expansion on this, the issue does not occur when importing from specific modules within the `history` package (https://codesandbox.io/s/qx8Ey6lry).

```js
// fails
import { createBrowserHistory } from 'history';
// works
import createBrowserHistory from 'history/createBrowserHistory';
```

I had also created a temporary fork of `history` called `tmp-history` and that fails as well for imports from `tmp-history` but works for imports from `tmp-history/___`.

The `manifest.json` file from @jsdelivr does not contain a `./history` external entry like it does for the other imports. I cannot find any source for how jsdelivr generates the manifest, so it is difficult to say why this is happening.

If it was only `history` having this problem, I would have guessed that there was some strange interference with `window.history`, but since `tmp-history` is also affected, that doesn't really make sense. `tmp-history` _is_ a fork of `history`, so that would lean towards it being an issue with how the packages are structured, but they had worked previously, so I'm not really sure why that would be the case either.

**Comment by CompuIves** [comment]
Thanks a lot for the clarification @pshrmn, the issue was that `history` didn't have a `main` entry in its `package.json`. Thanks to the fix of @christianalfoni [here](https://github.com/cerebral/webpack-packager/pull/18) we now default to a main of `index.js` if none is specified.

**Comment by pshrmn** [comment]
Thanks! That sounds like the type of problem that I would have spent way too much time looking in the wrong places for a solution for. I just opened a PR in the `history` package, so at least one less package will soon have this issue.

**Comment by CompuIves** [comment]
Ah that's great to hear!
