### ISSUE TITLE
TypeScript errors on local module imports

### ISSUE THREAD

**Issue by danielearwicker** [CompuIves/codesandbox-client#220]
First - thank you for the TypeScript support, it's a wonderful thing.

One thing I noticed, which you may be able to see replicated here:

https://codesandbox.io/s/j40262x8zy

Certain module imports show an error `Cannot find module` with red underline. I have created ones called `model.ts`, `sierpinski.ts` and `Painter.tsx`. For some reason the import of `./model` in `index` is fine, but several others show the error.

**Comment by Xananax** [comment]
Same for me, even on a freshly created project

![image](https://user-images.githubusercontent.com/836082/32027365-487734d6-b9f1-11e7-92fd-7531b0c8f43e.png)

**Comment by CompuIves** [comment]
Thanks for reporting this! I'm getting the same. I think we need to refresh all Monaco models after loading once to give them full context. I'll make sure to check it this week.

**Comment by CompuIves** [comment]
This was a nasty bug, took me a while to figure out what it was 😅 .

So Monaco drops definition of files if they aren't touched for a while, this means that you cannot find the module anymore. The temporary solution is to add the files as dependencies and update them as soon as you switch from files. I'm going to deploy it now.

**Comment by NoahBres** [comment]
Hi. Sorry for resurfacing this old issue but I seem to be experiencing the same issue. However, the code seems to run fine. The editor just displays the error. Thanks for your time!

![screenshot from 2018-10-27 22-09-55](https://user-images.githubusercontent.com/6739076/47611508-0f52b300-da35-11e8-970e-3722dd16d54d.png)

**Comment by CompuIves** [comment]
Oh man, seems like it comes back in some race conditions. I have half the mind to not show type definitions when not all type files have been loaded yet just to keep TypeScript from throwing errors prematurely. This will probably be fixed when we go fully to VSCode, in the meantime I'll try to find an alternative!

**Comment by KingHenne** [comment]
I noticed the errors as well and they disappeared when I switched to VSCode.

**Comment by foisonocean** [comment]
Same issue here. I suggest reopen this issue since "use VSCode" isn't the default behavior.
