### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by aarongarciah** [CompuIves/codesandbox-client#221]
Would be nice to have a CONTRIBUTING.md in this repository.

**Comment by Tushkiz** [comment]
@CompuIves @lbogdan I will create an initial draft and raise a PR out of it.

**Comment by CompuIves** [comment]
That's great @Tushkiz, I see that this is very important.

**Comment by CompuIves** [comment]
Done, thanks @Tushkiz!
