### ISSUE TITLE
Add possibility to change hotkeys keymap. 

### ISSUE THREAD

**Issue by RIP21** [CompuIves/codesandbox-client#222]
Hi @CompuIves 
I here to propose a nice and very convenient change.
Since it uses VS Code editor, it also uses its default keymap. It's amazing for VS Code users. But for guys who are move from Webstorm, Sublime etc. is a little pain :) 
Can you add an option to change keymap from the list of default ones like Sublime, Webstorm, Atom etc. (basically those which have such plugins in VS Code marketplace)
Thanks a lot for your amazing work!

**Comment by Piterden** [comment]
It is better to have an ability to edit keymap config, if it is possible. As I know, for the Codemirror you can edit a keymap.

**Comment by liuderchi** [comment]
looks like the logic of adding keymap lies in here [app/components/CodeEditor/CodeMirror/index.js#L261](https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/components/CodeEditor/CodeMirror/index.js#L261)

**Comment by SaraVieira** [comment]
Hey!

As we jumped completely to VSCode thus can now be done in their UI: https://code.visualstudio.com/docs/getstarted/keybindings and just copy from the extension you wish.
Example for sublime: https://github.com/Microsoft/vscode-sublime-keybindings/blob/master/package.json#L57

We will in the future allow a user to add extensions but for now I think this covers most issues faced here

Feel free to reopen if you think opposite :)
