### ISSUE TITLE
Embed throws errors to console when editing or switching views

### ISSUE THREAD

**Issue by malwilley** [CompuIves/codesandbox-client#226]
This can be seen on the homepage or any direct link to an embed, [this one for example](https://codesandbox.io/embed/vue). While editing or switching views, it throws errors to the console:

![image](https://user-images.githubusercontent.com/10888943/31368191-270b5128-ad4a-11e7-8b1d-01cf690d0ded.png)

I poked around a bit and found that the CodeEditor component isn't being called with all the necessary props. Adding `corrections={[]}` seems to be enough to fix it (I assume corrections is not used for embed?). It is also missing a couple other required props but those don't result in any bugs. Running the flow typechecker gives nearly 900 errors :grimacing: 

Would you accept a PR to fix this issue? And perhaps some other typing errors?

**Comment by CompuIves** [comment]
Thanks for reporting this! Your suggested solution is good, would be really great if you could open a PR for it. Man I'm really ashamed if how Flow is handled right now, it's a mess...

**Comment by lbogdan** [comment]
Maybe we should do a "fix flow" hackathon, as we did with "fix eslint"! (I have to admit I got a bit discouraged after fixing hundreds of eslint errors :smile:)
