### ISSUE TITLE
Homepage crashes tab

### ISSUE THREAD

**Issue by qm3ster** [CompuIves/codesandbox-client#230]
[codesandbox.io](//codesandbox.io) crashes the physical tab in seconds. There are also these in the console, not that they are remotely related to the crashing or anything:
[codesandbox.io-1507668111866.log](https://github.com/CompuIves/codesandbox-client/files/1373389/codesandbox.io-1507668111866.log)
To me this type of crash only ever happened when loading too much local files, at around 1.2GB.
The browser is Chromium 61.0.3163.100 on Ubuntu, nothing esoteric.

**Comment by CompuIves** [comment]
This is big, thanks for the headsup. I'm lowering the embed count for the homepage to make it manageable.
