### ISSUE TITLE
Infinite loop protection

### ISSUE THREAD

**Issue by kanoshin** [CompuIves/codesandbox-client#241]
Recently I was running interview of React Frontend Engineer with help of codesanbox and Skype screen share. Accidently the guy wrote infinite loop and Chrome tab became unresponsive. Also candidate was not saving his edits during the interview, so we lost everything. 

We tried to open Chrome Dev Tools to stop scripts execution, but it didn't help to copy existing code to different place because tab was still frozen. Why?

**Comment by CompuIves** [comment]
This is a serious issue, we need to detect endless loops and give the option to stop them. I already opened an issue for it here: https://github.com/CompuIves/codesandbox-client/issues/50. I'll give this more priority now, see if I can find a fix today.

**Comment by OnkelTem** [comment]
So what am I supposed to do if my box went into some loop and never stops?
I spent 7 hours on creating it and now I cannot do anything.
