### ISSUE TITLE
Internal server error when trying to import from GitHub

### ISSUE THREAD

**Issue by maple3142** [CompuIves/codesandbox-client#244]
[https://codesandbox.io/s/github/maple3142/WynnStats/](https://codesandbox.io/s/github/maple3142/WynnStats/)
[https://codesandbox.io/api/v1/sandboxes/github/maple3142/WynnStats/](https://codesandbox.io/api/v1/sandboxes/github/maple3142/WynnStats/)
I still cannot import my project

**Comment by CompuIves** [comment]
I'll check this out later today, we need to propagate more clear errors to the user.

**Comment by alansouzati** [comment]
I'm facing the exact same issue with `path is not defined`.

Here is my repo: https://github.com/alansouzati/test-codesandbox

It has the exact same structure/api as a `create-react-app`. I've added npm scripts that matches their api: `npm run start`, `npm run build`. The webpack dev server runs in the same port.

The reason I'm not using create-react-app is that I wanted to add a simple babel plugin for Grommet and just for that simple reason I'm being forced to eject my entire app.

It would be great if you can describe the steps required to sync Github to Codesandbox without using `create-react-app`.

**Comment by alansouzati** [comment]
this issue seems to be fixed now!

**Comment by divyanshu013** [comment]
Hi @CompuIves, facing the same internal server error. Any clues? Here is the github path https://github.com/appbaseio/reactivesearch/tree/dev/site

Also tried another app built with cra but facing the same issue https://github.com/appbaseio-apps/booksearch

Thanks!

**Comment by CompuIves** [comment]
Thanks for letting me know! I fixed the error, could you try again?

**Comment by divyanshu013** [comment]
Thank you Ives, works now :smile:

**Comment by lbogdan** [comment]
Closing as fixed.
