### ISSUE TITLE
Error fetching data the sandbox via Github Import: No dependencies in package.json

### ISSUE THREAD

**Issue by artivilla** [CompuIves/codesandbox-client#247]
Ref Repo: https://github.com/ianstormtaylor/is-hotkey

<img width="743" alt="screen shot 2017-10-16 at 12 05 29 pm" src="https://user-images.githubusercontent.com/2120159/31622801-67129c92-b26b-11e7-8ff6-89f0bf7c6197.png">

**Comment by CompuIves** [comment]
This one got fixed 😄
