### ISSUE TITLE
DependencyNotFoundError for installed dependency

### ISSUE THREAD

**Issue by jfsiii** [CompuIves/codesandbox-client#250]
https://codesandbox.io/s/3r5jz2n8pm shows

```
DependencyNotFoundError
Could not find dependency: 'react-map-gl'
```

even though `react-map-gl` is installed. I've tried re-installing, refreshing and everything else I can think of, but it still fails.

FWIW, this same code fails (with a different error) on stackblitz.com. I opened an issue there https://github.com/stackblitz/core/issues/173 and [apparently](https://github.com/stackblitz/core/issues/173#issuecomment-337059552) it's due to `mapbox-gl`'s dynamic `require`s. 

Perhaps the same issue is causing this error?

**Comment by EricSimons** [comment]
Wow, I'm actually surprised that the server-side bundler CSB is using didn't actually fix this either. That must be one gnarly package. As I mentioned in the issue on the SB repo, you might wanna run the create-react-app template on Glitch for the time being and see if it works there: https://glitch.com/edit/#!/create-react-app-sample

**Comment by CompuIves** [comment]
Indeed very interesting! Seems like Webpack has trouble resolving the file in that case as well. I'm curious if our new packager is capable of loading the package, I'm not at my MacBook right now but I'll tell tomorrow!

**Comment by EricSimons** [comment]
@CompuIves I actually just tried and it didn't work (different errors coming back than the webpack bundler though). Did some additional digging on the StackBlitz end & it looks like the culprit package is really https://github.com/browserify/webworkify; there's some pretty intense stuff going on in there 😓

**Comment by CompuIves** [comment]
It seems like we fixed it in the meantime 😄!

Closing...
