### ISSUE TITLE
Export to GitHub

### ISSUE THREAD

**Issue by Hum4n01d** [CompuIves/codesandbox-client#256]
It would be very useful to be able to export directly to GitHub from CodeSandbox. 

On a side note, thank you so much for CodeSandbox. It is such an **amazing** app and makes React development from the web so much easier.

**Comment by CompuIves** [comment]
Thanks @Hum4n01d! 😄 .

I'm working on it currently, using this issue as reference: https://github.com/CompuIves/codesandbox-client/issues/204. I'll close this one so we can move the discussion to there.

**Comment by phyninja** [comment]
Hey @CompuIves I'm having problems when I export a codesandbox project to github. 
I get this error:
*.default is not a constructor
![screen shot 2017-12-30 at 9 36 29 pm](https://user-images.githubusercontent.com/10854442/34459296-9668e464-eda9-11e7-8bef-0ec7661dc002.png)
 Could you please suggest ways of fixing this?

**Comment by Hum4n01d** [comment]
This doesn't look like an issue with codesanbox, you could ask in reactiflux.com
