### ISSUE TITLE
Add the GPL notice to the LICENSE file

### ISSUE THREAD

**Issue by bakednevada** [CompuIves/codesandbox-client#257]
Github doesn't recognize the project as GPLv3.  It unfortunately looks for specific text in LICENSE files.  The example in the "How to Apply These Terms to Your New Programs" section of http://www.gnu.org/licenses/gpl-3.0.html should suffice:

```
    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

**Comment by CompuIves** [comment]
Thanks! Changed it, but it seems like GitHub still can't infer the license 🤔

**Comment by bakednevada** [comment]
Hmm I wonder i the entire license needs to be included.  https://github.com/andrewngu/sound-redux/blob/master/LICENSE from a project GitHub recognizes as GPL v3

**Comment by SaraVieira** [comment]
Closed as this license is already implemented https://github.com/CompuIves/codesandbox-client/blob/master/LICENSE
