### ISSUE TITLE
Cursor keys not working on iPad

### ISSUE THREAD

**Issue by ksmth** [CompuIves/codesandbox-client#260]
I just tried navigating the code with the cursor keys with my attached Logitech Slim Combo keyboard and they plain don’t work. All other fields respond correctly (say, the description, etc.), but the editor ignores them.

**Comment by CompuIves** [comment]
Ah, good one @ksmth. I think this could be related to the Monaco editor not working with touch screen devices.

What happens if you use CodeMirror instead? (Preferences -> Code Editor -> Use CodeMirror)

**Comment by ksmth** [comment]
Hey @compulves! Thanks for the tip, I’ll try it when I get a chance. You’re right in that it is related to the monaco  editor. I can’t find it right now, but there is an open issue and the repository mentioning that the iPad external keyboard isn’t working, the reason being that mobile Safari doesn’t trigger the right keyboard events, it’s only triggering selection change events.

 I’ll report back once I have tried code mirror

**Comment by ksmth** [comment]
Yes, it is fixed by using CodeMirror instead, I’ve just checked it out and it works like a charm. ☺️

**Comment by CompuIves** [comment]
Great! Then I'll add a check to check for mobile safari and enable CodeMirror by default for mobile safari.

**Comment by noodlemind** [comment]
I believe this is still an issue. I am trying to use it on the ipad pro and doesn't seem to be working.
