### ISSUE TITLE
Add chat on discord in navigation menu

### ISSUE THREAD

**Issue by chakrihacker** [CompuIves/codesandbox-client#275]
I am thinking to add chat on discord link in navigation bar, so users can come to discord and discuss about issues. I am also thinking to remove feed back button and replace with chat on discord. This may increase user engagement. please throw your thoughts @CompuIves , @lbogdan

**Comment by CompuIves** [comment]
I agree, the feedback button is a lot of manual work for me and it's starting to get cumbersome. Would be good to replace it with something like Discord.
