### ISSUE TITLE
[Editor] Prettify and Save buttons - browser inconsistencies

### ISSUE THREAD

**Issue by taylorham** [CompuIves/codesandbox-client#277]
First off: I'm a big fan. I've wanted to create something like CodeSandbox ever since I started working with React, and you (and the community) have done a *stellar* job putting this together and adding features I didn't even think were possible.

Thank you **_so much_** for building this and keeping it open source. I hope to give back somehow!

On to my issue...

---

### IN CHROME:
The blue buttons in the editor pane header (`Prettify` and `Save`) aren't functioning and there are no console errors.

**Steps to Reproduce:**
1. Open Google Chrome
1. Go to [this sandbox](https://codesandbox.io/s/93onqlx62p) (default, just with no newlines)
1. Click the `Prettify` button (nothing happens)
1. Change some text in the file
1. Click the `Save` button next to the `Prettify` button (nothing happens)

### IN SAFARI:
`Save` works, but `Prettify` doesn't

**Steps to Reproduce:**
1. Open Safari
1. Go to [this sandbox](https://codesandbox.io/s/93onqlx62p) (default, just with no newlines)
1. Click the `Prettify` button (nothing happens)
1. Change some text in the file
1. Click the `Save` button next to the `Prettify` button (saves successfully!)

### IN FIREFOX:
Both buttons work!

**Steps to Reproduce:**
1. Open Firefox
1. Go to [this sandbox](https://codesandbox.io/s/93onqlx62p) (default, just with no newlines)
1. Click the `Prettify` button (Prettier runs successfully!)
1. Change some text in the file
1. Click the `Save` button next to the `Prettify` button (saves successfully!)

To be clear, the `Save` button in the main page header works just fine. I don't have any way to test IE/Edge right now so someone else should look into those if possible.

I can take a look at this tonight or sometime this weekend if you need some help ironing it out!

**Comment by CompuIves** [comment]
Wow, this detailed description is great! I can take a look at what's happening the coming week, maybe it's related to our recent Webpack changes (I remember something weird with ModuleConcatenationPlugin and Prettier) 🤔 .

**Comment by ValentinH** [comment]
I have tried to reproduce on Safari 11.0 and Chrome 61 and both buttons are working fine here.

On Chrome:
![prettify-chrome](https://user-images.githubusercontent.com/2678610/32692464-bc4c7e6e-c718-11e7-91eb-ac84425e4a50.gif)

On Safari:
![pretify-safari](https://user-images.githubusercontent.com/2678610/32692467-c13c776c-c718-11e7-9eb5-221424472d98.gif)

**Comment by taylorham** [comment]
Well I'll be damned.

It's still not working in my normal Chrome window but it *does* work in an Incognito tab. I must have some extension messing with functionality.

I also just checked it in Safari and was suddenly able to both format and save without issue or delay.

Looks like I didn't dig deep enough before reporting, and this issue can probably be closed since it appears to be an extension issue in Chrome.

If anyone else comes across this and can test in their local browsers, I'd love to feel less crazy!

**Comment by Haroenv** [comment]
Yep, I can prettify now but couldn't earlier in november

**Comment by taylorham** [comment]
Pretty sure this one's safe to close. I haven't been able to replicate it since opening the issue.
