### ISSUE TITLE
Support github dependencies in npm

### ISSUE THREAD

**Issue by goodmind** [CompuIves/codesandbox-client#278]
How would I install dependency from github, npm supports this, but I can't do this in codesandbox

**Comment by CompuIves** [comment]
Ah, yes I haven't tested this fully. I can work on this the coming week 😄

**Comment by goodmind** [comment]
It can't install from master?

**Comment by CompuIves** [comment]
Hey! Do you have an example sandbox? It works for me.

**Comment by washingtonsteven** [comment]
Hi, has this been pushed to http://codesandbox.io or is it only available in a self-hosted client? I am trying to import http://github.com/washingtonsteven/react-json-component@0.1.0 and getting an error.

Sandbox: https://codesandbox.io/s/pwlxp2yj8j

**Comment by CompuIves** [comment]
Hey Steven, I believe that it should be specified differently in
package.json to work. I forked it and made the change and it works for me
now: https://codesandbox.io/s/1810xvpqyj.

**Comment by washingtonsteven** [comment]
Oh I see, I was using the Add Dependency button and having trouble there. Thanks!

**Comment by yairopro** [comment]
Would be great to be able to add the branch|tag|commit like this: 
userName / repo **#branch**

**Comment by AurelReb** [comment]
up, any chance to add the branch|tag|commit like this:
userName / repo #branch 
?

**Comment by mikefrancis** [comment]
Further to the above, is there a way to specify a path too for monorepos?
