### ISSUE TITLE
Prettify prettifies .json as .js

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#285]
It seems like we don't properly check for file type when giving a file to prettier, it makes JSON files invalid.

I think we need to change the code here:

https://github.com/CompuIves/codesandbox-client/blob/master/src/app/components/sandbox/CodeEditor/Monaco.js#L885-L892

Is someone interested in looking at this?

**Comment by ValentinH** [comment]
I'm on it.
