### ISSUE TITLE
No longer works in Safari

### ISSUE THREAD

**Issue by OllieJennings** [CompuIves/codesandbox-client#291]
You can no longer view a personal Sandbox in Safari.

Error:

[Error] SyntaxError: Cannot declare a let variable twice: 't'. (monaco-linter.f7fe4c09abe3764fa812.worker.js, line 3656)

**Comment by CompuIves** [comment]
Hey @OllieJennings, thanks for reporting this (important) issue! On which page do you get this error, with which version? I tried to replicate the error, but I can't seem to get it.

**Comment by ValentinH** [comment]
Yes, I also tried it with version 11.0 and everything looks fine.

**Comment by OllieJennings** [comment]
Hi @CompuIves, so l only get this on the Sandbox page, nothing else.

I am on Safari 10 (haven't upgraded to MacOS High Serria just yet)

**Comment by macklinu** [comment]
When I open Safari 10.1.1 (on MacOS version 10.12.5) and visit https://codesandbox.io/s/new (can be signed in with GitHub or not, both result in the following error):

![image](https://user-images.githubusercontent.com/2344137/32956311-6c2d9fd6-cb86-11e7-93fd-e6d2c5073db4.png)

```
[Error] SyntaxError: Cannot declare a let variable twice: 't'. (monaco-linter.d66bfae515c2f3dae3da.worker.js, line 3668)
```

The latest commit in this repo is https://github.com/CompuIves/codesandbox-client/commit/b2a64ad2d0c7d8f6e7181c778ec149010dea8a56 at the time of this comment, so I'm guessing that's the build deployed to codesandbox.io? Not 100% sure, but hoping that helps with debugging. I tried to get more information from the Safari console but wasn't sure how to debug this exact error in the browser.

**Comment by OllieJennings** [comment]
@CompuIves , @macklinu  This is the exact error am getting as well.

**Comment by CompuIves** [comment]
Ahh I found the issue! It's related to this: https://github.com/mishoo/UglifyJS2/issues/1753. I'll make a deployment with the fix now.
