### ISSUE TITLE
.css-files not loaded with preact-cli

### ISSUE THREAD

**Issue by vedam** [CompuIves/codesandbox-client#299]
hey all,
first of thx for this really easy way of fast prototyping.
I created a fast test-case for an issue I had during local development with loading .css-files in preact-cli:
https://codesandbox.io/s/k05nxn4jxv

I asked for help at [preact slack](https://preact.slack.com/archives/C3M9NTD16/p1510818546000247)

and Jason Miller noticed:
https://preact.slack.com/archives/C3M9NTD16/p1510881541000061

Maybe you would like to have a look at it?

**Comment by CompuIves** [comment]
Thanks for reporting this! I'm fixing it now.
