### ISSUE TITLE
Unable to click on React cube 

### ISSUE THREAD

**Issue by ayusharma** [CompuIves/codesandbox-client#301]
<img width="1280" alt="screen shot 2017-11-18 at 1 30 21 pm" src="https://user-images.githubusercontent.com/6918450/32978278-e0820546-cc64-11e7-9545-4c1c11b572ed.png">

React cube get displace outside of the screen on the right side.

**Comment by CompuIves** [comment]
Thanks for the report @ayusharma! I'll fix this somewhere in the coming week.

**Comment by lbogdan** [comment]
Fixed in #360 .
