### ISSUE TITLE
Remove `position: relative` from body tag in sandbox

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#303]
We add a `position: relative` to the body tag to measure its size. This pollutes the sandbox and it's better if we find another way to do this.

**Comment by tlrmlr** [comment]
Would love to see this changed!

**Comment by CompuIves** [comment]
Yes absolutely, I think we should just remove the whole size listener from the sandbox (which adds the relative).

So we use the size listener to measure the size of the sandbox for eg. auto sizing Medium posts, however it seems like it pollutes the sandbox. I'm curious if there's a way to find the size of the content without any body changes.

**Comment by CompuIves** [comment]
Fixed in master, will be deployed either this evening or tomorrow morning.
