### ISSUE TITLE
Creating a github repository for our sandbox silently renames and replaces files that include underscores (_) which breaks it

### ISSUE THREAD

**Issue by pfftdammitchris** [CompuIves/codesandbox-client#305]
As I was reading on the new github feature I went ahead and created a new repository on my github for my sandbox and it silently renamed one of my files **JSR_Toolbar.js** to JSRToolbar.js.

This throws an error for me and I would have to manually change the filename back to JSR_Toolbar.js for my project to work. I was then forced to refresh the page because it was giving an error that I had to pass in a valid react component to be rendered. 

This is not a big of a deal but I can assume that a large project with many file names with underscores would become a nightmare to "migrate".

Screenshot:

![github_codesandbox](https://user-images.githubusercontent.com/20717348/32994711-f1580eea-cd1f-11e7-8070-bb6b9098281e.PNG)

**Comment by CompuIves** [comment]
This is a very good report, I know exactly what cases this issue. Thanks!

I'll fix that this evening.
