### ISSUE TITLE
Support for different syntax highlighting themes

### ISSUE THREAD

**Issue by pfftdammitchris** [CompuIves/codesandbox-client#306]
It would be great to have different syntax highlighting themes.
The current theme is a little rough on the eyes

**Comment by Piterden** [comment]
Would be great to have ability to upload own theme in `tmTheme` and other popular formats.

**Comment by Haroenv** [comment]
#359 is a subset of this AFAICT

**Comment by Haroenv** [comment]
This can be closed too now @CompuIves

**Comment by CompuIves** [comment]
Whoop!
