### ISSUE TITLE
package-lock.json is not checked into git

### ISSUE THREAD

**Issue by nagamalli9999** [CompuIves/codesandbox-client#312]
package-lock.json is generated whenever we do some npm related operations. If it is not checked into the git, it always pops up in the git's untracked files. we can either check it into git or add it to .gitignore if there is a reason to not check it in

**Comment by chakrihacker** [comment]
Yes, But codesandbox is using ***yarn.lock***, so it can be safely ignored

**Comment by CompuIves** [comment]
Yep, that's right. We don't use `package-lock.json` but use `yarn.lock`. I've added `package-lock.json` to the `.gitignore`.
