### ISSUE TITLE
Achieve "true" HMR

### ISSUE THREAD

**Issue by lbogdan** [CompuIves/codesandbox-client#313]
Right now, whenever you change a file, the sandbox app gets re-evaluated, which re-initialises all app state. It would be very nice to have HMR support with the same [API as Webpack](https://webpack.github.io/docs/hot-module-replacement.html), so that we can leverage existing HMR loaders for React, Vue etc.

**Comment by CompuIves** [comment]
Yes! Okay, from what I know we should take this approach:

The `Manager` class should get an extra map for tracking all hot-reloading callbacks. Key = path, value = callback. We should add a global called `module.hot` before evaluation, with `accept` function that takes path+callback and adds it to the extra map.

So every time we start evaluation we first check if the hot module map is > 0. If it is we start a new flow.

When we evaluate we normally delete the `compiled` cache for the changed module and all modules that depend on it. We still go through this flow, but we need to stop going through parents when we encounter a module that has a `module.hot.accept`. Furthermore we need to call all callbacks of the changed modules after evaluation.

I think it's something like this? I just typed what came to mind, it's definitely not finished but a good start I think.
