### ISSUE TITLE
[feature request] Support env variables

### ISSUE THREAD

**Issue by Andarist** [CompuIves/codesandbox-client#314]
It would be cool to support env variables, they could be defined in a file like CRA does it.

**Comment by CompuIves** [comment]
Good one!

**Comment by CompuIves** [comment]
This has been deployed 😄 . You can now define environment variables in a `.env` file.

**Comment by Andarist** [comment]
wow, this is great!

**Comment by Pyrolistical** [comment]
would have been useful if it were added here
<img width="243" alt="screen shot 2018-06-12 at 1 53 34 pm" src="https://user-images.githubusercontent.com/463642/41316754-0cf1f296-6e48-11e8-93fd-e2947d43658d.png">

**Comment by HunderlineK** [comment]
What if my env variable is my db password? Anyway to hide it? >~<

**Comment by Andarist** [comment]
Codesandbox is useful for developing frontend applications - you should never store urs db password on frontend

**Comment by Pyrolistical** [comment]
@HunderlineK proxy your database calls in a https://github.com/zeit/micro on https://zeit.co
