### ISSUE TITLE
Broken on FF 57

### ISSUE THREAD

**Issue by eschaefer** [CompuIves/codesandbox-client#319]
ServiceWorker error on FF57 makes CodeSandBox unusable on that browser. Seems like a pretty critical issue.

URL: https://codesandbox.io/s/j4w5orx8yw

Click any of the JS files in the filetree, and nothing responds.

<img width="1168" alt="screen shot 2017-11-22 at 16 40 11" src="https://user-images.githubusercontent.com/547148/33135850-e0604036-cfa3-11e7-974e-41139fd5594e.png">

**Comment by eschaefer** [comment]
Apologies, the site does work with μBlock disabled. The service worker error persists, but doesn't break the UX.

**Comment by lbogdan** [comment]
@eschaefer Can you please provide a stack trace?
