### ISSUE TITLE
[feature request] Honour NODE_PATH in package.json

### ISSUE THREAD

**Issue by JikkuJose** [CompuIves/codesandbox-client#320]
Please consider honouring `NODE_PATH` in package.json. For instance:

```js
  "scripts": {
    "start": "NODE_PATH=src react-scripts start",
    "build": "NODE_PATH=src react-scripts build",
    "test": "NODE_PATH=src react-scripts test --env=jsdom",
    "eject": "NODE_PATH=src react-scripts eject"
  }
```

Then, things like this:

`import "../../../../../../../../library/NavBar.js"`

will become:

`import "library/NavBar.js"`

**Comment by CompuIves** [comment]
We can combine this issue with https://github.com/CompuIves/codesandbox-client/issues/314. Our bundler already supports multiple `modulesDirectories` like webpack does, so the biggest thing to add here is environment variable support.

Parsing the `package.json` can be a bit tricky, and we need to check which templates support the `.env` file, but other than that this can be a pretty straightforward implementation.
