### ISSUE TITLE
Add support for atomic css

### ISSUE THREAD

**Issue by VinSpee** [CompuIves/codesandbox-client#324]
Hi!

Loving codesandbox. Game changer.

I've been following the [Atomic CSS methodology](http://acss.io/) lately and would love to see it enabled in codesandbox. 

There are several ways to implement it, most commonly, via the [webpack loader](https://github.com/acss-io/webpack-atomizer-loader), but could likely be handled in a c-r-a fashion by doing something like [this](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc) with the [atomizer cli](https://github.com/acss-io/atomizer#api). Thoughts?

**Comment by Piterden** [comment]
What is the difference between atomic CSS and direct style setting in the HTML attribute?

**Comment by VinSpee** [comment]
A bit out of scope for this request, but here’s a fantastic post about the merits that rebuts many arguments - I liked specifically to the section about inline styles:

http://cssmojo.com/a-retort-to-reuse-on-maintainablecss/#it-says-classred-is-the-same-as-stylecolor

>- style is more specific (1,0,0,0 versus 0,0,1,0)
>- style does not have room for abstraction (fallbacks, tweaks, ltr/rtl support, etc.)
>- style creates more bytes in HTML (you can abbreviate classes, not declarations)
>- style cannot be used to apply contextual styling, nor to style element state, etc.
>- style cannot do media queries
>- declarations associated to style are not cached, while declarations in style sheets are cached.

**Comment by CompuIves** [comment]
Interesting, I like the idea Atomic CSS.

I'd love to implement Atomic CSS in CodeSandbox, I want to combine this with sass/less support for React. The main idea with this is that we should eject CRA and add the given options manually, the question is how we can do this with the most simple/easy UX. I'm open for suggestions on this 😄.

**Comment by VinSpee** [comment]
I think it’d have to go in the sandbox sidebar under its own expandable, right? I’ll try to put together a concept in a PR to get the ball rolling (on the UI side of things at least)

**Comment by VinSpee** [comment]
I started the UI side of this in #331—I'd love feedback / iteration before I go further

**Comment by SaraVieira** [comment]
I'm gonna close due to inactivity :(

Feel free to reopen @VinSpee :)
