### ISSUE TITLE
[feature request] [Vue] Stylus syntax highlighting

### ISSUE THREAD

**Issue by Piterden** [CompuIves/codesandbox-client#328]
Now it is not work

![image](https://user-images.githubusercontent.com/5930429/33234427-b422674c-d237-11e7-9b96-61c279789a99.png)

**Comment by Piterden** [comment]
Monako is now has it, thanx)

PS CodeMirror has lost all highlights, but Monako has became normal.

**Comment by CompuIves** [comment]
This works now for CodeMirror too, will go live tomorrow morning!

**Comment by Piterden** [comment]
Thnx. You rock, man!! ) :+1:
