### ISSUE TITLE
Allow using tag for package version

### ISSUE THREAD

**Issue by yesmeck** [CompuIves/codesandbox-client#332]
We are looking into use codesandbox as a reproduce tool for `Ant Design`. Do you have, or plan to support tag for package version? So that we can always pointing our package to the latest version.

**Comment by CompuIves** [comment]
That's great! We don't support version ranges yet, but we do support this on creation of a sandbox. So if you create a sandbox with a POST request you can do this:

```json
{
  "dependencies": {
    "react": "latest"
  }
}
```

And we'll resolve the latest version.

**Comment by CompuIves** [comment]
Yoep, this is here now!
