### ISSUE TITLE
Sign in button on homepage

### ISSUE THREAD

**Issue by Hum4n01d** [CompuIves/codesandbox-client#334]
It would be useful to have a link straight to the sign-in page on the homepage. I just opened CodeSandbox on a new computer and couldn't find an easy way to the sign-in page. If I remember correctly, there used to be one in the top right corner but it's no longer there.

**Comment by Hum4n01d** [comment]
This is still missing... @CompuIves

**Comment by CompuIves** [comment]
Hmm yes, I'm definitely open to it. We could create a page called /signin or something and start the auth flow there. Then we can open a popup from the homepage that goes that page.

**Comment by Hum4n01d** [comment]
My thoughts exactly. Wasn’t that what I said in the Discord server?

**Comment by CompuIves** [comment]
Yep, exactly!

**Comment by chakrihacker** [comment]
@CompuIves do you want a new page in gatsby for authentication or is it ok to handle auth on home page??

**Comment by CompuIves** [comment]
I think we should have a page in the editor app itself that calls the required logic (I think `props.signals.signInClicked`). We don't have the logic for it on the homepage.

**Comment by SaraVieira** [comment]
This has been created! YAAAAY

**Comment by Hum4n01d** [comment]
I don't see it on the website, has it not been pushed?

**Comment by SaraVieira** [comment]
Sorry, this was my mistake . It's still not in it :(

**Comment by arthurdenner** [comment]
@SaraVieira, I think this issue can be closed now. :tada:

**Comment by SaraVieira** [comment]
OMG YAY
