### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by eladcandroid** [CompuIves/codesandbox-client#335]
Any chance for that?

**Comment by CompuIves** [comment]
This one slipped my notifications, sorry! We can absolutely make an Angular template, I will add that before 2018.

**Comment by kpats** [comment]
Well.. Its 2018.. But still no Angular support.. It is a big framework and good for marketing/advertising you know. :-)

**Comment by vvo** [comment]
Any pointers on where to add the relevant template code to support Angular @CompuIves? Thanks

**Comment by CompuIves** [comment]
Heya! I'm releasing an update next week with Angular template support, stay tuned 😄.

**Comment by CompuIves** [comment]
Tomorrow!

**Comment by vvo** [comment]
❤️

**Comment by CompuIves** [comment]
Deployed! https://medium.com/@compuives/announcing-codesandbox-2-5-be767d15ffd
