### ISSUE TITLE
[Feature request] Search in own sandboxes

### ISSUE THREAD

**Issue by lbogdan** [CompuIves/codesandbox-client#342]
It would be nice to be able to search in my own sandboxes (in the https://codesandbox.io/u/:user/sandboxes page). Right now I'm doing Ctrl-F, next page, Ctrl-F, next page, Ctrl-F... ah, there it is! :smile:

**Comment by dnlsandiego** [comment]
@CompuIves Is this a feature that has the go ahead to be on the app? If so, I'd like to give it a shot!

**Comment by arthurdenner** [comment]
@lbogdan, can this issue be closed since we now have a dashboard?

**Comment by SaraVieira** [comment]
BLESS YOU MAN!
