### ISSUE TITLE
Tab width setting ignored when 'Use tabs' is active.

### ISSUE THREAD

**Issue by ryanpcmcquen** [CompuIves/codesandbox-client#344]
An easy way to reproduce this is to set `Tab width` settings to `4` and set `Use tabs` to true. The width stays at `2` spaces.

**Comment by ryanpcmcquen** [comment]
Also, hitting <kbd>Tab</kbd> when set to _4 spaces_ indents only _2 spaces_.

**Comment by CompuIves** [comment]
Oh, I missed this in my notifications, sorry!

I think this is a problem in `Monaco.js`. We need to get this from preferences: https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/components/sandbox/CodeEditor/Monaco.js#L795-L796.

**Comment by ryanpcmcquen** [comment]
@CompuIves, would that look something like this?

```js
model.updateOptions({ tabSize: this.props.preferences.tabSize });
```

**Comment by CompuIves** [comment]
Exactly @ryanpcmcquen! Thank you very much, could you open a PR for it?

**Comment by ryanpcmcquen** [comment]
@CompuIves, tests are running now!
https://github.com/CompuIves/codesandbox-client/pull/397

**Comment by ryanpcmcquen** [comment]
This bug is back @CompuIves, regression?

**Comment by CompuIves** [comment]
Yep, I'll commit a fix now.

**Comment by ryanpcmcquen** [comment]
@CompuIves, is this fix live? Because I am still seeing the issue. It also seems that the tab width setting disappeared from preferences.

**Comment by CompuIves** [comment]
Yep it's live! We infer it from `Prettier` settings though, that's why it's not in `Code Editor` preferencecs anymore. Do you think it'd be better if it was in Code Editor?

**Comment by ryanpcmcquen** [comment]
Well, I have it set to `4` in Prettier settings and am still getting an indent of `2`.

**Comment by CompuIves** [comment]
Ah I'm so sorry for that! Just committed a fix and will go live today.

**Comment by ryanpcmcquen** [comment]
Thanks @CompuIves!

**Comment by jfcieslak** [comment]
This problem seems to be fixed only when monaco editor is selected. With CodeMirror it still remains unfixed.
