### ISSUE TITLE
Use puppeteer to create thumbnail image of sandbox

### ISSUE THREAD

**Issue by viankakrisna** [CompuIves/codesandbox-client#345]
figure that we can use puppeteer to generate thumbnails. It would make the shared sandbox nicer :) I've searched ready to use solutions like https://github.com/zenato/puppeteer-renderer but they seem to not wait until the sandbox rendered before taking the screenshot. https://puppeteer-renderer-hfrnufoxcj.now.sh/?url=https://k375101wo7.codesandbox.io&type=screenshot.

I think we need to dispatch a global event for puppeteer to listen (or is this already available? haven't dig much into the sandbox area) and write custom implementation around puppeteer-renderer.

**Comment by viankakrisna** [comment]
(or make a PR to puppeteer-renderer for a feature to listen to events before taking screenshots)

**Comment by lbogdan** [comment]
I just played around with `puppeteer` a bit, it has a pretty comprehensive API, something like this seems to work:
```js
const puppeteer = require('puppeteer');

function timeout(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

puppeteer.launch(/*{ devtools: true }*/).then(async browser => {
    const page = await browser.newPage();
//    page.on('request', msg => console.log(msg.url));
    await page.goto('https://o29j95wx9.codesandbox.io/', {
      waitUntil: 'networkidle0'
    });
    await timeout(1000);
    await page.screenshot({
        path: './screenshot.png'
    });
    await browser.close();
})
```

**Comment by viankakrisna** [comment]
nice! but 1000 seems like a magic number to me. isn't it? have you tried with a heavier sandbox?

**Comment by lbogdan** [comment]
It is a bit of a magic number, indeed. It means "1 second after all network requests finished", which should be enough for running the sandbox code.

**Comment by viankakrisna** [comment]
I think it's better for sandbox compiler to dispatch an event so puppeteer can listen to that.
https://github.com/GoogleChrome/puppeteer/blob/master/examples/custom-event.js

**Comment by lbogdan** [comment]
You'll still have to wait a bit after the compiler finishes - for the actual code to execute, so it's not really a solution to get rid of that magic number. 😄

**Comment by CompuIves** [comment]
Yes I'd love to have this system in place! I think the best approach is to check every 5 minutes for sandboxes changed within that time, then we invoke for every sandbox a serverless function that makes a screenshot and saves it to an S3 bucket.

We already have puppeteer testing for integration tests: https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/integration-tests/tests/sandboxes.test.js. We check here for an element, but I like the idea of a custom event more. Works for every sandbox.

**Comment by viankakrisna** [comment]
@lbogdan ah, yes, I think I found a solution in the question below. how can we start working on this solution? @CompuIves some questions: 

1. what is actually running when we share a sandbox? I want to know where we can put the url for the thumbnail :grin:
2. Isn't it better to have the serverless function running when the user click save? or is it more costly that way?
3. We still need to let the sandbox code run even after listening to the compiled event right? how about checking if the root element has a child?

**Comment by viankakrisna** [comment]
I see that you use 
```
await page.waitForSelector(root, { timeout });
``` 
I actually think it's better for puppeteer to wait for that rather than custom event 😄

**Comment by CompuIves** [comment]
> what is actually running when we share a sandbox? I want to know where we can put the url for the thumbnail 😁

I think we should put the URL in the HTML of the editor + the embed page. When you share on Slack/Twitter/etc you will then see the image as a thumbnail.

> Isn't it better to have the serverless function running when the user click save? or is it more costly that way?

That would be best case scenario, but I think it'd also be too expensive. In the past week alone we had 69728 saves for 6202 sandboxes.

> We still need to let the sandbox code run even after listening to the compiled event right? how about checking if the root element has a child?

I'm not sure if this would work with every sandbox, because some sandboxes work on different selectors (like `#app` or `#root`). The custom event feels save, because most rendering is synchronous. Which means that after evaluation you have the result right there. Maybe we can do a combination? After custom event wait for 30 seconds to take a screenshot OR wait for a selector to be filled.

**Comment by lbogdan** [comment]
@CompuIves Do you see any reason why my solution wouldn't work? (it also accounts for the situation where the sandbox does one or more API requests - like the preact sandbox)

**Comment by viankakrisna** [comment]
>I think we should put the URL in the HTML of the editor + the embed page. When you share on Slack/Twitter/etc you will then see the image as a thumbnail.

is the html is processed in anyway by server side script? i mean the thumbnail url should change based on the sandbox id right?

>After custom event wait for 30 seconds to take a screenshot OR wait for a selector to be filled. 

yea I think it's best to wait for known selector first, then wait for the timeout, 
one of the use case of using `Promise.race` I think 😄  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race

**Comment by CompuIves** [comment]
Oh interesting @lbogdan! I'm curious if this works in more cases. Could you adept https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/integration-tests/tests/sandboxes.test.js with your code and open a PR? Then we can check if it works for multiple examples.

**Comment by CompuIves** [comment]
> is the html is processed in anyway by server side script? i mean the thumbnail url should change based on the sandbox id right?

Yes, that's another thing I'll need to build. Luckily we do something similar already for the sandbox HTML.

**Comment by lbogdan** [comment]
@CompuIves I just tested with your presentation, and it worked! 😄 
![](https://i.imgur.com/NJDcsmG.png)

**Comment by lbogdan** [comment]
Just made a PR, seems to be working: https://github.com/CompuIves/codesandbox-client/pull/357.

**Comment by CompuIves** [comment]
Wooow that's great @lbogdan!! Okay great, in that case we have a flexible way to create screenshots. Now we need to get puppeteer working on AWS Lambda as next step.

**Comment by lbogdan** [comment]
I'm thinking of something like:
- sandboxes have a boolean flag (let's say `is_thumb_generated`) which is `false` by default;
- there a sandbox thumb url under the API, like `https://codesandbox.io/api/thumb/{sandboxId}.png`;
- the handler for that url looks as `is_thumb_generated` and:
  - if `false`, it calls the AWS lambda function that generates the thumbnail, waits for it to finish, and sets `is_thumb_generated` to true;
  - redirects to the S3 url;
- whenever saving a sandbox, set its `is_thumb_generated` to false.

**Comment by lbogdan** [comment]
Also, found this: https://github.com/sambaiz/puppeteer-lambda-starter-kit .

**Comment by CompuIves** [comment]
That's perfect @lbogdan. I like your solution much better as well, let's start working on this!

One limitation is that a serverless lambda should be able to generate a screenshot within 30 seconds, though this seems doable, right? Anyone wants to write the code for the lambda? Then I'll connect the server.

**Comment by lbogdan** [comment]
Great success!
