### ISSUE TITLE
Repo not syncing

### ISSUE THREAD

**Issue by alansouzati** [CompuIves/codesandbox-client#346]
Hi I have this project [here](https://github.com/grommet/grommet-site) where the integration with github + codesandbox is enabled.

It seems that the repo is not syncing anymore. I added 4 new components and when I click in the "Edit in Codesandbox" button they are no there.

Here is an example: http://v2.grommet.io/tabs

**Comment by CompuIves** [comment]
Hey @alansouzati. I checked what caused the syncing issue, it turns out to be a limit on our side.

We have a limit of 100 files currently, it seems like there are 115 files in the Grommet site repo right now. The main reason of this is the 50 images here: https://github.com/grommet/grommet-site/tree/master/public/img. Would it be possible to remove some images? If that's not desired I can raise the limit to 130 modules.

**Comment by alansouzati** [comment]
Hey @CompuIves good to hear from you again. Hopefully all is going well on your side.

Our v2 site is not finished yet, so we plan to add more files and pages for the new components what we are slowly adding.

With regards to the images, you can see that it is being used by the Selection component: http://v2.grommet.io/selection. I will go ahead and reduce the number, maybe 25 or so. But it would be great if you can raise the module limit as well, since we still have a lot of new components to cover in the site. Can you work on that?

Codesandbox is a really great tool, and I want to keep relying on that as the only source of code reference for our v2 site.

**Comment by stormasm** [comment]
I am observing that the syncing is not working, and I have only a couple of files...  You can try testing it by forking my repo, doing the import, and then make a change to the repo you just forked and you will probably observe that the syncing does not appear to be working...

**Comment by CompuIves** [comment]
Hey @stormasm! To be sure, did you commit the changes of the fork back to GitHub? You can do that in the sidebar:

![screen shot 2017-12-28 at 19 26 13](https://user-images.githubusercontent.com/587016/34419608-196a0ec0-ec05-11e7-9a6a-11c5e69fd24e.png)

**Comment by stormasm** [comment]
@CompuIves  --- Unfortunately, it is NOT working...

https://github.com/stormasm/csbox-mui-demos/commits/master

If you look at these 4 commits...

Commit number 3 was done on the Codesandbox side
Which was ButtonAppBar

Commit number 4 was done on the Github side and Codesandbox did NOT sync it back up...
Update index.js

In other words, index.js on the codesandbox did not sync back up with this line of code...
import App from './demos/app-bar/MenuAppBar';
which got changed on the Github side...

You have a super fantastic product ---- happy to help debug this further...
Just let me know what you want me to do...
Thanks,
Michael Angerman

**Comment by stormasm** [comment]
@CompuIves In thinking about this further maybe it is my lack of understanding....

After importing a repo from Github into my sandbox...
Then I make a change on the sandbox and commit that back to Github...
Up to this point everything works.

Here is my question...

Later on --- on my home computer I make a another change and commit that to Github.
And then go back to the tab on sandbox ---- will it sync back up (automagically)
that change that I committed to Github from my computer or Github website ?

Thanks,
Michael

**Comment by CompuIves** [comment]
You can see a fork of a Github sandbox (sandbox urls starting with /s/github) as creating a new branch. When you press 'Commit' you merge the changes of your fork back to master, but you stay on the fork. To get the latest version of a git sandbox you'll need to go back to 'master', which is the original git url, in your case this is https://codesandbox.io/s/github/stormasm/csbox-mui-demos/commits/master.

I'm thinking of redirecting the user back to 'master' after a commit, to clear up any confusion on that regard. I'll also write some documentation on this this weekend.

**Comment by stormasm** [comment]
@CompuIves Yes !  That does clear things up....  And now I see everything is working as well...

My problem here was not understanding the **fork issue**... And your intuition to redirect people **back to master** to clear up any confusion is probably a very good idea...

I appreciate you taking the time to explain this to me...

Have a very nice weekend !  And again many thanks for creating codesandbox.
It is certainly helping the developers of material-ui and their many users 
on Gitter out tremendously.

Michael Angerman
Corvallis, Oregon

**Comment by rajatvijay** [comment]
@CompuIves is the syncing with GitHub one way only. 

I mean, I manually changed the README on GitHub using their online editor but the change is not reflecting on my sandbox. Is there a way I can do a `git pull`?

**Comment by CompuIves** [comment]
Hey @rajatvijay, do you have a link to the GitHub repo? The sandbox should automatically sync with the latest changes, but sometimes there's a race condition where GitHub still gives old content for the new sha I think. I've had 2 other reports over the past time that a sync didn't happen. 

The solution would be to create a new blank commit and push, then the latest changes should reflect automatically in the sandbox.

**Comment by rajatvijay** [comment]
@CompuIves 

>The solution would be to create a new blank commit and push, then the latest changes should reflect automatically in the sandbox.

I cant since I am unable to do a `git satsh` or remove all the current changes that I don't want to push to the repo.

**Comment by rnallu** [comment]
@CompuIves

> The solution would be to create a new blank commit and push, then the latest changes should reflect automatically in the sandbox.

I tried this steps suggested by you, its not updating to latest changes of code. Is there any improvement in this regard lately. Please update.

**Comment by lbogdan** [comment]
@rnallu Can you please provide a link to your github repo, and also tell us what changes are not updating properly?

**Comment by rnallu** [comment]
@lbogdan [Github repo](https://github.com/rnallu/nba-app)
the `feature_slider` branch is merged to `master` in github, same is not getting updated in [codesandbox](https://codesandbox.io/s/m76k4prww9) even after i tried to push a blank commit thru codesandbox.

**Comment by Harshu53** [comment]
I am also facing the issue that the codesandbox ( https://codesandbox.io/s/crown-clothing-g6fhz ) is not in sync with my github repo ( https://github.com/Harshu53/crown-clothing ).

I tried :

- Fork the own sandbox.
- Commit the README.md file on git

But nothing is working and the codesandbox is not updated with my git master repo.

Any help or hint would be great.

Thanks.
