### ISSUE TITLE
Sign in erases unsaved content

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#347]
Need to test it myself, reference is from [Twitter](https://twitter.com/GabeRicard/status/936344948630269952):

@CompuIves I noticed a bug in codesandbox when I was writing that. I started it off without being logged in, but then I logged in via github and it overwrote parts of it with the default react project. index.js was overwritten and Modal.js had the default Hello.js contents.

**Comment by gricard** [comment]
Hmm... I tried doing the exact same thing I did before, on the same computer, and it didn't happen this time. This is what I did:

- hit codesandbox.io
- click create sandbox in top right
- renamed Hello.js to Modal.js and put this code in:
```javascript
import React from "react";

export default ({ title }) => <div>{title}</div>;
```
- created a new module Title.js and put this code in: 
```javascript
import React from "react";

export default ({ label, foo }) => (
  <h1>
    Title: {label}! ({foo})
  </h1>
);
```
- put this code in index.js:
```javascript
import React from 'react';
import { render } from 'react-dom';
import Modal from './Modal';
import Title from './Title';

const title = <Title label="my title" foo="baz" />;
const anotherTitle = <Title {...title.props} foo="bar" />;

const App = () => (
  <div>
    <Modal title={anotherTitle} />
  </div>
);

render(<App />, document.getElementById('root'));
```
- saved
- signed into my github account
- index.js was reverted and Modal.js had the old Hello.js contents

**Comment by gricard** [comment]
I did the above in Chrome. I tried it in Safari as well just now, to see what happens with a clean slate. It looked fine after I modified/added the files, saved and then signed in. But, when I reloaded, the content of index.js was replaced with the default code, and Modal.js had the Hello.js in it.

Here is the sandbox I created: https://codesandbox.io/s/3r54w224k5

**Comment by ebrahim-tadbir** [comment]
Have the same problem! with no answers!
