### ISSUE TITLE
Mode select causes layout flickering

### ISSUE THREAD

**Issue by maciej-ka** [CompuIves/codesandbox-client#349]
Good Morning, CodeSandbox-Vietnam!

Bug reproduction:
1. Open a project
1. Move cursor over mode select
1. Hover on Preview mode
1. Move cursor down, out of header

Expected behavior: 
mode options disappear, the layout looks good

Actual behavior: 
after mode options disappear for a short moment page gets a margin on the right side. 

![codesandbox-flicker](https://user-images.githubusercontent.com/5403694/33498419-8cc0350a-d6d1-11e7-8755-b2442c490ecb.gif)

Warm greetings!

**Comment by lbogdan** [comment]
Closing this since there was a major UI refactor meanwhile and the layout selector was removed.
