### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#35]
We're moving more and more to touch devices, CodeSandbox is in the unique position that it already works on any device.

Let's make CodeSandbox responsive and start brainstorming on React Native support.

**Comment by Haroenv** [comment]
I checked using the iPad simulator, and it seems to work just fine, except the menu starting to overlap. iPhone size is a different story, since there definitely is space too little right now. Even editor view is overflowing. We could maybe give that a max width of the whole width. 

Screenshots: 

<img width="332" alt="screen shot 2017-07-04 at 00 04 39" src="https://user-images.githubusercontent.com/6270048/27809018-77937af8-604c-11e7-933b-f50622ef6889.png">
<img width="1024" alt="screen shot 2017-07-04 at 00 01 50" src="https://user-images.githubusercontent.com/6270048/27809020-78d3f190-604c-11e7-9d80-b9d93c859260.png">

**Comment by CompuIves** [comment]
Thanks for the screenshots!

The iPad version looks better than I expected, maybe we should do something about the header icons, but otherwise it looks pretty great.

I think that we should do some overhauling for the iPhone view. CodeSandbox is divided in 3 parts ([workspace, editor, preview]). I'm thinking that we could maybe put these as view options at the bottom of the screen, so you can switch between them.

I think we're going to need a sidebar with actions for all overflowing actions in the header, behind a hamburger menu.

I can make some mockups this week to show what I mean 😄 .

**Comment by haraldur12** [comment]
In my iPhone the page does not even load after the animation is rendered. Is it a normal behaviour ?

**Comment by sprmn** [comment]
Would love a better mobile experience as well! I think for mobile (at least in portrait mode) a horizontal split screen would fit better than a vertical split screen. Most of the time I click on an example of a certain something on twitter. I don't know yet wether I'd prefer to see the code first or the rendered result, but I guess I'd take a quick look at the result before checking out the code, so the rendered result would be shown at the top. The sidebar should probably start collapsed on mobile then as well. 

As @Haroenv mentioned, the options for different screen settings overlap with the feedback and twitter buttons, so it is impossible to select the Preview View on my device. 

I'd love to help out with React Native support. Building the whole app in the cloud probably won't be feasible, so you'd have to ship an app with some precompiled libraries and then somehow dynamically compile and load the javascript bundle, just like https://snack.expo.io does. The dependency management is going to be a challenge here, especially if you'd like to add dependencies with native code in it. It would be great if we could somehow select some dependencies somewhere and then download an apk/ipa that contains these dependencies. Until we figure out how to make that process easy, we could stick with supporting everything that create-react-native-app does. We could make a codesandbox app to preview stuff or just make codesandbox.io compatible with the expo app.

**Comment by CompuIves** [comment]
> In my iPhone the page does not even load after the animation is rendered. Is it a normal behaviour ?
That's definitely not normal behaviour, I'll look into it today. Thanks for letting me know!


Good points @sprmn. I think a horizontal split option would really beneficial in general, also for desktops. I opened an [issue](https://github.com/CompuIves/codesandbox-client/issues/36) for it.

Great to hear that you want to help with React Native support! Building on client side sounds indeed most beneficial, it's also something we do right now. I think we should focus first on the existing functionality of CodeSandbox, supporting current sandboxes and the templates that will come.

Supporting native React Native projects sounds very interesting, my main question what the added benefit is over snack.expo.io.

**Comment by Haroenv** [comment]
It's interesting to remind that the keyboard blocks a significant part of the screen when using a horizontal layout. It might not be ideal to show more than one thing at the same time. It's more important to have the view switcher prominently visible on the mobile view

**Comment by CompuIves** [comment]
@Haroenv Good point.

I made a quick rough mockup of what it could look like:

![mobile](https://user-images.githubusercontent.com/587016/27830476-e4653e6c-60c6-11e7-880b-78503927c8a8.png)

**Comment by sprmn** [comment]
Looks very promising! A prominent switcher that switches between single views would indeed work better with the keyboard. I think you could hide even more data and focus on showing the directory tree and dependencies.  

Regarding the benefit of RN support on CodeSandbox over snack.expo.io, I'd say all features of CodeSandbox would add great value: supporting multiple files and directories, publishing versions of your sandbox, importing from github, embedding/sharing sandboxes, adding (javascript only) dependencies, etc.

**Comment by daton89** [comment]
on my hwauei m3 lite 10" it looks very great... 

![img_20180617_213256](https://user-images.githubusercontent.com/6856342/41511431-d708e2ce-7276-11e8-937b-04030f82e294.png)

i've noticed two things,
1. tapping on the code editor the device zoom in to the code automatically and sometimes is not possible to zoom out.
2. using swiftkey the code editing doesn't work.

should i open some issues for these?
how can i contribute to help? i've just bought the tablet to use it with this awesome web application during my trips.

**Comment by SaraVieira** [comment]
@CompuIves Is this still valid ? Most things are already responsive

**Comment by SaraVieira** [comment]
Closing this as I think all the issues here have been fixed 🎉
