### ISSUE TITLE
Sentry/Raven errors in navtive developer console.

### ISSUE THREAD

**Issue by colshacol** [CompuIves/codesandbox-client#351]
In my native console I am getting errors from Raven about `yarn.lock` and `.gitignore` files missing. This only happens when I have a fresh preview and switch files. The three errors come in synchronously, each about 0.2s after the previous, and the errors are not initiated for about 1 second after switching files.

This is not affecting my work as a user, and not effecting my code, so it is not a big issue. But it is irritating and I would like to file this bug and look into the issue myself, potentially resulting in a PR.

**Expected**: No Sentry errors in native developer console.
**Actual**: Yes Sentry native developer console errors.

**Happening in Chrome.**
**Independent of view type.**
**Happening on Monaco editor.**
**Happening on Windows, possibly others.**
**Doesn't happen in external live view.**

_I am not sure if this will happen in all sandboxes, so the steps to reproduce may not work for all._

Steps to reproduce:
1. Log in to CodeSandbox.
2. Enter a sandbox with multiple files.
3. Open Chrome's developer console.
4. Click to another file.

![sentry0](https://user-images.githubusercontent.com/19484365/33503218-8a12776a-d6a8-11e7-98c0-584f453631f1.png)

**Comment by CompuIves** [comment]
Very interesting, it seems like the Monaco editor is throwing these errors. I haven't seen them before, but I see them in Sentry from time to time. Thanks for sending this, maybe we can squash these errors now 😄 .

Which operating system are you on?

**Comment by colshacol** [comment]
I confirmed that it is happening only on Monaco and not on CodeMirror. **thumbs up emoji?**

Adding this finding to the initial report.

As for OS, I use CodeSandbox on Windows when the misses makes me play video games with her. Have not experimented with it on Arch yet, but I will soon.

(Adding this to bug report, too.)

**Comment by colshacol** [comment]
**Update:** I noticed that it was not happening on a new sandbox. But as soon as I exported it to GitHub and the page refreshed, the error began.

**Comment by CompuIves** [comment]
Good observation! Maybe we're remounting the Monaco editor on fork, and it complains of duplicate instances?

**Comment by CompuIves** [comment]
I found this origin of this issue. It seems like it happens for modules with `code: null`. I think I have fixed this, I'll close this issue now.

We can reopen it if it reoccurs!
