### ISSUE TITLE
White theme

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#359]
Would be nice to have an optional white theme for embeds and editor for people that prefer it.

**Comment by farskid** [comment]
I'd like to help with this issue. Any particular steps to start from?

**Comment by CompuIves** [comment]
Ahh that's absolutely perfect @farskid! 

We're already using `styled-components` and our styles are defined in `common/theme.js`. It may be too good to be true, but maybe just changing those colors will already make it possible to create a light theme. That would be a very good start.

**Comment by farskid** [comment]
@CompuIves Very nice! I'll start right away and will keep this issue posted :)

**Comment by steventsao** [comment]
IMO, the font colors need to be darkened to increase contrast in a white background. We'll also need to update the backgroundColor in tabs, user highlights, and maybe the autocomplete popover.
![screen shot 2018-06-15 at 8 24 47 pm](https://user-images.githubusercontent.com/15185301/41495363-3db8a2be-70da-11e8-9147-7762d0a49b9c.png)

**Comment by aleksspeaker** [comment]
Hello, I just want to mention that, we're waiting patiently for day theme.
;)

**Comment by farskid** [comment]
@aleksspeaker Sorry for the delay. I'll try to ship it soon

**Comment by aleksspeaker** [comment]
@farskid No worries.
I want you to know that we're (or at least I'm) with you. :)
If you need something - just drop me a line here.

**Comment by CompuIves** [comment]
I'm also taking a look at this combined with theme support! @farskid, curious what you already have 😄

**Comment by Haroenv** [comment]
Can be closed!!!

**Comment by farskid** [comment]
@CompuIves Sorry for not delivering this and late responses :(
Just seen the support for theme :)
Glad we have this right now and so sad to miss the chance.
Great Job!

**Comment by CompuIves** [comment]
Hey @farskid! I'm so sorry for bumping in there and doing this suddenly, I was very enthusiastic about getting the vscode themes to work and went a bit overboard. I hope I've not wasted too much of your time here :(.

**Comment by CompuIves** [comment]
Also, let me know if you want a walkthrough of how I did it! I'd gladly do that.

**Comment by steventsao** [comment]
Walking through this list of commits...https://github.com/CompuIves/codesandbox-client/pull/647

**Comment by farskid** [comment]
@CompuIves I'd love to have a walkthrough :)
And btw, no worries about this, you did a great job as usual :)

**Comment by aleksspeaker** [comment]
Thanks, everyone!
Works great!
Finally!!!))) 🎉

**Comment by sinedied** [comment]
Is there any way to force a specified theme (ie VSCode Light instead of default dark for example) for embeds? I could not find any way to do that

**Comment by sisardor** [comment]
Any updates or how to enable the white theme on embeds?
