### ISSUE TITLE
Horizontal split

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#36]
An option to have a horizontal split over the vertical split.

**Comment by Arthelon** [comment]
Hmm should the button to trigger this be an additional split view button in the header bar? (It's getting a bit crowded there). Alternatively I was thinking the middle split view button can toggle between horizontal/vertical with additional clicks but this may be misleading even with a hover message.

**Comment by CompuIves** [comment]
> (It's getting a bit crowded there).

I agree. I'm thinking of moving the three buttons in the header altogether, since they're taking up so much space. Maybe we should rework the buttons or just put them in another place. I haven't found a good solution yet... Maybe a dropdown, or a smaller, more efficient version 🤔.

**Comment by CompuIves** [comment]
This is live now! 😄
