### ISSUE TITLE
Tabs disappear out of no where

### ISSUE THREAD

**Issue by pfftdammitchris** [CompuIves/codesandbox-client#361]
For some reason the tabs seem to disappear randomly. I don't know why this happens but I can leave this here for now for the heads up.
Screenshot provided below. (I had 5-6 tabs open at once before they magically disappeared in the screen).

![image](https://user-images.githubusercontent.com/20717348/33530172-706cc606-d830-11e7-84a8-62c0238b9c05.png)

# Edit: After careful examination it actually doesn't seem like its magically disappearing. The top 5-6 lines are being cropped off.
(New screenshot provided below).
As you can see the scrollbar to the right is already scrolled to the farthest upward and its showing inside the editor that some content is being cropped for some reason. This is happening everywhere inside the editor even if I flip through files. Its statically cropped until I have to manually refresh (F5) the page. This is a problem because when refreshing the page the opened tabs are gone and I'd have to open every single tab all over again.

![image](https://user-images.githubusercontent.com/20717348/33530197-21f96dd4-d831-11e7-884c-4155c6cb4a85.png)

**Comment by lbogdan** [comment]
Closing this since there was a major UI refactor meanwhile.
