### ISSUE TITLE
"Relative" paths in the code preview panel

### ISSUE THREAD

**Issue by Nufflee** [CompuIves/codesandbox-client#368]
Not sure if this is in development and/or reported before but I encoutered this issue earlier today while working on a 720p screen. It is not really an issue, but it was kind of annoying to scroll all the way till the en d of the url bar just to change the current route. There should be an option to only show the part of the url, for instance https://sandbox.io/ [my route here] and not the mile long randomly generated one. 
Cheers!

**Comment by SaraVieira** [comment]
Closed due to inactivity

Feel free to reopen @Nufflee
