### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by wellyal** [CompuIves/codesandbox-client#37]
Something is wrong trying to access this url 
https://codesandbox.io/s/new

Error: 
```
bootstrap f260dcf…:54 Uncaught TypeError: Cannot read property 'call' of undefined
    at t (bootstrap f260dcf…:54)
    at Object.0 (app.f260dcff.js:29627)
    at t (bootstrap f260dcf…:54)
    at window.webpackJsonp (bootstrap f260dcf…:25)
    at app.f260dcff.js:1
```

Google Chrome Version 59.0.3071.115

The application gets freezed on this screen  

![image](https://user-images.githubusercontent.com/3047016/27881513-4cb8ec4c-619f-11e7-9b43-814fe8b391b2.png)

**Comment by CompuIves** [comment]
Thanks for sending this! Seems like a deploy went wrong halfway? Redeploying...

**Comment by wellyal** [comment]
@CompuIves no problem. Thanks for the fastest response I`ve ever seen on github :)

**Comment by CompuIves** [comment]
Should work again now! This is really strange, since it works in dev mode. I'll investigate.
