### ISSUE TITLE
can the github file limit be increased?

### ISSUE THREAD

**Issue by faceyspacey** [CompuIves/codesandbox-client#39]
It's currently 30. What about 60?

**Comment by CompuIves** [comment]
Sounds okay to me, which repository are you trying to import?

**Comment by faceyspacey** [comment]
this one:

https://github.com/faceyspacey/cra-test

but I'm going to change the name after I get this working.

**Comment by CompuIves** [comment]
Okay! I'll increase it in 15 min.

**Comment by faceyspacey** [comment]
awesome thanks brother!

**Comment by CompuIves** [comment]
Done! Took some longer than expected because I saw you had a dynamic import, we support that too now 😄 .

**Comment by CompuIves** [comment]
Currently deploying...

**Comment by faceyspacey** [comment]
awesome!!!

**Comment by faceyspacey** [comment]
im changing the styles to match codesandbox right now fyi

**Comment by CompuIves** [comment]
Great! Let me know if you come across anything strange in the process. I'm closing this issue now.
