### ISSUE TITLE
New Share Modal

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#390]
Our current share modal is very unintuitive and outdated, it'd be good to refactor this. Would love to hear some discussion on this.

**Comment by Anenth** [comment]
- I feel the name share doesn't suit the content inside the modal, Shouldn't it be Embed?
- Showing a preview of the embedding content would be really useful

**Comment by CompuIves** [comment]
> I feel the name share doesn't suit the content inside the modal, Shouldn't it be Embed?

Wow yes, I completely agree. We will change the name with the redesign.

> Showing a preview of the embedding content would be really useful

Agreed!

**Comment by Anenth** [comment]
@CompuIves would love to help you in the redesign.

**Comment by CompuIves** [comment]
That's great! Nowadays we have a full list of what we support here:

https://codesandbox.io/docs/embedding

The challenge is how we're showing all these options in an intuitive way. A live preview of the embed would also be really great.

**Comment by Tushkiz** [comment]
Also, we will need tabs like we have for preference modal to support multiple sharing platforms (e.g. Carbon)

**Comment by SaraVieira** [comment]
Closed by https://github.com/CompuIves/codesandbox-client/pull/1530
