### ISSUE TITLE
codesandbox CLI:[error] This project is too big, it contains 67 files which is more than the max of 50

### ISSUE THREAD

**Issue by IndeDude** [CompuIves/codesandbox-client#395]
I liked **codesandbox** as an IDE for react, and decided to upload a project I am working on and got this error. IMO 50 is too small a number for any non trivial application. Now, I could lessen the number of files - for example by combining all common components in one index file and concatenating all the CSS files for the components in to a single,  unwieldy monster.  For obvious reasons I wouldn't like to do that. 

I can understand your need to limit the project size esp. considering your offering this excellent service for free.

So folks, any chance of increasing this limit? If so, I am going to be one ardent fan!

**Comment by CompuIves** [comment]
Hey! You're right, in the meantime we have increased the limit to 120. I forgot to update the cli to reflect that change 😅. I was about to go to bed, but I can do this tomorrow!

**Comment by CompuIves** [comment]
If you update codesandbox-cli it should be possible to upload bigger projects 😄.
