### ISSUE TITLE
paste key combo closes file panes instead

### ISSUE THREAD

**Issue by hoschi** [CompuIves/codesandbox-client#396]
When I want to paste from clipboard with `Ctrl+V`, it closes the current file pane instead. Copy works. I'm on Linux with Chrome 62.0.3202.75

**Comment by CompuIves** [comment]
Hey @hoschi! Just to be sure, did you change any keybindings in the preferences? We check [here](https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/components/sandbox/CodeEditor/Tabs/index.js#L107) for closing the pane, but I can't see why it's called for a V. Also interesting to know is what keyboard layout you are using.

**Comment by hoschi** [comment]
> just to be sure, did you change any keybindings in the preferences?

nope

> Also interesting to know is what keyboard layout you are using.

It is [neo2](https://en.wikipedia.org/wiki/Keyboard_layout#Neo ) a variant of the german (QWERTZ) keyboard layout. When I use QWERTZ pasting works.

It closes the pane because the key `W` is my `V`, so it seams the code given in the line you linked matches the hardware keyboard but not the layout.

**Comment by CompuIves** [comment]
Interesting, what keyCode do you see when you press V in the preview here?

http://jsfiddle.net/laelitenetwork/zrz141ox/

**Comment by hoschi** [comment]
hehe did the same http://jsfiddle.net/huchengtw/Wk7jR/
86 which is v which is right, also the `key` property prints 'v'
![2017-12-14-142748_601x493_scrot](https://user-images.githubusercontent.com/163128/33994490-f74b570c-e0da-11e7-8006-7afc1642ee7a.png)

**Comment by CompuIves** [comment]
Okay, that says enough! Would you be interested in opening a PR to change the check to keyCode? If you're too busy I can do it as well around this evening.

**Comment by hoschi** [comment]
I have no time, sorry :disappointed:

**Comment by CompuIves** [comment]
No problem, thanks a lot for the quick responses! You'll see a fix this evening 😄

**Comment by lukePeavey** [comment]
@CompuIves Is it ok if submit a PR to fix this?

**Comment by hoschi** [comment]
works now :+1:
