### ISSUE TITLE
exceeded the maximum required depth

### ISSUE THREAD

**Issue by faceyspacey** [CompuIves/codesandbox-client#40]
I guess this isn't supported. Is it something that can be supported. You'd figure if it works in CRA it works here. Thoughts?

**Comment by CompuIves** [comment]
You're right should work in CodeSandbox too then. This is an issue that I don't know how to handle yet, I should investigate.

What currently happens is this:

You have module A and B, module A requires B and B requires A.

When A is executed, it will first execute all imports of A (unless they are cached), so B gets executed, but first all imports of B get executed, which is A again. You'll get an endless loop, which is why the depth check is created.

I don't know how webpack handles this, lemme check.

**Comment by CompuIves** [comment]
Ah, okay, found it. Node does it like this:

if a requires b, and b requires a, then a will be an empty object for the first execution of b.

This is really strange behaviour, can cause some strange bugs. But I'll work according to spec, I'll build it in 😄 .

**Comment by faceyspacey** [comment]
solid brother. i worked around it temporarily.

**Comment by faceyspacey** [comment]
hey brother, one quick thing, i put a `<link />` tag in `index.html` and it's getting embedded in the body, but it's styles are not being displayed:

https://codesandbox.io/s/6R5OR5q0n

click one of the tabs in the left side sidebar that isn't home, then click a row and u will see a large circle overlayed over a video image with no play button displayed in it. It's supposed to have a PLAY button.

**Comment by CompuIves** [comment]
Ah I see, doesn't look right. The dependency is blocked because of a mixed-content issue. You need to use the `https` version instead, it's blocked now because an `http` url is requested over `https`.

Fix: https://codesandbox.io/s/wpYJy8nMg

**Comment by faceyspacey** [comment]
excellent. shoulda checked the console, but i've been styles ur styles :)

**Comment by faceyspacey** [comment]
...im wrappin up. check this URL:

https://codesandbox.io/s/6R5OR5q0n

...any recommendations on finalizing the styles? If it was urs how would u like it?

**Comment by faceyspacey** [comment]
...by the way, sometimes things dont save. i just reloaded and lost a bunch of stuff.

**Comment by faceyspacey** [comment]
put it all back, so it's nice when u look at it. ...the BACK/NEXT buttons in ur fake address bar work perfectly with Redux-First Router by the way. ...I had previously made this long ago in Webpack bin and had to make my own fake address bar.

**Comment by CompuIves** [comment]
Wow this looks great! Love the styles (naturally ;D).

The issue with not saving is really strange, I'll take a look in the logs.

**Comment by faceyspacey** [comment]
im movin pretty fast and saving a lot. probably has something to do with it. 

also fyi, the error about https is still in the console even though it's correct and everything is working. maybe it's remembering the file from the github repo which had http instead of https.

**Comment by CompuIves** [comment]
Yes, it's a bit duplicate right now. It's both in external resources and in the index.html. It will be fixed if you use the github version again with https.

**Comment by CompuIves** [comment]
Cyclic dependency support has landed!

**Comment by faceyspacey** [comment]
Excellent, i'm about to do a medium post and promote this. You down to put this on the homepage?

**Comment by CompuIves** [comment]
Okay, sounds good!

**Comment by faceyspacey** [comment]
there's no way to sync back to github right? (im grabbin my code, putting it back on the correct repo, than pushing to a new codesandbox URL).

**Comment by CompuIves** [comment]
Not yet, in the future there'll be an export to GitHub branch feature, but sadly it's not here yet.

**Comment by faceyspacey** [comment]
ok, here it is:

https://codesandbox.io/s/github/faceyspacey/redux-first-router-codesandbox

**Comment by faceyspacey** [comment]
the URL changed after i reloaded it. Here's that one:

https://codesandbox.io/s/R66kAGKDE

**Comment by faceyspacey** [comment]
also you need to add the `sandbox="allow-presentation"` attribute to your iframe:

https://www.chromestatus.com/feature/5462833647058944

to avoid this:
![screen shot 2017-07-09 at 4 00 40 pm](https://user-images.githubusercontent.com/154732/27998253-c804f738-64bf-11e7-9e8a-10f8c02c0453.png)

That exception occurs when the video plays. 

The video plays nevertheless, but sometimes things slow down after the video starts playing--perhaps if this exception is caught the app wouldn't slow down.

**Comment by CompuIves** [comment]
Okay, deploying the fix. I'd use the long URL regardless, that one stays in sync with the git repo.

**Comment by faceyspacey** [comment]
the "Forked From" link by the way should link to the actual REPO if a github a repo. Also, you should be able to edit the original repo synced from github. Instead, as soon as you save, it forks the sandbox, and in fact you have to re-apply what you just did. It would be nice to keep the URLs from github.

**Comment by faceyspacey** [comment]
It does? That's excellent. I guess I need to apply my changes to github and then it will be reflected there.

**Comment by CompuIves** [comment]
I just deployed a fix for the 'forked from'. The choice to make the github version non-editable is because this could generate conflicts as soon as the GitHub repo changes.

**Comment by faceyspacey** [comment]
totally understand the choice

**Comment by faceyspacey** [comment]
confirmed that it picks up changes from github. VERY NICE! this is a good stop-gap solution until you get around to full-featured github syncing.

...ok so u got my original URL. do whatever u need to do with that. i may make some more tweaks here and there. Now that I feel secure about what repo is powering this, i'm in good shape.

..small thing: the link for "forked from" goes to "../tree/master": https://github.com/faceyspacey/redux-first-router-codesandbox/tree/master/

...if it makes sense, u probably want to remove that so it's the cleanest URL with less path segments, so the name sticks in users' heads.

**Comment by faceyspacey** [comment]
there's unfortunately another problem: when you edit the Title or Description, it forks it.

**Comment by CompuIves** [comment]
Cool! I'll embed it on the homepage. 

> ..small thing: the link for "forked from" goes to "../tree/master": [faceyspacey/redux-first-router-codesandbox@`master`](https://github.com/faceyspacey/redux-first-router-codesandbox/tree/master/)

I think I can't change this, since some repos have another branch (like `dev`) as default view. Which means that I need to explicitly specify what branch it is since I can't get the default view.

**Comment by CompuIves** [comment]
> there's unfortunately another problem: when you edit the Title or Description, it forks it.

Hmm, you're right. I need to find something to determine who the owner is. For now you can specify the description and title in `package.json` and it'll use those values.

**Comment by faceyspacey** [comment]
you're the man!

**Comment by faceyspacey** [comment]
it looks fantastic on the homepage. Anyway possibly it could get one of the links in the Example projects? I know it's newer, but maybe just while it gets a bunch of traffic over the next few days.

**Comment by CompuIves** [comment]
Sure! deploying it, I'm going to bed now, it's getting late. Have fun with the Medium post!

**Comment by faceyspacey** [comment]
thank you!

**Comment by faceyspacey** [comment]
damn, the title + description doesn't update appear

**Comment by faceyspacey** [comment]
also, the link on the homepage has a typo. there's a "K" added as the last character

**Comment by CompuIves** [comment]
Deploying fix for both

**Comment by faceyspacey** [comment]
excellent. i added some css media queries to fix the squished design in the iframe on the homepage. and now it looks far better. sleep well brother. thanks again!

**Comment by faceyspacey** [comment]
im sorry to bug u if ur still around, but now my sandbox is completely gone:

https://codesandbox.io/s/github/faceyspacey/redux-first-router-codesandbox
403

**Comment by CompuIves** [comment]
Oh no! I think we just hit the rate limit on GitHub, I'll check.

**Comment by CompuIves** [comment]
Okay, some API keys were not set what caused GitHub to rate limit. Fixed it but found another issue because of a wrong commit I did now. I'm making a lot of mistakes right now because of my tiredness. I'll quickly fix this and then rush to bed 😅 .

**Comment by CompuIves** [comment]
Fixed! 😴

**Comment by faceyspacey** [comment]
excellent work. sleep well!

**Comment by faceyspacey** [comment]
ok, the article is finally done:

https://medium.com/faceyspacey/redux-first-router-lookin-sexy-on-code-sandbox-d9d9bea15053

**Comment by faceyspacey** [comment]
im gonna promote it in a few minutes. give it a read. let me know if u want me to make any edits. it's a very casual article compared to my others. hopefully a fun article. may not even make sense to people not yet familiar with RFR. but a picture says a thousand words, and there are a great number of those from ur sexy UI. If anything it will inspire people to play with Code Sandbox.
