### ISSUE TITLE
Range Error on loops with more than 5000 iterations

### ISSUE THREAD

**Issue by gary-menzel** [CompuIves/codesandbox-client#403]
I'm assisting with the maintenance of react-table that uses codesandbox for the majority of the examples.  Many of the examples generate just over 5000 rows of data in a loop and have been working correctly until recently (not sure when - but it is being reported in the last 24 hours of writing this issue).

The following error is being triggered when the data is being created.  Changing the call to the function that triggers the error allows it to work correctly.  Was there a recent change and is there any configuration that can be set to change this?

RangeError
Potential infinite loop: exceeded 5000 iterations.

The example below is at: https://codesandbox.io/s/X6npLXPRW?from-embed

[Screenshot - yes, the code iterates more than 5000 times but was working correctly].

![image](https://user-images.githubusercontent.com/5697099/34098375-2e9524ce-e430-11e7-94e7-a9fdab3d6150.png)

**Comment by CompuIves** [comment]
Ah, I'm very sorry for this. Thanks for letting me know! Deploying a fix
now.

**Comment by gary-menzel** [comment]
Thanks for the quick response it will save a lot of rework on the examples.

**Comment by CompuIves** [comment]
Deployed, it works again! I'll add this sandbox to our tests as soon as I'm at my laptop 😄

**Comment by gary-menzel** [comment]
Sorry to be a pain on this one @CompuIves but there is also a very big 100K example for ReactTable which now violates the 25000.  Tanner Linsley was wondering if there could be a config option for this.

**Comment by CompuIves** [comment]
Haha, that's pretty funny. It's not a pain at all, I can add a sandbox
specific config right after Christmas.

**Comment by techniq** [comment]
@CompuIves I appear to be running into this running as well on my [marchingsquares.js image outline](https://codesandbox.io/s/w00kr6k887) codesandbox (worked when I first wrote it).

**Comment by CompuIves** [comment]
Progress update on this issue: I've worked on this and am planning to release this with CodeSandbox 2.5, somewhere next week.

It looks like this:
![screen shot 2018-01-18 at 16 27 37](https://user-images.githubusercontent.com/587016/35105813-e729d74c-fc6c-11e7-8760-904bf3dfd35d.png)

**Comment by techniq** [comment]
@CompuIves That looks and sounds good.  Thanks for the update.

**Comment by CompuIves** [comment]
Hey! This is live now, if you create a `sandbox.config.json` you will be able to disable infinite loop protection 😄

**Comment by CompuIves** [comment]
Hey! I want to lower the loop iteration count to 10.001, but first want to make sure that everyone in here disabled `Infinite Loop Protection`. Can I lower it tonight? 😄

**Comment by gary-menzel** [comment]
I don't control those sandboxes (Tanner does) - I am not sure he has been able to change them (but that would mean they are still breaking - so it probably doesn't matter for the really large one).

Also, I don't know if you have thought about "shared" sandboxes (where an owner can invite others to maintain them) - just a thought.

**Comment by techniq** [comment]
@CompuIves I just revisited my [marchingsquares.js image outline](https://codesandbox.io/s/w00kr6k887) and it's working without turning off the infinity loop protection turned of.  I went ahead and added the sandbox.config to test it out, but it's working regardless.  I'm assuming because it went from 5k to 100k.  I'll turn off  infinity loop protection if I see it return after you drop it.  Thanks
