### ISSUE TITLE
How can you use jQuery's $?

### ISSUE THREAD

**Issue by im1dermike** [CompuIves/codesandbox-client#404]
I'm trying to create a React sandbox with the following code:

    declare const $: any;

This works in my own codebase without having to do anything special.  I get an "Unexpected token, expected" error, though.

How can I get use jQuery in CodeSandbox and get `$` to work?

**Comment by CompuIves** [comment]
Heya! You can use jQuery by doing something like this:

```js
import $ from 'jquery';

// Now you can use $
```

or you can add jQuery (https://code.jquery.com/jquery-3.2.1.min.js) under External Resources under Dependencies in the sidebar.

We have plans to add better support for custom aliases, so that would make it possible to do this in the future.
