### ISSUE TITLE
Syntax highlighting doesn't work in .vue file when switching to VIM mode

### ISSUE THREAD

**Issue by YassineGherbi** [CompuIves/codesandbox-client#406]
Reproduce:

1. Create an vue-cli project in CSB
2. See the syntax highlighting
3. Switch to VI mode in preferences
4. The syntax highlighting is gone and the autocompletion doesn't work properly anymore

<img width="1680" alt="screen shot 2017-12-18 at 23 59 32" src="https://user-images.githubusercontent.com/15906337/34132313-8cd5be62-e44f-11e7-8d58-ab1168900024.png">

<img width="1522" alt="screen shot 2017-12-19 at 00 00 21" src="https://user-images.githubusercontent.com/15906337/34132330-a7223994-e44f-11e7-8acd-f4a45fcfce77.png">

let me know If any help is needed

**Comment by YassineGherbi** [comment]
Can anyone confirm this bug, please?

**Comment by CompuIves** [comment]
Hey @YassineGherbi, thanks for reporting this issue. I can confirm it.

I think CodeMirror is getting the wrong file type here: https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/components/sandbox/CodeEditor/CodeMirror.js#L316 for vue files. I'll try to fix this today if someone doesn't pick this up 😄

**Comment by CompuIves** [comment]
Fixed with https://github.com/CompuIves/codesandbox-client/commit/eafb0d8264e3d66f6e7e90183e8e8015ddb252ef, will go live tonight or tomorrow morning!
