### ISSUE TITLE
[ERROR] Firebase initializeapp() not working on loading multiple times

### ISSUE THREAD

**Issue by meetzaveri** [CompuIves/codesandbox-client#410]
##  Problem

I have been trying this - https://codesandbox.io/s/w0nvzjy218 in my desktop with local server. It's been working fine. 

But when I moved it to codesandbox platform, on multiple refreshing/loading it crashes as two types of error occur simultaneoulsy.

1. Firebase: Firebase App named '[DEFAULT]' already exists (app/duplicate-app)

![scr1codesand](https://user-images.githubusercontent.com/21293048/34193827-c9bcab42-e57b-11e7-9128-8fa6103df807.png)

2. When I resolve 1st issue then, ANOTHER ERROR - FIREBASE FATAL ERROR: Can't determine Firebase Database URL. Be sure to include databaseURL option when calling firebase.intializeApp().

And I continue solving these issue one after the another as they happen in recursive manner.

Also if you change config in your way, there is response though config is wrong. There is some real issue here with firebase with implementing it with firebase

Thanks for incredible platform!

**Comment by CompuIves** [comment]
Heya! You hit a good point: our HMR doesn't work well yet with stateful applications (like with a firebase config). We're working on fixing this here: #313. For now the thing to make it work is to reload the browser window everytime.

I want to work on this issue some more the coming weekend, do you perhaps have a GitHub repo of the project as a real-world test application for CodeSandbox?

**Comment by meetzaveri** [comment]
@CompuIves Yes for sure I have, but you have to mess/hack with it to find out that two different bugs. Link- https://codesandbox.io/s/w0nvzjy218

**Comment by charlietfl** [comment]
Quick hack is firebase stores initializations in `apps` array

Can workaround it doing:
```
if(!firebase.apps.length){
    firebase.initializeApp(config);
}
```

not likely a good production approach but prevents having to refresh for every change in the sandbox

**Comment by meetzaveri** [comment]
@charlietfl I tried that also, but after one or two attempts, it started showing that error again.

**Comment by CompuIves** [comment]
You can now configure your sandbox to do a full reload by creating a `sandbox.config.json`, that should fix this issue!
