### ISSUE TITLE
Cannot import full Redux module.

### ISSUE THREAD

**Issue by ryanpcmcquen** [CompuIves/codesandbox-client#413]
Small example sandbox:
https://codesandbox.io/s/6vkz096m5r

This code:
```js
import Redux from "redux";
console.log(Redux.createStore);
```

Causes this error:
```js
TypeError: Cannot read property 'createStore' of undefined
```

Is this an issue with the Redux library or the way it is being imported? I tried the UMD build of Redux in a different environment and did not have the same issue:
https://jsfiddle.net/ryanpcmcquen/8dyf2o02/

**Comment by CompuIves** [comment]
Hey! This is how the Redux library works, the `default` export is null.

You can fix it by doing this:

```js
import {createStore} from "redux";
console.log(createStore);
```

instead.

**Comment by ryanpcmcquen** [comment]
Oh! Is there any way to import the whole library?

**Comment by CompuIves** [comment]
import * as Redux from 'redux' ;

**Comment by ryanpcmcquen** [comment]
Thank you! Does that use more memory than just importing one part (like `createStore`)?
