### ISSUE TITLE
Blank screen in Chrome

### ISSUE THREAD

**Issue by Peretz30** [CompuIves/codesandbox-client#415]
Hello! I am using Google Chrome version 39.0.2171.71 m. When I click on "Create Sandbox" blank screen appears. Same thing with trying to open different sandboxes. Just white blank screen with no errors in console.

**Comment by lbogdan** [comment]
@Peretz30 Just doing a routine spring cleanup here, do you still have this issue?

**Comment by arthurdenner** [comment]
@lbogdan, since no more information was provided, can this issue be closed?

**Comment by arthurdenner** [comment]
@Peretz30, nice to hear that it's working now. If you don't mind, could you close the issue? Thanks.
