### ISSUE TITLE
Error when add redux dependency in Chrome

### ISSUE THREAD

**Issue by danielsegura** [CompuIves/codesandbox-client#421]
I'm trying to use redux (3.7.2) in my CodeSanbox project but it never finish to load, in the browser (Chrome) only appears "Downloading Dependencies..."; I thinked maybe it was only my problem so I explored other CodeSanbox projects where the redux dependency is use and all have the same issue (no matter what version of redux had been use).

Thanks for any help!

**Comment by lbogdan** [comment]
Hey @danielsegura , can you give us more details, please? What OS, browser, version, are there any (error) messages in the console, are there any network errors? Thanks!

**Comment by lbogdan** [comment]
@danielsegura Just doing a routine spring cleanup here, do you still have this issue?

**Comment by lbogdan** [comment]
Closing this, as there was no reply in a while, so I'm assuming it's solved. If not, please reopen.
