### ISSUE TITLE
eslint in typescript projects

### ISSUE THREAD

**Issue by iamdanthedev** [CompuIves/codesandbox-client#424]
Hello. Is it possible to switch off eslint in typescript projects? Obviously it produces messy results. Maybe it would be possible to replace is with tslint or nothing.. Thanks

**Comment by CompuIves** [comment]
Hey @rasdaniil. This is a good suggestion, for now you can disable it manually by going to preferences (CMD/Alt + ,).

If anyone's interested in contributing, we could add a check for `this. hasNativeTypescript()` here https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/components/sandbox/CodeEditor/Monaco.js#563

**Comment by rasdaniil** [comment]
Hi!
I should report, that now the problem seems to have disappeared and it works perfectly in monaco editor

**Comment by CompuIves** [comment]
That's good to hear! It could be related to the DevTools console upgrade 😄.
