### ISSUE TITLE
"could not find the Sandbox you're looking for..." when importing from github

### ISSUE THREAD

**Issue by marcinczenko** [CompuIves/codesandbox-client#429]
I have a very basic project created with create-react-app in a public repository with URL:

https://github.com/marcinczenko/personas.git

## Intended

1. Create a new sandbox by importing from github:

    ```
    URL: https://github.com/marcinczenko/personas.git
    Sanbox URL: https://codesandbox.io/s/github/marcinczenko/personas.git
    ```

2. After clicking `Open Sandbox` I expect to see a sandbox that reflects the content of the imported repository and is associated with that repository (meaning I can commit, PR, etc). I also expect that if I push to the repo externally, the sandbox will pick up the changes (at least after it is reopened if not automatically).

## Actual
1. Create a new sandbox by importing from github:

    ```
    URL: https://github.com/marcinczenko/personas.git
    Sanbox URL: https://codesandbox.io/s/github/marcinczenko/personas.git
    ```

2. After clicking `Open Sandbox` I receive the message:

    ```
    We could not find the Sandbox you're looking for...
    Create Sanbox
    ```

3. After clicking on `Create Sanbox` a new clear sanbox is created that has no association with the github repository provided in the 1st step above.

**Comment by CompuIves** [comment]
Ah, good one! We currently aren't parsing the `.git` correctly, removing that should work:

https://codesandbox.io/s/github/marcinczenko/personas

I'll fix that.

**Comment by CompuIves** [comment]
Well, it got fixed by @arthurdenner 😄 .
