### ISSUE TITLE
Docs on how to create synced github examples

### ISSUE THREAD

**Issue by Andarist** [CompuIves/codesandbox-client#43]
I would like to incorporate sandboxes as live examples in [redux-saga](https://github.com/redux-saga/redux-saga), but as those were not generated by CRA, I'm not 100% sure what are the exact requirements.

Would be great if the list of requirements would be listed in the main README.

**Comment by CompuIves** [comment]
That's a good point! We need more documentation for CodeSandbox in general, this would fit right in. Thanks for the feedback.

As temporary solution, this is what I check for:

1. `package.json` in root
2. `src` folder
3. `src/index.js`

Not very strict, if you put have `public/index.html` we will also import the `index.html` separately.

**Comment by Andarist** [comment]
what about webpack/babel configs?

**Comment by CompuIves** [comment]
Babel/webpack configs are not parsed yet, because CRA apps don't expose these files. Support for this is the next thing on my list though, it will come with templating + ejecting support.

**Comment by Andarist** [comment]
so only stock CRA configs r supported right now?

**Comment by CompuIves** [comment]
Yes, which loaders are you missing?

**Comment by Andarist** [comment]
Oh, maybe none :P was just asking, so I would know in advance what to expect

**Comment by CompuIves** [comment]
Okies! Let me know when you need a loader, I can keep it in mind for the templates later on.

**Comment by jthegedus** [comment]
Are there plans to support arbitrary directory structures in repos?

**Comment by CompuIves** [comment]
Hey @jthegedus, I'm sorry for the late response. I missed your reply.

I'm deploying an update today or tomorrow that will allow arbitrary directory structures, we will attach a custom template for those sandboxes 😄

**Comment by CompuIves** [comment]
Oh, and this issue can be closed, the documentation is here now: https://codesandbox.io/docs

**Comment by jthegedus** [comment]
:100: Thanks!
