### ISSUE TITLE
Console is not working

### ISSUE THREAD

**Issue by harlley** [CompuIves/codesandbox-client#432]
it shows this message:
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://23m6zmlkwj.codesandbox.io') does not match the recipient window's origin ('https://new.codesandbox.io').

**Comment by gautamarora** [comment]
Hey Harlley - are you still seeing this issue?

I tried out the sandbox at https://codesandbox.io/s/23m6zmlkwj and am not seeing any errors.

![image](https://user-images.githubusercontent.com/1215971/35081144-3083494c-fbe0-11e7-9fd0-30bafaf19624.png)

**Comment by gautamarora** [comment]
awesome! could you close this issue in that case?

**Comment by harlley** [comment]
Yes. Thanks again.
