### ISSUE TITLE
Dependency dialog closes after typing "cq-d"

### ISSUE THREAD

**Issue by ZeeCoder** [CompuIves/codesandbox-client#435]
![screenshot from 2018-01-07 17-24-28](https://user-images.githubusercontent.com/3679506/34691608-05dbad9c-f4b5-11e7-9be0-8e8758b5632b.png)
👆
 This is what I see in the console.
Pretty random. 😅

**Comment by lbogdan** [comment]
Hey @ZeeCoder, thanks for your report! That's pretty random, all right! :smile: Found the issue, will fix it shortly.

**Comment by ZeeCoder** [comment]
Awesome mate, thanks 👍
