### ISSUE TITLE
postcss<6.0.10 works, postcss>=6.0.10 fails transpiling with missing module

### ISSUE THREAD

**Issue by ZeeCoder** [CompuIves/codesandbox-client#436]
Based on: https://twitter.com/ZeeCoder/status/950051949952618496

![screenshot from 2018-01-07 17-07-21](https://user-images.githubusercontent.com/3679506/34691947-3dfd26c8-f4b6-11e7-97bb-fd61e7f9d666.png)

I get this error when I try to use `postcss@>=6.0.10`.
Works fine with 6.0.9, and as far as I can tell the module (supports-color) codesandbox complains about is the exact same dep in both postcss versions.

A link that reproduces the issue:
https://codesandbox.io/s/1vk6lz431q

Downgrading to 6.0.9 fixes the issue. 🤔

Also: locally all postcss runs fine bundled.

**Comment by lbogdan** [comment]
Again, thanks for your report!
I found the culprit, if you take a look at https://unpkg.com/postcss@6.0.9/package.json and https://unpkg.com/postcss@6.0.10/package.json, you'll see that the latter contains `{ supports-color: false, chalk: false }` in the `browser` field (meaning that these packages [should be ignored in the browser] (https://github.com/defunctzombie/package-browser-field-spec#ignore-a-module), and somehow the library we're using for resolving modules doesn't support this.
We'll see what we can do and keep you posted.

**Comment by ZeeCoder** [comment]
Awesome, thanks for the update! 👍 
I've figured I found some edge-cases. 😅

And I was this 👌 close to getting my Container-Query solution finally work online this sunday. :D
