### ISSUE TITLE
embed URL doesn't work on the repo URL

### ISSUE THREAD

**Issue by faceyspacey** [CompuIves/codesandbox-client#44]
when i was first trying to figure out how to paste a full on iframe embed to Medium, I couldn't get it to work. Try it:

https://codesandbox.io/s/github/faceyspacey/redux-first-router-codesandbox

Then i realized only forks with proper IDs have this feature working.

Also, links to this sort of URL with module IDs you want opened in the editor do not open with that file.

**Comment by CompuIves** [comment]
Deploying fix.
