### ISSUE TITLE
Potential uPort/crypto problem

### ISSUE THREAD

**Issue by marcinczenko** [CompuIves/codesandbox-client#444]
The following sandbox:

https://codesandbox.io/s/407vljolv0

uses [uPort](https://www.uport.me) (a blockchain identity system) that apparently depends on `Crypto` (`v0.0.3`). When exported and run in the local environment the app works. Only when installing dependencies (`yarn install`) there is a warning:

```bash
warning uport-connect > uport > jsontokens > crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
```

When running in the sandbox, the console reports on the top-level:

```
ModuleNotFoundError
Could not find module in path: 'string_decoder/index.js'
```

and in the console:

```
Error: Cannot find module 'string_decoder/' from '/node_modules/readable-stream/lib'
```

Adding crypto@0.0.3 manually in the sandbox does not help. Any ideas? Is it possible that you filter out crypto?

**Comment by CompuIves** [comment]
Hmm, this is interesting. We've had problems with `string_decoder` before, I'll fix this issue tomorrow.

**Comment by CompuIves** [comment]
Okay! Fixed it in https://github.com/CompuIves/codesandbox-client/pull/468, it's a big change. So I'll test it more tomorrow and merge it in.

**Comment by marcinczenko** [comment]
Nice. I checked and it looks ok. Thanks!
