### ISSUE TITLE
Add framework info in user's list of sandboxes

### ISSUE THREAD

**Issue by radi-cho** [CompuIves/codesandbox-client#449]
## Is this a bug or a feature request?
Feature request.

## Current behavior
When you go to someone's profile page -> SANDBOXES you will view something like this:

![image](https://user-images.githubusercontent.com/12954909/34907066-7cfddbaa-f881-11e7-8220-b2bdc7ca59e8.png)

Table/Grid with links to the sandboxes, their titles, date of creation, likes, forks, ect...

## Expected behavior
It'll be helpful to add one more column in the grid to show which _**framework**_ is used in the sandbox (React, Vue, Preact, Svelte...). Something like this:

![image](https://user-images.githubusercontent.com/12954909/34907159-ffd8dc36-f882-11e7-8437-d5fd064430b2.png)

(This image is created with Paint.net, that's why frameworks' icons are not high-res)

## If you accept this, I'll be happy to contribute, so should I create PR or you'll take this, or this is not good idea?

**Comment by CompuIves** [comment]
Hey @radi-cho! This looks really beautiful, I'd love to have this in CodeSandbox 😄 .

**Comment by radi-cho** [comment]
So I'm gonna work on it and open new PR for it.
But do you have any preferences @CompuIves ? SVG icons or PNG images?

**Comment by CompuIves** [comment]
I'd prefer SVG, I think we have something already that we have here: https://github.com/CompuIves/codesandbox-client/blob/master/packages/common/templates/index.js#L11

**Comment by radi-cho** [comment]
OK. So you can add `someone working on it` label. I'll open PR or chat you within a day. 😄

**Comment by CompuIves** [comment]
Great @radi-cho! Thank you 😄

**Comment by radi-cho** [comment]
It's ready! #453 is merged and deployed and #451 is done so I'll close this.
