### ISSUE TITLE
when u deep link into files, apps dont work

### ISSUE THREAD

**Issue by faceyspacey** [CompuIves/codesandbox-client#45]
all these apps are just starting on the entry point. i think the app should run based on the entry point (index.js) even if u deep link into a module u want showing in the editor. my 2 cents.

**Comment by CompuIves** [comment]
You're right, I need to make this an option. I'm planning to work this out with custom renderer support.

**Comment by faceyspacey** [comment]
this will be huge for people doing the medium thing. here's why:

i want to show multiple sandboxes in the article, highlighting a specific area INSTEAD OF PASTING SCREENSHOTS OR CODE SNIPPETS.

Because I could not do that, i had to paste all these graphics. But really it should be ur widget in the correct context.

In addition, u should be able to specify the URL of the inner iframe. I realize that most apps thus far probably dont make use of the URL. But u notice how the URL changes in mine? Pretty sweet right. 

So it would be nice to be able to choose what URL it displays on. And in the future for apps that don't have URLs, be able to specify some set of variables to display what is shown in the app. 

In conclusion: u want to be able to show within the widget:
- a specific code file
- a specific portion of the app
- and have it run from the entry point so it doesnt break (as an option I guess)

My plan is this: to use that one primary sandbox, and do a great many things with it. And then use it for very many articles, promoting and talkin up CodeSandBox all the way. So I can reach the top of this chart lol:

https://user-images.githubusercontent.com/587016/27984787-c02f4f54-63de-11e7-9082-e7551b649b82.png

jk, but for real though, i dont want my users confused and spread through many sandboxes. Maybe a few. But I want one go-to sandbox that demonstrates many features. And then I can just link to the correct embed (with the correct params, options, selected module, etc) to make clear what they should be focusing on for the given lesson/portfionOfArticle.

I got another medium piece comin out thursday at the latest. If this is done, i'll have 3-5 embeds in the medium article (however many don't make the page too heavy).

**Comment by faceyspacey** [comment]
we did this. why isnt this closed.

**Comment by CompuIves** [comment]
Because someone is working on highlighting lines. Look, I'm in the jungle right now, I'll respond when I get to a proper location.

Be glad that I'm still offering support while on this vacation, which was planned before I even started working on CodeSandbox.

**Comment by faceyspacey** [comment]
Highlighting lines isn't related. It's an enhancement.

Brother man, i barely need support. Im just letting u know so ur sandbox is correct. I'd be fine using gists, and I might have to if im showing the wrong stuff in all my articles. However, it's just better for the community to work together. This is only in [small] part about my needs. I didn't really care that much about the issues, but after seeing you responded to an old issue yesterday, decided it might be helpful to give you some cues and updates on all these things to get some *perspective*. Even if it's not pleasant to hear.

*Be glad* that I've been helping u out so much and so focused on getting ur product ship-shaped. Don't make the mistake of talking to ur customers that way, even if they do first. Don't *if u want to be the best.* Some famous developers in the community have made this sorta response *ok* to provide. No, it's not. Don't say "be glad" or it will hurt you very badly in the long run. 

My tone hasn't been any of that in what i wrote u in other messages. It's nothing but strong support. Check yourself if it bothers you for other reasons. I understand you're in a stressed situation on a pre-planned trip at the peak of ur app roll-out. My point is u still gotta figure something out nevertheless.

...Neither of us can be glad. That's also an option. It's the perspective we choose to take. But one thing is for sure: this is your ship, so you steer the tone. You can redirect around any such conflict through the language you choose. Don't listen to what those 2 babel developers say. They manifested the negativity. Don't make the same mistake. Law of attraction.

This is all ur test. Get the most out of time with family in the jungle, AND make this work. Every moment u have with ur family, dont be thinking about CSB. But when u peel away for a few moments, operate like a surgeon with a patient dying on the table.

**Comment by CompuIves** [comment]
Whoops, you're right. Will close this issue.

Sorry for the snarky comment, I hadn't slept that night and was trekking through a jungle on 35 degrees Celcius, I was exhausted. Shouldn't have commented until I had some sleep.
