### ISSUE TITLE
"fs hasn't been transpiled yet." on every other refresh

### ISSUE THREAD

**Issue by ZeeCoder** [CompuIves/codesandbox-client#450]
This is another weird one:
https://codesandbox.io/s/mo7nr90vmj

If you keep refreshing the preview for this one, on every other refresh you'll be greeted with the following error:

![screenshot from 2018-01-13 22-51-16](https://user-images.githubusercontent.com/3679506/34910805-7eba1e94-f8b4-11e7-84a3-c66484f93444.png)

**Comment by ZeeCoder** [comment]
Any way I could help with this?

**Comment by ZeeCoder** [comment]
Actually, I think one of my deps requires "fs", but doesn't actually use it.
The weird thing is though, that instead of consistently failing, on every other refresh it just works. 🤔

**Comment by ZeeCoder** [comment]
This is the exact file that uses fs:
https://github.com/ZeeCoder/container-query/blob/master/packages/postcss-container-query/src/saveJSON.js

**Comment by CompuIves** [comment]
I found the issue for this: it seems like we cache some paths wrongly for native modules. I'll investigate further tomorrow 🤓
