### ISSUE TITLE
Question: Why there isn't option `svelte` in templates getDefinition function?

### ISSUE THREAD

**Issue by radi-cho** [CompuIves/codesandbox-client#451]
I was just working on #449 and saw [this function](https://github.com/CompuIves/codesandbox-client/blob/master/packages/common/templates/index.js#L118). Why there isn't option `svelte` for `themes` in function's arguments? Is this just gap or there are reasons for this? Should I fix it with the PR for #449?

![image](https://user-images.githubusercontent.com/12954909/34915336-6d20e626-f92d-11e7-9f33-47c7f0183fba.png)

**Comment by CompuIves** [comment]
Ah, that's wrong in the code. `svelte` should be there, sorry 😅

**Comment by CompuIves** [comment]
I'll close this one as it's more a code related question. I'll fix this in the redesign branch 😄

**Comment by radi-cho** [comment]
I added this in my PR, #453 - Take a look at it and leave review.
