### ISSUE TITLE
you can't view the code files in the embeddable widget

### ISSUE THREAD

**Issue by faceyspacey** [CompuIves/codesandbox-client#46]
check it:

https://medium.com/faceyspacey/redux-first-router-lookin-sexy-on-code-sandbox-d9d9bea15053

open the sidebar. try to view a file.

**Comment by CompuIves** [comment]
It works for me, it could be because you're viewing the embed as author on Medium. You can't interact with Medium widgets while editing, I always open the article in incognito to fix this.

**Comment by faceyspacey** [comment]
that's not it. I've tried other different browsers.

im not sure what ur desired experience is in the widget. I'm expecting to click a file and see the code. Instead some of the files actually render, but some like CSS and true javascript files (rather than components) show the yellow and pink page of death. 

Are u supposed to be able to code in the widget?

![screen shot 2017-07-10 at 4 16 43 am](https://user-images.githubusercontent.com/154732/28015812-9ac3f0aa-6526-11e7-94e0-c7d15e67d74c.png)

**Comment by CompuIves** [comment]
Ah, I see what you mean. What URL do you use for the embed?

**Comment by CompuIves** [comment]
It should work if you remove the `module=:id` part from the embed url, module view/project view is a good exploration point in general. I'll think some more on this.

**Comment by faceyspacey** [comment]
i used a non-deep-linked URL since the deep links weren't working. But if they were, I'd link to the routesMap.js file. I'm not sure what you mean about `module=:id`. But it's all good. I'm going to bed. I'm tired now :). As long as u know the issue, its urs to prioritize. I just wanna be able to see all my code in a widget via the sidebar.

**Comment by faceyspacey** [comment]
ps. i edited the article. it came off foolish. hopefully it's better now.

**Comment by faceyspacey** [comment]
ps. tweet if u feel it

**Comment by faceyspacey** [comment]
...oh, it's the same issue regarding not being able to evaluate any file except the entry point. ..i didnt click the switches to change to code mode or split mode. now i get it. so if u make it always render just the entry point (or perhaps have a default mode for this), as per the other Issue, ur good to go. closing this.

**Comment by faceyspacey** [comment]
lol. i finally figured it out. it's this switch:

![screen shot 2017-07-10 at 5 03 54 am](https://user-images.githubusercontent.com/154732/28017244-3142c514-652d-11e7-8c97-78b02a7d1508.png)

i've been wondering what that does. if that is beige, while u change files, it wont break. u have exactly what i want already. now i just need to see if i can make it default in the embed.

**Comment by faceyspacey** [comment]
all better now. no more beige + pink screens of death lol.
