### ISSUE TITLE
Display the actual dependency version along `latest`

### ISSUE THREAD

**Issue by vvo** [CompuIves/codesandbox-client#470]
When showing the dependencies I see:

![image](https://user-images.githubusercontent.com/123822/35217936-353e3998-ff6d-11e7-9d08-57fcabc114fa.png)

And I am fine with the usage of `latest` because that's what I actually want as a behaviour (to have the sandbox use whatever latest version).

But still, for transparency/observability/exhaustivity I would like to actually know the exact version. So something like `latest (16.2.0)` would be useful, what do you think?

**Comment by CompuIves** [comment]
That's a perfect & helpful suggestion! Would love to have this.

**Comment by CompuIves** [comment]
Just merged, will deploy tomorrow morning!
