### ISSUE TITLE
Crashes documentation on react-transition-group page

### ISSUE THREAD

**Issue by mockdeep** [CompuIves/codesandbox-client#471]
This is a copy/pasta from https://github.com/reactjs/react-transition-group/issues/278

**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

When I visit the documentation page at https://reactcommunity.org/react-transition-group/ I see the documentation initially, but I quickly get an "Aw, snap!" error from Chrome. It appears to be caused by codesandbox.io, as when I disabled the JavaScript coming from there, the page does not crash. I tried it in an incognito tab with no plugins enabled, and still saw the issue.

![snap](https://user-images.githubusercontent.com/80543/35206079-db22ac74-feee-11e7-9bc4-dccfc5acbcf4.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

Visit https://reactcommunity.org/react-transition-group/ in Chrome.

**What is the expected behavior?**

I can view the documentation.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

Chrome: Version 63.0.3239.132 (Official Build) (64-bit)
OS: Linux Mint 18.1 Cinnamon 64-bit (Kernel version: 4.4.0-71-generic)

I haven't tried this on other versions of Chrome, so not sure if it worked otherwise. I have not seen this issue on any other websites. It works fine for me on Firefox.

**Comment by mockdeep** [comment]
It does not, however, crash if I visit a page directly on codesandbox.io, say https://codesandbox.io/s/preact.

**Comment by CompuIves** [comment]
This is a really bad situation. It may be related to the OS since some of my friends had the same issue when opening the homepage with ~4 embeds a couple months ago in Linux. 

I'm thinking of adding a 'Click to Run' (https://codesandbox.io/docs/embedding/#embed-options) by default for embeds (if not explicitly specified) for Linux users, to be on the safe side.

I'll investigate further for a long term solution. I'll do some more testing with different embeds on a local linux system to find out where this crash is coming from.

Thanks for the clear information @mockdeep, this is really helpful.

**Comment by rgtk** [comment]
@CompuIves, I have noticed that crash happens after requesting these via Service Worker:

https://codesandbox.io/monaco-typings-ata.1383fafa041b0c5876ae.worker.js
https://codesandbox.io/monaco-syntax-highlighter.c900a81d5350f8f4244b.worker.js
https://codesandbox.io/monaco-typings-ata.1383fafa041b0c5876ae.worker.js

All of these seems to be related to polyfills that might do some crazy stuff to built-ins, causing the crash on Linux. It might be worth to investigate further in this direction.

**Comment by arthurdenner** [comment]
@mockdeep (and @rgtk), is this still happening for you? If not, can you close the issue?

**Comment by mockdeep** [comment]
Seems to be working now.
