### ISSUE TITLE
Feature Request: Top / Bottom layout

### ISSUE THREAD

**Issue by bigopon** [CompuIves/codesandbox-client#472]
At the moment only left / right layout is supported. It would be nice to have ability to have code on top, preview at the bottom. This layout is better for embed environment

**Comment by CompuIves** [comment]
Hah, I have this ready in our redesign! It allows you to resize the preview in any way.

It looks like this:

![screen shot 2018-01-19 at 13 38 58](https://user-images.githubusercontent.com/587016/35387243-320a587e-01cf-11e8-9381-22fc16e15c04.png)

Will be released somewhere next week :).

**Comment by bigopon** [comment]
Awesome 1111. Thanks for the info :+1

**Comment by EisenbergEffect** [comment]
FYI, once you have this ready, we'd love to start incorporating it in our Aurelia documentation. Should provide some great visibility for the cool service you are building. Looking forward to it!

**Comment by CompuIves** [comment]
Whoop! Live now! 😄 

> FYI, once you have this ready, we'd love to start incorporating it in our Aurelia documentation. Should provide some great visibility for the cool service you are building. Looking forward to it!

That's awesome!! Would be really cool to have an Aurelia template, do you have any default setup you recommend to most users?

I'll close this one now :).

**Comment by EisenbergEffect** [comment]
Oh, heck yeah! I'll give it a try this week and see what we can do for a default template. @bigopon Do you have some ideas on this? I'd love to move quickly to re-write our getting started tutorial, incorporate and do a blog post to help promote it and Code Sandbox.

**Comment by EisenbergEffect** [comment]
@CompuIves Thanks for doing this! I was playing with it today and noticed that this option wasn't available for embed ;( Any chance of adding that? Embedding is the primary context in which we need the top/bottom layout. Thanks!

**Comment by CompuIves** [comment]
Ah that makes a lot of sense @EisenbergEffect, I'll add that as an option!

**Comment by CompuIves** [comment]
Will this deploy this afternoon, you can then do this:

https://codesandbox.io/embed/new?verticallayout=1

**Comment by EisenbergEffect** [comment]
Awesome! I'll start experimenting with it this week. Do you guys think you could provide official Aurelia support like you do for other frameworks? We'd be happy to do some cross promotion of your product on our official blog if you do. Let me know @CompuIves Thanks!

**Comment by CompuIves** [comment]
That sounds like a good idea @EisenbergEffect! Do you have a recommended default template we could use?

**Comment by EisenbergEffect** [comment]
@bigopon Didn't you put one together? Is this one good? https://codesandbox.io/s/215vp3v1xj

**Comment by EisenbergEffect** [comment]
Actually, that one seems to have issues. Maybe this one is better: https://codesandbox.io/s/0wpjv6yp0

**Comment by EisenbergEffect** [comment]
There are a lot of things happening in the console. Not sure if that's something wrong with the sample or a different underlying issue. @CompuIves Let me know what you think our nest step is. Thanks!

**Comment by CompuIves** [comment]
Interesting, I see a lot of require statements in https://codesandbox.io/s/0wpjv6yp0 that resolve to a file that doesn't exist (for example `aurelia-templating-router/router-view`, which I think should be `aurelia-templating-router/dist/commonjs/router-view`).

I find the sandbox loader file really interesting, do you think it's better to build expose this one from within CodeSandbox itself?

For our templates we have two functions which we can use for configuration: `setup` and `teardown`. `setup` is ran before the evaluation starts, so for example, you could use that to setup the CodeSandbox loader in Aurelia. `teardown` is for cleanup, but often not used.

**Comment by EisenbergEffect** [comment]
I believe @niieani built the original that I forked. He's an Aurelia core team member and has a strong Webpack background so is probably the best person to describe what's happening with the module ID discrepancy.

I'd love to have something like this built into a standard Aurelia template so that people don't have to see it. It's really an infrastructure thing that isn't visible in a real Aurelia app. Is that something that's possible through the setup/teardown hooks that you are talking about?

**Comment by niieani** [comment]
@EisenbergEffect @CompuIves Continued in #578.
