### ISSUE TITLE
Adding NPM Request package and importing causes exception

### ISSUE THREAD

**Issue by RavenHursT** [CompuIves/codesandbox-client#473]
Why is this causing so many errors in the dev console?

https://codesandbox.io/s/wn98lm3j5w

**Comment by CompuIves** [comment]
Hmm, this seems to be related to this issue #444. It's fixed with #264, I'll deploy that either today or tomorrow morning.

**Comment by CompuIves** [comment]
Just deployed a fix and verified that it works!

**Comment by RavenHursT** [comment]
👍🏼👍🏼👍🏼
