### ISSUE TITLE
Hyperapp support

### ISSUE THREAD

**Issue by tyhof** [CompuIves/codesandbox-client#480]
Any chance for Hyperapp support?

**Comment by CompuIves** [comment]
Absolutely! Is there a default starter template that's normally used for Hyperapp apps?

**Comment by emersonlaurentino** [comment]
@CompuIves maybe the [Awesome Hyperapp](https://github.com/hyperapp/awesome-hyperapp) help you.

**Comment by SaraVieira** [comment]
Issue closed due to lack of activity
