### ISSUE TITLE
Framework agnostic setup with webpack

### ISSUE THREAD

**Issue by radixzz** [CompuIves/codesandbox-client#481]
Hi guys, I'm loving what you are doing thank you!.

Do you have a template to start a project without a framework? It would be great to have the option when starting a new project to setup something like HTML+Stylus+Babel. Pretty much like the Vue.js skeleton but without the framework. So I'm currently trying to mod the Vue.js by removing the framework entirely (from all the webpack and package.json configs) and works locally but when deploying with the codesandbox cli the project is recognized as to be using the react template.

Also, when redeploying with the cli I got the following errors:
```
> [error] Something went wrong while uploading to the API
> [error] Module doesn't have a unique title
```
Is there a simpler way?

**Comment by lbogdan** [comment]
Added vanilla (Parcel) template in #593 .
