### ISSUE TITLE
Sandbox created by define API can not download as a CRA application

### ISSUE THREAD

**Issue by yesmeck** [CompuIves/codesandbox-client#486]
Here is a [sandbox](https://codesandbox.io/s/jnw46698m3) created by define API, and the sidebar on the left shows it's template is `create-react-app`,  I'd expect it can be download as a `create-react-app` application.

**Comment by CompuIves** [comment]
This is a good one @yesmeck, we didn't create a CRA boilerplate around the project because we detected `package.json` and assumed the project to be CRA already.

I'll fix this.

**Comment by yesmeck** [comment]
Can confirm this issue has been fixed, thanks!
