### ISSUE TITLE
[bug] Importing projects with "proxy" directories fails

### ISSUE THREAD

**Issue by Andarist** [CompuIves/codesandbox-client#487]
I suspect this is a bug in a module resolver, wasnt sure in which repo I should report it.

**Input**
```js
import { deferred } from 'redux-saga/utils'
```

**Output**
```
Could not find module in path: 'redux-saga/utils'
```

[This](https://github.com/redux-saga/redux-saga/tree/master/utils) is how `redux-saga/utils` is structured. It is a directory which proxies to appropriate files (so main/module can be appropriately resolved in cjs/es environments) using private `package.json`.

**Comment by CompuIves** [comment]
Hmm, seems like https://github.com/CompuIves/codesandbox-client/pull/468 introduced this bug. I'll investigate and write a fix now.
