### ISSUE TITLE
The pipe character cannot be entered on Slovenian, Croatian, Serbian keyboard layouts

### ISSUE THREAD

**Issue by zocky** [CompuIves/codesandbox-client#489]
On my (Slovenian) keyboard layout, the pipe character "|" is on right alt +W , which transmits the same keycodes as alt + ctrl + W, which closes the current tab in Code Sandbox. This makes it very hard for me to enter pipes. There are also other important characters on Slovenian and other keyboard layouts that are entered with alt+ctrl+[some key].

It would be therefore very helpful if key bindings that use the alt+ctrl combination could be made configurable.

**Comment by CompuIves** [comment]
Yap, absolutely! This could be related to our recent changes in KeybindingManager, maybe @christianalfoni knows what the reason for this could be?

**Comment by zocky** [comment]
Oh, I think that "not closing the tab" isn't intentional. This is what happens when I press altGr+W  or alt+ctrl+W:

````
raven.js:422 Uncaught TypeError: Cannot read property 'filter' of undefined
    at r.closeListener (index.js:47)
    at d (raven.js:418)
````

**Comment by christianalfoni** [comment]
@CompuIves Raven error? Seems weird. It might be blocking what codesandbox is trying to do :)

**Comment by zocky** [comment]
I think raven.js might be just reporting the error, the error is really in `closeListener` in `Editor/Content/Tabs/index.js`. Which, BTW, checks directly for keyCode 87. 

Please, when/if you fix that, don't make it close the tab on hardcoded alt+ctrl+W, or I still won't be able to type a pipe.

**Comment by zocky** [comment]
This works now, so I will close it.
