### ISSUE TITLE
Scroll position is not preserved when switching between tabs

### ISSUE THREAD

**Issue by zocky** [CompuIves/codesandbox-client#492]
When I switch forth and back between editors in tabs, the cursor position is preserved, but the scroll position isn't. The editor is always scrolled to the top after switching tabs.

**Comment by CompuIves** [comment]
Good one! This definitely needs to be built.

**Comment by chakrihacker** [comment]
Hey, I can get position from this line
https://github.com/CompuIves/codesandbox-client/blob/a9934ced5758d84a5bbbe9d9fc4f342a489c7640/packages/app/src/app/components/CodeEditor/Monaco/index.js#L588

I want to save this position locally...
 and then monaco has this function

```editor.revealPositionInCenter({ lineNumber: 50, column: 120 });```

looking where to add this, need little help

**Comment by CompuIves** [comment]
That's perfect! We already cache the pos here:

https://github.com/CompuIves/codesandbox-client/blob/a9934ced5758d84a5bbbe9d9fc4f342a489c7640/packages/app/src/app/components/CodeEditor/Monaco/index.js#L598

So we only have to add that functionality here:

https://github.com/CompuIves/codesandbox-client/blob/a9934ced5758d84a5bbbe9d9fc4f342a489c7640/packages/app/src/app/components/CodeEditor/Monaco/index.js#L888

**Comment by zocky** [comment]
This now works (although there is some noticeable scroll jumping), so I will close it.
