### ISSUE TITLE
CodeSandbox feature Upload files would be great.

### ISSUE THREAD

**Issue by CodeLover19** [CompuIves/codesandbox-client#493]
It would be great if, you were able to add a feature to drag and drop files from our local to the codesandbox. I was thinking there would be an option some how, to click on the right position maybe an icon saying Upload then what would appear would be upload files, upload folders.

Simply having this feature would be great so you can test your projects on both local and codesandbox to compare.

So Recap

Drag and drop files/folders from your computer to the codesandbox so you can add them.

Have an icon that says upload then opens a window of two options, upload files/upload folders.

**Comment by wuweiweiwu** [comment]
Related to #495

**Comment by lbogdan** [comment]
Added in #685 .

**Comment by karlhorky** [comment]
From what I can tell, #685 implemented upload of files (half of this request) but the upload of folders doesn't work (at least when clicking on the upload button):

<img width="408" alt="Screen Shot 2019-05-27 at 15 07 15" src="https://user-images.githubusercontent.com/1935696/58421947-97fc0500-8091-11e9-8a23-4e3a8683d411.png">

**Comment by karlhorky** [comment]
Oh wait, it seems like dragging folders into the tree works... so it's just the button that doesn't accept folders...

**Comment by karlhorky** [comment]
Opened #1981 to track this.
