### ISSUE TITLE
Read from codesandbox

### ISSUE THREAD

**Issue by den1k** [CompuIves/codesandbox-client#494]
I'd like to write aws lambda functions as part of a codesandbox prpject. To load/deploy a lambda I need to be able to get & set the editor's files and dependencies. Is there any way to do this today? If not, are there any plans to add this feature?

**Comment by CompuIves** [comment]
That should be possible at this moment! If I understand correctly you want
something like this: https://codesandbox.io/docs/importing/#define api.
Right?

**Comment by den1k** [comment]
This let's me make a new sandbox but how do I *get* the code and dependencies of an existing sandbox programmatically?

**Comment by gautamarora** [comment]
@den1k - this is a really cool idea!

I did some digging around and think the api to get code & deps is:
`https://codesandbox.io/api/v1/sandboxes/m3nv37wx28`
`https://codesandbox.io/api/v1/sandboxes/github/reactjs/redux/tree/master/examples/todomvc`

using the response, the code is under `modules` & `directories` and the deps under `npm_dependencies`

**Comment by den1k** [comment]
@gautamarora thank you! Will give this a shot!
