### ISSUE TITLE
× ModuleNotFoundError Could not find module in path

### ISSUE THREAD

**Issue by drcmda** [CompuIves/codesandbox-client#499]
I seem to have problems including anything that imports ESM. Here is the sandbox: https://codesandbox.io/s/vjzy5o7yy0

I bablify sources using the following:

```js
{
    "plugins": [
        [
            "@babel/plugin-transform-runtime",
            {
                "helpers": true,
                "polyfill": false,
                "regenerator": true,
                "moduleName": "@babel/runtime"
            }
        ]
    ],
    "presets": [
        ["@babel/preset-env", { "loose": true, "modules": false }],
        "@babel/preset-stage-2",
        "@babel/preset-react"
    ]
}
```

and package.json points to:

      "module": "dist/index.js",

It works fine locally but something throws it off in CSB.

<img width="692" alt="screen shot 2018-02-05 at 21 35 43" src="https://user-images.githubusercontent.com/2223602/35827506-92a16c2c-0abc-11e8-8706-99927cbc8b91.png">

**Comment by CompuIves** [comment]
Hey @drcmda! Thanks for showing this issue, it seems like our resolver doesn't use package.json#module at all. I'll open a PR for a fix.

Small note:
In the case of CodeSandbox es modules are **less** performant, the reason for that is that we don't transpile our `node_modules` by default, but we have to if we find any `export` or `import` statements. We shouldn't block your development though. Fix will be live soon!

**Comment by CompuIves** [comment]
Just saw react-contextual by the way, that looks **really** cool! I love the simplicity of it.

**Comment by CompuIves** [comment]
Oh, it seems like it only works if you add a package.json in the root. We will deploy an update tomorrow that will add the `package.json` by default.

**Comment by drcmda** [comment]
@CompuIves thanks so much for all you do, couldn't be happier about csb! I just saw it's already working now, holy cow, that was fast!

> Just saw react-contextual by the way, that looks really cool! I love the simplicity of it.

Wow, that means a lot to me, thank you! 😊
