### ISSUE TITLE
Find a way to detect endless loops

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#50]
When a sandbox has an endless loop it won't stop executing until the tab kills the editor. This means that users can lose their sandbox.

Maybe there is a way to limit execution time of a sandbox, or maybe we should add a 'Run' button when you're editing your own sandbox. Would love to hear some thoughts.

**Comment by brumm** [comment]
Prior work:
https://jsbin.com/blog/protection
https://github.com/jsbin/loop-protect

**Comment by CompuIves** [comment]
Ah interesting! Just checked loop-protect and they've done a really great job, cool solution. Would be cool if we had something similar but then that it alters the AST, like a babel plugin. This is what I quickly found: https://www.npmjs.com/package/babel-plugin-looptar but I believe repl.it also has a plugin to solve this.

**Comment by CompuIves** [comment]
Just found this https://repl.it/site/blog/infinite-loops, interesting as they are using a babel plugin as well.

**Comment by gjactat** [comment]
Hello,
Maybe just being able to download the broken sandbox from the "Sandboxes" page could be an easy first step. From this point, one can fix the latest lines of code (the ones that broke the whole thing) and start a new sandbox whith that fixed code.
Or just being able to open a sandbox without any preview (just the editor, to fix things).

**Comment by dbkaplun** [comment]
This is still a bug in the React TypeScript starter.

**Comment by dbkaplun** [comment]
To freeze your tab, open https://codesandbox.io/s/react-ts and type `while (true) {}`.

**Comment by OnkelTem** [comment]
So what am I supposed to do if my box went into some loop and never stops?
I spent 7 hours on creating it and now I cannot do anything.
