### ISSUE TITLE
Add Searchbox on home page

### ISSUE THREAD

**Issue by chakrihacker** [CompuIves/codesandbox-client#503]
Sometimes, I may want to search sandboxes and I don't want to go to my profile or create sandbox just to search, I think there will be other devs who are lazy like me 🥇 .

Puns apart, Search box will help to find a demo sandbox about a topic

**Comment by chakrihacker** [comment]
If you like adding search box, I will add it

**Comment by CompuIves** [comment]
This is a really good one! Where do you think the best place would be to place the search?

**Comment by chakrihacker** [comment]
A search icon next to create sandbox button, when clicked expand search input or a search modal when text entered goes to search page

**Comment by CompuIves** [comment]
Hmm, I'm not sure if that would fit in all cases. Maybe we can also add something in the header instead? Or maybe that wouldn't fit as well 🤔

**Comment by lbogdan** [comment]
Hey @chakrihacker ,

Does redirecting / to the dashboard for logged in users solve this for you?

**Comment by chakrihacker** [comment]
yes, thanks closing this issue
