### ISSUE TITLE
New preview can overflow the sidebar

### ISSUE THREAD

**Issue by k15a** [CompuIves/codesandbox-client#504]
Hey,

nice work on codesandbox 2.5!
I've found a little ui bug:

![screen shot 2018-02-07 at 16 07 15](https://user-images.githubusercontent.com/20357450/35923636-17512164-0c21-11e8-9a98-9bd6c862d309.png)

**Comment by CompuIves** [comment]
Thank you! That's a good one, funny bug.

**Comment by k15a** [comment]
`z-index: 1000000;` and fixed 😀

**Comment by lbogdan** [comment]
Closing this, since it should be fixed by the recent switch to VSCode as the default editor. Feel free to reopen if this is still happening.
