### ISSUE TITLE
Closing all tabs leads to a grey screen

### ISSUE THREAD

**Issue by ForsakenHarmony** [CompuIves/codesandbox-client#506]
Close all tabs -> Whole page is grey

**Comment by CompuIves** [comment]
Yep, bug!

**Comment by chakrihacker** [comment]
How can you close all tabs, the opened tab can't be closed

**Comment by ForsakenHarmony** [comment]
Middle click

**Comment by wuweiweiwu** [comment]
@CompuIves What should be the behavior/view when all tabs are closed

**Comment by ForsakenHarmony** [comment]
it should probably just not allow the last tab to be closed

**Comment by CompuIves** [comment]
Yes, I think we should add a check for middle click as well.

**Comment by CompuIves** [comment]
Fixed this together with another issue. Will go live today!
