### ISSUE TITLE
Resizable window preview can get too small

### ISSUE THREAD

**Issue by samdenty99** [CompuIves/codesandbox-client#510]
Loving the new update ❤️ 

The minimum height should be something like:
![image](https://user-images.githubusercontent.com/13242392/35948417-4d8e2158-0c64-11e8-9fef-f9acf6f744a5.png)

Instead of:
![image](https://user-images.githubusercontent.com/13242392/35948457-6e416aae-0c64-11e8-9669-f39a9fb3726c.png)

Once it gets to that point, it's bad from a ux perspective as it's difficult to resize again.

Side-note the window should be prevented from being dragged off-screen as it's impossible to bring back onto screen (with the buttons being in the window)

**Comment by CompuIves** [comment]
Fixed with PR #519! Will be live in 10min
