### ISSUE TITLE
Typescript in-editor support partially broken at least in create-react-app-typescript

### ISSUE THREAD

**Issue by jtheisen** [CompuIves/codesandbox-client#515]
When you select the "React TypeScript" template, you get in-editor complaints about react modules not being found.

The sandbox compiles and runs fine, but the editor doesn't seem to think so:

![image](https://user-images.githubusercontent.com/1516294/35976934-ed72703e-0ce1-11e8-88fc-1c9bb281534a.png)

**Comment by CompuIves** [comment]
Interesting, I can't reproduce this on my side. I'll do some more investigation!

**Comment by jtheisen** [comment]
I'm talking about the version hosted at codesandbox.io I should add.

**Comment by lbogdan** [comment]
@jtheisen Do you still have this issue?

**Comment by jtheisen** [comment]
@lbogdan Actually no, I forgot this is still open.

A while ago Ives suggested on twitter to clear all cookies and that fixed it.
