### ISSUE TITLE
Delete sandboxes from Profile/Sandboxes

### ISSUE THREAD

**Issue by donavon** [CompuIves/codesandbox-client#52]
Allow the user to delete one of their sandboxes from their Profile/Sandboxes page. Either on hover, hamburger menu, or static icon. We probably want a confirmation as well, warning the user that: _"This action is permanent and **can not be undone**! Are you sure?"_

**Comment by CompuIves** [comment]
Great idea! Thanks a lot for opening this.

We could also show an 'undo' button in the notification before sending. I know that the notification still has some functionality for it as I built it for that intention. Sadly I didn't have time to implement it at that time.

The API also has the functionality to 'undelete' a sandbox, fully depends on what's easier to implement.

**Comment by donavon** [comment]
Undelete functionality would require that we keep and display a list of sandboxes in your "recycle bin". Probably overkill. Delete. Gone. (for MVP)

What is your preference on showing the delete icon? Additional column, on hover, or Delete from a hamburger menu. And if on hover, where would the icon be?

This just in case I take a stab at the feature (no promises). 😉

**Comment by CompuIves** [comment]
Yap, you're right. I'd say that it should be a (small) additional column, this way the user can easily find it without having to interact with it first.

**Comment by donavon** [comment]
Something like this? (faint, then brighter on hover)

![image](https://user-images.githubusercontent.com/887639/28174153-af315d94-67be-11e7-9659-5f45acea8a22.png)

**Comment by CompuIves** [comment]
Ex-act-ly!

**Comment by HoldOffHunger** [comment]
I'm only seeing these trashcan icons intermittently, at best.

**Comment by tofanelli** [comment]
In my storage management view, the trash can icons doesn't shows up neither I have a place to manage the files uploaded. Is there a way to delete from the CLI?

![image](https://user-images.githubusercontent.com/5512922/41782944-fa4277d4-7611-11e8-9b2f-f17d4d86ad71.png)
