### ISSUE TITLE
undefined is logged as null in the built-in console

### ISSUE THREAD

**Issue by noinkling** [CompuIves/codesandbox-client#522]
`console.log(undefined)` results in `null` being printed in the built-in console, rather than `undefined` as expected.

**Comment by CompuIves** [comment]
Hmm, interesting. This is probably related to #511. Maybe we need to separately check for undefined @samdenty99?

**Comment by samdenty99** [comment]
I've started adding the actual types to the dispatcher => https://github.com/samdenty99/codesandbox-client/commit/f2442aa4f174a4e93c9abacfa1ac3e7a235d4c83. All that's left is to integrate the react components + the test logs.

It'll also allow the use of the DOM inspector from the `react-inspector` package + `console.table`

**Comment by CompuIves** [comment]
Wow, that looks badass @samdenty99!
