### ISSUE TITLE
version of bootstrap changed on import from github

### ISSUE THREAD

**Issue by pdngithub** [CompuIves/codesandbox-client#523]
I imported a project from github (https://github.com/pdngithub/NavbarComp) into https://codesandbox.io/s/qzwn6lmzr6. The version of bootstrap changed from the one I that is specified (^3.3.7) in the github package.json to the latest. I deleted it, then used "dependencies", "Add Dependency" button on the sidebar to try to add it back in. The first time I got the latest again, but I don't know what I clicked in the search window so that it ignored the version I selected. Then I tried again and got 3.3.7, but without the "or later" caret. I then realized I could just type the package.json.

**Comment by CompuIves** [comment]
Hmm, that's interesting. That means that we have changed the package.json during import. I'll check if there is any step where we do that unknowingly or deliberately.

**Comment by lbogdan** [comment]
Closing this, as I can't really replicate it. Also, it looks like you have an intensive `console.log()` loop in that sandbox, that pretty much grinds everything to a halt. @pdngithub Fell free to reopen if you still have version issues.
