### ISSUE TITLE
Possible to drag preview "off-screen"

### ISSUE THREAD

**Issue by donavon** [CompuIves/codesandbox-client#528]
It's possible to drag the preview to where you can't move it again. A page reload is necessary to regain control.

![codesandbox drag bug](https://user-images.githubusercontent.com/887639/36037808-d7f74298-0d8b-11e8-8b6d-e9988bcd686e.gif)

**Comment by aaronshaf** [comment]
Same problem here. Related issue: I need a way to hide the browser (especially when I already have the preview in another tab).
