### ISSUE TITLE
Ability to hide the preview browser

### ISSUE THREAD

**Issue by aaronshaf** [CompuIves/codesandbox-client#530]
I need this especially when I have opened the preview browser in a new tab. Thanks!

**Comment by CompuIves** [comment]
Very good one, I knew that I forgot something with the redesign! 😅

**Comment by iDVB** [comment]
I'm looking at the code committed here and its not clear to me what this nets out to in the UI.
How CAN we hide that preview panel when we pop it into external browser window/tab?

**Comment by CompuIves** [comment]
You can find the button here (red arrow): 
![image](https://user-images.githubusercontent.com/587016/48800069-0a69e200-ed09-11e8-8d2b-7f82b29741e8.png)

**Comment by iDVB** [comment]
Doh! Thanks.
My issue was that I had experimental VSCode editor turned on and for that
one those buttons are missing. Not sure if that is intensional or not.

**Comment by CompuIves** [comment]
Ahhh, that makes sense!

For VSCode we have it next to the 'Split Editor' button, or you can do (CTRL/CMD + SHIFT + D).

**Comment by aoberoi** [comment]
I know this is an old issue, but I think its the most relevant for my question.

Is there a way to hide the "Browser" part of the preview, and still keep the "Terminal", "Console", "Problems", etc panels which are usually split below?

I'm building a Node application that isn't consumed by a browser, so the Browser panel always displays 404. But the Terminal and other panels still have valuable output.

**Comment by KibitO69** [comment]
> You can find the button here (red arrow):
> ![image](https://user-images.githubusercontent.com/587016/48800069-0a69e200-ed09-11e8-8d2b-7f82b29741e8.png)

Thank you!

**Comment by garethx** [comment]
Note also that you can drag the terminal to be the first panel opened, or set it to be like that within the config file if you're sharing the sandbox with others. See https://codesandbox.io/docs/faqs#can-i-open-the-terminal-or-console-or-test-panel-instead-of-the-browser-in-a-sandbox

**Comment by dandv** [comment]
Sorry, but I don't see any button to hide the browser. Has it been moved?

![image](https://user-images.githubusercontent.com/33569/86336571-e1a80f00-bc04-11ea-9965-b0b6ff35cdfc.png)

**Comment by bduffany** [comment]
Some feedback: The "toggle preview" button is very non-obvious. Feels non-intuitive that the button is in the editor window as opposed to the browser itself, or maybe even in the "view" menu.

**Comment by BassemMagdi0007** [comment]
> Sorry, but I don't see any button to hide the browser. Has it been moved? The preview button hides the entire right panel, including the console, which I want to show.
> 
> ![image](https://user-images.githubusercontent.com/33569/86336571-e1a80f00-bc04-11ea-9965-b0b6ff35cdfc.png)


Well actually i'm trying to get to this view but i don't know how, tried the 'flip full layout' but that didn't work with me.
