### ISSUE TITLE
Reopening sandbox using the blue "play" like button stays stuck on loading git repositories

### ISSUE THREAD

**Issue by kaidoj** [CompuIves/codesandbox-client#532]
Reopening sandbox using the blue "play" like button stays stuck on "fetching git repository". I have to refresh the page and then it loads sandbox. Firefox 58.0.2.

**Comment by alekhka** [comment]
Same with me in Chrome version 63.0.3239.132 , it is easily solved by refreshing the page as you told, but it's a little annoying.

**Comment by CompuIves** [comment]
Good one! This must be a regression from the rewrite to Cerebral.

**Comment by CompuIves** [comment]
Fixed, will be live later today!
