### ISSUE TITLE
import gists

### ISSUE THREAD

**Issue by vedam** [CompuIves/codesandbox-client#537]
Hi all,
first of all thx for this great tool.
I'm wondering if codesandbox has an option to define a gist as external ressource.
i.e. I created a basic css-reset-gist and wanted to integrate it in all of my sandboxes.
I was not able to find some info about such a use-case, so I'm asking here.
thx in advance

PS: I saw the git-repo-support, but I think a complete repo is too much for a simple code-snippet

**Comment by viankakrisna** [comment]
why not publish it to npm? or you can use https://rawgit.com/ to serve it as an external asset

**Comment by vedam** [comment]
thx for the hint.
I wanted to avoid publishing to npm for such a small snippet.
I'll give rawgit a try.
Thx again

PS: Should I close or is this still an interesting info for anyone else?

**Comment by CompuIves** [comment]
Good tip @viankakrisna, I think we can close this one. Hopefully people will find this issue when they have a similar question 🙂.
