### ISSUE TITLE
Errors updates from other module does not update after module changed in monaco editor

### ISSUE THREAD

**Issue by br1anchen** [CompuIves/codesandbox-client#538]
I am fairly new user to codesandbox.io, it might be an user error after all :P

**Bug reproduce**:
If user removed template file `Hello.js`, and recreated an new `Hello.js` file, and export correct default module.
Original `index.js` will still have error info about `Can not find module in path './Hello'`

**Screenshot**:
<img width="1918" alt="screen shot 2018-02-11 at 23 03 30" src="https://user-images.githubusercontent.com/1086461/36079152-3973c35c-0f80-11e8-84b5-70b89afbff45.png">

After some digging, I think the reason causes it is that, after new `Hello.js` is created, observable `store.editor.erros` is notified through reaction `disposeErrorsHandler` ([here](https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/pages/Sandbox/Editor/Content/index.js#L119)), since the `modue` now is `Hello.js` instead of `index.js`, it will not call `setModelMarkers` with corresponding `model` ([here](https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/components/CodeEditor/Monaco/index.js#L352)).

Then I think if any errors updates for other module will be retrieved by not-current module at all. It seems working fine with `CodeMirror`.

**Comment by CompuIves** [comment]
Fixed by you! :D
