### ISSUE TITLE
"Import from GitHub" page sometimes shows invalid output URL

### ISSUE THREAD

**Issue by bengummer** [CompuIves/codesandbox-client#54]
If I go to https://codesandbox.io/s/github and enter `http://github.com/test/123` it output a sandbox URL of `https://codesandbox.iohttp://github.com/test/123` (or `https://www.github.com/test/123`) it outputs something like `https://codesandbox.iohttps://www.github.com/test/123`.

Should be a relatively uncommon edge case if people are copy + pasting GH URLs directly from their browser into the page.

I'm happy to take a look at fixing this :)

![image](https://user-images.githubusercontent.com/1089897/28186343-ad1f63fa-67cf-11e7-86f5-225221e78742.png)

**Comment by CompuIves** [comment]
Oh good find! I probably didn't check good enough.

Would be great if you could take a look at it 😄 .
