### ISSUE TITLE
ctrl+S occasionally shows the browser Save As dialog

### ISSUE THREAD

**Issue by zocky** [CompuIves/codesandbox-client#544]
I haven't figured out the pattern, but sometimes the keyboard event handler that should handle ctrl+S fails to suppress the default behaviour, and the Save As dialog pops up.

**Comment by CompuIves** [comment]
Ah, a friend of mine found the scenario: if you press CTRL+V, then remove your finger from V and move it to S you get the dialog.

Pretty interesting issue, do you think this is fixable @christianalfoni?

**Comment by zocky** [comment]
I don't think that's the only way it occurs. And showing the save as dialog isn't the only symptom, it also doesn't actually save the file. My guess is that saving fails silently for some reason, and `event.preventDefault()` never gets called.

**Comment by CompuIves** [comment]
Fixed this one!
