### ISSUE TITLE
Zen mode does not use full height

### ISSUE THREAD

**Issue by TryingToImprove** [CompuIves/codesandbox-client#546]
Going into Zen-mode does not use the space the removed top bar had. See picture

![image](https://user-images.githubusercontent.com/1690457/36150088-b6b42f8a-10c2-11e8-8bf8-9f1912374009.png)

**Comment by CompuIves** [comment]
Hmm, I've never seen this before. Which browser are you using?

**Comment by TryingToImprove** [comment]
Google Chrome is up to date
Version 64.0.3282.140 (Official Build) (64-bit)

**Comment by CompuIves** [comment]
Oh! I see what you mean now, I'll write a fix now.

**Comment by TryingToImprove** [comment]
Here is a animated GIF of the issue:

![codesandbox](https://user-images.githubusercontent.com/1690457/36150563-6966ab48-10c4-11e8-9cc1-1b30542b419c.gif)

**Comment by CompuIves** [comment]
Pushed! Will go live somewhere this afternoon :smile:
