### ISSUE TITLE
The Navigator in Preview failed to behave as a normal browser.

### ISSUE THREAD

**Issue by Williammer** [CompuIves/codesandbox-client#547]
The Navigator in Preview acts quite strange when I'm playing with it. :(
For example, if I inputted a new url in the addressBar and press Enter, the 'Back' icon didn't activate and Navigator has no history new added.

Although it's quite minor as there's not much need to use the Navigator as a normal browser, it'll be more user-friendly to have it feature-completed.

I can create a PR for this issue, please let me know if I missed sth on this and it is the expected behavior. :)

**Comment by lbogdan** [comment]
Closing this, as this is expected behavior, and #548 was also closed.
