### ISSUE TITLE
Visibility issue of Helper text for errors/issues in code.

### ISSUE THREAD

**Issue by venkat4541** [CompuIves/codesandbox-client#554]
The tooltip prompt that explains possible reason for an error is not visible completely if the error is towards the top of the editor(screenshot attached). 

It should be easy to fix by mentioning a higher z-index but I think the dev/maintainer should decide on the behavior: if the z-index should be edited or if the tooltip should show up below the mouse pointer to avoid overlapping with editors tab bar.

![codesandbox2](https://user-images.githubusercontent.com/10798758/36214880-8ca21a16-1178-11e8-983a-19f23393c53a.png)

**Comment by CompuIves** [comment]
Good one! I committed a fix, I decided to show the text over the tabs so we don't have to change the render logic of Monaco.

**Comment by CompuIves** [comment]
Oh, should be live in an hour 😄. I'm first getting dinner
