### ISSUE TITLE
Make multi-line error messages in the console shorter

### ISSUE THREAD

**Issue by zocky** [CompuIves/codesandbox-client#555]
Basically, error messages in the console should be wrapped with `<details><summary>{firstLine}</summary>{otherLines}</details>`, to reduce extreme clutter in the console resulting from React error messages.

It would also be nice if filenames/line numbers in the error message were clickable, like they're in the preview window.

**Comment by joeynimu** [comment]
Seems like it's not that complex I can have a look at this.

**Comment by CompuIves** [comment]
That's great, thank you @joeynimu!

**Comment by joeynimu** [comment]
I addressed this here https://github.com/CompuIves/codesandbox-client/pull/620 I guess this can be closed?

**Comment by CompuIves** [comment]
Yep! Thank you very much 😄
