### ISSUE TITLE
Content jumps when hovering on file tree

### ISSUE THREAD

**Issue by smably** [CompuIves/codesandbox-client#557]
Noticed a little UI issue, repro'd in latest Chrome. Hovering over the entries in the file tree causes a glitch on the right side of the page:
![codesandbox_bug](https://user-images.githubusercontent.com/1466970/36260820-820ee0d0-1230-11e8-8170-5a17fe5423c9.gif)
(Please excuse my bad tab hygiene!)

**Comment by CompuIves** [comment]
Oii this is really bugging me! It seems like a scroll bar appears or something?

Would someone be interested in investigating this one? I can look at it at the end of this week if it's still open.
