### ISSUE TITLE
CodeMirror scrolling is not working

### ISSUE THREAD

**Issue by pavloDeshko** [CompuIves/codesandbox-client#558]
when using CodeMirror editor scrolling moves only the browser's viewport, not editor's. PageDn/PageUp works fine
Firefox 58

**Comment by phpsmarter** [comment]
yeah .Same way . when close CodeMirror , can't see content of files, because of  console screen. My browser is safari,  Chrome  working is normal .

**Comment by CompuIves** [comment]
Good one, I'm working on a layout refactor that should fix this. Hopefully done this week!

**Comment by CompuIves** [comment]
Fixed, will deploy today!

**Comment by phpsmarter** [comment]
Thank you. Provide so wonderful tools !
