### ISSUE TITLE
Codesandbox does not work on Safari

### ISSUE THREAD

**Issue by LAITONEN** [CompuIves/codesandbox-client#562]
Keep getting errors like this when opening any project:
<img width="1280" alt="screen shot 2018-02-17 at 2 27 54 pm" src="https://user-images.githubusercontent.com/23742868/36340913-d30a1648-13ee-11e8-9e29-1659b944cd99.png">

The errors above came from [this project](https://codesandbox.io/s/lr6qm56637).

This is what I see in the browser window when I open a new project:
<img width="1280" alt="screen shot 2018-02-17 at 2 29 46 pm" src="https://user-images.githubusercontent.com/23742868/36340936-2ef39092-13ef-11e8-8b9c-89088fe57b2f.png">

Everything works fine on Google Chrome.

Running on:
macOS Sierra: 10.12.6
Safari: 10.1.2

**Comment by CompuIves** [comment]
Thanks for letting me know if this! I'll check this out tomorrow.

**Comment by CompuIves** [comment]
Fixed, will deploy today!
