### ISSUE TITLE
Allow directly linking to a URL

### ISSUE THREAD

**Issue by phiresky** [CompuIves/codesandbox-client#57]
I can't see a way to do this currently. Example:

I want to directly link `/topics/props-v-state` for the react-router example https://codesandbox.io/s/r0wXp0Njw

Same thing for URL parameters, I want to pass external data to a sandbox via an URL parameter, but that doesn't seem possible currently.

I'm assuming this is not implemented right now because [getSandboxOptions](https://github.com/CompuIves/codesandbox-client/blob/a03d4f02405978a8ed081d99146ba9f4b656de81/src/common/url.js#L3) seems to be used to pass external data to the sandbox, and that doesn't contain a parameter for the initial path.

Adding this would make this project very useful for me, right now I have to use codepen.io which allows reading external URL parameters (and thus passing data to a snippet) but has many other limitations. Thanks!

**Comment by CompuIves** [comment]
Thanks for sending in this feature request!

To be clear, you want a way to specify the default url to open when sharing a sandbox? In that case this PR: https://github.com/CompuIves/codesandbox-client/pull/49 will allow that. I can finish up the PR today and deploy it.

**Comment by phiresky** [comment]
Exactly. I didn't see that PR. Nice!

**Comment by CompuIves** [comment]
Credits to @faceyspacey 😄 . I'll close this issue as soon it's deployed.

**Comment by faceyspacey** [comment]
General configuration vars would be nice too--then u can customize how ur embed looks/behaves in different places. Similar to vars passed to flash embeds back in the day.

Let me know if u need anything to finalize module+URL deep linking.

**Comment by CompuIves** [comment]
Oops, forgot to mention it here! Yesterday I deployed the functionality, thanks to @faceyspacey for building this. Cc @phiresky

**Comment by phiresky** [comment]
Thank you!
