### ISSUE TITLE
Error: Cannot find module 'quasar-framework' from '/'

### ISSUE THREAD

**Issue by BellenWalker** [CompuIves/codesandbox-client#576]
Today I’m encountering this error that cannot find quasar-framework module, it’s working fine until this morning.
I removed this dependency and reload it, but still didn’t fix it.

When launching the application,  it didn’t scan dependency folder I can see from the error log, but scanned components folder instead, turn out it couldn’t find it.
Any ideas on this? really appreciate it. 

Error log:
Error: Cannot find module 'quasar-framework' from '/'
    at https://mo0ooy4pl9.codesandbox.io/static/js/sandbox.6ecbe0fa.js:3214:2972
    at p (https://mo0ooy4pl9.codesandbox.io/static/js/sandbox.6ecbe0fa.js:3214:2159)
    at n (https://mo0ooy4pl9.codesandbox.io/static/js/sandbox.6ecbe0fa.js:3214:2120)
Error: Cannot find module 'quasar-framework' from '/components'
    at https://mo0ooy4pl9.codesandbox.io/static/js/sandbox.6ecbe0fa.js:3214:2972
    at p (https://mo0ooy4pl9.codesandbox.io/static/js/sandbox.6ecbe0fa.js:3214:2159)

**Comment by CompuIves** [comment]
Hmm, that's really weird. I haven't deployed anything yesterday.

I'll do some more investigating now1

**Comment by CompuIves** [comment]
Hmm, it seems like `quasar-framework` removed its `main` fields in `package.json` from `0.15.0`, which is required for the framework to work if you call `import 'quasar-framework';`.

You can see the difference here:

If you go to https://unpkg.com/quasar-framework@0.15.1 you will see a `Not Found`. If you go to https://unpkg.com/quasar-framework@0.14.9 you will see the necessary file.

If you downgrade `quasar-framework` to 0.14.9 it should work again: http://localhost:3000/s/7k73vmknk1
