### ISSUE TITLE
Not possible to try/catch dynamic import()

### ISSUE THREAD

**Issue by niieani** [CompuIves/codesandbox-client#578]
Continuing from #472 conversation with @EisenbergEffect and @CompuIves:

@CompuIves What seems like a new bug to me, it seems to be impossible to catch dynamic `import()` statements within CodeSandbox. It used to work, but now you get these errors in the console and in the view. So even though everything works, the error overlay kicks in. Here's the code for the `getModule` that I'm using [here](https://codesandbox.io/s/2w8J7n9W):

```js
async function getModule(moduleName) {
  const hasJS = moduleName.endsWith('.js');

  try {
    return await import(`${moduleName}` /* webpackMode: 'eager' */);
  } catch (e) {}

  try {
    return await import(`./${moduleName}` /* webpackMode: 'eager' */);
  } catch (e) {}

  try {
    return await import(`${moduleName}/dist/commonjs/${moduleName}` /* webpackMode: 'eager' */);
  } catch (e) {}

  if (moduleName.includes('/')) {
    try {
      const [dep, ...path] = moduleName.split('/');
      return await import(`${dep}/dist/commonjs/${path.join('/')}`);
    } catch (e) {}
  }

  if (!hasJS) {
    return await getModule(`${moduleName}.js`);
  }
}
```

If we could access the module cache (together with the filenames) from within the app to check which path exists or doesn't, without having to trying to load it first, it would solve any issues here. Normally (outside of CodeSandbox), there exists only one right way to access a module, and that's provided either by Webpack or SystemJS. 

For example, we map `aurelia-templating-router/[anything]` to `aurelia-templating-router/dist/commonjs/[anything]` in the Node environment, but to `aurelia-templating-router/dist/native-modules/[anything]` in Webpack environment, and to `aurelia-templating-router/dist/systemjs/[anything]` under JSPM.

The crux is that Aurelia's loader depends on **file paths** being resolvable to modules, so that it can do its magic with components by e.g. loading the related (same-named) `.html` together with the `.js` next to it.

Here I had to "hack" it like that just so it works, but some recent change seems to have disallowed catching imports.

**Comment by CompuIves** [comment]
Ah, yes I see what happens here. It seems like a change got through that causes us to throw during transpilation when we can't find the module. I'll write a fix for that now.

> If we could access the module cache (together with the filenames) from within the app to check which path exists or doesn't, without having to trying to load it first, it would solve any issues here. Normally (outside of CodeSandbox), there exists only one right way to access a module, and that's provided either by Webpack or SystemJS.

When we integrate the loader into CodeSandbox we can easily use the `Manager` instance of CodeSandbox to test file existence. I think that's the best way to approach it 😄. You can see an example here:

https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/sandbox/eval/presets/angular-cli/index.js

For the Angular example we have a setup function that loads polyfills specified in the `angular-cli` configuration file. This function is executed before transpilation, in runtime. We could add a CodeSandbox loader that has the manager as property to check for modules.

If you're interested in writing the preset, these actions need to be done:

1. We need a preset, (example: https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/sandbox/eval/presets/create-react-app/index.js).
2. We need a template definition, (example: https://github.com/CompuIves/codesandbox-client/blob/master/packages/common/templates/react.js)

I can open a branch that sets up the basics for Aurelia template & preset, maybe someone else could then write the loader that uses the CodeSandbox manager?
