### ISSUE TITLE
Is it possible to programatically show files?

### ISSUE THREAD

**Issue by davestewart** [CompuIves/codesandbox-client#582]
Hi there,

Firstly, this project is amazing! Thanks so much for creating it. Certainly the most awe-inspiring talk at the VueJS conf too 😃 

So, questions:

- Is there any way to programatically show a file in the editor?
- And if so, is there, or would there be any way to trigger that from the running app preview?

I ask because I'm wondering if I could write my next talk / demo in CS and it would be really nifty to be able to click a button in the running app and show code from that file.

Thanks again,
Dave

**Comment by CompuIves** [comment]
Hey @davestewart, I'm really happy to say that's actually possible already!

Here's an example sandbox of the usage:

https://codesandbox.io/s/3k03oxm471

The necessary code:

```js
dispatch(actions.editor.openModule("/src/Hello.js"));
```

**Comment by davestewart** [comment]
YOU. ARE. AMAZING.

Out if interest, is that documented?

**Comment by CompuIves** [comment]
This is quite hidden currently 😅. We could definitely use documentation for this, would you be interested in writing some?

We store all documentation here: https://github.com/CompuIves/codesandbox-client/tree/master/packages/homepage/content/docs. I think it makes sense to create a separate entry for `codesandbox-api`.

All generated docs can be found in `/packages/codesandbox-api/docs`. Hmm, now I think of it, maybe it would make more sense to just host the generated content on codesandbox.io. It would simply require an extra build step in https://github.com/CompuIves/codesandbox-client/blob/master/Gulpfile.js... Would you be interested in that instead? 😄

**Comment by davestewart** [comment]
> would you be interested in writing some?

Flattered that you would ask!

I do like docs writing, but finding the time at the moment is sooo difficult.

Why don't I get used to the platform and maybe it will come naturally out of that?

**Comment by CompuIves** [comment]
> Why don't I get used to the platform and maybe it will come naturally out of that?

Sounds good! Let me know if you have any questions 😄
