### ISSUE TITLE
Editor does not mark // comments as errors in css files

### ISSUE THREAD

**Issue by kpldvnpne** [CompuIves/codesandbox-client#583]
I stumbled upon this editor recently, and so far I'm loving it. However, just now, I wasted about 3 hours to notice that I had // comments in .css files, which the editor didn't point out. Considering how far this editor goes on to show minute errors or redundant codes, I think this simple task of pointing // comments in .css as error should be addressed.

I am just a beginner, so I might not know that this is not actually an issue. If so, please remove this. Thank you

**Comment by lbogdan** [comment]
@kpldvnpne Do you still have this issue? It's strange, because it should show warnings / errors if you comment CSS with `//`:

![](https://bogdanl.tinytake.com/media/75bdb6?filename=1525308362800_03-05-2018-03-45-57.png&sub_type=thumbnail_preview&type=attachment&width=480&height=173)
