### ISSUE TITLE
Zeit integration is not working

### ISSUE THREAD

**Issue by chakrihacker** [CompuIves/codesandbox-client#584]
I am working on this [https://codesandbox.io/s/4q3qj58l4x](sandbox) and tried to deploy in [https://csb-4q3qj58l4x-dteqvombqa.now.sh/](zeit) and it's not working and then I tried deploying new sandbox, it also didn't worked. So I started looking into zeit logs and `The project was built assuming it is hosted at /s/new/.`

And there is another issue.

Let's say you deployed a sandbox to zeit and then updated the sandbox, you cannot redeploy it

**Comment by CompuIves** [comment]
I found this issue of this! It seems like the `homepage` field prevents the deployment from happening. Will write a fix for it now.
