### ISSUE TITLE
Documentation nav links using relative path

### ISSUE THREAD

**Issue by mdxprograms** [CompuIves/codesandbox-client#585]
I noticed that when clicking on a left nav link instead of going to `https://codesandbox.io/docs/importing` it goes to `https://codesandbox.io/docs/docs/importing`

After being on `docs/importing` and clicking on configuration it goes to:
`https://codesandbox.io/docs/importing/docs/configuration`

**Comment by jthegedus** [comment]
I second this. All navigation from the docs page
[https://codesandbox.io/docs/](https://codesandbox.io/docs/)
 an additional `docs/` added to the subsequent route
[https://codesandbox.io/docs/ **docs/** embedding](https://codesandbox.io/docs/docs/embedding)

**Comment by CompuIves** [comment]
Good one! I think it should be fixed if we put a `/` before the url here: https://github.com/CompuIves/codesandbox-client/blob/master/packages/homepage/src/components/StickyNavigation.js#L163 and here: https://github.com/CompuIves/codesandbox-client/blob/master/packages/homepage/src/components/StickyNavigation.js#L173

Is anyone interested in opening a PR for this?

**Comment by CompuIves** [comment]
That's super great @mdxprograms! Thank you 😄

**Comment by CompuIves** [comment]
Can close this one now 😄
