### ISSUE TITLE
The browser component doesn't return to normal size after hiding the console

### ISSUE THREAD

**Issue by radi-cho** [CompuIves/codesandbox-client#586]
![sandbox](https://user-images.githubusercontent.com/12954909/36627431-47096718-194b-11e8-8337-88d769de2696.gif)

It will be fine to restore the normal size of the browser window when we hide the console.

**Comment by lbogdan** [comment]
It seems to happen after you manually move or resize the browser window. What if you press the "Align to Right" button and try showing / hiding the console again?

**Comment by CompuIves** [comment]
> It seems to happen after you manually move or resize the browser window. What if you press the "Align to Right" button and try showing / hiding the console again?

Yep, that's intended behaviour. However, when you press a button (like 'Refresh') it will also see that as dragging, which causes it to lose its alignment.

Would be great if we could detect/fix this.

**Comment by CompuIves** [comment]
We now have anchoring which returns browser to normal size in case it's not moved yet.
