### ISSUE TITLE
Use existing repository folder instead of different repository

### ISSUE THREAD

**Issue by diegohaz** [CompuIves/codesandbox-client#587]
First of all, @CompuIves, thank you so much for yours and all the contributors work. The more I use CodeSandbox the more I get amazed. That's a really fantastic tool.

I'm working on some examples for https://github.com/diegohaz/reas using CodeSandbox (see README).

I see that there's GitHub integration, but it seems like it only exports to a different repository.

I would like to have each of the examples in a `/examples` folder inside `reas` repository, and keep it in sync with live demos in CodeSandbox.

Do you think this is possible?

**Comment by CompuIves** [comment]
Heya! Thanks for the kind words, that's really appreciated 😄.

Yep, that should be possible.

If you have an example in eg. `examples/test` then the corresponding GitHub URL should be https://codesandbox.io/s/github/diegohaz/reas/tree/master/examples/test (notice the last part, it's the directory). 

Or do you mean something else?

**Comment by lbogdan** [comment]
Hey @diegohaz , just doing a routine spring cleanup here, does @CompuIves's comment answer your question?
