### ISSUE TITLE
Tab name is wrong for link

### ISSUE THREAD

**Issue by acdcjunior** [CompuIves/codesandbox-client#592]
Check the tab name:

https://codesandbox.io/s/l22y3yk1vm?module=%2Fsrc%2Finput%2FField.vue

**Comment by CompuIves** [comment]
Good find! Seems like something goes wrong in the state management.

**Comment by gautamarora** [comment]
this seems to be an issue for react templates too: https://codesandbox.io/s/81m8q639q0?module=%2Fsrc%2FXMLToReact.js

**Comment by joeynimu** [comment]
I could look at this @CompuIves

**Comment by CompuIves** [comment]
@joeynimu is working on this 😄

**Comment by steventsao** [comment]
What is the expected tab name for the react template? @gautamarora

**Comment by lbogdan** [comment]
@acdcjunior @gautamarora @joeynimu Tab names look ok to me now, was this solved meanwhile?

**Comment by CompuIves** [comment]
I fixed it.
