### ISSUE TITLE
External dependencies sometime are not yet loaded

### ISSUE THREAD

**Issue by vvo** [CompuIves/codesandbox-client#597]
On this CodeSandbox preview: https://24zn89jm5p.codesandbox.io/?cities=Boston&productTypes=Speaker

I get:
![image](https://user-images.githubusercontent.com/123822/36786569-21cf83b2-1c87-11e8-8b99-7932fd876e14.png)

The preview only seems to constantly fail while the editor fails one time out of two.

Shouldn't the dependencies be loaded before the actual sandbox code?

**Comment by lbogdan** [comment]
Hey @vvo ,

Unfortunately it's very hard to synchronise loading of external resource scripts with sandbox code execution. A workaround would be to wait for the script to load (in this particular case, wait until the global `instantsearch` is available on `window`) before running your code.

I made a naive example implementation here https://codesandbox.io/s/wk26r3qo3l , please take a look and let me know what you think.

**Comment by vvo** [comment]
Hi @lbogdan I never imagined it to be hard frankly because I don't know the internal code of the loading at all. But I thought since those are just script tags it could be achieved (again I am sure this is hard yes). For our own usecase yes we can find workarounds like using actual npm imports but I guess most people using external dependencies will have the same issue.

Maybe for now since it's unstable and requires workarounds that are not documented/hard to implement (wait until x) we should hide this feature? I expected it to work flawlessly.

Thanks!

**Comment by CompuIves** [comment]
Hmm, I think this should work without a workaround regardless. I was expecting that it would work on an event, I can fix this with this PR #702. Let's keep it open until that one is merged in.

**Comment by CompuIves** [comment]
Fixed in master, will be deployed either this evening or tomorrow morning.

**Comment by vvo** [comment]
You 🤘
