### ISSUE TITLE
parcel-bundler examples failing

### ISSUE THREAD

**Issue by vvo** [CompuIves/codesandbox-client#599]
Excited by the release of this new template, I tried it immediately, with mixed results unfortunately for now:
- https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/InstantSearch.js (error loading external script)
- https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/JavaScript%20client (html is not displayed)

**Comment by CompuIves** [comment]
Ah, I forgot to override the `entry` for the Parcel template. Big mistake on my side, I'll commit a fix now!

**Comment by CompuIves** [comment]
Not too fast! This last commit fixes the last example, I'll fix the first example now.

**Comment by CompuIves** [comment]
Confirming:

http://pr600.cs.lbogdan.tk/s/github/algolia/instantsearch-templates/tree/master/src/InstantSearch.js

http://pr600.cs.lbogdan.tk/s/github/algolia/instantsearch-templates/tree/master/src/JavaScript%20client

**Comment by vvo** [comment]
👌 thanks a lot

**Comment by vvo** [comment]
Oops one thing though, the http://pr600.cs.lbogdan.tk/s/github/algolia/instantsearch-templates/tree/master/src/JavaScript%20client now shows only the html page, but does not executes js or css

**Comment by CompuIves** [comment]
Hm, I should add some intergration tests for Parcel. I'll look into it no!

**Comment by CompuIves** [comment]
New URLs:

http://pr601.cs.lbogdan.tk/s/github/algolia/instantsearch-templates/tree/master/src/InstantSearch.js

http://pr601.cs.lbogdan.tk/s/github/algolia/instantsearch-templates/tree/master/src/JavaScript%20client
