### ISSUE TITLE
Update default template of parcel bundler

### ISSUE THREAD

**Issue by Noviny** [CompuIves/codesandbox-client#603]
Components that would default to create-react-app now default to parcel. Specifying an main of a .js does not resolve.

Handy example link: https://codesandbox.io/s/l58n9yjq5m

This is a fork of the official example of how to use the post API. Added a `{ main: index.js }` as my assumption is that only files with a `.html` as a main should use parcel.

**Comment by Noviny** [comment]
(Forgot to add, codesandbox is awesome and amazing, and I have absolutely been loving using it)

**Comment by CompuIves** [comment]
Heya, thanks for letting me know of this! I reverted the default back to `create-react-app` for now, until we have a better solution.

I'll keep this issue open until we know how to handle this 😄

**Comment by Noviny** [comment]
Thanks for resolving that so quickly!

**Comment by SaraVieira** [comment]
This has been fixed in the meantime :)
