### ISSUE TITLE
Previously react-create-app detected template is now parcel

### ISSUE THREAD

**Issue by vvo** [CompuIves/codesandbox-client#604]
Example: https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/React%20InstantSearch

I tried to look where the detection was done without luck.

**Comment by CompuIves** [comment]
I just deployed something for this (about 10 minutes ago). It should work
again if you make an empty commit to bust cache.

Sorry for the inconvenience!

**Comment by vvo** [comment]
Lemme try

**Comment by CompuIves** [comment]
The code can be found here by the way 😄 

https://github.com/codesandbox-app/codesandbox-importers/commit/d0dbc6674ccb403f1912d52423e813be6a460d09

**Comment by vvo** [comment]
Does it means we miss some dependencies in our templates for them to be considered create-react-app?

**Comment by vvo** [comment]
Why not do:

```js
if (totalDependencies.indexOf('react-scripts') > -1) {
  return 'create-react-app';
}

return 'parcel';
```

So that by default it's parcel when we don't know what to do.

**Comment by CompuIves** [comment]
Yes, that was the initial setting. However, templates that are created using the POST API expect until now that it is `create-react-app`. It's sort of a breaking change I noticed (related #603).

I'm thinking of using `create-react-app` when we detect `react-scripts` || `react`. I think that will solve most cases. I'm open to other ideas though, maybe there's a much better way to fix this.

**Comment by vvo** [comment]
Weirdly our template was a GitHub one, with a dependency of react-scripts so I am failing at understanding why it was failing

**Comment by CompuIves** [comment]
Ah, the deploy of yesterday went later than I expected which caused it to default to `parcel` regardless of `react-scripts`. Maybe the repo was used at that time.

Yesterday was quite a hectic day 😅. But everything seems to be back to normal now.

**Comment by vvo** [comment]
Thanks, it works now :)
