### ISSUE TITLE
Pass view=split in url does not load a view

### ISSUE THREAD

**Issue by maxfrigge** [CompuIves/codesandbox-client#605]
When loading codesandbox and passing the query param `view=split` it doesn't load the split view. It seems that this was working before as for example `react-table` uses it for their docs.

I have also created an issue in `react-table`.
https://github.com/react-tools/react-table/issues/834

**Comment by CompuIves** [comment]
Ah, this seems to be broken because of the redesign. I opened a PR to fix it, will merge it in today and deploy it in about 2 hours 😄.
