### ISSUE TITLE
"go to definition" event (ctrl+LMB) occasionally change file content to content from opened func

### ISSUE THREAD

**Issue by koyta** [CompuIves/codesandbox-client#606]
I lost my code (but rebuilt with GitHub) because of bug. CTRL + LMB opens the function definition, but for some reason replaces all the code of the initially opened file with the code from the file where the function definition is located. As a result, there are two files with the same code. Fortunately, the code can be returned to CTRL + Z, otherwise, all the code is overwritten (for example, if you pressed CTRL + S after opening the function definition)

**Comment by CompuIves** [comment]
I think I fixed this one with a release I'm going to do somewhere this week. Thanks for the clear report!

**Comment by CompuIves** [comment]
This one is fixed!
