### ISSUE TITLE
when you delete a dep and then re-add it, you have to refresh to see it

### ISSUE THREAD

**Issue by faceyspacey** [CompuIves/codesandbox-client#61]
What I'm doing is deleting a dependency, and then adding it right back `@next`. You can do things to try trigger it to be used like flipping our favorite module/project switch, but you have to refresh. 

In general, the `loading dependencies` UI elements are not quite in sync with when it's really ready. 

It's a small edge case, but at some point deleting/editing/re-adding deps is something you're gonna wanna polish.

Basically I suggest that when this shows:
![screen shot 2017-07-17 at 9 17 58 pm](https://user-images.githubusercontent.com/154732/28300598-7167afb6-6b35-11e7-9b3c-82cd97bd5e8b.png)

This also *immediately* shows:
![screen shot 2017-07-17 at 9 18 01 pm](https://user-images.githubusercontent.com/154732/28300597-7166068e-6b35-11e7-922b-f50257d7fd85.png)
> this will show if you do various things such as toggle the module/project view switch.

And then when it's truly done loading, it refreshes the iframe. There is also an issue with the package appearing in the `dll` bundle. So even if you just refresh a package (instead of doing the fancy thing I do where I'm switching `dist-tag`), it won't work, and you'll need to refresh the page. 

Refreshing the page automatically for the user (provided there is complete loading indicators) may be a fine stop-gap solution to get this done quicker. Although obviously the ideal solution, is *just* the inner iframe refreshes (while keeping the same URL it was on).

**Comment by CompuIves** [comment]
Ah, good points. I kept the dependency loading only after you type something because I don't want to trigger a build for a list of dependencies that's not going to be used. Since we only have 2 packagers that can bundle. Or am I missing something? 

The refresh of the inner frame is a very good suggestion, that's something that definitely needs to happen.

**Comment by CompuIves** [comment]
This has been fixed!
