### ISSUE TITLE
CompileError: Sass file in a subfolder could not found

### ISSUE THREAD

**Issue by boriskaiser** [CompuIves/codesandbox-client#613]
If I import a new Sass file in a subfolder, it will not be found.

I noticed that the path is wrong:

![image](https://user-images.githubusercontent.com/252113/36910254-7ae2ef92-1e40-11e8-9af1-89bbcbd3f858.png)

The correct path is not `/src/styles/variables`, but `/src/styles/module/variables`.

I use `parcel` template.

Link to CodeSandbox: https://codesandbox.io/s/4l28y68ow

Is there a solution for this?

Thanks in advance,
Boris

**Comment by CompuIves** [comment]
Hey! Thanks for the detailed report and reproduction sandbox. I'm now looking into a fix.

**Comment by CompuIves** [comment]
Should be live in ~15 min!

**Comment by boriskaiser** [comment]
Unfortunately, this still does not work:

![image](https://user-images.githubusercontent.com/252113/36918189-562611ac-1e59-11e8-84dc-548e3ef4650a.png)

**Comment by CompuIves** [comment]
Hmm, what happens if you refresh? Our service worker could still have the old cached version.

**Comment by boriskaiser** [comment]
Yo, I had a cached version — Now it works:

![image](https://user-images.githubusercontent.com/252113/36920683-d01e5caa-1e61-11e8-8952-54de870a5525.png)

---

But 😊 ...

I just tested the same thing with an NPM package. And the path is unfortunately not correct:

![image](https://user-images.githubusercontent.com/252113/36921301-21a0665c-1e64-11e8-983a-16d682fe0420.png)

When I import a `node_modules` package with a tilde `~`, it works fine.

But if something is imported inside the package — like this one at [srbreakpoints](https://github.com/superReal/srbreakpoints/blob/master/src/styles/srbreakpoints.scss#L5) — the path is wrong.

The correct path is not `/src/~/@superreal/srbreakpoints/src/styles/core/helpers`, but `/node_modules/@superreal/srbreakpoints/src/styles/core/helpers`.

Is this part of this issue or should I create a new one?

**Comment by CompuIves** [comment]
Hah, this is great! I'll make sure to fix that tomorrow, could you open a
new issue for it?

**Comment by CompuIves** [comment]
With that being great I mean, thanks for finding these inconsistencies  😊
