### ISSUE TITLE
More options for API

### ISSUE THREAD

**Issue by Samuell1** [CompuIves/codesandbox-client#617]
Its there a way to use same options for post API as Embed options? Mostly i like to see `view` and `module`

**Comment by CompuIves** [comment]
This one is a fun one to think about. We could add a separate parameter called `query` maybe and add that to the redirect if it exists. I think that's the simplest solution. What do you think? I can do that tomorrow morning if that's fine by you 😄

**Comment by Samuell1** [comment]
Yeah i think that will be fine

**Comment by CompuIves** [comment]
Hey! Just deployed the changes, I also wrote some documentation about it here: https://github.com/CompuIves/codesandbox-client/blob/master/packages/homepage/content/docs/2-importing.md#define-api

**Comment by kostasx** [comment]
@CompuIves The link above is broken. Any idea whether this is still available somewhere?

**Comment by CompuIves** [comment]
Is this the documentation you're looking for?

https://codesandbox.io/docs/learn/sandboxes/cli-api#define-api

**Comment by kostasx** [comment]
By the way, is there a way for supplying the view=preview option when using the GET request method as mentioned in the docs? I've tried almost everything but I could only get the file=/index.html option to work.
