### ISSUE TITLE
feature: URL param for line # to highlight :)

### ISSUE THREAD

**Issue by faceyspacey** [CompuIves/codesandbox-client#62]

**Comment by CompuIves** [comment]
Yes! I've heard this more, I need to look into how to line highlight properly.

**Comment by Haroenv** [comment]
This is possible in embed now, is that also in the main editor?  https://codesandbox.io/docs/embedding/#embed-options

**Comment by lbogdan** [comment]
Closing this, as we now support highlighting in the embed, like @Haroenv said, there was no further activity since, and also I don't think highlighting makes that much sense in the main editor anyway. @faceyspacey Feel free to reopen if I'm talking nonsense. 🙂
