### ISSUE TITLE
MIME type problem, interferes with styles and likely other things

### ISSUE THREAD

**Issue by kylecordes** [CompuIves/codesandbox-client#622]
Consider this Angular CLI project, one of a long series of short examples I help publish online:

https://github.com/AngularBootCamp/filtered-list-via-observable

It works locally, and it works in StackBlitz:

https://stackblitz.com/github/AngularBootCamp/filtered-list-via-observable

The code works in CodeSandBox, but the **styles are broken**:

https://codesandbox.io/s/github/AngularBootCamp/filtered-list-via-observable

A bit of investigation in the browser dev console shows the problem is that a CSS file (whichever happens to be under /assets, but it really shouldn't matter to CodeSandbox) is served with a mime type of text/html and thus rejected by the browser:

```
styles.css:14 Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://jp3mw38oq3.codesandbox.io/assets/materialize/materialize.css".
```

It appears that the bug is simple. Code sandbox needs, but does not yet have, the bit of logic that has been floating around Web servers for 20+ years to translate from common file extension patterns to the correct MIME type.

**Comment by CompuIves** [comment]
Hey @kylecordes, thanks for taking the time to let me know!

I found the problem behind it, the request to the file fell back to the `index.html` because our server couldn't resolve the correct file. I fixed that and the sandbox should work now.
