### ISSUE TITLE
Make the "delete sandbox" button red

### ISSUE THREAD

**Issue by zocky** [CompuIves/codesandbox-client#631]
And possibly add a trash icon to it.

As it is, blue and sitting under the dropdown for changing sandbox privacy, it looks very much like confirmation button for the form.

**Comment by ArStah** [comment]
Agree on that

**Comment by CompuIves** [comment]
Agreed as well, would someone be interested in opening a PR for this?

**Comment by jdonor** [comment]
Sounds good. Are we using something for icons already? FontAwesome, etc.

**Comment by CompuIves** [comment]
Yep, we're using `react-icons` for our icons 😄. http://gorangajic.github.io/react-icons/md.html
