### ISSUE TITLE
Reverting history pop not reflected in address bar

### ISSUE THREAD

**Issue by pshrmn** [CompuIves/codesandbox-client#633]
If an application "blocks" a navigation that is triggered using the browser's back button, the URL in the address bar is inconsistent with the actual location.

Clicking the back (or forward) buttons immediately update the location, which an application must detect by listening for `popstate` events. "Blocking" in this case consists of using `history.go` to revert to the previous location. This behavior is different than clicking a link, which can avoid the browser knowing about the navigation altogether.

### Actual Behavior

https://codesandbox.io/s/x2wr3p21qo

Click on the `/other` link and the pathname is now `/other`.

If you click on the `Home` link, then cancel the prompt, the pathname is still `/other`.

If you click on the fake browser's back button, then cancel the prompt, the pathname is `/`. However, if you open the console and type `window.location.pathname`, you will see that the actual pathname is `/other`.

### Expected Behavior

The app detects the `popstate` and the URL in the fake browser's address bar reflects the true state.

----

I haven't looked into how CodeSandbox's fake browser works, so I'm not sure whether this has a quick fix or if it will require something more involved. I can probably take a look at it sometime soon.

**Comment by lbogdan** [comment]
Hello, @pshrmn, thanks for the detailed report! I was the one implementing the "fake browser", I'll take a quick look at it now.
If you also want to take a look, the code is in https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/sandbox/url-listeners.js and the pr is #198 .

**Comment by CompuIves** [comment]
Hmm yes, I think we should also take a look at hash route handling. I've seen some use cases where it behaves differently from the browser.

**Comment by lbogdan** [comment]
That was actually an easy fix, the overriden `history.go()` inside the preview iframe was not sending the URL changes to the editor.

@CompuIves The only other ongoing issue with the "fake browser" that I know of is that clicking on a hash link (i.e. `<a href="#somehash">`) doesn't get you to the DOM element with `somehash` id - issue #572 2nd point.
