### ISSUE TITLE
"include" section in tsconfig.json

### ISSUE THREAD

**Issue by PavelPZ** [CompuIves/codesandbox-client#637]
I have this section in tsconfig.json:

```
  "include": [
    "src/**/*",
    "node_modules/reactxx-mdi/typings.d.ts",
    "node_modules/reactxx/typings/**/*"
  ],
```

It seems than CodeSandbox build process ignote it, see

[![Edit reactxx](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1zro5x26zq?module=%2Ftsconfig.json)

I have some ambient definitions in NPM packages, which must be included explicitly

Thanks a lot for clarification

**Comment by CompuIves** [comment]
Ah, yes, our bundler only transpiles files that are directly required. We only use `compilerOptions` from the config at this moment. We could implement the behaviour of `ts-loader` from `webpack`, do they handle `include` currently?

**Comment by PavelPZ** [comment]
Ok, thanks a lot for info. Problem is a bit more serious, see my comment in [636](https://github.com/CompuIves/codesandbox-client/issues/636)
