### ISSUE TITLE
Border on "file explorer" overlaps the preview

### ISSUE THREAD

**Issue by TryingToImprove** [CompuIves/codesandbox-client#638]
See the picture below...

![image](https://user-images.githubusercontent.com/1690457/37282343-5d97249c-25f4-11e8-9ce5-925c8bb2a88e.png)

**Comment by SaraVieira** [comment]
Hey! 

I am doing some issue cleanup. Can you tell me how you managed to reproduce this bug?

**Comment by TryingToImprove** [comment]
Can't really remember. It a old issue :-)

**Comment by SaraVieira** [comment]
Doooooope
