### ISSUE TITLE
Drag resizers haven't got a max-height set

### ISSUE THREAD

**Issue by samdenty** [CompuIves/codesandbox-client#639]
The drag resizers can be unexpectedly resized larger than their parents boundaries. Setting the `maxHeight` prop to `100%` should resolve it.

### Resizing the component beyond it's boundaries

![](https://i.imgur.com/tIkgORr.gif)

**Comment by CompuIves** [comment]
Oh I didn't know the fix would be that easy! Would you be interested in opening a PR for this @samdenty99?

**Comment by Komar0ff** [comment]
I can take it upon myself if no one is against it

**Comment by CompuIves** [comment]
Awesome @Komar0ff! That would be very nice

**Comment by lbogdan** [comment]
@Komar0ff Did you get a chance to take a look at this?

Might be related to https://github.com/CompuIves/codesandbox-client/issues/1615 .

**Comment by samrith-s** [comment]
If no one is on it, can I pick this up? @lbogdan @SaraVieira

**Comment by samrith-s** [comment]
Created a PR for this. https://github.com/CompuIves/codesandbox-client/pull/1691

Do check it out whenever! 😄

**Comment by lbogdan** [comment]
It can be tested here http://pr1691.cs.lbogdan.tk/s/new , btw.

**Comment by samrith-s** [comment]
Cool, thanks!

**Comment by CompuIves** [comment]
We can close this one now, thanks @samrith-s!!

**Comment by samrith-s** [comment]
Welcome @CompuIves! 😊
