### ISSUE TITLE
TypeError - Could not fetch Dependencies: Failed to fetch

### ISSUE THREAD

**Issue by aulisius** [CompuIves/codesandbox-client#640]
I believe  #144 is repeating again. My console has gone crazy

![image](https://user-images.githubusercontent.com/6629172/37296200-3491cf24-2640-11e8-962d-babc57582344.png)

**Comment by CompuIves** [comment]
Heh, interesting. It seems like it can't find the resource because it has trouble with the `.` in the URL. I'll check if I can fix that.

**Comment by CompuIves** [comment]
Oh hmm I think it's something different. It seems like the file pointed out by `main` in `driver.js` doesn't exist: https://unpkg.com/driver.js@0.1.4

**Comment by NataliaTepluhina** [comment]
I have `ERR_NAME_RESOLUTION_FAILED` error on any added dependency (and one 403 at the start of fetching):
![2018-03-13_7-45-37](https://user-images.githubusercontent.com/18719025/37324644-069cbbee-2693-11e8-9ad7-6a4d84ec0809.png)

**Comment by aulisius** [comment]
@CompuIves , Yes that was the issue. Fixed at library's end with https://github.com/kamranahmedse/driver.js/pull/12. The sandbox is loading now. Closing the issue. 👍
