### ISSUE TITLE
Static class properties don't work w/ the Parcel JS template?

### ISSUE THREAD

**Issue by RavenHursT** [CompuIves/codesandbox-client#641]
This works on the typical React project.  But seems to not be working for the Parcel template one:

https://codesandbox.io/s/40m6k0x31w

**Comment by RavenHursT** [comment]
Hmmm.. apparently neither does object destructuring (`let foo = {...obj}`). :-/

**Comment by CompuIves** [comment]
Hmm, does it work in the Parcel template locally? You can fix it by
creating a .babelrc config and adding the `stage-0` or `env` preset.

**Comment by CompuIves** [comment]
Example: https://codesandbox.io/s/rlo9k7q6o4

**Comment by RavenHursT** [comment]
Perfect! Thank you!

**Comment by kostasx** [comment]
The "env" wasn't working on my sandboxes. The following addition to `.babelrc` worked:

```
   ...
  "plugins": [ 
    ...
    "@babel/plugin-proposal-class-properties" 
  ],
  ...
```
