### ISSUE TITLE
Could not find module in path: 'redux-persist/integration/react'

### ISSUE THREAD

**Issue by ivinjose** [CompuIves/codesandbox-client#645]
First of all, thanks for the codesandbox project. First time user and loving it.

Im getting the below error. 
`Could not find module in path: 'redux-persist/integration/react'` 

In Index.js this is what Im doing:
`import { PersistGate } from "redux-persist/integration/react";`

Couldnt find any leads on net. Same repo runs fine on my local. 

Any hints on what this might be?

**Comment by CompuIves** [comment]
Ah, I think I know why this is happening. It seems like we have trouble resolving the `main` in `package.json` in https://unpkg.com/redux-persist/integration/react/. This is an interesting case, because it seems like there's only a package.json in the folder which then resolves to a parent directory.

I think it should work by changing the statement to:

`import { PersistGate } from "redux-persist/lib";` in the meantime.

I can give this weekend a bit more time to debug and hopefully fix it 😄.

**Comment by developit** [comment]
Just wanted to bump this up a bit - seems like this issue applies to any node_modules import where the package.json cannot be resolved within `dirname(<import>)`. For example:

```
import 'unistore/preact'
// resolves to node_modules/unistore/preact.js 
// (works because the package.json is at node_modules/unistore/package.json)

import 'preact-material-components/TopAppBar'
// fails to resolve to node_modules/preact-material-components/TopAppBar/index.js
// (fails because the package.json is at node_modules/preact-material-components/package.json)
```

**Comment by median-man** [comment]
I believe I may be experiencing the same issue.
```javascript
import { render, cleanup } from 'react-testing-library';
```
This line produces the following error in the test console:
```
Could not find module in path: 'react-dom/test-utils' relative to '/node_modules/react-testing-library/dist/index.js'

ModuleNotFoundError: Could not find module in path: 'react-dom/test-utils' relative to '/node_modules/react-testing-library/dist/index.js'
...
```

**Comment by median-man** [comment]
I deleted the broken sandbox and made a fresh test. It seems to be working fine now. Thank you.

Working sandbox: https://codesandbox.io/s/p5026oxx97

**Comment by CompuIves** [comment]
Cool! Glad that it works @median-man 😄. Closing this issue now.

**Comment by probablyup** [comment]
I'm seeing this happen for the styled-components beta as well :/

https://codesandbox.io/s/mmvjo5l948

**Comment by CompuIves** [comment]
Hey Evan,

Does this still happen to you? For me the sandbox works.

**Comment by probablyup** [comment]
Appears to work now! Thanks for whatever y'all did.
