### ISSUE TITLE
React: A cross-origin error was thrown.

### ISSUE THREAD

**Issue by emzero** [CompuIves/codesandbox-client#648]
When using the React template, the errors are not displayed properly. Instead this message is shown:

```
Error
A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
```
Per the documentation: If you use Webpack, we recommend using the cheap-module-source-map setting in development to avoid this problem.

Can this be applied in Codesandbox so we get proper error descriptions?

**Comment by Komar0ff** [comment]
There is a similar issue #667

**Comment by CompuIves** [comment]
Yes, I'm closing this one for #667, even though this one is older. I responded to the other issue and just saw this one 😅.
