### ISSUE TITLE
Feat req: Customize UI

### ISSUE THREAD

**Issue by corysimmons** [CompuIves/codesandbox-client#649]
Writing tests with Jest, browser just takes up space.

**Comment by corysimmons** [comment]
For that matter, it'd be nice to set defaults for UI in settings. Like "Browser > Disabled", "Tests > Enabled".

**Comment by CompuIves** [comment]
Makes sense. I want to be able to swap out the browser with other views, like console, jest view. Kind of like you suggested 😄.

**Comment by corysimmons** [comment]
Yea that'd be really nice! Like some sort of dropdown at the top-right of these panels that let's you swap out what's there with a different panel, or hide the view entirely. Then just cache the user's preference might be best UX.
