### ISSUE TITLE
"Run All Tests" doesn't seem to work

### ISSUE THREAD

**Issue by corysimmons** [CompuIves/codesandbox-client#650]
Tests run fine on load, don't auto-add new tests, and when I push "Run All Tests" button they don't run. Terminal just blanks.

**Comment by CompuIves** [comment]
Heh, interesting. Maybe the cache is not reset.

Do you have a sandbox with a small reproducible example? It seems to work here for me: https://codesandbox.io/s/n9m2w9q8x0

**Comment by corysimmons** [comment]
Oh, maybe I'm crap. 😅 
Trying to make a reduced test case, I noticed I kept trying to use `@cerebral/mobx-state-tree` because it was first in list when adding deps. rip.

I still suspect there's some weirdness and will keep my eyes peeled and create some reduced test cases if I run into it.

Sorry! Love your site/work-ethic! Can't wait for CodeSandbox to take over the world.
