### ISSUE TITLE
Can't find variable: regeneratorRuntime

### ISSUE THREAD

**Issue by tryzniak** [CompuIves/codesandbox-client#656]
Hi. I think I found a bug. Running the following code in the vanilla template:
```javascript
function fetchStuff(i) {
  return Promise.resolve(i);
}

async function doSomething(i) {
  return await fetchStuff(i);
}

doSomething(10).then(i => console.log(i))

```
Produces the following error `ReferenceError
Can't find variable: regeneratorRuntime`.
That code works perfectly fine on node v8.9.4.

I hope that was helpful and thank you for your great editor 👍

**Comment by CompuIves** [comment]
Hey! Thanks for submitting this issue, it's a good one.
I found a similar issue here https://github.com/parcel-bundler/parcel/issues/871, it seems that CodeSandbox handles `babel-preset-env` in an incorrect way. I have a branch open that will fix this. In the meantime you can use the proposed solution in the thread, this one: https://github.com/parcel-bundler/parcel/issues/871#issuecomment-370135105.

Here's a sandbox with the solution: https://codesandbox.io/s/20n9yj7w9n.
