### ISSUE TITLE
app: can't download project

### ISSUE THREAD

**Issue by edm00se** [CompuIves/codesandbox-client#658]
Inexplicably, I can't download a project I worked on for a couple hours. I've tried in Chrome (latest stable) and Firefox (latest stable), to the same result of nothing happening. No download triggers, no alert or warning, nothing being logged to the JS console in the browser.

![codesandbox_nodownloadforme](https://user-images.githubusercontent.com/622118/37792444-d273fb22-2dd9-11e8-8821-396c0f6606dd.gif)

**Comment by CompuIves** [comment]
Hmm, that's weird. It works for me here, on which template is this happening?

**Comment by edm00se** [comment]
A parcel template.

**Comment by CompuIves** [comment]
Hmm, okay. I'll do a quick test on Windows to see if it happens there now.

**Comment by edm00se** [comment]
I am on Windows, so that might be something. Still, strange it would be OS specific. Thanks.

**Comment by CompuIves** [comment]
Hm, seems like I can download https://codesandbox.io/s/vanilla on Windows as well. 

I think I see what's going wrong after taking a look at the code. Does your project have a `src` directory?

**Comment by edm00se** [comment]
It does not have a src directory.

The vanilla template downloaded fine.

**Comment by CompuIves** [comment]
Ah, I found the issue then! Sorry for that, I'll commit a fix now

**Comment by edm00se** [comment]
Cool. Thank you.

**Comment by CompuIves** [comment]
Commited to master, it should take about ~20 minutes before it's deployed

**Comment by edm00se** [comment]
Excellent. I'll check again in about half an hour.

**Comment by CompuIves** [comment]
Great! You might have to refresh twice to see the changes: the first load the client will install the new application which will be applied the second load. Otherwise opening in incognito works as well 😄

**Comment by CompuIves** [comment]
New deploy has version `PROD-1521746611`, it's in the bottom left corner!

**Comment by edm00se** [comment]
I checked early, the client picked up the change, I reloaded and was able to see the new deployed version. Download works, thanks!

**Comment by CompuIves** [comment]
Perfect! 😄
