### ISSUE TITLE
Can't Upload project using CLI

### ISSUE THREAD

**Issue by hiteshsahu** [CompuIves/codesandbox-client#659]
While using CLI tool I am keep getting error:

> Something went wrong while uploading to the API > [error] You're not signed in

I have logged into Sandbox client using my GitHub credentials

Attached screenshot for reference:

<img width="546" alt="screen shot 2018-03-23 at 3 01 28 pm" src="https://user-images.githubusercontent.com/4076925/37822048-617816ba-2eab-11e8-897c-9e8a8e5f54d7.png">

**Comment by CompuIves** [comment]
Hey! Sorry for the late response, I'm looking into it now. Which version of CodeSandbox CLI are you using?

**Comment by CompuIves** [comment]
This one has been fixed!
