### ISSUE TITLE
Export & Import for React applications

### ISSUE THREAD

**Issue by YazanAabeed** [CompuIves/codesandbox-client#663]
### Is this case right? or I missing something?
When I use this code in code sandbox its work:
```
// File Photo.js
export default Photo;

// File index.js
export Photo from "./Photo/Photo";
export Comments from "./Comments/Comments";
```

But when I install the project using GitHub on my local machine its not working until I change the code to this:
```
// File Photo.js is the same
// File index.js
import Photo from "./Photo/Photo";
import Comments from "./Comments/Comments";

export default {
    Photo,
    Comments
};
```

The error is shown on my local machine `'./../components' does not contain an export named 'Photo'`

**Comment by YazanAabeed** [comment]
Hello @Komar0ff 
Thank you for your help and your time 😄 🔥

**Comment by CompuIves** [comment]
Closing this one since it's solved! Thanks @Komar0ff 😄
