### ISSUE TITLE
Inaccurate views on public sandboxes

### ISSUE THREAD

**Issue by artivilla** [CompuIves/codesandbox-client#664]
I could be entirely wrong but is there a way to validate if the views on public sandboxes represent views by other people and not myself? What about incognito mode? How is this measured and is there a FAQ I might have missed?

**Comment by CompuIves** [comment]
Hey! We keep track of who viewed the sandbox to make sure that someone cannot press refresh 10 times to get 10 views. However, I found a leak in this, we use cookies to track uniques, but this doesn't work exactly when we process a view from eg. `new.codesandbox.io`. We'll disable counting those views. Thanks for letting me know!

I'll close this issue as soon as that's in.

**Comment by CompuIves** [comment]
Fixed with https://github.com/CompuIves/codesandbox-client/commit/54b97d9f22d13ca3a2d18cf7e102a7af26ff758b
