### ISSUE TITLE
[Website] Improving Feature Highlights section

### ISSUE THREAD

**Issue by donysukardi** [CompuIves/codesandbox-client#666]
Currently the Feature Highlights section is a bit cluttered. It could be improved by adding separators between the grid items.

I have two proposals below for the improvement. I'm leaning more towards Design 2 as left aligned text is easier to read.

Design 1:
<img width="1066" alt="design-1" src="https://user-images.githubusercontent.com/410792/37887270-68c01c8e-30f3-11e8-8fec-175eab27582f.png">

Design 2:
<img width="1066" alt="design-2" src="https://user-images.githubusercontent.com/410792/37887272-6a0da782-30f3-11e8-8fd8-620978007fc4.png">

I'd love to hear your thoughts on this, @CompuIves. I can take on the work once there's a consensus on the design.

**Comment by CompuIves** [comment]
This is **so** nice! I briefly discussed your suggestions with @bazzjuh, I personally find the second suggestion the most beautiful. But I'd like to hear Bas' thoughts on this as well 😄

**Comment by donysukardi** [comment]
If there's no further objection, I'll go ahead and work on it. We can take it from there :D Wait for my PR!
