### ISSUE TITLE
User Menu is missing after deleting the current Sandbox

### ISSUE THREAD

**Issue by ReneCode** [CompuIves/codesandbox-client#669]
- open a sandbox from "my sandboxes"
- in "project info" click "delete sandbox"
- => a new blank (react) sandbox apears
- => the User Menu (top right corner) is missing when clicking on the user-avatar. (only the hint apears)

**Comment by CompuIves** [comment]
Very interesting, thanks for sending the bug report!

This is probably because there is an inconsistency in the Cerebral state.

**Comment by steventsao** [comment]
I have not been able to reproduce this issue. See attempt https://youtu.be/BIJrf0b9dtw

**Comment by CompuIves** [comment]
Thanks for the reproduction @steventsao! I think we can close this one.
