### ISSUE TITLE
No way to scroll files list in embed mode

### ISSUE THREAD

**Issue by maciejmyslinski** [CompuIves/codesandbox-client#670]
There is no way to scroll files list in embed mode 😢 

![Alt text](https://monosnap.com/file/VAkYRsM5hFXMfgeWYQk7NZOlGDGVi8.png)

**Comment by CompuIves** [comment]
Yep, you're completely right. The embed deserves much more UI work, I'm doing that today!

**Comment by CompuIves** [comment]
Fixed and deployed!
