### ISSUE TITLE
Not loading page - Showing just the logo (Full page)

### ISSUE THREAD

**Issue by adyz** [CompuIves/codesandbox-client#672]
If I try to access any sandbox, eg: https://codesandbox.io/s/v818xwl670, just the logo is shown.

If I open the devtools I see:

```
Uncaught SyntaxError: Unexpected end of input
common.5a871827.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at common.5a871827.js:1
app.bdf0d16f.js:1890 Uncaught SyntaxError: Invalid or unexpected token
```

Only with my console open, If I do a hard Force Reload (Shift + Command + R) the page will load properly.

**Comment by adyz** [comment]
<img width="1439" alt="screen shot 2018-03-27 at 15 34 43" src="https://user-images.githubusercontent.com/611174/37967557-75a083c6-31d4-11e8-8658-cb7a6077f921.png">

**Comment by adyz** [comment]
Also, if I close the developer tools and I hit refresh, the error is back.

**Comment by Komar0ff** [comment]
Hi @adyz 

It's strange. data does not come.
You tried to run on other browsers?

**Comment by adyz** [comment]
No, I think it's due to the fact that I am already logged in and I have some corrupted cache or cookies. I tried in chrome with private mode and it works fine.

I logout/login did not help.

Going in the chrome devtools, application -> clear storage and clicking on clear all data worked.

**Comment by CompuIves** [comment]
Extremely weird, looks like this indeed has to do with the cache. It seems like the chunk hashes didn't update. I'll look into this!

**Comment by CompuIves** [comment]
I added an expiration to all chunks of a day, that should fix filling up the storage and preventing updates!
