### ISSUE TITLE
React File Icon performance issues

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#673]
This is an interesting issue to solve. For the files in the sidebar we show icons related to the file type, for React we check the module code with a Regex for an import statement.

I noticed that this impacted performance by a large amount, for every keystroke we had to rerender the sidebar and tabs (all components that use `getType`), to run the RegEx again. I disabled the functionality for now with commit https://github.com/CompuIves/codesandbox-client/commit/87d66fb77be41aa494c49daf876aa43edc551e35, but it would certainly nice to get this back in a more performant way. Does anyone have an idea how to solve this?

**Comment by donysukardi** [comment]
What if you only set the icon for every save? That would be a decent compromise.

**Comment by CompuIves** [comment]
Hmm yes that makes the most sense. Then we would add an extra field to module maybe? Or create a separate map that maps moduleId to type.

**Comment by donysukardi** [comment]
I think it'd be better to have it inside the module itself or a derived state from module. That way, we don't have to handle file removal separately. I'm not familiar with celebral, still wrapping my head around it

**Comment by SaraVieira** [comment]
👋

There was a complete rewrite of how the icons work in codesandbox and as far as I see this now looks waaay better

https://codesandbox.io/s/041q2oox20
