### ISSUE TITLE
[UX/UI Suggestion] Close icon on tab

### ISSUE THREAD

**Issue by alexvcasillas** [CompuIves/codesandbox-client#674]
Hello @CompuIves !

I've been playing around with CodeSandbox and saw this "issue" that is related to the UI and UX more than business logic :)

![image](https://user-images.githubusercontent.com/9496960/38039309-443c3792-32ad-11e8-9a27-2b4d898db982.png)

If you have pending changes on the file and you hover it's tab, it doesn't show up the cross icon (x) to close that tab as if the file has no changes. When you click on the dot that displays that there are changes pending to be saved, then the tab dissapears.

As the sceenshot doesn't show the current mouse position, it's right on top of the `package.json` tab.

Also suggest that if I have only one tab active, it won't show the cross icon (x) to close this tab :)

![image](https://user-images.githubusercontent.com/9496960/38039655-08cd07e4-32ae-11e8-9c5e-fcef1816d935.png)

It's a silly issue, but for UX/UI I find it as an interesting suggestion to be reported : )

**Comment by CompuIves** [comment]
Ah, that's an interesting one. I copied this logic over from `vscode`.

> When you click on the dot that displays that there are changes pending to be saved, then the tab dissapears.

I think we should just disable the close icon when the module is unsaved, does that make sense?

> Also suggest that if I have only one tab active, it won't show the cross icon (x) to close this tab :)

Good one, I like this!

Would you be interested in opening a PR for this? 😄

**Comment by alexvcasillas** [comment]
If the module is unsaved and we get the mouse hover the tab we should replace the dot icon with the cross icon, so even though it's unsaved, the action will be closing this unsaved tab so, the close icon it's more likely to be there : )
And yeah, for sure, I would be interested in PR-ing this : )

**Comment by CompuIves** [comment]
That's even better! Good suggestion.

**Comment by alexvcasillas** [comment]
PR [https://github.com/CompuIves/codesandbox-client/pull/738](https://github.com/CompuIves/codesandbox-client/pull/738) 😄

**Comment by alexvcasillas** [comment]
Solved with #738 :)
