### ISSUE TITLE
Proposal: add ability to run tests or add a documentation how todo so

### ISSUE THREAD

**Issue by FDiskas** [CompuIves/codesandbox-client#677]
It would be very handy if it will be possible to run tests

**Comment by FDiskas** [comment]
example: https://codesandbox.io/s/q9624qv3x9

**Comment by CompuIves** [comment]
Hey! Thanks for the example sandbox, I was a bit confused. We already have test support, but it seems like we don't detect .tsx tests properly. If I change the file to .ts it seems to be detected: https://codesandbox.io/s/24w96p9jop. But that of course will throw.

So this is just a matter of adding .tsx to the extension list to check :smile:. Would you be interested in adding it? We do the check here: https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/sandbox/eval/tests/jest-lite.js#L123. If you don't have time I can also add it tomorrow.

**Comment by FDiskas** [comment]
Ok I will try to create a pull request
