### ISSUE TITLE
Unable to load public sandbox 

### ISSUE THREAD

**Issue by vinzloh** [CompuIves/codesandbox-client#678]
A few of my sandboxes have this error when I click to open them:

<img width="1279" alt="screen shot 2018-04-01 at 12 03 54 am" src="https://user-images.githubusercontent.com/5501845/38165075-8169bbc2-3540-11e8-8816-18e4f3d551f1.png">

I haven't opened them in a while, are they broken and no longer accessible?
Link here: https://codesandbox.io/s/42lz4l4z1x

**Comment by vinzloh** [comment]
Never mind it's ok now.

**Comment by CompuIves** [comment]
Hey Vincent, sorry for that! We were getting DDOSed, still are actually. I started doing more rate limiting now.

**Comment by vinzloh** [comment]
No probs. Really appreciate the work you're doing. Big fan. Keep it up!
