### ISSUE TITLE
Tags and other new options missing from sidebar for GitHub-repo-based sandbox

### ISSUE THREAD

**Issue by faceyspacey** [CompuIves/codesandbox-client#68]
![img_3097](https://user-images.githubusercontent.com/154732/28481411-a9a947e0-6e19-11e7-873b-6a29d74d1a6c.PNG)

That stuff isn't showing in my repo. Only in forks, ie regular sandboxes

**Comment by faceyspacey** [comment]
Would be nice to have this to tag the RFR repo

**Comment by CompuIves** [comment]
Yes, exactly. This is related with claiming ownership over a git repo. I'll try my hand at this this weekend.

**Comment by faceyspacey** [comment]
i need this brotha. im a paying customer. this is bullshit. ...im just messin wid u. tell me what to do, i'll do it. i'd like to see the RFR tags gain meaning in the algolia search.

git repo-based sandboxes should not be treated like second class citizens. it's what the power users use. see what im saying. they would at least if it was working and promoted better as described in the other thread, eg: "FORK TO GITHUB". Once you have fork to github, ironically it means more sandboxes coming from github--since u can overwrite the readme to contain whatever links, graphics, etc u want, in order to promote CSB.

**Comment by CompuIves** [comment]
Coming somewhere this week. Need to find a stable internet connection.

You'll be able to set tags using the `keywords` feature of `npm`.
