### ISSUE TITLE
Sandbox Icons are all React logo

### ISSUE THREAD

**Issue by trainorpj** [CompuIves/codesandbox-client#684]
Hi there!

I found a small issue when going through some users sandboxes.  Basically, all projects have the React logo, even though they're not React projects.  

* [You can see my page here, with mostly Vue projects](https://codesandbox.io/u/trainorpj/sandboxes)
* [Here's another example, with lots of Vue projects](https://codesandbox.io/u/chrisvfritz/sandboxes)
* [And a preact-heavy user, for good measure](https://codesandbox.io/u/developit/sandboxes)

The image below shows the bug.  These are all Vue projects, using the *vue-cli* template, but when I look at my sandboxes, the React logo is shown.

<img width="997" alt="screen shot 2018-04-01 at 12 22 55 pm" src="https://user-images.githubusercontent.com/13276704/38175283-3fe6ac06-35a8-11e8-81ef-265e6fe29a59.png">

I found this on 

* Chrome 65.0.3325.181 
* Firefox 59.0.2.

I'm happy to help with this.  I use codesandbox all the time; it's a great project, and I'm always looking for ways to show my appreciation for great open source projects 😄

**Comment by FDiskas** [comment]
Demo: http://pr686.cs.lbogdan.tk/u/developit/sandboxes :headphones:
