### ISSUE TITLE
Relative images not showing up with Parcel

### ISSUE THREAD

**Issue by francoischalifour** [CompuIves/codesandbox-client#687]
Hey there!

It seems like `img`s with relative paths are not working with the Parcel template (they're not displayed).

* Example not working on CodeSandbox: https://codesandbox.io/s/github/francoischalifour/medium-zoom/tree/master/examples/dropbox-paper-template
* Example working on Zeit: https://medium-zoom-dropbox-paper-oiahlcqkke.now.sh
* Source code: https://github.com/francoischalifour/medium-zoom/tree/master/examples/dropbox-paper-template

A few things I noticed:

* An image with an absolute source (from an external website) displays correctly
* `img`s are not present in the DOM (they seem to be skipped during the build process)
* No errors are thrown (while an error is thrown when the image path is wrong)

This example is working fine locally on my machine and on Zeit. That's why I think it's an issue on CodeSandbox's side.

I'm not sure if this issue is related to #100.

**Comment by CompuIves** [comment]
This is a perfect reproduction and super clear issue. I'll fix this now!

**Comment by CompuIves** [comment]
It's live, you may need to do a hard reload to see the changes!

**Comment by francoischalifour** [comment]
You're awesome! Thank you so much!
