### ISSUE TITLE
Issue with exporting Sandbox to Github

### ISSUE THREAD

**Issue by TaroWong** [CompuIves/codesandbox-client#689]
Hi! 

I tried to export a new sandbox to my Github account but there was an error. I am using `Firefox 59.0.2(64-bit)` if that helps.

**Error Message**
`405 Not Allowed`

<img width="1276" alt="issue" src="https://user-images.githubusercontent.com/8980164/38217707-e8439a9e-3701-11e8-91ce-9e369e735515.png">

[Sandbox link](https://codesandbox.io/s/rr6kkpm39o)

**Sandbox dependencies**
```
react
react-dom
react-redux
react-scripts
redux
```

**Comment by CompuIves** [comment]
Interesting, I cannot reproduce this locally. It's maybe because of the title. I'll check it out more tomorrow!

**Comment by TaroWong** [comment]
Sorry @CompuIves , you are right! `[]` is not allowed on Github.
