### ISSUE TITLE
Icon for Private/Hidden/Public sandboxes on Profile page

### ISSUE THREAD

**Issue by donavon** [CompuIves/codesandbox-client#69]
In the list view, show if a sandbox is private, hidden, or public (default). Maybe show a lock icon for private. Hidden... not sure.

**Comment by donavon** [comment]
Sorry... Just noticed it now.

![image](https://user-images.githubusercontent.com/887639/28484716-0492bd8a-6e42-11e7-9dc0-d8a3f31d45a8.png)

**Comment by CompuIves** [comment]
Haha, one step ahead! 😉
