### ISSUE TITLE
[error] Could not find package.json

### ISSUE THREAD

**Issue by ryanpcmcquen** [CompuIves/codesandbox-client#691]
Any ideas what would be causing this?
```
$ codesandbox .

  CodeSandbox CLI
  The official CLI for uploading projects to CodeSandbox

> Deploying . to CodeSandbox
> [error] Could not find package.json

$ ls package.json
package.json
```

**Comment by FDiskas** [comment]
what output of? :wolf:
```
ls -la package.json
```

**Comment by ryanpcmcquen** [comment]
```
$ ls -la package.json
-rw-r--r-- 1 rmcquen 1049089 1597 Apr  3 12:06 package.json
```

**Comment by FDiskas** [comment]
You are on windows OS?

**Comment by ryanpcmcquen** [comment]
Yes.

**Comment by CompuIves** [comment]
Interesting, this could be related to Windows. Which version of codesandbox-cli do you have installed?

**Comment by ryanpcmcquen** [comment]
`1.2.7`

**Comment by gangsthub** [comment]
same here, windows, using https://github.com/pi0/codesandbox-nuxt

**Comment by lazyTai** [comment]
![mark](http://p7whtc26y.bkt.clouddn.com/blog/180510/5327cKFFA6.png?imageslim)
![mark](http://p7whtc26y.bkt.clouddn.com/blog/180510/Am630KE97D.png?imageslim)
![mark](http://p7whtc26y.bkt.clouddn.com/blog/180510/I31mLkHCDE.png?imageslim)
any help?

**Comment by marquez138** [comment]
Same error..anyone have any suggestions?

**Comment by gt3** [comment]
I am seeing this as well on Windows 7 - codesandbox@1.2.11
looks like we're missing `path.resolve` somewhere

**Comment by lbogdan** [comment]
@gt3 Can you please provide a link to the project you're trying to upload?

**Comment by gt3** [comment]
@lbogdan we should be able to reproduce this on windows by creating a new app via `create-react-app`, then running codesandbox cli.

By the way, this guy blows my stack:
```
function createDirectoryRecursively(path, directories) {
    if (directories[path]) {
        return directories[path];
    }
    var parentDir = path_1.dirname(path);
    // This means root, so create it
    if (parentDir === ".") {
        directories[path] = generateSandboxDirectory(path, undefined);
        return;
    }
    if (!directories[parentDir]) {
        createDirectoryRecursively(parentDir, directories);
    }
    directories[path] = generateSandboxDirectory(path_1.basename(path), directories[parentDir].shortid);
}
```
Windows does not have "." as root, and so runs forever. I'll try to dive in and submit a fix.

**Comment by gt3** [comment]
This turned out to be a relatively easy fix. Please review PR - codesandbox-app/codesandbox-importers#8

**Comment by CompuIves** [comment]
Thank you so much @gt3! Deploying a new version of the cli now.
