### ISSUE TITLE
jsDelivr 404 errors

### ISSUE THREAD

**Issue by MartinKolarik** [CompuIves/codesandbox-client#693]
Hi, this is Martin from jsDelivr.

I noticed an unusually high number of CDN requests failing with a 404 error in the recent days. It seems that most of those are for packages from `@types` and come from https://codesandbox.io. I just wanted to ask if this is expected (e.g. you try to fetch `@types/<name>` for every installed package automatically and expect an error when it doesn't exist) or if it's something we should look into.

**Comment by CompuIves** [comment]
Hey Martin, 

That's true, we query `@types/<name>` to find out if there is an official type definition available for the library.

We do these steps to get typings:

1. We check if there is a `types` field on the `package.json` of the dep, and use that if available.
2. If not available, we check the tree of the dependency for `index.d.ts`.
3. If that's not available we try to fetch at `@types/<name>`.

I hope we don't cause any higher load, if that's the case I can change the logic to first check if there's an `@types` available.

**Comment by MartinKolarik** [comment]
The load is not a problem, I just wanted to make sure everything is alright.

Btw I also noticed sometimes you make requests like https://cdn.jsdelivr.net/npm/@angular/common@5.2.9/src/directives/index, which fail because we don't resolve the file to `index.d.ts`. You might want to ensure that the requested files always have the `.d.ts` extension (I guess this would be a common problem since the extension is optional).

Thanks for a fast response and feel free to ping me any time if you have questions about our service 😄

**Comment by CompuIves** [comment]
Yap! You're right, I fixed it with this commit: https://github.com/CompuIves/codesandbox-client/commit/4ce8eb63f6c5db52e0f1b2eeef9e8b6582455248. Thanks for the headsup!

**Comment by MartinKolarik** [comment]
👍
