### ISSUE TITLE
Read Only Mode for the owner?

### ISSUE THREAD

**Issue by giggioz** [CompuIves/codesandbox-client#696]
Hi,

i shared a codesandbox for the first time and i was wondering if i can put that box in a read only mode *even for me*.
I want to avoid to edit that box after a while because i forgot that i shared it.

Thanks!

**Comment by antoninadert** [comment]
Hello, where is this going right now ?

**Comment by SaraVieira** [comment]
This was added in the latest release :D

**Comment by CompuIves** [comment]
Whoop whoop!
