### ISSUE TITLE
Clear console on change

### ISSUE THREAD

**Issue by ValentinH** [CompuIves/codesandbox-client#698]
When using the Console Preview mode, it would be nice to be able to clear it automatically on each code change.

I was thinking about adding a configuration item like `clearConsoleOnChange`
 in the `sandbox.config.json` file.
Another solution could be to add a toggle directly in the Console view header (both devtools and preview) so it's more obvious to find this feature.

What do you think about this? Can I provide a PR?

**Comment by CompuIves** [comment]
Hmmm, I think we have this one in preferences already? In the Preview setting. I think we should enable it by default though, so I'm open for a PR for that!

**Comment by ValentinH** [comment]
You are right, I forgot about these preferences :) I only looked at the sandbox config file.
Let's go for a PR to change this default!
