### ISSUE TITLE
New file, New directory buttons are missing on Android (touch screen)

### ISSUE THREAD

**Issue by sompylasar** [CompuIves/codesandbox-client#706]
Repro video from the phone sent over Twitter DM to @CompuIves – also reproducible in Chrome DevTools Device Emulation.

**Comment by CompuIves** [comment]
Hmm, is this still the case? I thought I fixed this yesterday and can't reproduce the issue at this moment.

**Comment by sompylasar** [comment]
@CompuIves I believe I checked via DevTools and still saw it, but I went to check again from Android now and the buttons are in place. Probably the app didn't reload. Closing.
