### ISSUE TITLE
Cannot remove default key bindings

### ISSUE THREAD

**Issue by pshrmn** [CompuIves/codesandbox-client#707]
I'm trying to get rid of the "Toggle Sidebar" <kbd>ctrl</kbd> then <kbd>shift</kbd> binding, but even when I assign something else, <kbd>ctrl</kbd> then <kbd>shift</kbd> still toggles. The same applies to the other key bindings.

**Comment by CompuIves** [comment]
Fixed! Thanks for letting me know 😄
