### ISSUE TITLE
Matching tag highlighting

### ISSUE THREAD

**Issue by Infining** [CompuIves/codesandbox-client#710]
I find it difficult to find the matching opening/closing html tags in the editor at the moment. For ease of use, it might be useful to add functionality similar to this vscode plugin: [highlight-matching-tag](https://marketplace.visualstudio.com/items?itemName=vincaslt.highlight-matching-tag).

ps: Amazingly useful tool! Thank you so much.

**Comment by Komar0ff** [comment]
@Infining What is the difficulty? The highlighting of the tags is there and it works

![gif](https://user-images.githubusercontent.com/10588170/38580297-46721116-3d12-11e8-9eaf-6933fcb11377.gif)

**Comment by Infining** [comment]
Wow, do I feel like such an idiot! I was trying this by putting my cursor after the closing carrot of an html tag. Thanks for clearing that up @Komar0ff!
