### ISSUE TITLE
Delete Line key binding

### ISSUE THREAD

**Issue by singletoncoding** [CompuIves/codesandbox-client#714]
It would be nice to have a key binding that allows you to delete the current line that the cursor is in.  I normally use this a lot in most local editors that I'm working in, generally something like ctrl + D as a shortcut.

**Comment by ValentinH** [comment]
The key bindings are the same than VSCode. 

You can use ⇧⌘K to delete a line on Mac (Probably something similar on Windows).

**Comment by singletoncoding** [comment]
Looks like VS Code is ctrl + shift + k for vs code (https://code.visualstudio.com/docs/getstarted/keybindings#_basic-editing).  Still, I think that there is a good mix of editors that default with ctrl + d, etc, so being able to bind it would be a really nice feature.

**Comment by ValentinH** [comment]
Actually, being like VSCode is not just a choice for key bindings: the editor part uses Monaco which is the editor that powers VS Code: https://github.com/Microsoft/monaco-editor

**Comment by emersonlaurentino** [comment]
Hey @singletoncoding the codesandbox uses Monaco like VSCode and CodeMirror for VIM mode, so he uses the commands line of editor you choose. 

You can close this issue?

**Comment by singletoncoding** [comment]
So, I think my question still stands on this.  Is there a way for me to set a specific key binding for deleting a line.  While the editors might chose one, it doesn't necessarily mean it's the one that I prefer to use.  When I work with editors, I change this key binding.

Perhaps there's a way that I can set it for the editor through code sandbox that I'm just not familiar with (I use webstorm, so I'm not overly familiar with these editors).

**Comment by SaraVieira** [comment]
@singingwolfboy You can do that in VSCode now by going to your keybind settings like you would on desktop :D
