### ISSUE TITLE
Consistent Live Coding Session URL

### ISSUE THREAD

**Issue by singletoncoding** [CompuIves/codesandbox-client#716]
I was streaming last night and because of #699, I was having to refresh to see the code changes that people who joined were making.  When I did this, it kicks all of the users out of the session because a new URL is generated.  While I realize that the fix is to deal with #699, I think it would still be beneficial of there was a way to create a consistent URL that is used for live coding sessions so that they could be used for multiple separate sessions, etc.  It would simplify any communication that you send out to others about how to join the live session as well.

**Comment by singletoncoding** [comment]
Another way to accomplish this that I just thought of is instead of generating a URL, just have it such that when someone navigates to your sandbox, there is a "join live coding session" button available.  An example of what sandbox page I'm talking about is this:

https://codesandbox.io/s/9y3978199o

**Comment by CompuIves** [comment]
This is a good one. I think a good solution for this would be to close the session if the author has been away for ~2 minutes for example. 

It would also be cool to show such a button, if the author marks the live session as 'public'.

**Comment by SaraVieira** [comment]
This was fixed in the live rewrite :D
