### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#717]
It would be nice to have an Issue Template. The main information I'm missing from issues currently is: CodeSandbox version (can be found in the bottom of the sidebar) and a sandbox in which the error can be reproduced. It would also be good to know if the error cannot be reproduced when you download the sandbox locally and run it.

**Comment by singletoncoding** [comment]
Perhaps additional information such as browser, browser version, OS?  I'm not sure of the architecture of code sandbox, but perhaps user OS makes a difference, such as when considering line endings.

**Comment by CompuIves** [comment]
That's a good one! Would be good to have indeed.

**Comment by Komar0ff** [comment]
@CompuIves awesome idea! 

I think it should look something like this:
{ description of the problem }
<b>Link to sandbox: [link]()</b> (optional)
### Environment
| Software         | Name/Version/Link |
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | 
| Operating System |

I think you can add something else😊

**Comment by CompuIves** [comment]
Wow, that's beautiful @Komar0ff, definitely what we need!

**Comment by Komar0ff** [comment]
@lbogdan okay, i can do it!

**Comment by lbogdan** [comment]
Thanks to @Komar0ff , we now have different templates for bugs / features / questions. Good job!
