### ISSUE TITLE
Can't import from Github

### ISSUE THREAD

**Issue by mnm5774** [CompuIves/codesandbox-client#718]
Hello,
My name is Marc. I'm pretty new to coding. Hopefully this is the right place for this.
I'm trying to import my existing repo on github to a new sandbox, and for some reason I always get a message similar to below.
"Something went wrong
should be at most 48 character(s)"
In the console I see a "failed to load resource: server responded with a status of 422" error.
I created a test repo and it seemed to import fine. for some reason it's not working with my existing code though. Any thoughts on why?
github: [my repo](https://github.com/mnm5774/Portfolio)

**Comment by CompuIves** [comment]
Hi! Thanks for letting me know, I updated our limits to make it work with your github repository. We had a limit of maximum 48 characters in a filename, I raised it to 64.

I think the sandbox will start working of you add `parcel-bundler` to your `devDependencies` in the `package.json` in your GitHub repository.

**Comment by durkinio** [comment]
@CompuIves might it be possible to raise the limit again? Here's an example of a repo that's throwing the "should be at most 64 character(s)" error > https://github.com/netlify-templates/gatsby-starter-netlify-cms

**Comment by CompuIves** [comment]
Hey @durkinio, I raised the limit!

**Comment by rszalski** [comment]
Hey @CompuIves I encountered the same problem today. When importing this repo: https://github.com/the-road-to-learn-react/react-interval-setstate-unmounted-component-performance I get an error `"should be at most 64 character(s)"`.

The codesandbox in question: https://codesandbox.io/s/github/the-road-to-learn-react/react-interval-setstate-unmounted-component-performance

Is this 64-char limit related to filenames? Or the resulting URL? And is it something that has to be raised on per-repository case?

Anyway, I love this feature of CodeSanbox, really simplifies demoing of many repos! Hope this can be resolved.

**Comment by rwieruch** [comment]
Yep. Anything against raising the limit? I started to use CodeSandbox to mirror all my source code projects from GitHub, but ran into this issue with @rszalski
