### ISSUE TITLE
Create new Sandbox Popup Menu

### ISSUE THREAD

**Issue by donavon** [CompuIves/codesandbox-client#72]
When you click the ➕  to create a new sandbox, have a popup menu appear asking: "Create: Public, Private, or Hidden".

**Comment by CompuIves** [comment]
Hmm, I need some thinking on this one. It will remove the 'Create a React project in one click' motto...

**Comment by donavon** [comment]
well when you get templates, you'll want the plus to popup with a "From what template" anyway, I would imagine.

**Comment by CompuIves** [comment]
You're right, this could go right in the templates filter.

**Comment by SaraVieira** [comment]
Closed as this no longer makes sense since we have so many templates

Feel free to reopen
