### ISSUE TITLE
Ctrl + Click On Consumed class causes contents to be copied into the current file

### ISSUE THREAD

**Issue by singletoncoding** [CompuIves/codesandbox-client#726]
This is a really weird one that I seem to keep see happening.  In my code sandbox located [here](https://codesandbox.io/s/5zyj7k470n) when I have the BudgetContainer open (located in src/components/BudgetContainer/BudgetContainer.js) and I ctrl + click on the BudgetCategory component in the render method, it actually copies the contents of the BudgetCategory component into the BudgetContainer component.  

The navigation still happens as would be expected such that the BudgetCategory is brought up, but then when I navigate back to my BudgetContainer I can see that the contents have been modified.

The version:
PROD-1523452809

Running on:
Windows 10
Chrome Version 65.0.3325.181 (Official Build) (32-bit)

Additionally, I tried using my personal account (and not my Channel's account) and I was able to reproduce the issue even though my personal account doesn't have access to modify anything. When I was trying to reproduce this issue on my other account, I was using Firefox version 59.0.2

Also, I forked my repo that was causing this issue for your usage (in the link above), feel free to do whatever, the issue should stick around as I won't be changing that sandbox.

**Comment by singletoncoding** [comment]
Also, I forked my repo that was causing this issue for your usage, feel free to do whatever, the issue should stick around as I won't be changing that repo.

**Comment by CompuIves** [comment]
Fixed with https://github.com/CompuIves/codesandbox-client/commit/f8df5c136b7afb824ba5317542af908d711188b2.

**Comment by singletoncoding** [comment]
I'm not super familiar with the deployment approach used here.  When an issue is resolved, is the code pushed already?  I still seem to be seeing the issue.

**Comment by CompuIves** [comment]
The update has not been deployed yet, will do that within an hour!
