### ISSUE TITLE
Ligatures `fl`, `fi` within a monospace font in the code editor

### ISSUE THREAD

**Issue by sompylasar** [CompuIves/codesandbox-client#728]
I noticed that the code editor uses ligatures (i.e. when two letters are glued together and occupy less space), and that looks weird for pairs like `fl`, `fi` in code where these are supposed to occupy two characters.

Is this by design?

`font-family: Menlo, "Source Code Pro", monospace;` in the `monaco-editor`:
```
.monaco-editor.enable-ligatures {
  -webkit-font-feature-settings: "liga" on,"calt" on;
  font-feature-settings: "liga" on,"calt" on;
}
```

### Actual

<img width="524" alt="screen shot 2018-04-12 at 1 35 20 pm" src="https://user-images.githubusercontent.com/498274/38702829-7907defe-3e56-11e8-8f4b-6eb1b8320501.png">
<img width="547" alt="screen shot 2018-04-12 at 1 36 29 pm" src="https://user-images.githubusercontent.com/498274/38702861-8d37cb14-3e56-11e8-8704-c28a9bca7d98.png">

### Expected

<img width="503" alt="screen shot 2018-04-12 at 1 41 02 pm" src="https://user-images.githubusercontent.com/498274/38703103-301a63be-3e57-11e8-9412-adc53f99d8a0.png">

**Comment by CompuIves** [comment]
Haha, I fixed this one today already (https://github.com/CompuIves/codesandbox-client/commit/3453bbce5f1986da3e46884a5625f5b0d6fb8e5e). I'm deploying this within ~30 minutes.
