### ISSUE TITLE
Misaligned Cursor In Recent Version

### ISSUE THREAD

**Issue by Infining** [CompuIves/codesandbox-client#729]
### Misaligned Cursor In Recent Version
1. While working on a sandbox I got the notification to refresh after an update. Afterward ,my cursor was misaligned.
![misalign](https://user-images.githubusercontent.com/9121936/38709788-1a4d29f4-3e7a-11e8-82d4-05e73db518ba.gif)
2. Makes it difficult to type.

### Environment
Software | Name/Version
----------|-----------------
Codesandbox | PROD-1523566170
Browser | Chrome Version 65.0.3325.181 (Official Build) (64-bit)
Operating System | Windows 10

**Comment by Infining** [comment]
I'm not using a custom font.

**Comment by CompuIves** [comment]
Hmm interesting. I found out that you can fix it by enabling ligatures in Preferences. I will take a closer look later.

**Comment by CompuIves** [comment]
I enabled ligatures again by default as temporary fix. Will take a closer look at it today!

**Comment by Infining** [comment]
That looks to have been fixed with ligatures enabled on my end as well.

**Comment by lbogdan** [comment]
I'll close this for now, please re-open if you encounter any more issues.
