### ISSUE TITLE
Show tags on Profile page

### ISSUE THREAD

**Issue by donavon** [CompuIves/codesandbox-client#73]
Show tags under each title on my profile page. Allow me to filter by tag.

**Comment by CompuIves** [comment]
This is a really good one! Definitely something we need asap. I'm thinking of using Algolia search for these sandboxes as well, allows you to filter on deps, tags, name, etc.

**Comment by SaraVieira** [comment]
Closed and moved to our trello board as this will be implemented on the new profile page we are making :D
