### ISSUE TITLE
Github synced sandbox does not recognise that I am owner

### ISSUE THREAD

**Issue by PandaSandStudio** [CompuIves/codesandbox-client#734]
I synced my sandbox with github and it does not recognise that I am the owner, and when I make an edit it forks the sandbox and creates a new one with the edit which is not synced to github.

Here's the screenshot of the sandbox not seeing me as owner even though I am (it is synced with github)

![screenshot 2018-04-15 at 11 11 37](https://user-images.githubusercontent.com/28838817/38773955-2dc32f1c-409e-11e8-8c2e-ed3bafc9eeb9.png)

**Comment by CompuIves** [comment]
Hey @PandaSandStudio, that's indeed true. GitHub sandboxes are marked immutable. We have more documentation on this here: https://codesandbox.io/docs/git#base-concept.

This part explains it:

"An imported sandbox will automatically stay in sync with the GitHub repository; if you make a commit to GitHub it will reflect immediately in the sandbox. For that reason we've made GitHub sandboxes immutable, this means that you cannot make direct changes to the sandbox itself. However, you can still fork the sandbox. When you create a fork of a GitHub sandbox we will still keep a reference to the original GitHub repository. This allows you to create commits and open pull requests from the forked sandboxes."
