### ISSUE TITLE
vue+typescript render components not working

### ISSUE THREAD

**Issue by M-Zuber** [CompuIves/codesandbox-client#740]
https://codesandbox.io/s/6n0p42o72r

I am trying to put together an example that shows a render only component, using `vue-property-decorator`

if I use a `ts` file, there are no errors about lacking generator support, but then I get `Could not find module in path: './collapsible'`

Probable I am simply missing some setup...<br>
Would prefer if there is a way to get the ts version working

**Comment by CompuIves** [comment]
Hmm, I think it is fixed by changing 

`import Collapsible from "./collapsible"` to `import Collapsible from "./collapsible.ts"`. Could you verify that this is the case? I will change the Vue template to also ignore `ts` extensions with resolving in the meantime.

**Comment by CompuIves** [comment]
Oh, also, is it expected that the `ts` code also gets transpiled by `babel`? Just curious if I should add that step 😄

**Comment by M-Zuber** [comment]
adding `.ts` to the import path was what I was missing, thank you!!

the .babelrc was in there because I was trying anything too get it to work, but it is not needed
