### ISSUE TITLE
CodeSandbox crashing when running unit tests

### ISSUE THREAD

**Issue by PandaSandStudio** [CompuIves/codesandbox-client#742]
As soon as I open up the unit tests panel, nothing happens for a second, then it freezes for a few seconds, then the sandbox crashes and shows an empty blue screen (https://codesandbox.io/s/zlvkw42x3p)

(opening unit tests)
![screenshot 2018-04-17 at 15 18 54](https://user-images.githubusercontent.com/28838817/38850044-fa1f2a7e-4252-11e8-9ce8-2de1be34297c.png)

(screen freezing)
![screenshot 2018-04-17 at 15 19 00](https://user-images.githubusercontent.com/28838817/38850046-fa4c733a-4252-11e8-8cb5-26ea513d56cf.png)

(codesandbox crasing)
![screenshot 2018-04-17 at 15 19 57](https://user-images.githubusercontent.com/28838817/38850047-fa7afcdc-4252-11e8-8616-d8aa876242cd.png)

**Comment by CompuIves** [comment]
This is a big issue, thanks for reporting this! It seems like the `expect(...).toThrow` doesn't give source mappings, which caused the jest runner to get a null exception. I added a null check to fix it. It will be live somewhere later today, depending on when I get a network connection 🙂.

**Comment by PandaSandStudio** [comment]
Thanks!
Also thanks for your work at CodeSandbox -- Its a great editor and lets me prototype quickly when I don't have access to my usual computer!
