### ISSUE TITLE
ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by imcodingideas** [CompuIves/codesandbox-client#754]
Hello,

I've pushed my code: https://codesandbox.io/s/xjmvj910nq and I'm getting an error: `ReferenceError: __dirname is not defined` but this works locally. 

Any ideas?

**Comment by gautamarora** [comment]
@imcodingideas - 👋 well, hello there!! 😄 glad to see you trying out codesandbox!

codesandbox currently only supports frontend projects, and it appears that the project you have is an electron app, right?

**Comment by imcodingideas** [comment]
Hey @gautamarora thanks for explaining this to me. :) See you on slack!

**Comment by CompuIves** [comment]
I'll open a PR to add `__filename` and `__dirname` to the globals, it seems like Webpack is doing the same I think.
