### ISSUE TITLE
Scrolling in the iFrame doesn't work in Safari

### ISSUE THREAD

**Issue by OllieJennings** [CompuIves/codesandbox-client#763]
Safari version: 11.0.3

No matter how large the content is inside of the iFrame, you cannot scroll.

MacOSX 10.12.6

**Comment by CompuIves** [comment]
Could this one be related to #102?

**Comment by OllieJennings** [comment]
Yeah i think so?

**Comment by CompuIves** [comment]
Hmm yes I'm curious what happens if you either update Safari or add the code mentioned in the other issue. I'll also do some more checks

**Comment by OllieJennings** [comment]
I will try adding in the code first, then do an update tonight

**Comment by OllieJennings** [comment]
So am finally on latest everything, Safari 11.1, MacOSX 10.13.4 and the scrolling still doesn't work in the iframe, it doesn't work either if using the code mentioned in the issue above

**Comment by SaraVieira** [comment]
Issue closed due to lack of activity
