### ISSUE TITLE
Dank dat font

### ISSUE THREAD

**Issue by donavon** [CompuIves/codesandbox-client#764]
Following up on this [Twitter thread](https://twitter.com/donavon/status/989921196681695234).
Let's make the [Dank Mono](https://dank.sh/) font available in CodeSandbox! 🙌

![image](https://user-images.githubusercontent.com/887639/39397886-54567946-4ad4-11e8-838d-cb8b072a204f.png)

cc: @kitten

**Comment by CompuIves** [comment]
Yasss!! So I'm not 200% sure how this would work, would we have something like a webfont that only works on codesandbox.io domain?

**Comment by kitten** [comment]
@Compulves right now I have an obfuscated version here: https://dank.sh/static/dmvendor.css

The ligatures in that one don’t work right now, but I’m trying to figure that out. I’m trusting people not to include it elsewhere as I think everyone’s got the decency for that :)

**Comment by CompuIves** [comment]
Cool great! I'll add it now!

**Comment by alistair-hmh** [comment]
OMGAWESOME

**Comment by F1LT3R** [comment]
OMGAWESOME

**Comment by SaraVieira** [comment]
This has been added :D

**Comment by CompuIves** [comment]
Whoop!
