### ISSUE TITLE
"regeneratorRuntime is not defined", goes away when running in local

### ISSUE THREAD

**Issue by adrienharnay** [CompuIves/codesandbox-client#772]
Hey,

Again, thanks a lot for Codesandbox, which is an awesome project!

I've been running into a weird issue lately, where my project has an error when I run it in Codesandbox: https://codesandbox.io/s/y36r9vxr6z

```
regeneratorRuntime is not defined
    at eval (https://y36r9vxr6z.codesandbox.io/node_modules/brigad/redux-rest-easy/lib/internals/network/getDefaultNetworkHelpers.js:261:48
```

but when I download it and run it locally (Open Codesandbox > Download > yarn > yarn start) I have no error. I also have this in [my library entry point](https://github.com/Brigad/redux-rest-easy/blob/master/src/index.js#L1):

```import 'regenerator-runtime/runtime';```

Have you ever seen this?

Thanks in advance!

**Comment by lbogdan** [comment]
If you import the regenerator runtime first thing in `index.js` like here https://codesandbox.io/s/71x6570zl6 it should work. Not sure why it works locally, though.

**Comment by adrienharnay** [comment]
Yeah but the point is to not bother the user with this, by importing it in my library instead (which I did).

**Comment by lbogdan** [comment]
You're right, that's why I marked this as a `workaround` for now. 😄 I'll take a better look at this and let you know.

**Comment by adrienharnay** [comment]
Alright, thank you very much! I'll keep digging too :)

**Comment by adrienharnay** [comment]
It seems Codesandbox is picking the `module` field of my libary's package.json, while in local the `main` field is used.

```
"main": "lib/index.js",
"module": "es/indexjs",
"jsnext:main": "es/index.js",
```

My es build seems to be broken, which causes the error. Still a bit weird that it doesn't work the same in Codesandbox as in local imo

**Comment by lbogdan** [comment]
Hm, how did you reach that conclusion? On my side I see it resolves just fine:
```
resolved @brigad/redux-rest-easy to /node_modules/@brigad/redux-rest-easy/lib/index.js
```

**Comment by adrienharnay** [comment]
Mmmhhh indeed, I jumped to this conclusion but was wrong.

I tried importing from `@brigad/redux-rest-easy/lib`, `dist`, and `es` in Codesandbox; none of them work. Locally, all of them work. I'm a bit lost on what is going on here...

**Comment by lbogdan** [comment]
Hm, but shouldn't everything in `lib` be ES5?! Right now I can see `import`s and `export`s there: https://unpkg.com/@brigad/redux-rest-easy@2.8.5/lib/index.js .

**Comment by adrienharnay** [comment]
Mmhhh you are indeed right, so the difference comes from Codesandbox transpiling node_modules I guess. Thanks for your help, I will fix my `lib` build!
