### ISSUE TITLE
Could not fetch dependencies, please try again in a couple seconds: Your key is too long

### ISSUE THREAD

**Issue by stackninigi** [CompuIves/codesandbox-client#773]
Hi, I'm trying to publish my code using codesandbox. I pushed it to github(https://github.com/stackninigi/haveiseenit). It works fine on my localmachine but I cannot get it running on codesandbox. Firstly I changed entry point in package.json to point to src/index.js as there were some issues with my webpack configuration. Then codesandbox was not able to see my devDependencies, so I moved them all to dependencies. As a result I receive the following error: Error
Could not fetch dependencies, please try again in a couple seconds: 

> Your key is too long
> ▼ 6 stack frames were expanded.
> (anonymous function)
> https://codesandbox.io/static/js/sandbox.8b82e14f.js:5660:1636

Do you have any idea what might be the cause and how can I deal with it? I'd be most grateful for any help. My codesandbox is: https://codesandbox.io/s/qv87q2lr39

**Comment by lbogdan** [comment]
Hey @stackninigi , thanks for your report!

That error is most probably because there are way too many dependencies. Can you leave in `dependencies` only the packages you're directly importing in your project (like `react`, `react-icons` etc.), and move the rest back to `devDependencies`? Don't worry if it won't work in CS, from there I'll be able to debug it further.

**Comment by lbogdan** [comment]
Here's a working version https://codesandbox.io/s/k0w29kn4w5 (it still gives some React / browser warnings, but that's not a dependencies issue).

**Comment by stackninigi** [comment]
Hi, thank you for your help. Previously I had majority of them in devDependencies but codesandbox seemd to have some issues with fetching them. Also I can see that in codesandbox provided by you React dnd and scss doesn't work. As for styling my guess would be that it's because my webpack is ignored. Can I add webpack for codesandbox? And do you have any idea why react dnd doesn't work while the same project works perfectly on my local machine?

**Comment by CompuIves** [comment]
Heylo @stackninigi! At this moment CodeSandbox only supports unejected CLIs, like `create-react-app` and `vue-cli` for example. This is the reason that we're not picking up the `webpack.config.js` yet. This functionality is currently in the works, but is not here yet.

**Comment by stackninigi** [comment]
Hi @CompuIves, thank you for the information.

**Comment by lbogdan** [comment]
I'll close this for now, please re-open if you have any more related issues.

**Comment by lbogdan** [comment]
I'll close this for now, please re-open if you have any more related issues.

**Comment by lbogdan** [comment]
@stackninigi Sorry for deleting your comment, wanted to delete one of mine, but clicked on yours instead. Unfortunately I see there's no way to undo that. :confused: 

@stackninigi said:
> Hi @CompuIves, thank you for the information.
