### ISSUE TITLE
json syntax error

### ISSUE THREAD

**Issue by juanda99** [CompuIves/codesandbox-client#778]
It throws syntax error if json props or values are not double quoted. Could it be set somewhere?

**Comment by lbogdan** [comment]
Hey @juanda99 ,

Not sure I understand, props are supposed to be double quoted as per JSON standard, and quoting of values depends on their type. Can you give us more details regarding your issue?

**Comment by juanda99** [comment]
I prefer not to use quotes for props and just single quotes for values (when required).
I can config it with eslint, see https://eslint.org/docs/rules/quote-props
But I can't see they way to do it here (I can't find eslint) and I don't think prettier has that option.

**Comment by lbogdan** [comment]
If we're talking about .json files, you can't really do that.

**Comment by juanda99** [comment]
ok, thank you!
