### ISSUE TITLE
Support for a terminal

### ISSUE THREAD

**Issue by rajatvijay** [CompuIves/codesandbox-client#779]
@CompuIves 
There are many reasons for an inbuilt terminal and biggest of them is freedom. Is this in the plan for future releases?

**Comment by lbogdan** [comment]
Hello there,

Closing this, as we recently launched [CodeSandbox Containers](https://hackernoon.com/codesandbox-containers-5864a8f26715), and you can now open a terminal inside a container / server sandbox.
