### ISSUE TITLE
Feature request: Search Personal Sandboxes and/Or Sort by Updated Date

### ISSUE THREAD

**Issue by JoshRosenstein** [CompuIves/codesandbox-client#782]
This would be super helpful. Currently, have to scroll page by page for a sandbox that has been created a while back but is frequently updated. Allowing to just sort by updated date will help, but search functionality for personal boxes would be best. Also, when using the general search, you cannot search for your private or unlisted boxes. Current workaround is bookmarking and searching bookmarks.

**Comment by SaraVieira** [comment]
Closing as this can now be done with the new dashboard :D
