### ISSUE TITLE
Add section with featured quotes/organizations/events

### ISSUE THREAD

**Issue by radi-cho** [CompuIves/codesandbox-client#783]
It will be good to has section on the home page above the Patron part with organizations, websites, events that use CodeSandbox. Its purpose will be to show new users that CodeSandbox is already popular between developer communities. For example the [React Finland](https://react-finland.fi/) speakers [used](https://twitter.com/mweststrate/status/989043014990487552) CodeSandbox and you can feature it in that section. Another example is [RSG Chess' documentation](https://rsg-chess.now.sh/docs/api) which officially uses CodeSandbox.

What do you think, @CompuIves?

**Comment by radi-cho** [comment]
Example: "Who is using [Jest](https://facebook.github.io/jest/)?" section
![image](https://user-images.githubusercontent.com/12954909/39483081-ee4ba2d6-4d79-11e8-8084-cbc3a79f6922.png)

**Comment by CompuIves** [comment]
But yeah, I think this is one of the best things to have at this moment! Would you be interested in opening a PR for this? Then I can send a list of companies and projects using CodeSandbox with some quotes. I've been meaning to add the @kenwheeler quote for some time now.

**Comment by radi-cho** [comment]
I can do it in my free time, but I'm not sure is there more of it this week, so if there are people who can do it faster let them do it...

**Comment by SaraVieira** [comment]
This is an amazing idea!

I am gonna tweet it out so we get some names

**Comment by SaraVieira** [comment]
Tweeted: https://mobile.twitter.com/NikkitaFTW/status/1097512239173681153

**Comment by gillchristian** [comment]
We use it at @housinganywhere

**Company name**: HousingAnywhere
**Link**: https://housinganywhere.com
**GitHub org**: https://github.com/housinganywhere
**Logo**: https://www.dropbox.com/s/urmfnp49b63zzox/ha-logo.svg.

---

Suggestion,check how @prettier does it.

They have a [similar section](https://prettier.io/en/users/) and they allow to add your company by adding your company [here](https://github.com/prettier/prettier/blob/master/website/data/users.yml) (check "ADD YOUR PROJECT" in the [home page](prettier.io)).

**Comment by SaraVieira** [comment]
That is smart! I will probably go with json and then parse it with Gatsby image to make it all the Dame size
Thank you man

**Comment by aderaaij** [comment]
We use it at Mercedes-Benz.io for workshops and coding challenges! ❤

**Company name**: Mercedes-Benz.io
**link**: http://mercedes-benz.io
**GitHub org**: https://github.com/mercedesbenzio
**Logo**: https://avatars3.githubusercontent.com/u/33899184?s=200&v=4

**Comment by shipstar** [comment]
We are using it at Woven for some of our frontend coding challenges as well:

[Homepage](https://www.woventeams.com/) • [GitHub](https://github.com/woven-teams) • [Logo](https://static1.squarespace.com/static/5bfef771f407b44dcae18711/t/5c114a5203ce6432d87ba487/1548944030671/?format=1500w)

**Comment by radi-cho** [comment]
We use it in an OSS game built with React Native - RSG Chess and its open sourced [API docs website](https://rsg-chess.now.sh/docs/api/game-setup).

**link**: https://play.google.com/store/apps/details?id=com.rsg.chess
**GitHub org**: https://github.com/RSG-Group
**Logo**: https://images-na.ssl-images-amazon.com/images/I/41B43F-ITqL.png

**Comment by SaraVieira** [comment]
Closed by https://github.com/CompuIves/codesandbox-client/pull/1552
