### ISSUE TITLE
Allow script tags in <head>

### ISSUE THREAD

**Issue by justinfagnani** [CompuIves/codesandbox-client#789]
I'm trying to add script tags to load critical polyfills, but it looks like their stripped out in the preview.

See this example here: https://codesandbox.io/s/lyx2rr076q

**Comment by lbogdan** [comment]
Hey @justinfagnani , thanks for your report.

`<script>`s in `<head>` are already allowed, it doesn't seem that's the issue with your sandbox. I instead tried to load `webcomponents` from `unpkg.com` - https://codesandbox.io/s/n4zolm8rmm - it loads (you can see that `window.WebComponents` is defined), but I still get the same error - `Class constructor LitElement cannot be invoked without 'new'`.

**Comment by lbogdan** [comment]
And this is the same, but loading `webcomponents` from the `node_modules` dependecy -https://codesandbox.io/s/0q03vy7wkv (basically your example with some `index.js` changes). You'll notice that if you comment out `webcomponents-bundle.js`, the 'scripts loaded' console log isn't showing anymore.

**Comment by SaraVieira** [comment]
The webcomponents issue can now be fixed by using the static template :D
