### ISSUE TITLE
Add ability to configure or disable compilation.

### ISSUE THREAD

**Issue by justinfagnani** [CompuIves/codesandbox-client#792]
Now that browsers support native modules, we'd like to show that working in samples. We need to turn off compilation completely though.

**Comment by CompuIves** [comment]
This is a good one, would be really cool if we could have a native module example without the setup. We already have a loader that skips transpilation in some templates (`noop-loader`), which can be enforced by running `require(!noop-loader!./test.js)`. But I believe that another requirement is that the code should be in a `script` tag with `type="module"`, right?

I think it would make most sense to create a separate template for this, just something like a `bare` template. What do you think?

**Comment by SaraVieira** [comment]
Closed has we now have the static template https://codesandbox.io/s/github/codesandbox-app/static-template
