### ISSUE TITLE
Cursor Alignment Bug

### ISSUE THREAD

**Issue by luiscarbonell** [CompuIves/codesandbox-client#793]
The further right a cursor move on a line the more left displaced it becomes.

So far I've realized: 
- The cursor moves every time arrow keys are pressed.
- The shift or displacement becomes smaller as I move rightward and smaller when translating leftward

Currently running CodeSandbox on ChromesOS Version 65.0.3325.209.

Attached is a picture of a full line selection of a `create-react-app` template.

![CodeSandbox Cursor Displacement Issue](https://farm1.staticflickr.com/948/41888963671_d4ce9f8a3c.jpg)

Though the comma does not appear to be part of the selection, if the `backspace` is pressed, the whole line is deleted.

 The problem only seems to become more egregious as the lines length grows.

**Comment by luiscarbonell** [comment]
I enabled the `Use CodeMirror` Setting and it appears to fix the issue. Seems to be a problem with the `Monako` editor

**Comment by CompuIves** [comment]
I think we've had this issue before... Hmm, it could be related to our custom font loading later than the default font, after the width calculations of the characters are done.

**Comment by CompuIves** [comment]
Related issues: #729.

**Comment by jbolda** [comment]
This was happening to me on a Chromebook. Enabling CodeMirror or enabling ligatures both seemed to resolve it.

(I had a hard time finding this thread as my keywords were not turning up results so for others, a few more keywords: cursor position was off, cursor misalignment / misaligned.)

**Comment by developit** [comment]
For those on a Chromebook / Pixelbook: you can fix this and stick with Monaco as your editor!  Just head to the Codesandbox settings, reduce the font size by one and manually set your font (I set mine to Source Code Pro). Works like a charm.

**Comment by SaraVieira** [comment]
Issue closed as we dropped the monaco editor in the latest release
