### ISSUE TITLE
Dojo template not reporting syntax errors

### ISSUE THREAD

**Issue by nicknisi** [CompuIves/codesandbox-client#796]
Given code with syntax errors such as 

```typescript
const obj = {
    foo: 'bar'
    bar: 
};
```

The editor is not highlighting this code as having issues (see sandbox [here](https://codesandbox.io/s/j2ynw71wlv)), but this code does get properly marked in a React-TS template ([sample](https://codesandbox.io/s/6w3knpmpy3)).

We've looked into the TypeScript worker, and `ts.transpileModule` is fed the broken code and it comes out correct, but no errors are being reported back to Monaco.

**Comment by CompuIves** [comment]
That is really weird. The Monaco editor should show an error in this case. Maybe updating Monaco first #647 makes sense.
