### ISSUE TITLE
Component recursion causes full project crash. Dangerous because the semi permanent crash occurs if code *ever* in this state.

### ISSUE THREAD

**Issue by yuchant** [CompuIves/codesandbox-client#798]
Hey team,

I lost some work because my sandbox crashed for good, including in my profile page, after I was renaming some components and ended up rendering a component from within the same component.

Please help!

```
class Footer extends React.Component{
  render() {
    return <Footer/> 
  }
}
```

**Comment by CompuIves** [comment]
Ahh, I'm really sorry to hear that @yuchant! Recursion is still a way fo code execution that we should fix. Do you have the sandbox id? I can make a manual change to it to make it work again.

**Comment by yuchant** [comment]
@CompuIves it seemed to auto revert (nice feature!) or if it was your hand, thank you! This is an incredible thing you've built.

**Comment by lbogdan** [comment]
I'll close this, as it's now prevented to happen in the future by https://github.com/CompuIves/codesandbox-client/commit/8cfdc431c8c89cc408fc626f5527f14cecbbc9c4 .
