### ISSUE TITLE
[Bug report] Export to github doesn't work after changing github username

### ISSUE THREAD

**Issue by yxuchen** [CompuIves/codesandbox-client#801]
## Description
I was modified my `GitHub` account from `forzeny` to `yxcchen`

when i was using `codesandbox` to create `react project` and  Export `Sandbox to GitHub`, Error throw `Could not find the specified repository or directory` and always show `Creating Repository...`

## Expected Behavior
Export `Sandbox to GitHub`

## Observed Behavior
Create `GitHub` rep and `readme` file, but no other things

## Environment
`Chrome High`
## Reproducible Demo
https://codesandbox.io/s/72q469qwn6
https://github.com/yxuchen/12
https://codesandbox.io/s/github/yxuchen/12

**Comment by CompuIves** [comment]
Hey @yxuchen, did you also change your e-mail when you changed your username? Maybe there's something wrong with us updating the username.

**Comment by yxuchen** [comment]
doesn't

**Comment by yxuchen** [comment]
@CompuIves Tell me you email address, I can provide my `GitHub` account and password to solve this problem .i hope that it can solved quickly 😭 😭 😭 😭 😭

**Comment by yxuchen** [comment]
@CompuIves yes, i was update my pwd and re sign in and solve this problems thanks 😀
