### ISSUE TITLE
Run an npm command before deploying using Zeit (optionally static)

### ISSUE THREAD

**Issue by babakness** [CompuIves/codesandbox-client#803]
Hello, this is mostly a feature request--it would be amazing if a command could be executed before doing a deploy, for example `npm run generate` which would generate static assets, then deploy from the `dist` folder statically.

**Comment by SaraVieira** [comment]
Hey

We support the now configuration that does this so you can add a `now-build` on your package.json and that will run instead and the same with `now-start`
