### ISSUE TITLE
Suddenly `public` folder not accessible in any projects. No images, no JSON files. Critical bug.

### ISSUE THREAD

**Issue by yuchant** [CompuIves/codesandbox-client#805]
@CompuIves hey there, as of today the public folder for `create-react-app` projects isn't accessible. Any URL loads the index. 

Seems like an emergency!

**Comment by yuchant** [comment]
Seems to be affecting more than just my project.

Here's a project you pointed to to show how you can host `list.json` as a static asset: https://n74m8py83l.codesandbox.io/list.json

**Comment by CompuIves** [comment]
Thanks for letting me know! Deploying fix now...

**Comment by yuchant** [comment]
@CompuIves you're amazing! Thank you!

**Comment by actionakin** [comment]
I am having this issue.  No public folder access, create-react-app
