### ISSUE TITLE
Couldn't Select Dependency Version

### ISSUE THREAD

**Issue by yoonwaiyan** [CompuIves/codesandbox-client#808]
I was trying to play around with an older version of a React UI Framework but realized that I couldn't select the version I want to install while adding dependency. The dropdown closed immediately after I clicked while trying to select the package version.

![dependency](https://user-images.githubusercontent.com/3081772/39743665-2ffc7d36-52d4-11e8-9f79-b8f9c6587808.gif)

**Comment by CompuIves** [comment]
This is very weird, it seems like this started happening with the new Chrome on OSX only. I'll do some more debugging.

**Comment by CompuIves** [comment]
Just deployed a fix for this!
