### ISSUE TITLE
feature: language translations

### ISSUE THREAD

**Issue by Arthelon** [CompuIves/codesandbox-client#81]
I'd love to share this platform with people I know (some of whom are not native English speakers). Any thoughts on using react-intl or a platform like [transifex](https://www.transifex.com) (free for OSS) for translations?

**Comment by CompuIves** [comment]
Yes, this is *very* important and will help a lot for new users. I haven't taken a detailed look on i18n yet, do you have a recommended system? 

Let's further discuss it in this issue: https://github.com/CompuIves/codesandbox-client/issues/25
