### ISSUE TITLE
imports from .d.ts files are not found 

### ISSUE THREAD

**Issue by nicknisi** [CompuIves/codesandbox-client#819]
# 🐛 bug report

## Description of the problem

If a TypeScript file in CodeSandbox imports an interface from a .d.ts file it's not found and results in a `ModuleNotFoundError`.

In the following code where the `interfaces` module is actually a file called `interfaces.d.ts`, the sandbox fails when the import is actually used.

```typescript
import { VNode } from '@dojo/widget-core/interfaces';

let foo: VNode; // using the import causes the ModuleNotFoundError
```

I started digging into what might be causing this. In the case of Dojo 2 sandboxes, the typings files are loaded inline with the compiled source instead of providing a `typings` entry in the package.json. In #476 we added an additional check for these types of inline type definition dependencies and now I'm wondering if something similar needs to be done in `packages/app/src/sandbox/npm/fetch-dependencies.js`? Inspecting the return values from the `getDependencies` call it looks like it only contains the JS values. Should this also return .d.ts files when they exist?

## How has this issue affected you? What are you trying to accomplish?

This breaks any sandboxes that use .d.ts imports.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome |
| Operating System | macOS |

**Comment by CompuIves** [comment]
Thanks for the report! Hmm, after taking a look I think that our resolver cannot infer the extension. The solution would be adding `.d.ts` to https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/sandbox/eval/presets/dojo/index.js#L14 I believe.

**Comment by CompuIves** [comment]
When changing the sandbox to explicitly get the `.d.ts` I get this weird thing: https://codesandbox.io/s/px8j3xz80

**Comment by nicknisi** [comment]
Ah, ok I did look into adding the extension in the preset and I also get the same error. I'll continue digging into why. Thanks for the help!

**Comment by CompuIves** [comment]
Fixed!
