### ISSUE TITLE
Live editor updates to dependencies dont update for viewers

### ISSUE THREAD

**Issue by jamesopti** [CompuIves/codesandbox-client#820]
# 🐛 bug report

## Description of the problem
When a live "Editor" updates the dependencies of a sandbox, the updates take effect for them but appear broken for viewers, causing the 2 to become out of sync.

If the live owner reloads the page, the live session ends.

## How has this issue affected you? What are you trying to accomplish?
Id like to watch editors add packages and not have it appear broken.

### Your Environment
Chrome 65

**Comment by CompuIves** [comment]
Thanks for the report! I will fix this today.
