### ISSUE TITLE
ESLint validating against previous code instead (one char behind)

### ISSUE THREAD

**Issue by donysukardi** [CompuIves/codesandbox-client#822]
# 🐛 bug report

## Description of the problem
It seems like eslint validation always runs against one character behind (prev state)

![image](https://user-images.githubusercontent.com/410792/39862395-4087a8d0-5476-11e8-9e3d-4d72a0a009d8.png)

## How has this issue affected you? What are you trying to accomplish?
Unable to get accurate linting errors

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1525812457-341660c
| Browser | Chrome
| Operating System | macOS

**Comment by jamesopti** [comment]
+1 I've noticed this too. But it seems to be more than just "1 character behind"

I'm unable to fix the lint error here even by adding/removing the semicolon or adding and removing a character from the string itself:

<img width="720" alt="screen shot 2018-05-10 at 7 09 49 am" src="https://user-images.githubusercontent.com/3718812/39874001-62d3a45c-5421-11e8-9635-f6ba0b591115.png">
