### ISSUE TITLE
Erroneous "Cannot find the specified entry point" message

### ISSUE THREAD

**Issue by davestewart** [CompuIves/codesandbox-client#824]
# ❔ Question

I have a subfolder in my main repo with demo files, that I run via code sandbox:

- https://codesandbox.io/s/github/davestewart/vuex-pathify/tree/master/demo

This runs just fine.

However I've decided to move all the files to a new repository, and instead host an HTML page which shows links to the new repo.

Unfortunately, the updated folder + package does not seem to want to display:

- https://codesandbox.io/s/github/davestewart/vuex-pathify/tree/feature/demo

I don't understand the error message in the context that the previous setup was working fine. 

FYI, I copied the new subfolder `package.json` setup from the "Vanilla" sandbox project.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | online
| Browser | Chrome
| Operating System | OSX

**Comment by CompuIves** [comment]
Hey! I think you need to add another `demo` to the end of the path to make it work!

https://codesandbox.io/s/github/davestewart/vuex-pathify/tree/feature/demo/demo

**Comment by davestewart** [comment]
BOY, DO I FEEL STUPID!!! 

* facepalm *

Thanks :D
