### ISSUE TITLE
resizer shows over the settings modal

### ISSUE THREAD

**Issue by vueu** [CompuIves/codesandbox-client#83]
When in settings, the bar that resizes the file tree, and the editor, is shown above the modal. Seen here:
![Resizer over](https://i.gyazo.com/c67182d4d621936aa2619def372c8175.png)

The modal had a z-index of 20. Bumping it up to 30 fixed it, as seen here:
![Resizer under](https://i.gyazo.com/4459edce5aee60dd6e72ad552448f03f.png)

I can put in a pull request on this tonight, let me know what you think!

**Comment by CompuIves** [comment]
This is great! I always thought my screen was broken when I saw this line, good that we can finally fix this issue.

**Comment by vueu** [comment]
> I always thought my screen was broken ...
😆

**Comment by Arthelon** [comment]
@CompuIves Seems like this issue can be closed

**Comment by ValentinH** [comment]
This issue still exists:
![image](https://user-images.githubusercontent.com/2678610/31586828-2ca84df2-b1d7-11e7-8ced-15629a477122.png)

I'll submit a PR now.
