### ISSUE TITLE
Locally Apollo fetches Coinbase data but on CodeSandbox it gives error

### ISSUE THREAD

**Issue by deadcoder0904** [CompuIves/codesandbox-client#835]
# 🐛 bug report

## Description of the problem

Locally it fetches the data from [this Coinbase Launchpad](https://launchpad.graphql.com/w5xlvm3vzz) but on CodeSandbox it throws an error

## How has this issue affected you? What are you trying to accomplish?

I can't show the demo to people bcz of this issue

### Your Environment

| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Every
| Browser | Every
| Operating System | Mac OS latest

**Comment by lbogdan** [comment]
Closing this, as it's expected behavior - that's just how [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) works.
