### ISSUE TITLE
Fork button doesn't show feedback while forking

### ISSUE THREAD

**Issue by ValentinH** [CompuIves/codesandbox-client#844]
# 🐛 bug report

## Description of the problem
Today at React-Europe, we used CodeSandbox (again) and had to fork a sandbox. However, the wifi was pretty slow and thus the fork was not immediate. Thus, it feels like it wasn't working so I clicked again (many times ^^). Then the sandbox reloaded several times with each time a new fork.

## Suggestion
Display a loader while forking or disable the button.

**Comment by lbogdan** [comment]
THIS!

**Comment by ValentinH** [comment]
I actually forgot about this issue. Can I work on it?
