### ISSUE TITLE
Code in index.ts gets run twice?

### ISSUE THREAD

**Issue by mindplay-dk** [CompuIves/codesandbox-client#845]
# 🐛 bug report

## Description of the problem

My Typescript file appears to *periodically* run twice (?)

I'm getting an error like the following:

![image](https://user-images.githubusercontent.com/103348/40128208-5726073e-5931-11e8-9a7f-50519bd0608c.png)

There's only one call to `customElements.define()`, so I could not have called it twice, and there's no reason this line would somehow get run twice - so my best guess is, the code evaluates twice, for some reason?

To reproduce the issue, repeat the following two steps:

* Switch to `index.html`, add or remove a line, and press CTRL+S
* Switch to `index.ts`, add or remove a line, and press CTRL+S

Every now and then, saving the `.ts` file makes this error appear - and then, as soon as I save the `.html` file again, the error disappears.

### Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1526301282-e37d7bc
| Browser | Chrome 66.0.3359.139 (Official Build) (64-bit)
| Operating System | Win10 Pro (64-bit)

**Comment by mindplay-dk** [comment]
It seems it's not only running twice, it's actually launching repeatedly - in one project, I have a `window.setInterval()` call, and every time I make a code change, it appears to launch a separate interval timer, so I have more and more timers running on top of each other...

I suspect it's an issue with HRM or something? Maybe it's not expecting the entry module to have side-effects or something. But I think that's pretty common and expected in a sandbox environment?

This currently affects practically all of my projects, since I use Typescript and JSX on almost everything atm.

**Comment by CompuIves** [comment]
Ah, I think I understand the issue. This is a good one.

It seems like some global values are set, and our HMR doesn't take those into account when reloading the code. The best solution to begin with a clean slate is to refresh in that case.

I can think of two solutions:

1. Create a `sandbox.config.json` file and mark `Hard Reload on Save` as `true`
2. Use the `module.hot` API to handle hot module reloading, but this one is pretty hard to do.

For now option 1 seems like the best solution, we should take a look at if we can improve HMR to account for these issues.

**Comment by mindplay-dk** [comment]
Thanks! Yes, hard reload on save fixes it.

Of course, that's not ideal for something a bit larger.

I guess the "correct" thing would be to avoid modules with side-effects - e.g. export an `init()` function from your main module instead, and run it on page load?

I tried this in `index.html`:

```html
	<script type="module">
		import {init} from './src/index.ts';
		init();
	</script>
```

It doesn't produce any errors, but it doesn't work either.

Is there a "right" way to do this?

**Comment by derkoe** [comment]
I tried "Hard Reload on Save" but the script is still loaded twice. 
Example: https://codesandbox.io/s/2vzmvyj0jp

**Comment by lbogdan** [comment]
@derkoe It seems to work just fine here, are you still seeing that behavior? If so, what OS / browser are you using?

**Comment by derkoe** [comment]
@lbogdan that's because I added a workaround checking if the element is already registered (`customElements.get()`). I changed it back - now it fails again.

Example: https://codesandbox.io/s/2vzmvyj0jp
Preview link: https://2vzmvyj0jp.codesandbox.io/

**Comment by lbogdan** [comment]
Confirmed as a `vanilla` (`parcel`) template bug.

**Comment by damianobarbati** [comment]
Did anyone solve this?

**Comment by JamesACS** [comment]
Hey @damianobarbati - If you're still experiencing this problem please could you create a new issue?
