### ISSUE TITLE
Unable to Load Private Sandbox on iOS

### ISSUE THREAD

**Issue by edm00se** [CompuIves/codesandbox-client#848]
I’m on iOS 11.3.1 (latest stable) and in mobile Safari, navigating to an existing, private sandbox (“only you can see the sandbox”), I end up at the “not found” page.

Possibly related to #630?

**Comment by edm00se** [comment]
As an aside, but possibly related, I wound up at the same not found page on attempting to start a new sandbox from a GitHub repo (specified branch w/ /tree/... in url), also on iOS.

**Comment by CompuIves** [comment]
Hmm, I think this one isn't related. Are you signed in when you try to access the sandbox on IOS?

**Comment by edm00se** [comment]
I was, but Interestingly enough, I did have to sign back in a couple of times. Specifically, I would log in, go to my profile, tap on the sandbox, get the “not found page”, go back to my profile/sandbox page, then sign in again. I tried to see if it would be consistent in that fashion, but I wasn’t able to confirm that.

**Comment by acronym2k2** [comment]
I am seeing the same exact issue. when I make it public from my desktop, it then is visible from the iOS device. This is running Chrome on iOS.

**Comment by edm00se** [comment]
As a general update, I still get this regularly for my private sandbox and haven’t been able to acces it at all from my iPhone.

**Comment by edm00se** [comment]
Currently on iOS 12.0.1, I’m not able to reproduce this.
