### ISSUE TITLE
Jest tests not auto running when modifying .spec file

### ISSUE THREAD

**Issue by canda** [CompuIves/codesandbox-client#851]
When modifying a component spec, the tests doesn't run automatically as it does when I modify the component. Not even if I save the file.

To run the tests I either need to click on the run tests button or modify the component file.
It's a bit confusing because there is a flashing on the ui that gives the feeling of the tests having run again but they actually don't and the output message is from the last run.

**Comment by CompuIves** [comment]
This one is fixed!
