### ISSUE TITLE
Crash over and over on exact same point

### ISSUE THREAD

**Issue by mikael1000** [CompuIves/codesandbox-client#855]
# 🐛 bug report

## Description of the problem

I'm following this tutorial:

https://www.youtube.com/watch?v=HjToX1WWE3w&list=PLcCp4mjO-z98WAu4sd0eVha1g-NMfzHZk&index=2

And at the time mark 15:52 he copies a line and paste it under. I did not do that, I tried to write it but the whole thing just freezes over and over at the exact same point. I write:
**import RightPane from '.**   ...and there it freezes, on that dot. I want to write:
**import RightPane from './RightPane'**

It freezes the browser window and after a while a popup ask if I want to wait or close the window. I tried it over and over. I copy the link address open a new window/tab and reload. 

###  Link to sandbox:

Since it works when I copy the line above and change the code inte the copied line I will move on with the tutorial so I don't know how interesting the link is? But here it is:
https://codesandbox.io/s/0ojo3k6lvw

### Your Environment

Win 8
Chrome

**Comment by arthurdenner** [comment]
Hey, @mikael1000, is this still happening to you? I tried to reproduce it a few times, but I couldn't. I typed `import RightPane from './RightPane'`, as you described and it's shown in the video, but none of the times the sandbox froze.

PS: If this is not happening anymore, could you please close the issue?

**Comment by SaraVieira** [comment]
I feel like this has been fixed as I tried to reproduce it too so I am gonna close :D
