### ISSUE TITLE
Could not fetch dependencies for relative package

### ISSUE THREAD

**Issue by splincode** [CompuIves/codesandbox-client#856]
# 🐛 bug report

https://github.com/splincodewd/client-logger/tree/sandbox
https://codesandbox.io/s/github/splincodewd/client-logger/tree/sandbox

I use a library relative to the root
package.json

```
{
  
  "dependencies": {
    "@splincode/client-logger": "file:./lib/"
  },

}
```

Could not fetch dependencies, please try again in a couple seconds: Could not fetch version for @splincode/client-logger@file:./lib/: ENOENT: no such file or directory, open '/var/task/lib/package.json'

**Comment by lbogdan** [comment]
Hey @splincode ,

Looks like that branch is not there anymore. Is this still an issue for you?
