### ISSUE TITLE
Differences when running Parcel, parcel-bundler typescript locally versus in CodeSandbox

### ISSUE THREAD

**Issue by dekz** [CompuIves/codesandbox-client#857]
# 🐛 bug report

## Description of the problem
Parcel with parcel-bundler and typescript produces different results when executed locally versus in the codesandbox.

Imports work correctly when ran locally but in Codesandbox they return undefined.

![sandbox](https://media.discordapp.net/attachments/446901265348296705/448526351855517696/unknown.png)
![local](https://cdn.discordapp.com/attachments/446901265348296705/448526499352412170/unknown.png)
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Google Chrome
| Operating System | MacOs

**Comment by emersonlaurentino** [comment]
Hey @dekz on your file _src/index.ts_ you use `import` (es6), so you should use `require` (CommonJS).

**Comment by CompuIves** [comment]
Yep, the suggestion with @emersonlaurentino would work. I also noticed that we have a small difference in the tsconfig with parcel, we set `esModuleInterop` to `false` while Parcel set it to `true`. Setting that option to `true` would fix the issue as well. I opened a PR (here)[https://github.com/CompuIves/codesandbox-client/pull/909] to fix that, will need to test it a bit today.

**Comment by SaraVieira** [comment]
Issue closed due to lack of activity
