### ISSUE TITLE
Can't search for sandboxes that use a specific dependency

### ISSUE THREAD

**Issue by wordofchristian** [CompuIves/codesandbox-client#858]
# 🐛 bug report

## Description of the problem

In the [Search](https://codesandbox.io/search?refinementList%5Btemplate%5D=&page=1) screen I want to search for sandboxes using the dependency `reas`. I can't accomplish this through the UI however because the dependency selector seems to only prioritize results by popularity and the result I'm looking for is not listed:

<img width="344" alt="capture d ecran 2018-05-24 10 59 24" src="https://user-images.githubusercontent.com/555044/40503208-2a33b6e2-5f42-11e8-84a2-cc9241b1bd98.png">

I think this UI should prioritize exact name match above popularity.

This seems to be how the "Add dependency" feature works when you are working inside a sandbox.

<img width="686" alt="capture d ecran 2018-05-24 11 00 46" src="https://user-images.githubusercontent.com/555044/40503350-a0d95eb4-5f42-11e8-9fef-3c52dee8dc68.png">

## Temporary Workaround

Filter by any dependency in the list and then change it's value in the URL query string to the one you want.

**Comment by SaraVieira** [comment]
Issue closed due to lack of activity
