### ISSUE TITLE
Not able to import private github repos

### ISSUE THREAD

**Issue by bcbrian** [CompuIves/codesandbox-client#860]
# 🐛 bug report

## Description of the problem
Unable to import private github repo.
The website says [here](https://codesandbox.io/docs/git#base-concept) that "any" github repo works. It would be nice if you are a patron that your could edit private repos.
This PR https://github.com/CompuIves/codesandbox-client/pull/859 helps clear it in the docs.
## How has this issue affected you? What are you trying to accomplish?
I cannot work my private things the only reason I want to pay for this awesome service.
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Current Prod |
| Browser | Chrome |
| Operating System | macOS |

**Comment by alizbazar** [comment]
I would totally be ready to pay / become a patron if this was possible 👍

**Comment by infinity1975** [comment]
I got a Patron today, thinking that private repos was a part of that, as private sandboxes, but now I know it's not possible to access private repos. Is this gonna be fixed soon?, i almost never wanna work on public git repos.

**Comment by michaellee8** [comment]
Any updates on this one? I will definitely go patron if it is possible to use codesandbox like a web ide for private projects. You know it is never a good idea to expose everything to public repo.

**Comment by infinity1975** [comment]
Not even an answer, so no :(

**Comment by michaellee8** [comment]
@CompuIves Hey will we get any chance for this one?

**Comment by clayperez** [comment]
Plus one here. Working on a project and wanted to check it out with a colleague. Understand the ethos of supporting open source, but not everything can be.

**Comment by CompuIves** [comment]
This seems like one of the biggest requested features right now. I'll put my sprint of this week on this!

**Comment by alizbazar** [comment]
@CompuIves Any news re: private Github repos? Can't wait to try it out!

**Comment by tsongas** [comment]
@Compulves I'm also eagerly awaiting this feature!!!

**Comment by arraboa** [comment]
Nice to know the functionality is here already, can't wait to see it delivered. It's the last thing I need to finally be a Patron for this awesome product.

**Comment by adoptavia** [comment]
Any news on this? Its why i became a patron - got caught out with private repo v private sandbox!

**Comment by jaeming** [comment]
I would patron for this feature alone

**Comment by aptfx** [comment]
Any update on it?

**Comment by techytuppers** [comment]
I thought I was doing something wrong when I got 404 errors for my private Github repos :). To "fix" this I keep temporarily switching my Github repo to public in order to check in code! Became a Patron in order to keep everything Private - fingers crossed this is available soon. Thanks for all the hard work!

**Comment by wpitallo** [comment]
Any updates?

**Comment by samhotchkiss** [comment]
Hey @CompuIves , what are the blockers here?

**Comment by onexdata** [comment]
I'm a patron. I want this feature so bad I am scratching chalk boards and running around outside naked and screaming while painting my body with mint chocolate chip ice cream.

Please, make the madness stop.

**Comment by zlw11063** [comment]
Same! Any update?

**Comment by CompuIves** [comment]
No need to run outside naked covered in mint chocolate chip ice cream anymore! It's live 😄

**Comment by RyanReedUSE** [comment]
@compulves, are there any docs on how to use private repos as it’s still not working after a refresh. Main reason why I signed up. Thanks!

**Comment by onexdata** [comment]
Thank you so so so much!! 👍

I switched to cheese nips on account of the weather in the North... For what its worth spreading "cheese nip" grease all over your body can lead to actual "cheese nips". Its hard to describe and probably for the better that way. But I will say this... Traffic cones.

**Comment by RyanReedUSE** [comment]
This works now!

**Comment by rootion** [comment]
Cant make this to work? Is there any documentation to import private repos? It just says there was an error.

**Comment by alizbazar** [comment]
Hmm... did not quite work. The private repo is owned by an organization. I granted access to Codesandbox and became a patron. In Github Organization access for Codesandbox appears correct. Trying to create the sandbox using the Github wizard gives this error: ![screenshot 2018-12-02 17 43 38](https://user-images.githubusercontent.com/736771/49348385-f2278a80-f659-11e8-8379-3dd16c154570.png)

**Comment by CompuIves** [comment]
> Cant make this to work. Is there any documentation to import private repos? It just says there was an error.

Hmm, that is indeed weird. Did you give private repo access? (It should ask for it beforehand)

> Trying to create the sandbox using the Github wizard gives this error:

For some reason we counted more than 200 files in the repository. Are `node_modules` committed to the GitHub repo? I'm trying to find a reason why it found more than 200 files.

**Comment by alizbazar** [comment]
Aah, I see, so it's dependent on the number of files in the repo? We have 229 files, out of which 95% are JSON5 files containing the structure of our program, i.e. lessons, their structures and copy (think MOOC content). Hmm... wonder if there's a way around that.

**Comment by wpitallo** [comment]
@CompuIves, just wanted to find out if this works for server sandboxes now as well?

**Comment by garethx** [comment]
@wpitallo importing private repos to a container is supported.

**Comment by wpitallo** [comment]
@garethx thanks, I just want to confirm that it works for server based container like node.js? I know there used to be an issue with this?

**Comment by garethx** [comment]
@wpitallo it works

**Comment by wpitallo** [comment]
@garethx awesome, thank you!

**Comment by ryansaam** [comment]
githubbox.com is not working for my private repo. Said status 500 error on the error screen. It asked I linked my github account so I did and it still isn't working
