### ISSUE TITLE
Internal Server Error for Project Imported from Github

### ISSUE THREAD

**Issue by anasshad** [CompuIves/codesandbox-client#862]
# 🐛 Internal Server Error for Project Imported from Github

**Comment by rebz** [comment]
I am experiencing the same with a recently imported repo.

**Comment by CompuIves** [comment]
Hey @rebz, could you link the mentioned GitHub repository? I cannot reproduce this with some repos.

**Comment by rebz** [comment]
@CompuIves well now it is loading the repo but it keeps loading an old cached version of the repo which is not up to date with the code at all.

**Sandbox**
https://codesandbox.io/s/github/rebz/vuejs-meetup-code-along/

**Github Repo**
https://github.com/rebz/vuejs-meetup-code-along/

**Comment by rebz** [comment]
@CompuIves 
I created a brand new repo and copied the files over, tried using that and am receiving the Server 500 error.

https://codesandbox.io/s/github/rebz/meetup
https://github.com/rebz/meetup

**Comment by CompuIves** [comment]
I found the issue and deployed a fix for this, the reason of the error was a database timeout due to many validations on all files. I upped the default timeout as a temporary fix for now.
