### ISSUE TITLE
Imposible to get to Preferences through the GUI 

### ISSUE THREAD

**Issue by alejo4373** [CompuIves/codesandbox-client#863]
# :bug: Bug
First of all thanks for the awesome work. Codesanbox has been a great resource for me personally and lots of my classmates learning to code.

I was wondering if you guys just forgot to put a way to get to Preferences through the GUI where you can set stuff like editor mode or keybindings, or I just couldn't find it.

I found [this](https://codesandbox.io/changelog/#key-bindings) googling and discovered the keybinding to get to Preferences but I couldn't get there in any other way.

I also got confused seen the config file `sandbox.config.json` and realized that I couldn't set my preferences there. 

Thanks in advance!

**Comment by CompuIves** [comment]
Ahh I see what you mean. You can find preferences under the user menu, which probably is not the first place where you'll look for this haha. I'll create a fix for this now.

**Comment by CompuIves** [comment]
Fixed with last commit, will deploy later today.

**Comment by alejo4373** [comment]
Yes, it wasn't intuitive to click on the user profile photo to get to the user menu you mentioned. 
Thank you though!
