### ISSUE TITLE
Question: Is the React-app-rewired supported?

### ISSUE THREAD

**Issue by miukimiu** [CompuIves/codesandbox-client#869]
# ❔ Question

Thank you for this awesome project! 🎉

I'm trying to override the create-react-app webpack configs using the **react-app-rewired**.  In the **package.json** I changed the scripts start, build and test to use **react-app-rewired** instead of **react-scripts**.

The reason to do this is that I want to override, using the file `config-overrides.js`, some LESS variables from the "antd" library.

If I download the codesandbox project and run it locally it works. But it doesn't work in the codesandebox app. I think because the app doesn't run the start script that I added in the package.json. 

Is the **react-app-rewired** supported?

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Latest
| Browser | Chrome v. 66
| Operating System | Mac OS Sierra

**Comment by CompuIves** [comment]
Thank you very much! You have a very valid use case, it's currently not yet possible but we're working currently on making it work. So expect it somewhere in the coming days to work 😄

**Comment by miukimiu** [comment]
Thanks! Keep up the good work! 😄

**Comment by selrond** [comment]
@CompuIves how is it now? Not working form me so far
