### ISSUE TITLE
Make preferences permanent

### ISSUE THREAD

**Issue by rhernandog** [CompuIves/codesandbox-client#87]
Hello Ives,

First of all, thanks for the great work, I love how easy is to create React live samples with this app.

More than an issue is an enhancement request actually. Right now if I create a new sandbox and then go back to it later that day, I have to set up all the preferences again, such as autocomplete, line height, prettier settings, etc. It would be nice to either saver those for each sandbox or create a general preferences for the account that could be fetched whenever the user creates/loads a sandbox.

Although I'm in no hurry about it, I can live with setting everything by hand for now.

Best,
Rodrigo.

**Comment by CompuIves** [comment]
Hey @rhernandog! You encountered a bug haha, the preferences weren't properly saved to localStorage. I fixed the bug and now the settings should persist again.

Thanks for opening the issue, I hadn't even noticed this bug yet!

**Comment by rhernandog** [comment]
Hi @CompuIves, 

Sorry to re-open this, but the issue is happening again. Every time I open a sandbox I have to set my preferences again. Mostly what I do is change the line height and font family.

Again, this is not too urgent, I can live changing this when I work on my sandboxes, so whenever you have the time to solve it.

Cheers,
Rodrigo.

**Comment by ryanpcmcquen** [comment]
@CompuIves, is there any way to save this to the cloud and not LocalStorage? It'd be nice to have it synced between all machines.

**Comment by CompuIves** [comment]
Yep, we need this @ryanpcmcquen. Could you open an issue for it?

**Comment by ryanpcmcquen** [comment]
@CompuIves: https://github.com/CompuIves/codesandbox-client/issues/405

**Comment by guaiamum** [comment]
Think it have resurfaced :(
Would be glad to help if I can :)
![bug](https://user-images.githubusercontent.com/21321095/130327297-482ed920-a415-4903-8e8c-bf0a97b4b946.gif)

**Comment by sannek** [comment]
Hi, have you tried saving your preferences via the menu? It's a little hidden, but you can find it here:
Click the three vertical dots all the way in the top right of the screen
<img width="479" alt="Screenshot 2021-08-23 at 10 21 29" src="https://user-images.githubusercontent.com/17491062/130414747-eb954ee1-761a-4f81-b4a2-7ad4a5e26ce9.png">
Then choose preferences, and preferences profiles. That will allow you to store your settings on our server, and they _should_ persist properly.

**Comment by guaiamum** [comment]
Yes, I have, but no dice 😢 
Tried updating settings locally, manually going to profile and hitting "Update Profile":
<img width="344" alt="Screenshot 2021-08-23 at 11 23 06" src="https://user-images.githubusercontent.com/21321095/130432044-6d90ed0a-5063-42b9-ad08-1beaf821ee0e.png">

Refreshed, changes not saved, and this is always what it tells me:
<img width="392" alt="Screenshot 2021-08-23 at 11 21 46" src="https://user-images.githubusercontent.com/21321095/130431973-99fa60d1-595e-4ed2-a0d4-de24712a8120.png">

**Comment by felipecrubio** [comment]
Hi @CompuIves ,
It seems that I have encountered the same bug. Tried to save the preferences via the menu, but it didn't work as well.
Everytime I open a sandbox I have to set up the preferences again.

Best wishes

**Comment by uguryediveren** [comment]
The problem remains. When I set my settings in codeSandbox the settings were default after closing the tab.

**Comment by JamesACS** [comment]
Hey @uguryediveren - This is something we're aware of. We're working on a wider set of fixes that should address this!

**Comment by uulaal** [comment]
Hey, it would be nice to see some updates here! I have the same issue - preferences are reset after every page reload. I've tried to save them to profile, but every time I reload the page I see message "Your local preferences are not in sync with the server"

**Comment by cobrabr** [comment]
Having the same exact issue, specifically with the autoclosing tags preferences.

**Comment by CompuIves** [comment]
Ah, yes. For the autoclosing tags we had to do an override because it
interferes with live collaboration and it would generate a lot of closing
tags at once when more people were in the sandbox. However, we do have a
fix for that and for settings that we're rolling out over the next few
months. The fix is part of a bigger upgrade for VSCode, which is why it's
taking longer than normal.
