### ISSUE TITLE
Feature Request: Support Node.js Server Development in Parallel with Client

### ISSUE THREAD

**Issue by Saeris** [CompuIves/codesandbox-client#872]
## What is this feature?

This feature would allow users to write and run Node.js servers that would run in parallel with their client application. For example: a GraphQL API server which can be queried by a React client application, both running in the same sandbox.

## How the feature should work?

Not sure how this could be supported in CodeSandbox's environment, but in my own projects I use `npm-run-all` to run two node processes in parallel, enabling webpack to build and watch my client application while simultaneously serverless-offline builds and watches my GraphQL API handler. You can look to my [mini-movie-db](https://github.com/Saeris/mini-movie-db) for an example of how this is set up on a local machine (the client was developed in CodeSandbox!).

In order to make this work, CodeSandbox may need to add support for running NPM scripts defined in `package.json` as an alternative to the current behavior of detecting a template from package dependencies + the main script path.

Alternatively, perhaps a good solution could be to have a CodeSandbox specific key within `package.json` to define the sandbox environment, wherein a user could define multiple entry points (one for each client/micro-service), templates for running each, optional config paths for those templates, and a `name` key to scope console output to. Example:

```json
...
  "codesandbox": {
    "sandboxes": [
      {
        "name": "client",
        "template": "preact-cli",
        "config": "preact.config.js",
        "main": "src/index.js"
      },
      {
        "name": "api",
        "template": "serverless",
        "config": "serverless.yml",
        "main": "api/index.js"
      }
    ]
  },
...
```

## You have examples or an idea how it can be implemented?

I would look at existing services which run publicly accessible node.js servers, such as [glitch](https://glitch.com/) or [apollo launchpad](https://launchpad.graphql.com/new). Running both a client and one or many services in parallel seems to be the major difference here from other sites/services. 

Additional thought needs to be put into how to run these services on different ports/addresses by which they can be connected to by a client application.

**Comment by onexdata** [comment]
http://repl.it allows this for free.  Until codesandbox offers a Node backend, this is a great way to compensate.  repl.it allows you to expose your node (or almost any other backend) to the public, so you can have your codesandbox frontend talk with your repl.it backend.

**Comment by lbogdan** [comment]
Closing this, as by using server sandboxes (and a bit of imagination) you can handle virtually any such use case.
