### ISSUE TITLE
Feature Request: Add a Gatsby Template

### ISSUE THREAD

**Issue by Saeris** [CompuIves/codesandbox-client#873]
## What is this feature?

As the title says, create a new template for building Gatsby based sites within CodeSandbox!

## How the feature should work?

I would expect the template to work similar to the existing templates. It would be ideal if it could detect and use `gatsby-config.js` to allow users to customize their site similar to how they would in a local development environment.

**Comment by jimthedev** [comment]
Good news. I think this launched. :)

**Comment by SaraVieira** [comment]
This already launched 🎉
