### ISSUE TITLE
Feature Request: Add Netlify Deployment Option

### ISSUE THREAD

**Issue by Saeris** [CompuIves/codesandbox-client#874]
## What is this feature?

This feature would allow users to deploy to services other than ZEIT Now, such as Netlify.

## How the feature should work? 

It would vary per deployment service target. As far as Netlify goes, I would take a look at their CLI deployment process: https://www.netlify.com/docs/cli/

**Comment by manniL** [comment]
I thought about a Netlify integration too *but* now that you can commit, PR and export to GitHub (which could then auto-deploy to Netlify), will it add value?

**Comment by SaraVieira** [comment]
We will add it still, we are thinking of at least Netlify and surge

**Comment by durkinio** [comment]
+1, as an avid Netlify user, this would be mega awesome

**Comment by lbogdan** [comment]
@Saeris Let's keep this one specifically for Netlify. Feel free to open other issues for other hosting providers.

**Comment by lbogdan** [comment]
It's live! https://github.com/CompuIves/codesandbox-client/pull/1520

Please test it and let us know if you have any issues. If everything's working, let's close this!

**Comment by lbogdan** [comment]
Well, I'm gonna close this for now, if you have any issues deploying to Netlify, please open a new issue.
