### ISSUE TITLE
CLI not uploading anything

### ISSUE THREAD

**Issue by riwu** [CompuIves/codesandbox-client#876]
# 🐛 bug report

## Description of the problem
CLI did not detect JS files.
I couldn't find the files it claimed to be uploading (`.DS_STORE`, `favicon`) on my profile too.
```
$ codesandbox ./

  CodeSandbox CLI
  The official CLI for uploading projects to CodeSandbox

> Deploying ./ to CodeSandbox

> We will upload 3 static files to your CodeSandbox upload storage:
> src/.DS_Store: 6 KB
> public/favicon.ico: 3.78 KB
> .DS_Store: 8 KB

> By deploying to CodeSandbox, the code of your project will be made public
? Are you sure you want to proceed with the deployment? Yes
> [success] Succesfully created the sandbox, you can find the sandbox here:
> [success] https://codesandbox.stream/s/undefined
```

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  1.2.10
| Browser |  Chrome Version 67.0.3396.62 (Official Build) (64-bit)
| Operating System | macOS Sierra 10.12.6
| Node | v9.10.1
| Yarn | 1.5.1

**Comment by CompuIves** [comment]
Hey! I think your `NODE_ENV` is set to `development` by default, because it's trying to upload to our staging server. I'm now publishing a `1.2.11` to use another env variable for it.
