### ISSUE TITLE
Support for dependency from Github branch?

### ISSUE THREAD

**Issue by alansouzati** [CompuIves/codesandbox-client#88]
First of all, really cool stuff. I first learned about codesandbox from `styled-components` issue template. I'm impressed with it, great job @CompuIves!
 
I want to replace Grommet base codepen with codesandbox. I like that I can use imports and have a structure that is very close to my local environment.

Our codepen today is used to test things in a branch called "stable" that is updated multiple times a day after CI passes in the master branch. I understand that I can use "External Resources" and add the minified css and js available [here](https://github.com/grommet/grommet/tree/stable).

But I wondering if there is a way to specify the branch in the version for the" Dependency" section. Something similar to this package.json [here](https://github.com/grommet/grommet-docs/blob/master/package.json#L23).

When I add `https://github.com/grommet/grommet/tarball/stable` as the version for a package, I get an error in codesandbox.

Thoughts?

**Comment by CompuIves** [comment]
Ah, good one @alansouzati! I now remember that I disabled Github imports at the beginning of CodeSandbox as it would maybe become a Patron feature later. I now decided that this should be an option for free users as well.

I'll add the functionality back in somewhere this week, thanks for making me aware of this!

**Comment by CompuIves** [comment]
It turns out that this is a bit harder to implement than I expected 😅 . I'm currently rewriting the packager and I hope to add this to the release, I need to find a way to extract a version from a git package.

**Comment by CompuIves** [comment]
This has been fixed!
