### ISSUE TITLE
Upgrade to TypeScript version 2.9

### ISSUE THREAD

**Issue by PandaSandStudio** [CompuIves/codesandbox-client#880]
# 🌈 Feature

Upgrade to TypeScript 2.9 (Expecially in the react-ts template)

TypeScript 2.9 should be supported (or the latest version / the one at https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html)

This would allow people to use the `Extract`, `conditional types` and many other features of typescript 2.8+

Update: upgrading to the latest version of typescript (3.0+) would also allow for many other features, such as mapped tuple types, unknown, etc.

**Comment by SaraVieira** [comment]
Hey!

I will close as this has been made in the meantime by moving to normal Create React app and now our versions come from react scripts

Please reopen if needed :)
