### ISSUE TITLE
Cannot read property 'Expression' of undefined

### ISSUE THREAD

**Issue by davestewart** [CompuIves/codesandbox-client#881]
# 🐛 Bug report

## Description of the problem

In a couple of sandboxes now, I keep getting this error when compiling Vue projects:

```
Y
https://codesandbox.io/static/js/sandbox.7b01ecfb.js:259:340177
r.<anonymous>
https://codesandbox.io/static/js/sandbox.7b01ecfb.js:259:342540
g
https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10482
Generator._invoke
https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10270
Generator.e.(anonymous function) [as next]
https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:10661
n
https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:45137
(anonymous function)
https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:45278
new t
https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:97647
Worker.<anonymous>
https://codesandbox.io/static/js/common-sandbox.405431f9.js:21:45072
Worker.<anonymous>
https://codesandbox.io/static/js/sandbox.7b01ecfb.js:259:343695
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.
```

###  Links to sandboxes

- https://codesandbox.io/s/2pn9rnnx0j
- https://codesandbox.io/s/github/davestewart/vuex-pathify-demos/tree/master/simple

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Online
| Browser | Chrome 66.0.3359.181
| Operating System | OSX 10.12.6

Not sure if this can be looked at urgently, but was going to use CS to submit files for an interview test this morning! If you have any workarounds in the interim of looking at it, that would be great.

I thought this was maybe just the code in one of my sandboxes, but I guess it's something to do with
CS internals now.

Cheers,
Dave

**Comment by CompuIves** [comment]
I'll take a look at it now!

**Comment by CompuIves** [comment]
Hmm, I'm afraid that I cannot fix it right now. The fix is very easy though, if you remove:

```
    "@vue/cli-plugin-babel": "^3.0.0-beta.9",
    "@vue/cli-plugin-eslint": "^3.0.0-beta.9",
    "@vue/cli-service": "^3.0.0-beta.9",
    "@vue/eslint-config-standard": "^3.0.0-beta.9",
```

from the `package.json` we will see it as a `vue-cli: 2.0` project and it will work.

**Comment by CompuIves** [comment]
I'll keep this open to track my progress on vue v3 support.

**Comment by davestewart** [comment]
> The fix is very easy though, if you remove ...

That's great!

Thanks Ives, hugely appreciated as always.

**Comment by SaraVieira** [comment]
Issue closed due to lack of activity
