### ISSUE TITLE
GitHub Sync appears to be broken

### ISSUE THREAD

**Issue by jtheisen** [CompuIves/codesandbox-client#885]
# 🐛 bug report

## Description of the problem

I pushed a change to the master branch of the [respective GitHub repo](https://github.com/jtheisen/brazen-bindings), but the code sandbox didn't sync.

Pushing further from the code sandbox to GitHub caused a popup warning me about a merge conflict.

I see that another branch was created by code sandbox.

**Comment by CompuIves** [comment]
Hey!

To be completely sure, is this sandbox (https://codesandbox.io/s/github/jtheisen/brazen-bindings) synced with the GitHub repository?

**Comment by jtheisen** [comment]
Yes!

**Comment by jtheisen** [comment]
Yes!

**Comment by SaraVieira** [comment]
Issue closed due to lack of activity
