### ISSUE TITLE
Can CSB handle es-modules?

### ISSUE THREAD

**Issue by drcmda** [CompuIves/codesandbox-client#887]
This line causes trouble in CSB:

```jsx
import { TimingAnimation, Easing } from 'react-spring/dist/addons'
```

It will lead to a regular es flat bundle: https://unpkg.com/react-spring@5.3.8/dist/addons.js which works in webpack at least.

In CSB only the commonjs variant work (by adding the ".cjs" extension). Is this a known issue, or do i export something in a way that's wrong?

PS.

Sandbox: https://codesandbox.io/embed/q9lozyymr9 (removing the .cjs will trigger it)

**Comment by CompuIves** [comment]
Ah, it turns out that our function to detect es-modules didn't really work with minified es modules code. I fixed it with https://github.com/CompuIves/codesandbox-client/commit/437075170e195f2f0e81c452f6a3c42b7f3e77e6 and will deploy that somewhere today.

**Comment by drcmda** [comment]
@CompuIves what! i didn't know. I ever there's something i can help you with in the process, i'm here. 😃And thank you for the fix!
