### ISSUE TITLE
upload not available for private sandboxes

### ISSUE THREAD

**Issue by ericbschwartz** [CompuIves/codesandbox-client#889]
# ❔ Question
Upload button is available for public sandboxes:
![screen shot 2018-06-06 at 7 12 08 pm](https://user-images.githubusercontent.com/1041207/41069840-9d3dcc92-69bd-11e8-966c-6e9331664682.png)

not private:
![screen shot 2018-06-06 at 7 11 46 pm](https://user-images.githubusercontent.com/1041207/41069858-afcf3760-69bd-11e8-9efa-f18362a10355.png)

Is this by design or a bug?

**Comment by ericbschwartz** [comment]
I see that drag-n-drop of files into sandbox works fine, so the upload button seems to be an inconsistency between public/private.

**Comment by CompuIves** [comment]
Hey! Yep, I added this by design. Uploaded binary files, like images, are
public by default and I don't want to confuse people by giving the option.
Maybe it's better to just show a warning though, what do you think?

**Comment by ericbschwartz** [comment]
Hey Ives! One can drag-n-drop a file into a private sandbox, so absence of the upload button for private doesn't stop drag-n-dropping. My use-case is mainly uploading js/html/css files during prototyping, usually before being organized enough for a repo - hence a sandbox! Yeah, maybe a warning if uploading a binary would work.  Related, I would love to see GitHub private repos work, as per https://github.com/CompuIves/codesandbox-client/issues/860
Thanks for all the work on codesandbox - a pleasure to use.

**Comment by SaraVieira** [comment]
Closed as an answer was found and pricvate repos are now supported :D
