### ISSUE TITLE
Badge for readme files

### ISSUE THREAD

**Issue by jamesmcallister** [CompuIves/codesandbox-client#89]
Would be nice to have a small badge image, so we can use it to link from the readme on the repo to its sandbox.

**Comment by CompuIves** [comment]
We have something like this already, if you open the share view (by clicking on share in the header) you can also copy the markdown for a button image. Or do you mean something else? 

Nevertheless we should make this button more clear, it's a bit hidden away right now 😅

**Comment by jamesmcallister** [comment]
I didn't even look in there. 

Just added it to the readme now, thanks!
