### ISSUE TITLE
Code Sandbox crashes when loaded in incognito tab

### ISSUE THREAD

**Issue by bvaughn** [CompuIves/codesandbox-client#890]
# 🐛 bug report

## Description of the problem
One of my sandboxes (https://codesandbox.io/s/mz5w04xpz9) crashes when loaded in an incognito Chrome tab.

## How has this issue affected you? What are you trying to accomplish?
I'm hoping to publish a new blog post on reactjs.org that links to this sandbox.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1528373306-8d63b65
| Browser | Chrome, 65.0.3325.146 (Official Build) (64-bit)
| Operating System | macOS 10.13.4 (17E202)

**Comment by bvaughn** [comment]
![screen shot 2018-06-07 at 9 36 45 am](https://user-images.githubusercontent.com/29597/41103314-d86175d4-6a36-11e8-84b7-658ec120e0f8.png)

**Comment by CompuIves** [comment]
So sorry for that! Deploying fix now...

**Comment by bvaughn** [comment]
No problem! 🙇 Thanks for the quick response!

**Comment by CompuIves** [comment]
It's live! Thanks for reporting this, really stupid mistake on my part.
