### ISSUE TITLE
Sandbox goes into infinite loop

### ISSUE THREAD

**Issue by Pyrolistical** [CompuIves/codesandbox-client#896]
# 🐛 bug report
I was writing a code sample for my library, and I think I wrote an infinite loop. Now whenever try to open the sandbox, the Chrome tab goes to 100% cpu.

### Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Browser | Chrome 67.0.3396.79|
| Operating System | macOS 10.13.4|

If the sandbox didn't auto run every time it opened, I could fix the code.

**Comment by Pyrolistical** [comment]
Another repo case: https://github.com/CompuIves/codesandbox-client/issues/50#issuecomment-372188074

**Comment by Pyrolistical** [comment]
One way to solve this is to for codesandbox to inject a js heartbeat into apps. The heartbeat will fail on load, at which point on next load codesandbox should prompt sandbox history and allow you to revert to a previous version.

**Comment by Pyrolistical** [comment]
I was able to pull the source from the broken sandbox and manually re-create it using the API `https://codesandbox.io/api/v1/sandboxes/4x9mx64kl0`

**Comment by Ikaer** [comment]
I think I am in the same case: https://codesandbox.io/s/v8km1067ml 
(sandbox vanilla + jquery & semUI)

**Comment by SaraVieira** [comment]
Issue closed due to lack of activity

**Comment by keverw** [comment]
Looks like I mistakenly made a loop too. https://codesandbox.io/s/vigilant-shannon-veu5b

I'd be cool if you could maybe add a query string like `?safemode=1` that would not auto run the code, so could fix it, save and exit safe mode when ready to run it again.

**Comment by bduffany** [comment]
+1, a query string like `?safemode=1` would be perfect.

**Comment by lbogdan** [comment]
It already exists, but it's named `runonclick`, i.e. https://codesandbox.io/s/vigilant-shannon-veu5b?runonclick=1 .
