### ISSUE TITLE
Embeds of URLs with a dot render a black screen

### ISSUE THREAD

**Issue by Haroenv** [CompuIves/codesandbox-client#901]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

Embedding a sandbox which had a `.` in the GitHub repo's folder. 

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | latest?|
| Browser | Chrome / Safari|
| Operating System | macOS|

`https://codesandbox.io/embed/github/algolia/doc-code-samples/tree/master/InstantSearch.js/getting-started` doesn't work, while the edit link does: `https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/InstantSearch.js/getting-started`

**Comment by Haroenv** [comment]
![image](https://user-images.githubusercontent.com/6270048/41402141-d3663886-6fc1-11e8-891d-0d765f2d6456.png)

This error is shown in the console

**Comment by joeynimu** [comment]
@Haroenv I don't quite understand when you say `Embedding a sandbox which had a . in the GitHub repo's folder.`. The link you provided doesn't render anything which makes it a bit hard to see what you are doing. Maybe share the code on here? if it's not much

**Comment by CompuIves** [comment]
Seems because this happens because of the embed that doesn't know how to handle a missing `dependencies` field. Making fix now.

**Comment by Haroenv** [comment]
thanks Ives <3
