### ISSUE TITLE
adding element-ui icon fonts to project

### ISSUE THREAD

**Issue by andreydos** [CompuIves/codesandbox-client#903]
# ❔ Question

I create base vue project and add element-ui library. 
I copy-paste of example (from elemet-ui site) and its work fine except problem with icon fonts(icons not displayed).
I try to import icon font manually in <style> section (with @import or font-face) and in main.js(as like stylesheet file). 
When I download project and run it locally icons font work fine.
Please help me to understand how to load such fonts correctly. 

### Your Environment
| Сodesandbox  |

**Comment by joeynimu** [comment]
@andreydos The link you provided gives an error

```
CompileError
Error: Could not find /node_modules/element-ui/lib/theme-chalk/fonts/element-icons.ttf
        on line 33 of /stdin
>> @import '../node_modules/element-ui/lib/theme-chalk/fonts/element-icons.ttf';
   --------^
```

**Comment by lbogdan** [comment]
@andreydos There's an issue with how `url(...)` is resolved in CSS included using `import`. As a workaround, you can load it from `unpkg.com` as an "external resource": https://codesandbox.io/s/km779ww4rv .

**Comment by andreydos** [comment]
@lbogdan  thanks a lot
