### ISSUE TITLE
error fetching dependency from cloudfront

### ISSUE THREAD

**Issue by smcatala** [CompuIves/codesandbox-client#904]
HTTP GET error occurs when downloading inferno@5.1.0 from cloudfront:
https://codesandbox.io/s/m9qyj2wv4p
![image](https://user-images.githubusercontent.com/3369203/41401554-7121215a-6fc0-11e8-9f2b-7a371d886cce.png)

same error when following the corresponding url:
https://d1jyvh0kxilfa7.cloudfront.net/v1/combinations/inferno@5.1.0%2Binferno-create-element@5.1.0.json

there are no such errors with inferno@5.0.6 (and any other previous versions):
https://codesandbox.io/s/znmyj24w4p
![image](https://user-images.githubusercontent.com/3369203/41401495-4e8429c6-6fc0-11e8-93e5-225f53fbc107.png)

**Comment by CompuIves** [comment]
Aii, seems like the postinstall script of the dependency failed. I'm deploying a fix now.

**Comment by CompuIves** [comment]
Fix is live!
