### ISSUE TITLE
Uncaught SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by wagon1104** [CompuIves/codesandbox-client#91]
![o 4a5 pwk xoetpqwbtx6j](https://user-images.githubusercontent.com/29653018/28708019-21622f84-73ad-11e7-93fa-1d167d1cf9cd.png)

**Comment by CompuIves** [comment]
Hmm, this is strange. I haven't encountered this issue before. 

Have you tried doing:

```
rm -rf node_modules
yarn install
```

from the codesandbox directory?

**Comment by Arthelon** [comment]
@CompuIves I've run into these error messages when running the development server as well.

**Comment by CompuIves** [comment]
Okay, good to know. Thanks @Arthelon, I'll look into fixing these 2 errors when I'm back from Vietnam.

**Comment by CompuIves** [comment]
Has been fixed!
