### ISSUE TITLE
Code works fine after download, but not on codesandbox.io

### ISSUE THREAD

**Issue by ferrao** [CompuIves/codesandbox-client#910]
# 🐛 bug report

## Description of the problem
Problem seems to be with the `react-semantic-toasts` dependency, which in turn depends on `semantic-ui-css` and `semantic-ui-react`. 

For some reason, none of the icons (not sure which of the above 2 semantic packages provides those) shows up.

If i download the project and `npm install` locally, all works as expected.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Browser | Chrome Version 67.0.3396.87 (Official Build) (64-bit)
| Operating System | OSX

**Comment by SaraVieira** [comment]
Issue closed due to lack of activity
