### ISSUE TITLE
Cannot find a way to configure it (code, navigation, etc.) to display with a normal color scheme (black or colored text on a WHITE background)

### ISSUE THREAD

**Issue by jabbott-dm** [CompuIves/codesandbox-client#915]
# 🌈 Feature
Cannot find a way to configure it (code, navigation, etc.) to display with a normal color scheme (black or colored text on a WHITE background)

**Comment by steventsao** [comment]
This is a WIP https://github.com/CompuIves/codesandbox-client/issues/359 @jabbott-dm

**Comment by CompuIves** [comment]
Yep, we already have an issue for this one. Closing in favor of #359.
