### ISSUE TITLE
CSS lost on edit

### ISSUE THREAD

**Issue by geddski** [CompuIves/codesandbox-client#917]
# 🐛 bug report

## Description of the problem
When editing my CSS the live reload loses most of the styling. It happens on the codesandbox site as well on my own site with an embed.

## How has this issue affected you? What are you trying to accomplish?
Making it so readers of my site can edit the examples and see their changes. But the examples get busted on the first edit. 

###  Link to sandbox: [link]() (optional)
https://codesandbox.io/s/n04w501kml

### Your Environment
Сodesandbox

![codesandbox-bug](https://user-images.githubusercontent.com/515722/41625368-d499ced0-73d5-11e8-988f-81afadb89259.gif)

**Comment by geddski** [comment]
I believe it's discarding the shared.css file on save.

**Comment by dfsq** [comment]
I think it affects parcel template.

**Comment by CompuIves** [comment]
Yep, this is affecting the Parcel template. I'll take a look now.

**Comment by geddski** [comment]
works great now, thanks!
