### ISSUE TITLE
Any interruption to host's internet causes live session to kick out all attendees

### ISSUE THREAD

**Issue by quintondang** [CompuIves/codesandbox-client#919]
# 🐛 bug report

## Description of the problem
Whenever the host of a live session loses internet or causes the app to go from "Gone live!" to "Reconnecting...", it will kick out people attending the live session.
 
## How has this issue affected you? What are you trying to accomplish?
We use this environment to collaborate with candidates to conduct engineering interviews, so this is disruptive to our flow and short time we have with a candidate. Our current work around is to restart the live session and send them a new live session link.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  React Environment
| Browser |  Google Chrome (latest)
| Operating System | Mac OS Sierra

**Comment by CompuIves** [comment]
This one will be fixed either today or tomorrow, I rewrote the logic behind Live.

**Comment by SaraVieira** [comment]
This has been fixed by the live rewrite 🎉
