### ISSUE TITLE
TypeError: CSS2Properties doesn't have an indexed property setter for '0'

### ISSUE THREAD

**Issue by mBeierl** [CompuIves/codesandbox-client#92]
My project at https://codesandbox.io/s/Q5AE9vG0 works fine in Chrome, but shows this error in Firefox:
`Error in index.js: TypeError: CSS2Properties doesn't have an indexed property setter for '0'`.

I removed the inline styling of the App's root-div element. Maybe it has something to do with that?

**Comment by Arthelon** [comment]
This seems to be an issue with your sandbox code. 

When I logged the `style.container` field in the `CustomContainer` component the output is an array. Removing that invalid `style` prop fixed this for me.

**Comment by mBeierl** [comment]
Thanks! That fixed it. Weird that it doesn't throw any error in Chrome.
