### ISSUE TITLE
Bug with ngxs typescript annotation @Selector()

### ISSUE THREAD

**Issue by sinedied** [CompuIves/codesandbox-client#923]
# 🐛 bug report

## Description of the problem
When adding a ngxs `@Selector()` annotation in my Angular project (https://codesandbox.io/embed/5455r3lj2n?module=%2Fsrc%2Fapp%2Feditor.state.ts, uncomment line 12), compilation is broken:
![image](https://user-images.githubusercontent.com/593151/41782312-2d954936-763a-11e8-93fd-3b3517d7cc79.png)
The same code works locally and in StackBlitz.

## How has this issue affected you? What are you trying to accomplish?
Use ngxs `@Selector()` annotation in an Angular project, and it's not working :(

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1529528672-ef4e3ca
| Browser | Chrome 67.0.3396.87
| Operating System | OSX 10.13.4

**Comment by CompuIves** [comment]
Hay! I'm sorry for that, our configuration generated went wrong and `experimentalDecorators` was turned off in our transpiler. The fix should be live in ~10 min!
