### ISSUE TITLE
key is too long import via github

### ISSUE THREAD

**Issue by thian4** [CompuIves/codesandbox-client#929]
# 🐛 bug report

## Description of the problem
Failed to import via github repo, got error of 

`Could not fetch dependencies, please try again in a couple seconds: Your key is too long`

https://codesandbox.io/s/github/thian4/hoc-redux

**Comment by CompuIves** [comment]
Hey! This error normally occurs when there are too many dependencies added,
which results in a huge bundle. I recommend dividing your dependencies in
package.json up: the dependencies you use to build the project would go to
`devDependencies` and all other dependencies should go to `dependencies`.
When you make this change it should work!

**Comment by SaraVieira** [comment]
Issue closed due to lack of activity
