### ISSUE TITLE
How do you access index.html in an imported repo?

### ISSUE THREAD

**Issue by colshacol** [CompuIves/codesandbox-client#931]
# After importing a Github repo into a new sandbox, how do you access the index.html used in the build?

_Example sandbox:_
https://t.co/ayeXzSORkB

Here is what you see when inspecting the DOM of the built app:

<img width="663" alt="screen shot 2018-06-26 at 1 28 34 pm" src="https://user-images.githubusercontent.com/19484365/41931862-ee692800-7944-11e8-813e-dd32b8e131ca.png">

You see a `#root` div, but in my index.html I am using `#mountPoint`. Thus, it is not my index.html being used and I need to know how to access the defaulted index.html to add things to the `<head>`.

_My index.html:_

<img width="634" alt="screen shot 2018-06-26 at 1 30 29 pm" src="https://user-images.githubusercontent.com/19484365/41931926-25adaa0c-7945-11e8-812b-9b1e98f2e2c0.png">

**Comment by CompuIves** [comment]
Hey! I believe we expect the `index.html` to be in the `public` path, like
CRA does. It _should_ work when you make this change.

**Comment by colshacol** [comment]
Ah, fair enough. Suppose looking into CRA would have helped, given the boiler that CodeSandbox uses. -_-

Appreciate it, good sir. I tested it and that is the correct answer. :+1:

For reference for any wanderers in the future: 
<img width="230" alt="screen shot 2018-06-27 at 8 09 05 pm" src="https://user-images.githubusercontent.com/19484365/42007486-0178f950-7a46-11e8-96bd-2b1bf63507bf.png">
