### ISSUE TITLE
Cursor vs. actual position drift short as cursor moves to the right

### ISSUE THREAD

**Issue by yurikoex** [CompuIves/codesandbox-client#934]
# 🐛 bug report

###  Link to sandbox: [https://codesandbox.io/s/5y986vvv4]()

**Comment by CompuIves** [comment]
This is interesting, are you perhaps using a custom font?

**Comment by yurikoex** [comment]
I noticed it would go away if a moved font size to 14. 12 still makes it come back. No custom fonts

**Comment by EmilTholin** [comment]
I also started getting this behavior today without changing preferences. It only seems to happen using Dank Mono without ligatures.

**Specs**

macOS Sierra Version 10.12.6 
Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Example**

![dank_mono_cursor_offset](https://user-images.githubusercontent.com/11573167/42786306-02b5b082-8956-11e8-9506-e8ea6db1f551.gif)

**Comment by CompuIves** [comment]
I have reverted Dank Mono for now, I will take a look tomorrow how these character width calculations drift off.

**Comment by CompuIves** [comment]
Should be fixed now!

**Comment by EmilTholin** [comment]
@lbogdan It works like a charm! Thank you for the quick work.
