### ISSUE TITLE
How to delete files from Storage Management?

### ISSUE THREAD

**Issue by tofanelli** [CompuIves/codesandbox-client#935]
# ❔ Question

Hey guys...  the question is literally the title... I will try to break down a little my problem and lets see what can be done with it...

I was having some problems to achieve some task on React, and someone on StackOverflow suggested me to create a sandbox. Ok, account created, and let's see how to upload things there. Oh, there's a CLI easy to follow... let's do it. But, this CLI doesn't create a new sandbox with the folder's name (for example). Just throw all the files on the folders and sub-folders and that's it... But, I only knew that is possible to upload more than 20MB after uploaded most of them. (Suggestion here, when I'm about to upload files from the CLI, creates a sandbox with the folder's name, but before run through the user's profile and check if there isn't a sandbox with the same folder's name created, if not, ask him what is that project is about (Angular, React, and so on), and only then, upload the files. And before the files be uploaded, check the folder size and ask to the user if is there any folder he wants to exclude to not have his quota exceeded). 

So now, what am I facing? My storage is completely full with PDF and JPG files (which I wasn't aware that I couldn't upload them) , any sign of how to delete these files either and any other way to clean up everything and start from scratch to try to get my things done

![image](https://user-images.githubusercontent.com/5512922/42049617-deac62da-7adc-11e8-9517-3c0970b2d229.png)

And, if I try to add these files to a newly sandbox created, there is no way to make a bulk selection neither keep on the screen to keep adding the files to the sandbox. But, turns out, even if I add the files to the sandbox and deletes the sandbox, these files on Storage won't be deleted. So, I really don't have too much option here. 

Is there any to delete the files from the Storage Management or clean up my profile to do everything from scratch?

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser |  Chrome 67.0.3396.99 (Official Build) (64-bit)
| Operating System | Windows 8.1

**Comment by CompuIves** [comment]
Hey! Sorry for this, the reason the button wasn't visible was because it was out of view. I created a commit that fixes this and will deploy it this evening.

**Comment by tofanelli** [comment]
Superb @CompuIves .... its working now....  thanks =)

Quick question... is there a way to make a bulk selection? One by one it will take a long time, depending in how many files will be selected...

**Comment by CompuIves** [comment]
Nice! That's not possible yet, but a good feature request. Could you open a
separate issue for this?

**Comment by tofanelli** [comment]
Done @CompuIves! =)

**Comment by kro12** [comment]
Was searching to see if this feature was supported and landed here **+1**
