### ISSUE TITLE
eslint errors in jest tests

### ISSUE THREAD

**Issue by gautamarora** [CompuIves/codesandbox-client#937]
# 🐛 bug report

As reported by @philiphendry at https://github.com/CompuIves/codesandbox-client/issues/364#issuecomment-401413230, there are errors when using eslint with jest tests.

@philiphendry - could you help share the information below...

###  Link to sandbox
in comment below

### Your Environment
in comment below

**Comment by philiphendry** [comment]
Hi @gautamarora  - I'll do my best:

Link to sandbox : [link](https://codesandbox.io/s/2j0qlx423n)

Software|Name/Version
----------|-------------
Codesandbox|PROD-1530208958-0a754e2 (is that what you need - I can't seem to find the version number in the format x.x!!!)
Browser|Chrome 67.0.3396.87 (Official Build) (64-bit) (cohort: Stable)
Operation System|Windows 10  Pro Version 1803

Whilst preparing the link above I loaded the sandbox in an Incognito browser window and it worked!! I then also tried it in Firefox and that worked too. I've also noticed that there's a pending Chrome update so I'm going to post this comment now then come back after I've done a full Chrome restart and update to see if that resolves the problem.

**Comment by philiphendry** [comment]
I've updated my Chrome and restarted and it now running `67.0.3396.99 (Official Build) (64-bit) (cohort: Stable)` but the problem still persists. One odd this I've noticed is if I'm in the sandbox then click 'Sandbox Editor' then the back button to return and immediately select 'tests\counter.spec.js' then the errors aren't there. However, if I click another code file then return the errors re-appear:
![image](https://user-images.githubusercontent.com/705830/42111732-5aa0144e-7bdd-11e8-8abf-d94ed90d21a1.png)
Armed with this new found knowledge, if I do that same click away and return in my incognito window and firefox then the errors appear in those too. (Specifically I clicked the 'components\Counter.js' file then returned to the tests.)

If there's anything else I can provide then please let me know! Oh, one last thing, in my attempts to overcome the issues I added the following to the package.json file but kind of assumed it wouldn't actually achieve anything:
```
  "eslintconfig": {
    "env": {
      "jest": true
    }
  },
```

**Comment by gautamarora** [comment]
@philiphendry - thanks for all this detailed info. I've not played with Jest on CodeSandbox with Vue projects compared to React projects, so i'm wondering if its something to do with that since I don't see it in the react redux todos sandbox here: https://codesandbox.io/s/github/reduxjs/redux/tree/master/examples/todomvc
do you see the issues in react sandbox?

not sure if you've already tried this or even want to do this, but one way to solve is by adding this to the top of your test file:
`/* global describe, it, expect */`

it can be a temporary way to resolve this until Ives can possibly weigh in and share his thoughts.

**Comment by philiphendry** [comment]
@gautamarora  - I'm afraid I've never used React but I have searched codesandbox and found [an example](https://codesandbox.io/s/xoqqvmo714) which seems to load fine, run tests and with no error 'squiggles' in the editor.

I've put `/* global describe, it, expect */` in my test file and that seems to have done the trick and the red squiggles have gone. That's not something I'd tried - this javascript web world is full of 'magic pixie dust' and that comment is not one I'd found! Does this help indicate what the underlying issue is?

**Comment by SaraVieira** [comment]
Issue closed due to lack of activity

**Comment by asfaltboy** [comment]
I also don't know how that example works ... I think it's perhaps provided by `react-scripts`? It seems customizing eslintrc isn't supported right now?

From https://codesandbox.io/docs/environment#container-environment:
> While you can also lint your code using ESLint via the command line in containers, we don't currently support custom ESLint configs in the editor itself.

**Comment by SaraVieira** [comment]
Hey!

For now, at least you need to set them as globals as mentioned above we will need to think about a lot of fixes and improvements for the test environment in the future

/* global describe, it, expect */

I am sorry about the issue
