### ISSUE TITLE
Getting ModuleNotFoundError on subpath import

### ISSUE THREAD

**Issue by skokenes** [CompuIves/codesandbox-client#938]
## Description of the problem
I have a library published on NPM. It has top level exports as well as some subpaths that can be imported from, like `import { foo } from "lib/submodule"`. When I try to import from the sub modules like this in CodeSandbox, I get mixed results. Sometimes, it imports them just fine. Other times, it throws "ModuleNotFoundError"s for the sub module import. It is extremely repeatable - reloading the page usually alternates between it working and not working.

## How has this issue affected you? What are you trying to accomplish?
This is issue is preventing me from importing submodules from my library. I use CodeSandbox to host examples on how to use the library.

**Comment by skokenes** [comment]
Thanks for the fix. Any idea on when this will make it into production?

**Comment by CompuIves** [comment]
Probably within an hour! I want to make sure we get some other fixes into the deploy as well.
