### ISSUE TITLE
Search all files

### ISSUE THREAD

**Issue by Alex-EEE** [CompuIves/codesandbox-client#940]
# ❔ Question

Is there a way to search all source files for a string or regex?

**Comment by arthurdenner** [comment]
Currently, no, but there is a pull request (#902 ) about this feature waiting for a review.

**Comment by CompuIves** [comment]
Not stale, stale-bot 😄. This one is one I want to be taking on soon.

**Comment by lbogdan** [comment]
Not stale, but actually a duplicate of #258 . Closing this in favor of the older one, please follow that instead.
