### ISSUE TITLE
Jest test are not automatically run for Vue apps

### ISSUE THREAD

**Issue by tzzl** [CompuIves/codesandbox-client#945]
Jest tests are not automatically run for Vue when changes are made. I have to manually press the arrow in the bottom panel for tests to be updated.

Steps to reproduce:
- Go to https://codesandbox.io/s/21kr47pq5p
- See that the test pass
- On the App.vue file, remove the id on the paragraph
- The test should fail, but actually it doesn't, nothing happens
- Press on the arrow in the bottom panel
- The test now fails

**Comment by SaraVieira** [comment]
Issue closed due to lack of activity
