### ISSUE TITLE
Live Mode - file switching

### ISSUE THREAD

**Issue by johncokos** [CompuIves/codesandbox-client#949]
# 🐛 bug report

## Description of the problem
I use CS in a classroom environment as an instructor.  I have recently tried to use the "Live" feature to assist in the process, but we're seeing a number of issues:

- If I open a new file those that are connected do not see that the new file has been created or is open
- if I have multiple files opened, connected users do not automatically switch with me
- If they do manually go into the file that I'm in, they can see that I'm in there (name and cursor shows) but anything that I've typed does not show up unless they do a screen refresh.
- If I go to a different file and then come back to the file we all started with, the same thing happens -- the connected users need to refresh to pick back up with my live typing.

## How has this issue affected you? What are you trying to accomplish?
As an instructor,  this makes the live feature not nearly as useful as it could be for the students that want to follow along in apps that require many files.

**Comment by lbogdan** [comment]
Hey @robbyoconnor, are you aware of [this feature](https://twitter.com/compuives/status/982237806360588292)?

**Comment by johncokos** [comment]
Is that video of an experimental feature?  My experience with the product as shipped isn't what's shown there ... although that's exactly what I'm looking for!

**Comment by lbogdan** [comment]
It's not experimental, but it's not enabled by default, if people want to follow along you they'll have to click on the small "Follow along" icon next to the live session's owner.

**Comment by robbyoconnor** [comment]
Wait, why was I tagged here?

**Comment by johncokos** [comment]
I'm guessing that was a typo and they meant it for me.

**Comment by johncokos** [comment]
... and that follow along link does work as far as I can tell. Thanks @lbogdan for pointing it out.

That's really non-obvious, but now that I know it, I can take advantage.

**Comment by lbogdan** [comment]
@robbyoconnor Sorry for that, you were the second `@` suggestion and I mistakenly chose you for some reason. 😃

**Comment by lbogdan** [comment]
@johncokos Glad that solved your issue! It's quite non-obvious, indeed, I remember saying the same thing to @CompuIves a while ago, maybe he'll make it more obvious when he finds some time. 😃
