### ISSUE TITLE
Babel transforms disabled in codesandbox?

### ISSUE THREAD

**Issue by tsiq-swyx** [CompuIves/codesandbox-client#954]
# 🐛 bug report

## Description of the problem

This code runs on my machine: https://codesandbox.io/s/github/sw-yx/babel-blade/tree/master/demo/react-graphql-apollo-tutorial-boilerplate

but it shows

```
TypeError
(0 , _blade.createQuery) is not a function
```

on codesandbox:

![image](https://user-images.githubusercontent.com/35976578/42602577-199866d6-8538-11e8-906d-67aceb44e86d.png)

Ives mentioned here: https://github.com/CompuIves/codesandbox-client/issues/662 that transpiling was disabled? What's the picture here?

I know i am doing something funky because this is on the next version of create-react-app. But please let me know if this is possible.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | n/a
| Browser | latest chrome
| Operating System | latest mac osx

**Comment by sw-yx** [comment]
hmm, ok thanks. im afraid templates are still quite magical to me haha
