### ISSUE TITLE
Intermittent issues with react-intl

### ISSUE THREAD

**Issue by alansouzati** [CompuIves/codesandbox-client#955]
# 🐛 bug report

## Description of the problem

Sometimes (actually most of the time) my codesandbox fails on react-intl. It then suddently starts to work again, and then fails again.

Here is the error:

```
Could not find module in path: 'react-intl/locale-data/index.js' relative to '/node_modules/react-intl/lib/index.js'
```

Here is the codesandbox:

https://codesandbox.io/s/7jnyw3qyr1 

## How has this issue affected you? What are you trying to accomplish?

Just run a simple test using Grommet.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | ??
| Browser | All Browser
| Operating System | MacOS

**Comment by CompuIves** [comment]
Hmm, this is interesting. It seems like we can't find the mentioned file because it's specified as a file not to use in the browser: https://unpkg.com/react-intl@2.4.0/package.json. That's the reason that we don't download and include the file, I'm not sure what the reason for this is(?)

**Comment by alansouzati** [comment]
it gets even more weird, if I delete any module and add it again, it works. maybe you can silently fail on it ?

**Comment by CompuIves** [comment]
Oh, actually you have a good point! This is a bug in CodeSandbox where we don't detect stubbed modules in evaluation phase.

I created a commit with a fix, should go live tonight (once CircleCI helps).

**Comment by alansouzati** [comment]
🎉

**Comment by gabriel403** [comment]
I know this is a slightly old issue, but I'm still getting this now
```
ModuleNotFoundError
Could not find module in path: 'react-intl/locale-data/index.js' relative to '/node_modules/react-intl/lib/index.js'
```
```
> 4 | import { IntlProvider, addLocaleData } from "react-intl";
```

**Comment by CompuIves** [comment]
Hey @gabriel403, on which version of CodeSandbox (you can find it in the bottom left corner) do you get this? I am not able to reproduce this.

**Comment by gabriel403** [comment]
@CompuIves PROD-1542588735-05f552a
