### ISSUE TITLE
Allow opening tests by default with share link

### ISSUE THREAD

**Issue by kentcdodds** [CompuIves/codesandbox-client#958]
# Share link option for opening the tests.

Add a "Show tests (instead of browser preview)" option to the share link modal.

<img width="437" alt="screen shot 2018-07-13 at 9 16 48 am" src="https://user-images.githubusercontent.com/1500684/42702156-8039efea-867d-11e8-829d-a6250d46f40b.png">

**Comment by satyarohith** [comment]
shall I take this?
