### ISSUE TITLE
embedded editor not reflecting changes

### ISSUE THREAD

**Issue by jayjaycross** [CompuIves/codesandbox-client#96]
I'm seeing this issue for all embedded sandboxes, as an example you can checkout [Formik Example](https://codesandbox.io/embed/zKrK5YLDZ).

Editing the sandbox results in the changes being reflected in the Preview view but not in the Editor view.

![aug-07-2017 16-28-15](https://user-images.githubusercontent.com/1153686/29044438-749dc55e-7b8d-11e7-9f1a-e40bef89b705.gif)

**Comment by CompuIves** [comment]
Really good report, thanks for the clear issue! Fixed it with https://github.com/CompuIves/codesandbox-client/commit/eb9687942edfddefe690bc0744e8296b785d282b.
