### ISSUE TITLE
console.log(Infinity)

### ISSUE THREAD

**Issue by donavon** [CompuIves/codesandbox-client#961]
# 🐛 bug report

## Description of the problem

![image](https://user-images.githubusercontent.com/887639/42726421-3ae55f66-8762-11e8-93ea-36b756237e28.png)

As you can see, when I `console.log` with `Infinity` or `-Infinity`, the built-in console shows `null`.

## How has this issue affected you? What are you trying to accomplish?

I can't sleep nights. I have this low, dull, pain in the back of my head. Aspirin does nothing.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1530978082-067f9fe
| Browser | Chrome/Version 67.0.3396.99 (Official Build) (64-bit)
| Operating System | MacOS/something.something

**Comment by donavon** [comment]
Here's how in look in Inspector

![image](https://user-images.githubusercontent.com/887639/42726464-e63ba9d8-8762-11e8-9bf2-a1de361acb49.png)

**Comment by CompuIves** [comment]
Hmm @samdenty99 maybe we need an exception for Infinity in `console-feed`?

**Comment by donavon** [comment]
It's probably not an issue for most people, but I think big. REALLY big. ;)

**Comment by samdenty99** [comment]
Nice one! Just published `console-feed@2.8.2` which fixes the rendering for `Infinity`, fixes the Typescript definitions and supports recursive custom rendering

![image](https://user-images.githubusercontent.com/13242392/42736265-a93c868e-885b-11e8-912d-d61d74149628.png)

**Comment by lbogdan** [comment]
Fixed in #976 .
@donavon you can test [here](http://pr976.cs.lbogdan.tk/s/jpl4p46p69).

**Comment by CompuIves** [comment]
You're so quick @samdenty99! Thanks a bunch
