### ISSUE TITLE
Cobalt 2 theme

### ISSUE THREAD

**Issue by avanslaars** [CompuIves/codesandbox-client#965]
# 🌈 Feature

I think cobalt2 by Wes Bos would be a great addition to the available, “pre-installed” themes

**Comment by Haroenv** [comment]
This can be closed now, since it's been added as an option in https://github.com/CompuIves/codesandbox-client/pull/972

**Comment by CompuIves** [comment]
Yep, thanks for the headsup @Haroenv!
