### ISSUE TITLE
Console scroll is broken in Chrome

### ISSUE THREAD

**Issue by ValentinH** [CompuIves/codesandbox-client#968]
# 🐛 bug report

## Description of the problem
Since this morning, I have noticed that the scroll of the console panels (both bottom and side ones) is very buggy. The bug can be noticed with trackpad and mouse.

If I move the scrollbar to the top, then the scroll works again for a moment. Then if I scroll to the bottom, it gets stuck again.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1531762091-1960c9d |
| Browser | Chrome 67 |
| Operating System | OSX 10.13.4 |

**Comment by CompuIves** [comment]
Whoah that's weird, didn't change anything there 🤔

**Comment by ValentinH** [comment]
I could reproduce it on 2 different machines today... Only Chrome though. 
Do you manage to reproduce?

**Comment by lbogdan** [comment]
It's also happening here, Chrome / Chrome Canary on macOS / Windows 10.

**Comment by jakub-astrahit** [comment]
It's not working for me either: Google Chrome is up to date - Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by CompuIves** [comment]
Doesn't only happen for console, I believe it's also happening in the test view.

**Comment by samdenty99** [comment]
@CompuIves Nope, haven't changed anything

**Comment by samdenty99** [comment]
@CompuIves Latest version with scrolling - https://codesandbox.io/s/3133oz520m
