### ISSUE TITLE
Theme suggestion: Solarized Light 

### ISSUE THREAD

**Issue by sun2rise** [CompuIves/codesandbox-client#971]
# 🌈 Feature

Solarized is a sixteen color palette (eight monotones, eight accent colors) designed for use with terminal and gui applications. It has several unique properties. I designed this colorscheme with both precise CIELAB lightness relationships and a refined set of hues based on fixed color wheel relationships. It has been tested extensively in real world use on color calibrated displays (as well as uncalibrated/intentionally miscalibrated displays) and in a variety of lighting conditions.

![VSCode Solarized Light](https://superdevresources.com/wp-content/uploads/2018/01/solarized-light-theme-1024x697.png)

**Comment by sun2rise** [comment]
I made a PR for this #970 
Only I don't know if I can use the official json from vscode repo

**Comment by lbogdan** [comment]
Closing this as it was added in #972 .
