### ISSUE TITLE
Cursor bug

### ISSUE THREAD

**Issue by sabeurthabti** [CompuIves/codesandbox-client#974]
# 🐛 bug report

## Description of the problem
The cursor is off by a few lines

![pxozhfisgv](https://user-images.githubusercontent.com/2606228/42822767-c6be52fe-89d3-11e8-9738-8688901bbddd.gif)

## How has this issue affected you? What are you trying to accomplish?
To use the editor 
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  yes
| Browser |  Chrome/latest
| Operating System | Mac OSX

**Comment by sabeurthabti** [comment]
I found changing the font from dank mono - fixed the issue.

**Comment by CompuIves** [comment]
Should be fixed now!

**Comment by sabeurthabti** [comment]
@lbogdan  @CompuIves works thanks.
