### ISSUE TITLE
Vue: Could not find/install babel plugin

### ISSUE THREAD

**Issue by francoischalifour** [CompuIves/codesandbox-client#979]
# 🐛 bug report

## Description of the problem

For a few days, [this kind of sandboxes using Vue](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch) display an error like:

```
Could not find/install babel plugin '-': Cannot find module 'babel-plugin--' from '/src'
```

Or

```
Could not find/install babel plugin 't': Cannot find module 'babel-plugin-t' from '/src'
```

The so-called babel plugins seem to be random. Note that it still works well locally.

## How has this issue affected you? What are you trying to accomplish?

I was trying to load a previously working sandbox.

### Your Environment

| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1531843111-627c19c
| Browser | Chrome / Firefox / Safari
| Operating System | macOS

**Comment by CompuIves** [comment]
That's bad, it seems like with our upgrade to Webpack 4 it started mangling the variable names in a broken way. Need to look into this.
