### ISSUE TITLE
[Question] How to use babel-plugin-macros in create-react-app template?

### ISSUE THREAD

**Issue by sw-yx** [CompuIves/codesandbox-client#981]
# ❔ Question

hi! I am trying to use @kentcdodds ' `babel-plugin-macros` inside the create-react-app template in CSB. I have upgraded `react-scripts` to a v2.0 beta (where babel-plugin-macros is supported) but it seems to still not be running. I feel like there is some key piece of knowledge I am missing, and am unable to debug this myself. any hints please?

**Comment by sw-yx** [comment]
confirmed that it is a create-react-app template issue, i have got it working in vanilla https://codesandbox.io/s/4lwoovknx9

**Comment by corysimmons** [comment]
@CompuIves I think this may be broken again.

Here's a reduced test case using styled-components `css` prop + their styled-components babel macro: https://codesandbox.io/s/bug-codesandbox-babel-macro-momoq

https://medium.com/styled-components/css-prop-support-for-create-react-app-37e8c5d96861
