### ISSUE TITLE
Add support for Dojo 3+

### ISSUE THREAD

**Issue by nicknisi** [CompuIves/codesandbox-client#988]
# 🌈 Feature

We're getting close to releasing Dojo v3+ and the big change is the deprecation of the `@dojo/core` package as it has now been consolidated into the `@dojo/framework` package. If I remember correctly, the backend looks for the `@dojo/core` dependency to know which template to use. Could we also have it check for `@dojo/framework` so that Codesandbox will work with both Dojo 2 and Dojo 3+? Thanks!

**Comment by CompuIves** [comment]
Yes! Makes sense!
We have that logic here: https://github.com/codesandbox-app/codesandbox-importers/blob/master/packages/import-utils/src/create-sandbox/templates.ts#L78

**Comment by nicknisi** [comment]
Oh wonderful! I can raise a PR to change that. Thanks for pointing that out!

**Comment by agubler** [comment]
Hey @CompuIves, do you know when the PR to support the next major of dojo will be reviewed and released?

**Comment by nicknisi** [comment]
@CompuIves This still seems to be an issue. CodeSandbox doesn't seem to recognize a sandbox as a Dojo template unless `@dojo/core` is present, but codesandbox-app/codesandbox-importers#12 added a check for `@dojo/framework` as well. Do you know if there is anything else we need to do here? Thanks!
