### ISSUE TITLE
Missing dependency detection should support scoped packages

### ISSUE THREAD

**Issue by tkh44** [CompuIves/codesandbox-client#99]
![image](https://user-images.githubusercontent.com/662750/29104332-09df35fe-7c82-11e7-9dfd-5ec4543fee29.png)

**Comment by CompuIves** [comment]
Oi, good one. I'll fix this as soon as I get my hands on my MacBook.

**Comment by CompuIves** [comment]
If you're feeling adventurous, you can add a test case to `dependency-not-found-error.test.js` (out the top of my head).

**Comment by CompuIves** [comment]
Fixed with https://github.com/CompuIves/codesandbox-client/commit/78298467ce1055b92b81629008149b6a52e88f30
