### ISSUE TITLE
Could not find module in path: 'geniejs' relative to '/src/other-examples/genie.js'

### ISSUE THREAD

**Issue by kentcdodds** [CompuIves/codesandbox-client#991]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

I'm trying to make an example of integrating geniejs with downshift. Despite adding the dependency I'm getting this:

<img width="1037" alt="screen shot 2018-07-19 at 3 39 39 pm" src="https://user-images.githubusercontent.com/1500684/42971540-f720077a-8b69-11e8-8904-edd604f397b4.png">

###  Link to sandbox: [link](https://codesandbox.io/s/nk1212npnj?module=%2Fsrc%2Fother-examples%2Fgenie.js&moduleview=1) (optional)

Note: This is in the `src/other-examples/genie.js` file with `moduleview` on :+1:

**Comment by kentcdodds** [comment]
Aaaaaaahhh!!!! Haha, that's really frustrating. Thank you for spending time digging into that and I'm sorry I didn't figure it out on my own. I'm releasing a fix to geniejs now.

I guess this goes to show that nobody's using that package because nobody's mentioned it 😅 

Thanks!

**Comment by CompuIves** [comment]
We use the package :D

**Comment by kentcdodds** [comment]
No way! That's awesome!!! 😍😍
