### ISSUE TITLE
Support for short JSX fragments

### ISSUE THREAD

**Issue by yunyu** [CompuIves/codesandbox-client#992]
# 🌈 Feature

The feature is described here: https://reactjs.org/docs/fragments.html#short-syntax

Basically,
```jsx
<>
  <Child1 />
  <Child2 />
</>
```
would be transpiled to
```jsx
<React.Fragment>
  <Child1 />
  <Child2 />
</React.Fragment>
```

It is available for Babel 7.x: https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#support-for-fragment-syntax

**Comment by danieldelcore** [comment]
Looks like this is already supported. It works for me 🤔 
https://codesandbox.io/s/7o3vyq4o40

**Comment by SaraVieira** [comment]
Thank you @danieldelcore !

Yeah, we now support this 🎉
