### ISSUE TITLE
Sandbox secretly changes the URL

### ISSUE THREAD

**Issue by dereks** [CompuIves/codesandbox-client#996]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

Beginning with commit 3dc8935, my project now keeps changing to a new URL address whenever I save a file with CTRL-S. (I disabled auto-save so I have to press CTRL-S in the editor.)

Original URL: https://codesandbox.io/s/pwxm9519rm

Add a harmless carriage return to any file and then save with CTRL-S. It will then change the URL. Here are some of the new (forked?) URLs that I've just been redirected to by trying to save a file:

https://codesandbox.io/s/ppr7vvv920
https://codesandbox.io/s/2xp2135m9p
https://codesandbox.io/s/7ox3xz3ow6

I never got a visual notification of this URL change from the User Interface. I was lucky to notice it on my own by watching the address bar. 

I have the first (original) URL in my bookmarks -- if I didn't notice the URL change and then worked for several hours, then I would come back to my original bookmark and all my work would be lost. 

In my opinion, the URL should never change. It should only change when the user requests to fork it. How else can I reliably save or share my sandbox URLs?

###  Link to sandbox: [link]() (optional)

Original URL: https://codesandbox.io/s/pwxm9519rm

Unwanted clones created by CTRL-S:

https://codesandbox.io/s/ppr7vvv920
https://codesandbox.io/s/2xp2135m9p
https://codesandbox.io/s/7ox3xz3ow6

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome 58.0.3029.81
| Operating System | Ubuntu Linux 14.04

**Comment by CompuIves** [comment]
Hmm, to be 100% sure, are you signed in when watching the sandbox?

**Comment by dereks** [comment]
No, I am not signed in. I've never signed in to CodeSandbox.io.

I've been working on the project anonymously for the past several weeks, on an (almost) daily basis. It never changed the URL on me before.

I did recently try "forking" the project as a test for another bug report. Does "forking" the project somehow invalidate the original sandbox URL?

**Comment by CompuIves** [comment]
Hmm, we do show a notification for 2 seconds in the bottom right corner when we fork a sandbox. I will change the timeout of the notification to be a bit longer so there's time to see it together with the other transitions.

**Comment by isaksky** [comment]
This can be reproduced by just using incognito mode (Chrome), signing in to the same github account used to create a sandbox, adding a newline to a sandbox you own and saving. This caused me a lot of embarrassment where none of my edits were getting shared, and people were looking at my first draft full of typos, mistakes, etc.
